objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Title</fullName>
        <active>true</active>
        <label>Title</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>HB Closing Tasks</fullName>
                    <label>HB Closing Documents</label>
                </value>
                <value>
                    <fullName>Closing</fullName>
                    <label>HO Closing Documents</label>
                </value>
                <value>
                    <fullName>Offer Package</fullName>
                </value>
                <value>
                    <fullName>RSI Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <description>Describes if (HomeBuyer) mortgage is an Agency or Non-Agency Mortgage. Agency is when the mortgage can be sold to Fannie or Freddie.</description>
        <inlineHelpText>Describes if (HomeBuyer) mortgage is an Agency or Non-Agency Mortgage. Agency is when the mortgage can be sold to Fannie or Freddie.</inlineHelpText>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billboard_Property_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billboard Property Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocuSign_Returned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DocuSign Returned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Officer_ID__c</fullName>
        <label>Loan Officer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentLinkTriggerHandlerTest.cls
@isTest(seealldata=true)
public class ContentDocumentLinkTriggerHandlerTest{

    @isTest
    static void datacreate(){
       Test.setMock(HttpCalloutMock.class, new SFDC2SFDCAPIMock()); 
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
                
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.Estimated_Funding_Amount__c  = 2;
        newOpportunity.Pricing_Ratio__c  = 2;
        newOpportunity.Final_OAV_Calculation__c = 4;
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
          /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup       
        newOpportunity.Billboard_Property_Approval__c = true;           
*/
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
		newOpportunity.Pricing_Ratio__c = 2;
		newOpportunity.Final_OAV_Calculation__c = 4;
        insert newOpportunity;     
        
        Success_Factor__c sf = new Success_Factor__c();
        sf.Opportunity__c = newOpportunity.Id;
        sf.Status__c = 'In Progress';
        sf.Success_Factor__c = 'Closing';
        sf.Program__c = 'HO';
        insert sf;
        
        Current_Conditions__c req = new Current_Conditions__c();
        req.Opportunity__c = newOpportunity.Id;
        req.Requirement__c = 'Closing';
        req.Code__c = 'R1018';
        req.Category__c = 'Mortgage';
        req.Internal_vs_External__c = 'Internal';
        //req.Assigned_To__c = 'PS'; /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        req.Success_Factor__c = sf.Id;
        
        insert req;
        system.debug('++++++req '+ req);
        List<Document_MetaData__c> dmdlist = new List<Document_MetaData__c>();
        
        Document_MetaData__c dmd = new Document_MetaData__c();
        dmd.Opportunity__c = newOpportunity.Id;
        dmd.Requirement__c = req.Id;
        dmd.Document_Type__c = 'Closing Documents';
        dmdlist.add(dmd);
        
        insert dmdlist;
        
        List<ContentVersion> cvlist = new List<ContentVersion>();
        
        ContentVersion cv = new ContentVersion(
            Title = 'ClosingDocuments',
            PathOnClient = 'Test.doc',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        cvlist.add(cv);
        
        insert cvlist;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        List<ContentDocumentLink> cdllist = new List<ContentDocumentLink>();
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = newOpportunity.Id;
        cdl.ContentDocumentId = documents[0].Id;
        //cdl.ContentDocument.Title  = 'ClosingDocuments';
        cdl.shareType = 'V';
        cdllist.add(cdl);
        
        Test.starttest();
        insert cdllist; 
        Test.stoptest();
       
    }
    
    @isTest
    static void datacreate1(){
        Test.setMock(HttpCalloutMock.class, new SFDC2SFDCAPIMock());
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
                
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
                 /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup
        newOpportunity.Billboard_Property_Approval__c = true;           
*/
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
		newOpportunity.Pricing_Ratio__c = 2;
		newOpportunity.Final_OAV_Calculation__c = 4;
        insert newOpportunity;     
        
        Success_Factor__c sf = new Success_Factor__c();
        sf.Opportunity__c = newOpportunity.Id;
        sf.Status__c = 'In Progress';
        sf.Success_Factor__c = 'Closing';
        sf.Program__c = 'HO';
        insert sf;
        
        Current_Conditions__c req = new Current_Conditions__c();
        req.Opportunity__c = newOpportunity.Id;
        req.Requirement__c = 'Offer Package';
        req.Code__c = 'R1072';
        req.Category__c = 'Mortgage';
        req.Internal_vs_External__c = 'Internal';
        //req.Assigned_To__c = 'PS'; /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        req.Success_Factor__c = sf.Id;
        
        insert req;
        system.debug('++++++req '+ req);
        
        List<Document_MetaData__c> dmdlist = new List<Document_MetaData__c>();
        
        Document_MetaData__c dmd1 = new Document_MetaData__c();
        dmd1.Opportunity__c = newOpportunity.Id;
        dmd1.Requirement__c = req.Id;
        dmd1.Document_Type__c = 'Offer Package';
        dmdlist.add(dmd1);
        
        insert dmdlist;
        
        List<ContentVersion> cvlist = new List<ContentVersion>();
        
        ContentVersion cv1 = new ContentVersion(
            Title = 'HOOfferPackage',
            PathOnClient = 'Test.doc',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        cvlist.add(cv1);
        
        insert cvlist;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        List<ContentDocumentLink> cdllist = new List<ContentDocumentLink>();
        ContentDocumentLink cdl1 = New ContentDocumentLink();
        cdl1.LinkedEntityId = newOpportunity.Id;
        cdl1.ContentDocumentId = documents[0].Id;
        cdl1.shareType = 'V';
        cdllist.add(cdl1);
        
        
        Test.starttest();
        insert cdllist; 
        Test.stoptest(); 
       
    }
    
    @isTest
    static void datacreate2(){
        Test.setMock(HttpCalloutMock.class, new SFDC2SFDCAPIMock());
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
                
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
              /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup       
        newOpportunity.Billboard_Property_Approval__c = true;           
*/
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
		newOpportunity.Pricing_Ratio__c = 2;
		newOpportunity.Final_OAV_Calculation__c = 4;
        insert newOpportunity;     
        
        Success_Factor__c sf = new Success_Factor__c();
        sf.Opportunity__c = newOpportunity.Id;
        sf.Status__c = 'In Progress';
        sf.Success_Factor__c = 'Program';
        sf.Program__c = 'HO';
        insert sf;
        
        Current_Conditions__c req = new Current_Conditions__c();
        req.Opportunity__c = newOpportunity.Id;
        req.Requirement__c = 'RSI Letter';
        req.Code__c = 'R1104';
        req.Category__c = 'Mortgage';
        req.Internal_vs_External__c = 'Internal';
        //req.Assigned_To__c = 'PS'; /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        req.Success_Factor__c = sf.Id;
        
        insert req;
        system.debug('++++++req '+ req);
        List<Document_MetaData__c> dmdlist = new List<Document_MetaData__c>();

        Document_MetaData__c dmd2 = new Document_MetaData__c();
        dmd2.Opportunity__c = newOpportunity.Id;
        dmd2.Requirement__c = req.Id;
        dmd2.Document_Type__c = 'RSI Letter';
        dmdlist.add(dmd2);
        
        insert dmdlist;
        
        List<ContentVersion> cvlist = new List<ContentVersion>();
        
        ContentVersion cv2 = new ContentVersion(
            Title = 'RSI Letter',
            PathOnClient = 'Test.doc',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        cvlist.add(cv2);
        
        insert cvlist;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        List<ContentDocumentLink> cdllist = new List<ContentDocumentLink>();
        
        ContentDocumentLink cdl2 = New ContentDocumentLink();
        cdl2.LinkedEntityId = newOpportunity.Id;
        cdl2.ContentDocumentId = documents[0].Id;
        cdl2.shareType = 'V';
        cdllist.add(cdl2);
        
        Test.starttest();
        insert cdllist; 
        Test.stoptest(); 
       
    }
    
    @isTest
    static void datacreate3(){
        Test.setMock(HttpCalloutMock.class, new SFDC2SFDCAPIMock());
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
                
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
              /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup
        newOpportunity.Billboard_Property_Approval__c = true;            
*/
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
		newOpportunity.Pricing_Ratio__c = 2;
		newOpportunity.Final_OAV_Calculation__c = 4;
        insert newOpportunity;     
        
        Success_Factor__c sf = new Success_Factor__c();
        sf.Opportunity__c = newOpportunity.Id;
        sf.Status__c = 'In Progress';
        sf.Success_Factor__c = 'Program';
        sf.Program__c = 'HO';
        insert sf;
        
        Current_Conditions__c req = new Current_Conditions__c();
        req.Opportunity__c = newOpportunity.Id;
        req.Requirement__c = 'CAP Completed';
        req.Code__c = 'R1015';
        req.Category__c = 'Mortgage';
        req.Internal_vs_External__c = 'Internal';
        //req.Assigned_To__c = 'PS'; /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        req.Success_Factor__c = sf.Id;
        insert req;
        system.debug('++++++req '+ req);

        List<Document_MetaData__c> dmdlist = new List<Document_MetaData__c>();
        
        Document_MetaData__c dmd3 = new Document_MetaData__c();
        dmd3.Opportunity__c = newOpportunity.Id;
        dmd3.Requirement__c = req.Id;
        dmd3.Document_Type__c = 'CAP Completed';
        dmdlist.add(dmd3);
        
        insert dmdlist;
        
        List<ContentVersion> cvlist = new List<ContentVersion>();
        
        ContentVersion cv3 = new ContentVersion(
            Title = 'HBCAP',
            PathOnClient = 'Test.doc',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        cvlist.add(cv3);
        
        insert cvlist;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        List<ContentDocumentLink> cdllist = new List<ContentDocumentLink>();
        ContentDocumentLink cdl3 = New ContentDocumentLink();
        cdl3.LinkedEntityId = newOpportunity.Id;
        cdl3.ContentDocumentId = documents[0].Id;
        cdl3.shareType = 'V';
        cdllist.add(cdl3);
        
        Test.starttest();
        insert cdllist; 
        Test.stoptest(); 
       
    }
@isTest
    static void datacreate4(){
        Test.setMock(HttpCalloutMock.class, new SFDC2SFDCAPIMock());
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
                
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
              /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup
        newOpportunity.Billboard_Property_Approval__c = true;            
*/
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
		newOpportunity.Pricing_Ratio__c = 2;
		newOpportunity.Final_OAV_Calculation__c = 4;
        insert newOpportunity;     
        
        Success_Factor__c sf = new Success_Factor__c();
        sf.Opportunity__c = newOpportunity.Id;
        sf.Status__c = 'In Progress';
        sf.Success_Factor__c = 'Closing';
        sf.Program__c = 'HO';
        insert sf;
        
        Current_Conditions__c req = new Current_Conditions__c();
        req.Opportunity__c = newOpportunity.Id;
        req.Requirement__c = 'HB Closing Tasks';
        req.Code__c = 'R1035';
        req.Category__c = 'Mortgage';
        req.Internal_vs_External__c = 'Internal';
        //req.Assigned_To__c = 'PS'; /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        req.Success_Factor__c = sf.Id;
        
        insert req;
    system.debug('++++++req '+ req);

    List<Document_MetaData__c> dmdlist = new List<Document_MetaData__c>();
        
        Document_MetaData__c dmd3 = new Document_MetaData__c();
        dmd3.Opportunity__c = newOpportunity.Id;
        dmd3.Requirement__c = req.Id;
        dmd3.Document_Type__c = 'Closing Documents';
        dmdlist.add(dmd3);
        
        insert dmdlist;
        
        List<ContentVersion> cvlist = new List<ContentVersion>();
        
        ContentVersion cv3 = new ContentVersion(
            Title = 'ClosingDocuments',
            PathOnClient = 'Test.doc',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        cvlist.add(cv3);
        
        insert cvlist;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        List<ContentDocumentLink> cdllist = new List<ContentDocumentLink>();
        ContentDocumentLink cdl3 = New ContentDocumentLink();
        cdl3.LinkedEntityId = newOpportunity.Id;
        cdl3.ContentDocumentId = documents[0].Id;
        cdl3.shareType = 'V';
        cdllist.add(cdl3);
        
        Test.starttest();
        try{
        insert cdllist;
        }
        catch(Exception e){

        }
    Test.stoptest();
       
    }
}