objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Lender Email - used in HB Agreement Closing Instructions</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <description>Application object to extend Lead applicants beyond 1 pair.</description>
    <fields>
        <fullName>Email_Co__c</fullName>
        <label>Email (Co)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <description>Co-applicant's email address As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Email (Co)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Email__c</fullName>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Salesforce User Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recorded_Information__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Recorded Informations (Application)</relationshipLabel>
        <relationshipName>Recorded_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escrow_Email__c</fullName>
        <description>Created for EOS HB team to quickly add/edit HB Contacts. Used in Nintex - Closing Instructions in HB Closing Documents.</description>
        <inlineHelpText>Please enter email address as it should read on the HB Closing Documents. This information appears on the first page of the Closing Instructions.</inlineHelpText>
        <label>Escrow - Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lender_Email__c</fullName>
        <description>Created for EOS HB team to quickly add/edit HB Contacts. Used in Nintex - Closing Instructions in HB Closing Documents.</description>
        <inlineHelpText>Please enter lender email address as it should read on the HB Closing Documents. This information appears on the first page of the Closing Instructions.</inlineHelpText>
        <label>Lender - Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Title_Email__c</fullName>
        <description>Created for EOS HB team to quickly add/edit HB Contacts. Used in Nintex - Closing Instructions in HB Closing Documents.</description>
        <inlineHelpText>Please enter email as it should read on the HB Closing Documents. This information appears on the first page of the Closing Instructions.</inlineHelpText>
        <label>Title - Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Trustee_Email__c</fullName>
        <description>Email Address of the Trustee to appear on Docs. This field is used by the Transaction Specialists: do not deprecate or otherwise alter without their explicit authorization to do so. This field has been determined to be necessary as of Q1 2020. Subject to review for relevance Q4 2021.</description>
        <inlineHelpText>Email Address of the Trustee to appear on Docs.</inlineHelpText>
        <label>Trustee - Email</label>
        <type>Email</type>
    </fields>
    <label>Recorded Information</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Recorded Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recorded Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvalidateEmail.cls
/**
 * Created by cveli on 3/2/2020.
 */

public with sharing class InvalidateEmail {

    public static Boolean thisIsSandbox(){
        return  [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }

    public static void invalidateEmail(List<lead> newList) {
        if (thisIsSandbox() || test.isRunningTest()) {
            for (Lead newLead : newList) {
                newLead.Email = invalidEmail(newLead.Email);
                newLead.Co_Applicant_Email__c = invalidEmail(newLead.Co_Applicant_Email__c);
                newLead.Manager_Email__c = invalidEmail(newLead.Manager_Email__c);
                newLead.Salesforce_User_Email__c = invalidEmail(newLead.Salesforce_User_Email__c);
                newLead.zisf__ZoomInfo_Email__c = invalidEmail(newLead.zisf__ZoomInfo_Email__c);
            }
        }
    }

    public static void invalidateEmail(List<Account> newList) {
        if (thisIsSandbox() || test.isRunningTest()) {
            for (Account acc : newList) {
                acc.Email__c = invalidEmail(acc.Email__c);
            }
        }
    }

    public static void invalidateEmail(List<Recorded_Information__c> newList) {
        if (thisIsSandbox() || test.isRunningTest()) {
            for (Recorded_Information__c riInformation : newList) {
                riInformation.Escrow_Email__c = invalidEmail(riInformation.Escrow_Email__c);
                riInformation.Lender_Email__c = invalidEmail(riInformation.Lender_Email__c);
                riInformation.Title_Email__c = invalidEmail(riInformation.Title_Email__c);
                riInformation.Trustee_Email__c = invalidEmail(riInformation.Trustee_Email__c);
            }
        }
    }
    public static void invalidateEmail(List<Application__c> newList) {
        if (thisIsSandbox() || test.isRunningTest()) {
            for (Application__c newApp : newList) {
                newApp.Email__c = invalidEmail(newApp.Email__c);
                newApp.Email_Co__c = invalidEmail(newApp.Email_Co__c);
            }
        }
    }

    public static void invalidateEmail(List<contact> newList) {
        if (thisIsSandbox() || test.isRunningTest()) {
            for (contact newContact : newList) {
                newContact.email = invalidEmail(newContact.email);
                newContact.Secondary_Email__c = invalidEmail(newContact.Secondary_Email__c);
                newContact.zisf__ZoomInfo_Email__c = invalidEmail(newContact.zisf__ZoomInfo_Email__c);
                System.debug(newContact.email);
            }
        }
    }

    private static string invalidEmail(string email){
        System.debug('invalidateEmail **1');
        if (string.isNotBlank(email)){
            System.debug('invalidateEmail **2');
            if(!(email.contains('+test'))) {
                System.debug('invalidateEmail **3');
                System.debug(email);
                System.debug(email.contains('.invalid'));
                System.debug(email.containsNone('.invalid'));
                if (!email.contains('.invalid') ){
                    System.debug('invalidateEmail **4');
                    email = email + '.invalid';
                }
            }
        }
        return email;
    }
}