objects/Account.object
<CustomObject>
    <fields>
        <fullName>LOP_Lender__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LOP Lender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ready_for_IM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for IM</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountTriggerHandlerTest.cls
@isTest
private class AccountTriggerHandlerTest{

    @IsTest
    private static void testDelete(){
        Account newacc = new Account();
        newacc.Name = 'Test Account';
        newacc.Ready_for_IM__c = false;
        newacc.LOP_Lender__c = true;
        insert newacc;

        Test.setMock(HttpCalloutMock.class, new SFDC2SFDCAPIMock());
        Test.starttest();
        delete newacc;
        Test.stoptest();
    }


}