objects/Account.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGh</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Broker/Owner</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Editor/Producer</fullName>
                </value>
                <value>
                    <fullName>Escrow</fullName>
                </value>
                <value>
                    <fullName>Escrow Assistant</fullName>
                </value>
                <value>
                    <fullName>Flood Insurance</fullName>
                </value>
                <value>
                    <fullName>Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Journalist</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Loan Officer - Reverse</fullName>
                </value>
                <value>
                    <fullName>Loan Ops</fullName>
                </value>
                <value>
                    <fullName>Non-Agent</fullName>
                </value>
                <value>
                    <fullName>Non-LO</fullName>
                </value>
                <value>
                    <fullName>Other Household Role</fullName>
                </value>
                <value>
                    <fullName>Title</fullName>
                </value>
                <value>
                    <fullName>Title Assistant</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Managing Member</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Chairman</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Director</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGw</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01 - Pacific Northwest</fullName>
    </customValue>
    <customValue>
        <fullName>02 - Northern California</fullName>
    </customValue>
    <customValue>
        <fullName>03 - Los Angeles/Orange County</fullName>
    </customValue>
    <customValue>
        <fullName>04 - San Diego</fullName>
    </customValue>
    <customValue>
        <fullName>05 - Mid Atlantic</fullName>
    </customValue>
    <customValue>
        <fullName>06 - Chicagoland</fullName>
    </customValue>
    <customValue>
        <fullName>07 - Greater New York</fullName>
    </customValue>
    <customValue>
        <fullName>08 - New England</fullName>
    </customValue>
    <customValue>
        <fullName>09 - Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>10 - Midwest-Exclude Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>--Other--</fullName>
    </customValue>
    <masterLabel>Territory</masterLabel>
</GlobalValueSet>

classes/ContactTriggerHandler_Test.cls
@istest
private class ContactTriggerHandler_Test {
    @TestSetup
    private static void Testdata() {
        Schema.DescribeSObjectResult conDesc = Schema.SObjectType.Contact; 
        Map<String,Schema.RecordTypeInfo> ContRTMapByName = conDesc.getRecordTypeInfosByName();
        
        Account account1 = new Account();
        account1.Name = 'Test Account';
        insert account1;

        Contact contact1 = new Contact();
        Contact1.AccountId = account1.Id;
        Contact1.FirstName = 'First1';
        Contact1.LastName = 'Last1';
        Contact1.Contact_Role__c = 'Loan Officer';
        Contact1.RecordTypeId = ContRTMapByName.get('Lender').getRecordTypeId();
        Contact1.Sales_Director__c = UserInfo.getUserId();
        Contact1.Branch_Name__c = 'Sanjose';
        contact1.Territory__c = '03 - Los Angeles/Orange County';
        Contact1.Email = 'test@test.com';
        Contact1.MailingStreet = 'Test Street';
        Contact1.MailingCity = 'Test City';
        Contact1.MailingState = 'Test State';
        Contact1.MailingPostalCode = 'TestCode';
        insert contact1;
        
        Account account2 = new Account();
        account2.Name = 'Test Account';
        insert account2;
        
        Contact contact2 = new Contact();
        contact2.AccountId = account2.Id;
        contact2.FirstName = 'First';
        contact2.LastName = 'Last';
        Contact2.Contact_Role__c = 'Loan Officer';
        Contact2.RecordTypeId = ContRTMapByName.get('Lender').getRecordTypeId();
        Contact2.Sales_Director__c = UserInfo.getUserId();
        Contact2.Branch_Name__c = 'Sanjose';
        contact2.Territory__c = '03 - Los Angeles/Orange County';
        contact2.Email = 'test2@test.com';
        contact2.MailingStreet = 'Test Street';
        contact2.MailingCity = 'Test City';
        contact2.MailingState = 'Test State';
        contact2.MailingPostalCode = 'TestCode';
        insert contact2;
    }
    
    @istest
    private static void contactsRollUp() {
        List<Contact> con = [select Id, AccountId from Contact limit 2];
        
        con[0].AccountId = con[1].Accountid;
        update con[0];
        
        delete con[0];
        
        undelete con[0];
                
    }
}