objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGh</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Invited to Train</fullName>
                </value>
                <value>
                    <fullName>Training Scheduled</fullName>
                </value>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>1st Lead Submitted</fullName>
                </value>
                <value>
                    <fullName>2nd Lead Submitted</fullName>
                </value>
                <value>
                    <fullName>3rd Lead Submitted</fullName>
                </value>
                <value>
                    <fullName>LO Active Converted</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOP_Contact_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>LOP Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LO_Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LO Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Types of clients</fullName>
                </value>
                <value>
                    <fullName>Loan product</fullName>
                </value>
                <value>
                    <fullName>Moved to unapproved branch</fullName>
                </value>
                <value>
                    <fullName>Don't understand</fullName>
                </value>
                <value>
                    <fullName>Distrust</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketing Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trained_Date_Time__c</fullName>
        <label>Trained Date Time</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGw</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyLOContactBatch.cls
/*************************************************************************************************
 * @className   : SurveyLOContactBatch.cls
 * @testClass   : SurveyLOContactSched_Test.cls
 * @author      : Omnivo Digital (omnivodigital.com)
 * @date        : May 16, 2019
 * @description : This class is used to get all lender Contact with Trained_Date_Time__c field value in the last 24 hours
 *				and send lo survey
 *
*************************************************************************************************/

global class SurveyLOContactBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
	
	global SurveyLOContactBatch(){

	}

	global Database.QueryLocator start(Database.BatchableContext context) {
		Datetime yDt = Datetime.now().addDays(-1);
		String queryStr = 'SELECT Id, Email, Name, Phone, OwnerId, RecordTypeId, RecordType.Name, '+
									'tdc_tsw__SMS_Opt_out__c, Loss_Reason__c, '+
									'Owner.Name, AccountId, Account.Name, Contact_Status__c, LOP_Contact_Type__c '+
									' FROM Contact ' +
										'Where Trained_Date_Time__c >= :yDt AND LO_Survey_Sent__c = false ' +
            							'AND Marketing_Opt_Out__c = false ' +
										'AND RecordType.DeveloperName = \'Lender\' ';
		return Database.getQueryLocator(queryStr);
	}

   	global void execute(Database.BatchableContext context, List<Contact> scope) {
		System.debug('***scope: ' + scope.size());
		if(scope != null && scope.size() > 0){
			for(Contact con: scope){
				DelightedHelper.SendSurveyLOContact(con);
			}//end for
		}
	}
	 
	global void finish(Database.BatchableContext context) {
		
	}
}