objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Data Request or Stipulation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Requirement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Data Request</fullName>
                </value>
                <value>
                    <fullName>Stipulation</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <description>Describes if (HomeBuyer) mortgage is an Agency or Non-Agency Mortgage. Agency is when the mortgage can be sold to Fannie or Freddie.</description>
        <inlineHelpText>Describes if (HomeBuyer) mortgage is an Agency or Non-Agency Mortgage. Agency is when the mortgage can be sold to Fannie or Freddie.</inlineHelpText>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billboard_Property_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billboard Property Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocuSign_Returned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DocuSign Returned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Officer_ID__c</fullName>
        <label>Loan Officer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Applicant__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trade_Account_Changes__c.object
<CustomObject>
    <fields>
        <fullName>Account_Identifier__c</fullName>
        <label>Account Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount_To_Pay_Off2__c</fullName>
        <label>Amount To Pay Off2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Loan_Type_pick__c</fullName>
        <label>Credit Loan Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
                <value>
                    <fullName>Educational</fullName>
                </value>
                <value>
                    <fullName>Automobile</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>InstallmentLoan</fullName>
                </value>
                <value>
                    <fullName>Collection</fullName>
                </value>
                <value>
                    <fullName>UnknownLoanType</fullName>
                </value>
                <value>
                    <fullName>Other Lien</fullName>
                </value>
                <value>
                    <fullName>Non-Subject Mortgage</fullName>
                </value>
                <value>
                    <fullName>Lease</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Monthly payments do not get included in the Sum of Debt Payments calculation</description>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Repayment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To indicate whether a credit line is in repayment and cannot be drawn on. This is most commonly used for a HELOC. This has a direct impact on the Post-Close LTV calculation.</description>
        <inlineHelpText>Is the credit line / HELOC in repayment?</inlineHelpText>
        <label>In Repayment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lien_Interest_Rate_Sub_Type__c</fullName>
        <label>Lien Interest Rate Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30-yr FRM</fullName>
                </value>
                <value>
                    <fullName>15-yr FRM</fullName>
                </value>
                <value>
                    <fullName>20-yr FRM</fullName>
                </value>
                <value>
                    <fullName>10-yr FRM</fullName>
                </value>
                <value>
                    <fullName>5/1 ARM</fullName>
                </value>
                <value>
                    <fullName>7/1 ARM</fullName>
                </value>
                <value>
                    <fullName>10/1 ARM</fullName>
                </value>
                <value>
                    <fullName>I/O</fullName>
                </value>
                <value>
                    <fullName>HELOC</fullName>
                </value>
                <value>
                    <fullName>HECM</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Reverse</fullName>
                </value>
                <value>
                    <fullName>Tax Lien</fullName>
                </value>
                <value>
                    <fullName>Judgment</fullName>
                </value>
                <value>
                    <fullName>UCC</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lien_Position__c</fullName>
        <label>Lien Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>First</fullName>
                    <isActive>false</isActive>
                    <label>First</label>
                </value>
                <value>
                    <fullName>Second</fullName>
                    <isActive>false</isActive>
                    <label>Second</label>
                </value>
                <value>
                    <fullName>Third</fullName>
                    <isActive>false</isActive>
                    <label>Third</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Monthly_Payment__c</fullName>
        <label>Monthly Payment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Pct_Value_Of_Home__c</fullName>
        <label>Target Percent of Home Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>To_Be_Paid_Off__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Be Paid Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Close_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Close Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type; Most Recent Adverse action</description>
        <label>Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Trade Account Changes</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trade Account Changes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Account Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TradeAccountTriggerTest.cls
/************************************************************************************
 Apex Class Name     : TradeAccountTriggerTest
 Version             : 1.0
 Created Date        : 3rd March 2019
 Function            : Test Class for TradeAccountTriggerHandler class and TradeAccountTrigger Trigger
 Author              : Vinitha Bhodhe
 
 Modification Log    :To Handle Trigger and Handler after Data CleanUp.

* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Vinitha Bhodhe             03/08/2019                Original Version
* Sundar Subramaniam         04/16/2019                Modified Version
*************************************************************************************
*/
@isTest
private class TradeAccountTriggerTest{

    @TestSetup
    static void makeData() {
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        //newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
        newOpportunity.Pricing_Ratio__c = 2;
        newOpportunity.Final_OAV_Calculation__c = 4;
        newOpportunity.IA_OAV_Override__c  = 4;
        insert newOpportunity;
        
        LASERCA__Personal_Credit_Report__c pcr = new LASERCA__Personal_Credit_Report__c();
        pcr.Opportunity__c = newOpportunity.Id;
        pcr.Name = 'Test PCR';
        insert pcr;

        Trade_Account_Changes__c tac = new Trade_Account_Changes__c();
        tac.Account_Identifier__c = 'id837345';
        tac.Monthly_Payment__c = 10000;
        tac.Interest_Rate__c = 6;
        insert tac;
        
        LASERCA__Trade_Accounts__c trdacc = new LASERCA__Trade_Accounts__c();
        trdacc.Name = 'testacc';
        trdacc.Credit_Loan_Type_pick__c = 'CreditCard';
        trdacc.LASERCA__Monthly_Payment__c = 10000;
        trdacc.LASERCA__Account_Balance__c = 5000;
        trdacc.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc.Target_Pct_Value_Of_Home__c = 0.10;
        trdacc.Exclude__c = false;
        trdacc.LASERCA__Account_Status_Type__c = 'Open';
        trdacc.Interest_Rate__c = 6;
        trdacc.LASERCA__Account_Identifier__c = 'id837345';
        trdacc.Trade_Account_Changes__c = tac.Id;
        insert trdacc;
    }
    /**
            *  About
            *  -----
            *  Author: Sundar Subramaniam
            *  
            *  Details
            *  -----
            *  Method to take care of all functionalities of POST, PRE-MDEBTS, PAYOFF in the Handler
    **/
    @isTest
    private static void testMethod1(){
        LASERCA__Personal_Credit_Report__c pcr = new LASERCA__Personal_Credit_Report__c();
        pcr.Name = 'Test PCR';
        insert pcr;
        
        List<LASERCA__Trade_Accounts__c> trdacclist = new List<LASERCA__Trade_Accounts__c>();
        
        LASERCA__Trade_Accounts__c trdacc = new LASERCA__Trade_Accounts__c();
        trdacc.Name = 'testacc';
        trdacc.Credit_Loan_Type_pick__c = 'CreditCard';
        trdacc.LASERCA__Monthly_Payment__c = 10000;
        trdacc.LASERCA__Account_Balance__c = 5000;
        trdacc.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc.Target_Pct_Value_Of_Home__c = 0.10;
        trdacc.Exclude__c = false;
        trdacc.LASERCA__Account_Status_Type__c = 'Open';
        trdacclist.add(trdacc);
        
        
        LASERCA__Trade_Accounts__c trdacc1 = new LASERCA__Trade_Accounts__c();
        trdacc1.Name = 'testacc1';
        trdacc1.Credit_Loan_Type_pick__c = 'CreditCard';
        trdacc1.LASERCA__Monthly_Payment__c = 10000;
        trdacc1.LASERCA__Account_Balance__c = 5000;
        trdacc1.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc1.To_Be_Paid_Off__c = TRUE;
        trdacc1.Lien_Position__c  = null;
        trdacc1.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc1);
        
        LASERCA__Trade_Accounts__c trdacc2 = new LASERCA__Trade_Accounts__c();
        trdacc2.Name = 'testacc2';
        trdacc2.Credit_Loan_Type_pick__c = 'Mortgage';
        trdacc2.To_Be_Paid_Off__c = TRUE;
        trdacc2.Lien_Position__c  = '2';
        trdacc2.Amount_To_Pay_Off2__c = 5000;
        trdacc2.LASERCA__Monthly_Payment__c = 10000;
        trdacc2.LASERCA__Account_Balance__c = 5000;
        trdacc2.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc2.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc2);
        
        

        LASERCA__Trade_Accounts__c trdacc3 = new LASERCA__Trade_Accounts__c();
        trdacc3.Name = 'testacc3';
        trdacc3.Credit_Loan_Type_pick__c = 'Other Lien';
        trdacc3.LASERCA__Monthly_Payment__c = 10000;
        trdacc3.LASERCA__Account_Balance__c = 5000;
        trdacc3.Amount_To_Pay_Off2__c = 5000;
        trdacc3.Lien_Position__c  = '2';
        trdacc3.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc3.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc3);       
        

        LASERCA__Trade_Accounts__c trdacc4 = new LASERCA__Trade_Accounts__c();
        trdacc4.Name = 'testacc4';
        trdacc4.Credit_Loan_Type_pick__c = 'Mortgage';
        trdacc4.To_Be_Paid_Off__c = TRUE;
        trdacc4.Lien_Position__c  = '2';
        trdacc4.Amount_To_Pay_Off2__c = 5000;
        trdacc4.LASERCA__Monthly_Payment__c = 10000;
        trdacc4.LASERCA__Account_Balance__c = 5000;
        trdacc4.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc4.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc4);

        LASERCA__Trade_Accounts__c trdacc5 = new LASERCA__Trade_Accounts__c();
        trdacc5.Name = 'testacc5';
        trdacc5.Credit_Loan_Type_pick__c = 'Mortgage';
        trdacc5.To_Be_Paid_Off__c = FALSE;
        trdacc5.Lien_Position__c  = '2';
        trdacc5.Amount_To_Pay_Off2__c = 5000;
        trdacc5.LASERCA__Monthly_Payment__c = 10000;
        trdacc5.LASERCA__Account_Balance__c = 5000;
        trdacc5.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc5.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc5);

        LASERCA__Trade_Accounts__c trdacc6 = new LASERCA__Trade_Accounts__c();
        trdacc6.Name = 'testacc6';
        trdacc6.Credit_Loan_Type_pick__c = 'CreditCard';
        trdacc6.To_Be_Paid_Off__c = FALSE;
        trdacc6.LASERCA__Monthly_Payment__c = 10000;
        trdacc6.LASERCA__Account_Balance__c = 5000;
        trdacc6.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc6.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc6);

        LASERCA__Trade_Accounts__c trdacc7 = new LASERCA__Trade_Accounts__c();
        trdacc7.Name = 'testacc7';
        trdacc7.Credit_Loan_Type_pick__c = 'Other Lien';
        trdacc7.LASERCA__Account_Status_Type__c = 'Open';
        trdacc7.Exclude__c = false;
        trdacc7.LASERCA__Monthly_Payment__c = 10000;
        trdacc7.LASERCA__Credit_Limit__c = 4000;
        trdacc7.To_Close_Account__c = true;
        trdacc7.Lien_Interest_Rate_Sub_Type__c = 'HELOC';
        trdacc7.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc7.To_Be_Paid_Off__c = true;
        trdacc7.Target_Pct_Value_Of_Home__c = 0.10;
        trdacclist.add(trdacc7);

        LASERCA__Trade_Accounts__c trdacc8 = new LASERCA__Trade_Accounts__c();
        trdacc8.Name = 'testacc8';
        trdacc8.Credit_Loan_Type_pick__c = 'Other Lien';
        trdacc8.LASERCA__Account_Status_Type__c = 'Open';
        trdacc8.Exclude__c = false;
        trdacc8.LASERCA__Monthly_Payment__c = 10000;
        trdacc8.LASERCA__Account_Balance__c = 5000;
        trdacc8.In_Repayment__c = true;
        trdacc8.LASERCA__Credit_Limit__c = 6000;
        trdacc8.To_Close_Account__c = true;
        trdacc8.Lien_Interest_Rate_Sub_Type__c = 'HELOC';
        trdacc8.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc8.To_Be_Paid_Off__c = false;
        trdacc8.To_Be_Paid_Off__c = true;
        trdacc8.Target_Pct_Value_Of_Home__c = 0.10;

        trdacclist.add(trdacc8);


        insert trdacclist;

         Account newAccount = new Account();
        newAccount.Name = 'Test Account';        
        insert newAccount;
                
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
                /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup
        newOpportunity.Billboard_Property_Approval__c = true;          
*/
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
        newOpportunity.Pricing_Ratio__c = 2;
        newOpportunity.Final_OAV_Calculation__c = 4;
        newOpportunity.IA_OAV_Override__c  = 4;

        insert newOpportunity;
        
        List<Success_Factor__c>  sflist = new List<Success_Factor__c>(); 
        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = newOpportunity.Id;
        sf1.Success_Factor__c  = 'LTV';
        sf1.Status__c  = 'In Progress';
        sf1.Program__c = 'HO';
        sflist.add(sf1);
        
        insert sflist;
        
        List<Current_Conditions__c>   reqlist  = new List<Current_Conditions__c>();
        Current_Conditions__c  req1 = new Current_Conditions__c();
        req1.Requirement__c     = 'Credit Supplement';   
        req1.Success_Factor__c  = sf1.Id; 
        req1.Opportunity__c     = newOpportunity.id;
        req1.Code__c            = 'R1035';
        req1.Category__c        = 'Credit';
        req1.Type__c='Stipulation';
        reqlist.add(req1);
        
        insert reqlist;
        
        Test.startTest();

        Opportunity newOpportunity1 = new Opportunity();
        newOpportunity1.Name = 'Test Opportunity';
        newOpportunity1.AccountId = newAccount.Id;
        newOpportunity1.StageName = 'Property in Contract';
        newOpportunity1.CloseDate = System.today();
        newOpportunity1.Agency_or_Non_Agency__c = 'Agency';
                /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup
        newOpportunity.Billboard_Property_Approval__c = true;          
*/
        newOpportunity1.DocuSign_Returned__c = true;
        newOpportunity1.Loan_Officer_ID__c = '12345';
        newOpportunity1.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity1.Property_City__c = 'City';
        newOpportunity1.Property_State__c = 'State';
        newOpportunity1.Property_Zip_Code__c = '12345';
        newOpportunity1.IA_OAV_Override__c  = 2;

        insert newOpportunity1;

        Opportunity newOpportunity2 = new Opportunity();
        newOpportunity2.Name = 'Test Opportunity';
        newOpportunity2.AccountId = newAccount.Id;
        newOpportunity2.StageName = 'Property in Contract';
        newOpportunity2.CloseDate = System.today();
        newOpportunity2.Agency_or_Non_Agency__c = 'Agency';
                /* 4/10/2019 Jonathan Vu - Commented for Data Model Cleanup
        newOpportunity.Billboard_Property_Approval__c = true;          
*/
        newOpportunity2.DocuSign_Returned__c = true;
        newOpportunity2.Loan_Officer_ID__c = '12345';
        newOpportunity2.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity2.Property_City__c = 'City';
        newOpportunity2.Property_State__c = 'State';
        newOpportunity2.Property_Zip_Code__c = '12345';
        newOpportunity2.IA_OAV_Override__c  = 2;

        insert newOpportunity2;

        List<LASERCA__Trade_Accounts__c> trdlist = [select opportunity__c from LASERCA__Trade_Accounts__c];
        for(LASERCA__Trade_Accounts__c ta : trdlist){
            ta.Opportunity__c = newOpportunity.Id;
        }
        

        trdlist[4].Opportunity__c = newOpportunity1.id;
        trdlist[5].Opportunity__c = newOpportunity1.id;
        trdlist[6].Opportunity__c = newOpportunity1.id;
        trdlist[7].Opportunity__c = newOpportunity2.id;
        trdlist[7].Target_Pct_Value_Of_Home__c = null;
        trdlist[8].Opportunity__c = newOpportunity2.id;
        trdlist[8].To_Be_Paid_Off__c = true;

        TriggrUtility.resetForTest();
        update trdlist;
        
        Test.stopTest();
    }


    @isTest
    private static void test_CopyChanges_1(){
        
        // Setup Data
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';        
        insert newAccount;
        
        Opportunity newOpportunity1 = new Opportunity();
        newOpportunity1.Name = 'Test Opportunity';
        newOpportunity1.AccountId = newAccount.Id;
        newOpportunity1.StageName = 'Property in Contract';
        newOpportunity1.CloseDate = System.today();
        newOpportunity1.Agency_or_Non_Agency__c = 'Agency';
        newOpportunity1.DocuSign_Returned__c = true;
        newOpportunity1.Loan_Officer_ID__c = '12345';
        newOpportunity1.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity1.Property_City__c = 'City';
        newOpportunity1.Property_State__c = 'State';
        newOpportunity1.Property_Zip_Code__c = '12345';
        newOpportunity1.IA_OAV_Override__c  = 2;
        insert newOpportunity1;
        
        LASERCA__Personal_Credit_Report__c pcr = new LASERCA__Personal_Credit_Report__c();
        pcr.Opportunity__c = newOpportunity1.Id;
        pcr.Name = 'Test PCR';
        insert pcr;
        
        LASERCA__Trade_Accounts__c trdacc = new LASERCA__Trade_Accounts__c();
        trdacc.Name = 'testacc';
        trdacc.Credit_Loan_Type_pick__c = 'CreditCard';
        trdacc.LASERCA__Monthly_Payment__c = 10000;
        trdacc.LASERCA__Account_Balance__c = 5000;
        trdacc.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc.Target_Pct_Value_Of_Home__c = 0.10;
        trdacc.Exclude__c = false;
        trdacc.LASERCA__Account_Status_Type__c = 'Open';
        trdacc.LASERCA__Account_Identifier__c = 'id837345';
        trdacc.Interest_Rate__c = 5;
        insert trdacc;

        // Run Code
        Test.startTest();

        trdacc.Interest_Rate__c = 6;
        update trdacc;

        Test.stopTest();

        // Verify Results
        trdacc = [SELECT Trade_Account_Changes__c, Trade_Account_Changes__r.Account_Identifier__c, Trade_Account_Changes__r.Interest_Rate__c
                    FROM LASERCA__Trade_Accounts__c WHERE Id = :trdacc.Id];
        System.assert(trdacc.Trade_Account_Changes__c != null);
        System.assertEquals('id837345', trdacc.Trade_Account_Changes__r.Account_Identifier__c);
        System.assertEquals(6, trdacc.Trade_Account_Changes__r.Interest_Rate__c);
    }


    @isTest
    private static void test_CopyChanges_2(){
        
        // Setup Data
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';        
        insert newAccount;
        
        Opportunity newOpportunity1 = new Opportunity();
        newOpportunity1.Name = 'Test Opportunity';
        newOpportunity1.AccountId = newAccount.Id;
        newOpportunity1.StageName = 'Property in Contract';
        newOpportunity1.CloseDate = System.today();
        newOpportunity1.Agency_or_Non_Agency__c = 'Agency';
        newOpportunity1.DocuSign_Returned__c = true;
        newOpportunity1.Loan_Officer_ID__c = '12345';
        newOpportunity1.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity1.Property_City__c = 'City';
        newOpportunity1.Property_State__c = 'State';
        newOpportunity1.Property_Zip_Code__c = '12345';
        newOpportunity1.IA_OAV_Override__c  = 2;
        insert newOpportunity1;
        
        LASERCA__Personal_Credit_Report__c pcr = new LASERCA__Personal_Credit_Report__c();
        pcr.Opportunity__c = newOpportunity1.Id;
        pcr.Name = 'Test PCR';
        insert pcr;

        Trade_Account_Changes__c tac = new Trade_Account_Changes__c();
        insert tac;
        
        LASERCA__Trade_Accounts__c trdacc = new LASERCA__Trade_Accounts__c();
        trdacc.Name = 'testacc';
        trdacc.Credit_Loan_Type_pick__c = 'CreditCard';
        trdacc.LASERCA__Monthly_Payment__c = 10000;
        trdacc.LASERCA__Account_Balance__c = 5000;
        trdacc.LASERCA__Personal_Credit_Report__c = pcr.Id;
        trdacc.Target_Pct_Value_Of_Home__c = 0.10;
        trdacc.Exclude__c = false;
        trdacc.LASERCA__Account_Status_Type__c = 'Open';
        trdacc.LASERCA__Account_Identifier__c = 'id837345';
        trdacc.Trade_Account_Changes__c = tac.Id;
        trdacc.Interest_Rate__c = 5;
        insert trdacc;

        // Run Code
        Test.startTest();

        trdacc.Interest_Rate__c = 6;
        update trdacc;

        Test.stopTest();

        // Verify Results
        tac = [SELECT Id, Account_Identifier__c, Interest_Rate__c FROM Trade_Account_Changes__c WHERE Id = :tac.Id];
        System.assertEquals('id837345', tac.Account_Identifier__c);
        System.assertEquals(6, tac.Interest_Rate__c);
    }

    @isTest
    private static void test_FindTradeAccountChanges(){
        
        // Setup Data
        // Moved in @testSetup

        // Run Code
        Test.startTest();

        LASERCA__Trade_Accounts__c trdacc2 = new LASERCA__Trade_Accounts__c();
        trdacc2.Name = 'testacc2';
        trdacc2.LASERCA__Personal_Credit_Report__c = [SELECT Id FROM LASERCA__Personal_Credit_Report__c LIMIT 1].Id;
        trdacc2.LASERCA__Account_Identifier__c = 'id837345';
        insert trdacc2;

        Test.stopTest();

        // Verify Results
        trdacc2 = [SELECT Id, Trade_Account_Changes__c, Interest_Rate__c FROM LASERCA__Trade_Accounts__c WHERE Id = :trdacc2.Id];
        List<Trade_Account_Changes__c> tacs = [SELECT Id FROM Trade_Account_Changes__c];
        System.assertEquals(1, tacs.size());
        System.assertEquals(tacs[0].Id, trdacc2.Trade_Account_Changes__c);
        System.assertEquals(6, trdacc2.Interest_Rate__c);
    }

    /*@isTest
    private static void test_SetTheRightPCROnNewTradeAccounts() {
        
        // Setup Data
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        //newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.Estimated_Funding_Amount__c = 2;
        newOpportunity.Pricing_Ratio__c = 2;
        newOpportunity.Final_OAV_Calculation__c = 4;
        newOpportunity.IA_OAV_Override__c  = 4;
        insert newOpportunity;
        
        LASERCA__Personal_Credit_Report__c pcr1 = new LASERCA__Personal_Credit_Report__c();
        pcr1.Opportunity__c = newOpportunity.Id;
        pcr1.Name = 'Test PCR 1';
        insert pcr1;
        LASERCA__Personal_Credit_Report__c pcr2 = new LASERCA__Personal_Credit_Report__c();
        pcr2.Opportunity__c = newOpportunity.Id;
        pcr2.Name = 'Test PCR 2';
        insert pcr2;

        newOpportunity.Personal_Credit_Report__c = pcr1.Id;
        update newOpportunity;

        // Run Code
        Test.startTest();

        LASERCA__Trade_Accounts__c trdacc2 = new LASERCA__Trade_Accounts__c();
        trdacc2.Name = 'testacc2';
        trdacc2.Opportunity__c = newOpportunity.Id;
        trdacc2.LASERCA__Personal_Credit_Report__c = pcr2.Id;
        insert trdacc2;

        Test.stopTest();

        // Verify Results
        trdacc2 = [SELECT Id, LASERCA__Personal_Credit_Report__c FROM LASERCA__Trade_Accounts__c WHERE Id = :trdacc2.Id];
        System.assertEquals(pcr1.Id, trdacc2.LASERCA__Personal_Credit_Report__c);

    }*/


}