objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGh</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Broker/Owner</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Editor/Producer</fullName>
                </value>
                <value>
                    <fullName>Escrow</fullName>
                </value>
                <value>
                    <fullName>Escrow Assistant</fullName>
                </value>
                <value>
                    <fullName>Flood Insurance</fullName>
                </value>
                <value>
                    <fullName>Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Journalist</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Loan Officer - Reverse</fullName>
                </value>
                <value>
                    <fullName>Loan Ops</fullName>
                </value>
                <value>
                    <fullName>Non-Agent</fullName>
                </value>
                <value>
                    <fullName>Non-LO</fullName>
                </value>
                <value>
                    <fullName>Other Household Role</fullName>
                </value>
                <value>
                    <fullName>Title</fullName>
                </value>
                <value>
                    <fullName>Title Assistant</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Managing Member</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Chairman</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LO_Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LO Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trained_Date_Time__c</fullName>
        <label>Trained Date Time</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGw</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyLOContactSched_Test.cls
/*************************************************************************************************
 * @className   : SurveyLOContactSched_Test.cls
 * @author      : Omnivo Digital (omnivodigital.com)
 * @date        : May 19, 2019
 * @description : This class provides test methods for SurveyLOContactSched, SurveyLOContactBatch
 *
*************************************************************************************************/

@isTest 
private class SurveyLOContactSched_Test {

	@isTest
	private static void testName() {
		// Data setup
        Account a = new Account();
        a.Name = 'Totally a Real Account';
        insert a;
        
		RecordType conRt = [Select Id from RecordType Where DeveloperName = 'Lender' AND SobjectType = 'Contact'];

        contact con = new Contact(FirstName = 'fname', LastName = 'LName', Email='lname@test.com', AccountId = a.Id,
									RecordTypeId= conRt.Id, Contact_Role__c = 'Loan Officer', Trained_Date_Time__c = Datetime.now().addHours(-3),
									LO_Survey_Sent__c = false);
		insert con;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
        
        // Run the code
        Test.startTest();
			SurveyLOContactSched sh1 = new SurveyLOContactSched();
			Datetime dt = Datetime.now();
			String sch = dt.second() + ' ' + dt.minute() + ' ' + dt.hour() + ' * * ?'; 
			system.schedule('Test Territory Check', sch, sh1);
        Test.stopTest(); 
        
        // Verify Results
		con = [Select Id, LO_Survey_Sent__c from Contact Where Id = :con.Id];
        //System.assertEquals(true, con.LO_Survey_Sent__c);
	}
}