objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGh</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Requirements (MRD)</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Investment_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Investment Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectTasksDocumentNotification.cls
/**
 * Created by Eliot Rojas on 5/1/2019.
 */

public with sharing class ProjectTasksDocumentNotification {
    // CONSTANTS
    private static final Set<String> TEMPLATE_NAMES = new Set<String>{ 'Pest_Inspection_Received', 'Certificate_of_Occupancy_Received',
            'Appraisal_1004D_Received', 'Natural_Hazard_Disclosure_Received', 'HOA_Questionnaire_Received', 'Vesting_Addendum_Received',
            'Hazard_Insurance_Received', 'Lender_Final_1003_Received', 'Lender_Final_1008_Received'};
    private static final List<EmailTemplate> EMAIL_TEMPLATES = [SELECT Id, DeveloperName, BrandTemplateId, IsActive, Body, Subject, HtmlValue
                                                                FROM EmailTemplate WHERE DeveloperName IN : TEMPLATE_NAMES];

    // Process Email alerts (ON INSERT)
    public static void notifyPS(List<Project_Task__c> newList) {
        Set<Id> ptIds = new Set<Id>();
        for(Project_Task__c opp : newList) {
            ptIds.add(opp.Id);
        }

        List<FeedItem> chatterPosts = new List<FeedItem>();
        List<ConnectApi.BatchInput> chatterPostsBatch = new List<ConnectApi.BatchInput>();
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        Map<Id, Project_Task__c> ptMap = new Map<Id, Project_Task__c>([SELECT Id, Name, Code__c, Completed__c, Requirement__c, Requirement__r.Requirement__c, Requirement__r.Name,
                                                                    Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                                                                    Requirement__r.Success_Factor__r.Lead__r.OwnerId, Requirement__r.Opportunity__c, Requirement__r.Opportunity__r.Name,
                                                                    Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId,
                                                                    Requirement__r.Opportunity__r.Investment_Analyst2__c,
                                                                    Requirement__r.Opportunity__r.UnisonProcessor__c
                                                                    FROM Project_Task__c WHERE Id IN : ptIds]);
        Map<String, Id> emailTemplates = new Map<String, Id>();
        for(EmailTemplate template : EMAIL_TEMPLATES) {
            emailTemplates.put(template.DeveloperName, template.Id);
        }

        for(string ptId : ptMap.keySet()) {
            if(ptMap.get(ptId).Requirement__r.Opportunity__r != null) {
                Id oppId = ptMap.get(ptId).Requirement__r.Opportunity__c;
                Id accountOwnerId = ptMap.get(ptId).Requirement__r.Opportunity__r.Account.OwnerId;
                Id investmentAnalystID = ptMap.get(ptId).Requirement__r.Opportunity__r.Investment_Analyst2__c;
                Id transactionSpecialistID = ptMap.get(ptId).Requirement__r.Opportunity__r.UnisonProcessor__c;
                string reqName = ptMap.get(ptId).Requirement__r.Name;
                string oppName = ptMap.get(ptId).Requirement__r.Opportunity__r.Name;
                Project_Task__c pt = ptMap.get(ptId);
                // RSI letter is PT is checked off
                if(pt.Code__c == 'T10182' && pt.Completed__c) {
                    // Post to Record
                    if(investmentAnalystID != null && transactionSpecialistID != null) {
                        ConnectApi.BatchInput postToRecord = chatterPost(oppId, investmentAnalystID, transactionSpecialistID);
                        chatterPostsBatch.add(postToRecord);
                    }
                }
                // Pest Inspection
                if(pt.Code__c == 'Task-258' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Pest_Inspection_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Certificate of Occupancy
                if(pt.Requirement__r.Requirement__c == 'Certificate of Occupancy' && pt.Requirement__r.Status__c == '') {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Certificate_of_Occupancy_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    email.setToAddresses(new List<String>{ pt.Requirement__r.Success_Factor__r.OwnerId, pt.Requirement__r.Success_Factor__r.Lead__r.OwnerId });
                    emailsToSend.add(email);
                }

                // Appraisal - 1004D
                if(pt.Code__c == 'Task-276' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Appraisal_1004D_Received'), accountOwnerId, ptId);
                    emailsToSend.add(email);
                }

                // Natural Hazard Disclosure
                if(pt.Code__c == 'Task-051' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Natural_Hazard_Disclosure_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // HOA Questionaire
                if(pt.Code__c == 'Task-255' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('HOA_Questionnaire_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Vesting Addendum
                if(pt.Code__c == 'Task-042' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Vesting_Addendum_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Hazard Insurance
                if(pt.Requirement__r.Requirement__c == 'Hazard Insurance' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Hazard_Insurance_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Lender Final 1003
                if(pt.Code__c == 'Task-248' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Lender_Final_1003_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Lender Final 1008
                if(pt.Code__c == 'Task-045' && pt.Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Lender_Final_1008_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }
            }
        }
        // Finally send email messages
        if(!emailsToSend.isEmpty()) {
            if(!Test.isRunningTest()) {
                Messaging.sendEmail((List<Messaging.Email>) emailsToSend);
            }
        }
        // Finally post to chatter
        if(!chatterPostsBatch.isEmpty()) {
            if(!Test.isRunningTest()) {
                ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), chatterPostsBatch);
            }
        }
    }


    // Process Email alerts (ON UPDATE)
    public static void notifyPS(List<Project_Task__c> newList, Map<Id, Project_Task__c> oldMap) {
        Set<Id> ptIds = new Set<Id>();
        for(Project_Task__c opp : newList) {
            ptIds.add(opp.Id);
        }

        List<FeedItem> chatterPosts = new List<FeedItem>();
        List<ConnectApi.BatchInput> chatterPostsBatch = new List<ConnectApi.BatchInput>();
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        Map<Id, Project_Task__c> ptMap = new Map<Id, Project_Task__c>([SELECT Id, Name, Code__c, Completed__c, Requirement__c, Requirement__r.Requirement__c, Requirement__r.Name,
                                                                    Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                                                                    Requirement__r.Success_Factor__r.Lead__r.OwnerId, Requirement__r.Opportunity__c, Requirement__r.Opportunity__r.Name,
                                                                    Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId,
                                                                    Requirement__r.Opportunity__r.Investment_Analyst2__c,
                                                                    Requirement__r.Opportunity__r.UnisonProcessor__c
                                                                    FROM Project_Task__c WHERE Id IN : ptIds]);
        Map<String, Id> emailTemplates = new Map<String, Id>();
        for(EmailTemplate template : EMAIL_TEMPLATES) {
            emailTemplates.put(template.DeveloperName, template.Id);
        }

        for(string ptId : ptMap.keySet()) {
            if(ptMap.get(ptId).Requirement__r.Opportunity__r != null) {
                Id oppId = ptMap.get(ptId).Requirement__r.Opportunity__c;
                Id accountOwnerId = ptMap.get(ptId).Requirement__r.Opportunity__r.Account.OwnerId;
                Id investmentAnalystID = ptMap.get(ptId).Requirement__r.Opportunity__r.Investment_Analyst2__c;
                Id transactionSpecialistID = ptMap.get(ptId).Requirement__r.Opportunity__r.UnisonProcessor__c;
                string reqName = ptMap.get(ptId).Requirement__r.Name;
                string oppName = ptMap.get(ptId).Requirement__r.Opportunity__r.Name;
                Project_Task__c pt = ptMap.get(ptId);
                // RSI letter is PT is checked off
                if(pt.Code__c == 'T10182' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    // Post to Record
                    if(investmentAnalystID != null && transactionSpecialistID != null) {
                        ConnectApi.BatchInput postToRecord = chatterPost(oppId, investmentAnalystID, transactionSpecialistID);
                        chatterPostsBatch.add(postToRecord);
                    }
                }
                // Pest Inspection
                if(pt.Code__c == 'Task-258' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Pest_Inspection_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Certificate of Occupancy
                if(pt.Requirement__r.Requirement__c == 'Certificate of Occupancy' && pt.Requirement__r.Status__c == '' && pt.Requirement__r.Status__c != oldMap.get(ptId).Requirement__r.Status__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Certificate_of_Occupancy_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    email.setToAddresses(new List<String>{ pt.Requirement__r.Success_Factor__r.OwnerId, pt.Requirement__r.Success_Factor__r.Lead__r.OwnerId });
                    emailsToSend.add(email);
                }

                // Appraisal - 1004D
                if(pt.Code__c == 'Task-276' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Appraisal_1004D_Received'), accountOwnerId, ptId);
                    emailsToSend.add(email);
                }

                // Natural Hazard Disclosure
                if(pt.Code__c == 'Task-051' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Natural_Hazard_Disclosure_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // HOA Questionaire
                if(pt.Code__c == 'Task-255' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('HOA_Questionnaire_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Vesting Addendum
                if(pt.Code__c == 'Task-042' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Vesting_Addendum_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Hazard Insurance
                if(pt.Requirement__r.Requirement__c == 'Hazard Insurance' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Hazard_Insurance_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Lender Final 1003
                if(pt.Code__c == 'Task-248' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Lender_Final_1003_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }

                // Lender Final 1008
                if(pt.Code__c == 'Task-045' && pt.Completed__c && pt.Completed__c != oldMap.get(ptId).Completed__c) {
                    Messaging.SingleEmailMessage email = sendEmail(emailTemplates.get('Lender_Final_1008_Received'), accountOwnerId, pt.Requirement__r.Opportunity__c);
                    emailsToSend.add(email);
                }
            }
        }
        // Finally send email messages
        if(!emailsToSend.isEmpty()) {
            if(!Test.isRunningTest()) {
                Messaging.sendEmail((List<Messaging.Email>) emailsToSend);
            }
        }

        // Finally post to chatter
        if(!chatterPostsBatch.isEmpty()) {
            if(!Test.isRunningTest()) {
                ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), chatterPostsBatch);
            }
        }
    }

    private static Messaging.SingleEmailMessage sendEmail(Id templateId, Id whoId, Id whatId) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        Messaging.SingleEmailMessage renderedTemplate = Messaging.renderStoredEmailTemplate(templateId, whoId, whatId);
        String emailSubject = renderedTemplate.getSubject();
        String emailTextBody = renderedTemplate.getHtmlBody();
        mail.setTargetObjectId(whoId);
        mail.setHtmlBody(emailTextBody);
        mail.setSubject(emailSubject);
        mail.setSaveAsActivity(false);
        return mail;
    }

    // Generate Chatter post
    private static ConnectApi.BatchInput chatterPost(Id parentId, Id investmentAnalystID, Id transactionSpecialistID) {
        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput2 = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
        ConnectApi.TextSegmentInput textSegmentInput2 = new ConnectApi.TextSegmentInput();
        ConnectApi.TextSegmentInput textSegmentInput3 = new ConnectApi.TextSegmentInput();

        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();

        textSegmentInput.text = 'Hi ';
        messageBodyInput.messageSegments.add(textSegmentInput);

        mentionSegmentInput.id = transactionSpecialistID;
        messageBodyInput.messageSegments.add(mentionSegmentInput);

        textSegmentInput2.text = ', \n\nThe RSI Letter has been populated by ';
        messageBodyInput.messageSegments.add(textSegmentInput2);

        mentionSegmentInput2.id = investmentAnalystID;
        messageBodyInput.messageSegments.add(mentionSegmentInput2);

        textSegmentInput3.text = ' and is now ready to be generated and sent to the customer.';
        messageBodyInput.messageSegments.add(textSegmentInput3);

        feedItemInput.body = messageBodyInput;
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = parentId;

        ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(feedItemInput);
        return batchInput;
    }
}