objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>012E00000002OGX</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <description>Homebuyer only. Whether the first mortgage will be agency or non-agency. As of
            Q4-2019, this field has been identified by Business Systems (and relevant stakeholders)
            as used or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Pre_Qualification_Status__c</fullName>
        <description>Status indicating whether the person is credit qualified. It is set
            automatically when Laser Credit pulls the credit. This is not the self-stated credit.
            No-match means that Laser credit wasn't able identify the person. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Credit Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Match</fullName>
                </value>
                <value>
                    <fullName>Approved (Single score)</fullName>
                </value>
                <value>
                    <fullName>Declined (Single score)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Unison's Investment Payment. This amount should not exceed Max Offer amount.</inlineHelpText>
        <label>Estimated Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Monthly_Base__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Income field used to determine DTI for the Lead: Base Income of the
            Applicant.</inlineHelpText>
        <label>Income Monthly Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Officer_ID__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Loan Officer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It's a link to the credit report of the lead contact As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Selected Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Lead__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Pricing Ratio based on Unison Program</inlineHelpText>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>City of prospective customer's property</inlineHelpText>
        <label>Property Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Property Street Number and Street Name</inlineHelpText>
        <label>Property Address Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Zip Code of customer's property</inlineHelpText>
        <label>Property Address Zip/Postal Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>HB Lead Status</businessProcess>
        <description>012E00000002OGS</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <description>Describes if (HomeBuyer) mortgage is an Agency or Non-Agency Mortgage. Agency is when the mortgage can be sold to Fannie or Freddie.</description>
        <inlineHelpText>Describes if (HomeBuyer) mortgage is an Agency or Non-Agency Mortgage. Agency is when the mortgage can be sold to Fannie or Freddie.</inlineHelpText>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Pre_Qualification_Status__c</fullName>
        <label>Credit Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Match</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DocuSign_Returned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DocuSign Returned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the Estimated Home Value stated from customer or Unison AVM</description>
        <inlineHelpText>This is the Estimated Home Value stated from customer or Unison AVM</inlineHelpText>
        <label>Estimated Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Officer_ID__c</fullName>
        <label>Loan Officer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Applicant__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEND_TO_ENCOMPASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Used for EOS go live only. May be deleted after Encompass LOS system is no longer used</inlineHelpText>
        <label>SEND_TO_ENCOMPASS</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PCR_trigger_handler_tests.cls
/**
 *  About
 *  -----
 *  Author: Cloud Mine Consulting
 *  Create date: 9/1/2017
 *  
 *  Details
 *  -----
 *  Test class for PCR Trigger and PCR Trigger Handler class
 *  
 *  Update History
 *  -----
 * 
 *  Issues / TODOs
 *  -----
 * 
**/
@isTest
public class PCR_trigger_handler_tests {

    /**
     *  About
     *  -----
     *  Author: Cloud Mine Consulting
     *  
     *  Details
     *  -----
     *  Test Class for PCR Trigger/Handlers
    **/
    private static testMethod void testPCRTriggers(){

        Schema.DescribeSObjectResult leadResult = Lead.SobjectType.getDescribe();
        Map<string, Schema.RecordTypeInfo> leadRTNameMap = leadResult.getRecordTypeInfosByName();

        Lead newLead = new Lead();
        newLead.RecordTypeId = leadRTNameMap.get('HomeBuyer').getRecordTypeId();
        newLead.FirstName = 'First';
        newLead.LastName = 'Last';
        newLead.Email = 'firstlast@unison.com';
        newLead.Phone = '1234567890';
        newLead.Company = 'First Last Household';
        newLead.Status = 'New';
        newLead.Street = 'Test Street';
        newLead.City = 'Test City';
        newLead.State = 'Test State';
        newLead.PostalCode = 'TestCode';
        newLead.Income_Monthly_Base__c = 8000;
        newLead.Home_Value__c = 500000;
        insert newLead;

        LASERCA__Personal_Credit_Report__c PCR = new LASERCA__Personal_Credit_Report__c(Name = 'Test PCR');
        PCR.LASERCA__Credit_Score_Equifax__c = '705';
        PCR.LASERCA__Credit_Score_Experian__c = '705';
        PCR.LASERCA__Credit_Score_TransUnion__c = '705';
        insert PCR;
        PCR.LASERCA__Lead__c = newLead.Id;
        update PCR;

        LASERCA__Personal_Credit_Report__c resultPCR = [SELECT Credit_Pre_Qualification_Status__c FROM LASERCA__Personal_Credit_Report__c WHERE Id =:PCR.Id];
        Lead resultLead = [SELECT Credit_Pre_Qualification_Status__c FROM Lead WHERE Id =:newLead.Id];
        system.assertEquals(resultPCR.Credit_Pre_Qualification_Status__c, resultLead.Credit_Pre_Qualification_Status__c);

        PCR.Credit_Pre_Qualification_Status__c = 'Approved';
        update PCR;
        resultLead = [SELECT Credit_Pre_Qualification_Status__c FROM Lead WHERE Id =:newLead.Id];
        system.assertEquals('Approved', resultLead.Credit_Pre_Qualification_Status__c);
        
        //Delete TEst
        delete PCR;
        //TO-DO: could use more assert statements here

        //Undelete Test
        undelete PCR;
        //TO-DO: could use more assert statements here
    }

    private static testMethod void test_HomeOwner_Tier1_Decline(){

        Schema.DescribeSObjectResult leadResult = Lead.SobjectType.getDescribe();
        Map<string, Schema.RecordTypeInfo> leadRTNameMap = leadResult.getRecordTypeInfosByName();

        Lead newLead = new Lead();
        newLead.RecordTypeId = leadRTNameMap.get('HomeOwner').getRecordTypeId();
        newLead.FirstName = 'First';
        newLead.LastName = 'Last';
        newLead.Email = 'tester@unison.com';
        newLead.Phone = '1234567890';
        newLead.Company = 'First Last Household';
        newLead.Status = 'New';
        newLead.Street = 'Test Street';
        newLead.City = 'Test City';
        newLead.State = 'Test State';
        newLead.PostalCode = 'TestCode';
        newLead.Income_Monthly_Base__c = 8000;
        newLead.Home_Value__c = 500000;
        insert newLead;

        LASERCA__Personal_Credit_Report__c PCR = new LASERCA__Personal_Credit_Report__c(Name = 'Test PCR');
        PCR.LASERCA__Credit_Score_Equifax__c = '685';
        PCR.LASERCA__Credit_Score_Experian__c = '685';
        PCR.LASERCA__Credit_Score_TransUnion__c = '685';
        insert PCR;
        PCR.LASERCA__Lead__c = newLead.Id;
        update PCR;

        LASERCA__Personal_Credit_Report__c resultPCR = [SELECT Credit_Pre_Qualification_Status__c FROM LASERCA__Personal_Credit_Report__c WHERE Id =:PCR.Id];
        Lead resultLead = [SELECT Credit_Pre_Qualification_Status__c FROM Lead WHERE Id =:newLead.Id];
        system.assertEquals(resultPCR.Credit_Pre_Qualification_Status__c, resultLead.Credit_Pre_Qualification_Status__c);
        system.assertEquals('Declined', resultLead.Credit_Pre_Qualification_Status__c);

    }

    private static testMethod void test_HomeBuyer_Tier1_Decline(){

        Schema.DescribeSObjectResult leadResult = Lead.SobjectType.getDescribe();
        Map<string, Schema.RecordTypeInfo> leadRTNameMap = leadResult.getRecordTypeInfosByName();

        Lead newLead = new Lead();
        newLead.RecordTypeId = leadRTNameMap.get('HomeBuyer').getRecordTypeId();
        newLead.FirstName = 'First';
        newLead.LastName = 'Last';
        newLead.Email = 'tester@unison.com';
        newLead.Phone = '1234567890';
        newLead.Company = 'First Last Household';
        newLead.Status = 'New';
        newLead.Street = 'Test Street';
        newLead.City = 'Test City';
        newLead.State = 'Test State';
        newLead.PostalCode = 'TestCode';
        newLead.Income_Monthly_Base__c = 8000;
        newLead.Home_Value__c = 500000;
        insert newLead;

        LASERCA__Personal_Credit_Report__c PCR = new LASERCA__Personal_Credit_Report__c(Name = 'Test PCR');
        PCR.LASERCA__Credit_Score_Equifax__c = '619';
        PCR.LASERCA__Credit_Score_Experian__c = '619';
        PCR.LASERCA__Credit_Score_TransUnion__c = '619';
        insert PCR;
        PCR.LASERCA__Lead__c = newLead.Id;
        update PCR;

        LASERCA__Personal_Credit_Report__c resultPCR = [SELECT Credit_Pre_Qualification_Status__c FROM LASERCA__Personal_Credit_Report__c WHERE Id =:PCR.Id];
        Lead resultLead = [SELECT Credit_Pre_Qualification_Status__c FROM Lead WHERE Id =:newLead.Id];
        system.assertEquals(resultPCR.Credit_Pre_Qualification_Status__c, resultLead.Credit_Pre_Qualification_Status__c);
        system.assertEquals('Declined', resultLead.Credit_Pre_Qualification_Status__c);

    }


    private static testMethod void test_Opportunity(){

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;

        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
        newOpportunity.Estimated_Funding_Amount__c = 10;
        newOpportunity.Pricing_Ratio__c = 10;
        newOpportunity.Final_OAV_Calculation__c = 10;
        newOpportunity.IA_OAV_Override__c = 10;
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.SEND_TO_ENCOMPASS__c = true;
        insert newOpportunity;

        Test.startTest();
        LASERCA__Personal_Credit_Report__c PCR = new LASERCA__Personal_Credit_Report__c(Name = 'Test PCR');
        PCR.LASERCA__Credit_Score_Equifax__c = '619';
        PCR.LASERCA__Credit_Score_Experian__c = '619';
        PCR.LASERCA__Credit_Score_TransUnion__c = '619';
        insert PCR;
        PCR.Opportunity__c = newOpportunity.Id;
        update PCR;
        Set<Id> ids = new Set<Id>();
        ids.add(newOpportunity.Id);
        PCR_trigger_handler.rollupPCRToOpp(ids);
        Test.stopTest();

        LASERCA__Personal_Credit_Report__c resultPCR = [SELECT Opportunity__c, Credit_Pre_Qualification_Status__c FROM LASERCA__Personal_Credit_Report__c WHERE Id =:PCR.Id];
        Opportunity resultOpportunity = [SELECT Personal_Credit_Report__c FROM Opportunity WHERE Id =: newOpportunity.Id];
        system.debug('++ resultPCR ' + resultPCR);
        system.debug('++ resultOpportunity ' + resultOpportunity.Personal_Credit_Report__c);
    }
    
    private static testMethod void test_manualTradeAcount(){

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;

        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAccount.Id;
        newOpportunity.StageName = 'Property in Contract';
        newOpportunity.CloseDate = System.today();
        newOpportunity.Agency_or_Non_Agency__c = 'Agency';
        newOpportunity.Estimated_Funding_Amount__c = 10;
        newOpportunity.Pricing_Ratio__c = 10;
        newOpportunity.Final_OAV_Calculation__c = 10;
        newOpportunity.IA_OAV_Override__c = 10;
        newOpportunity.DocuSign_Returned__c = true;
        newOpportunity.Loan_Officer_ID__c = '12345';
        newOpportunity.Property_Street_Number_and_Name__c = 'Street';
        newOpportunity.Property_City__c = 'City';
        newOpportunity.Property_State__c = 'State';
        newOpportunity.Property_Zip_Code__c = '12345';
        newOpportunity.SEND_TO_ENCOMPASS__c = true;
        insert newOpportunity;

        LASERCA__Personal_Credit_Report__c PCR1 = new LASERCA__Personal_Credit_Report__c(Name = 'Test PCR1');
        PCR1.LASERCA__Credit_Score_Equifax__c = '619';
        PCR1.LASERCA__Credit_Score_Experian__c = '619';
        PCR1.LASERCA__Credit_Score_TransUnion__c = '619';
        PCR1.Opportunity__c = newOpportunity.Id;
        insert PCR1;
        
        LASERCA__Trade_Accounts__c trdacc = new LASERCA__Trade_Accounts__c();
        trdacc.Name = 'TestManualAccount988756';
        trdacc.Credit_Loan_Type_pick__c = 'Mortgage';
        trdacc.To_Be_Paid_Off__c = TRUE;
        trdacc.Lien_Position__c  = '2';
        trdacc.Amount_To_Pay_Off2__c = 5000;
        trdacc.LASERCA__Monthly_Payment__c = 10000;
        trdacc.LASERCA__Account_Balance__c = 5000;
        trdacc.LASERCA__Personal_Credit_Report__c = PCR1.Id;
        trdacc.Target_Pct_Value_Of_Home__c = 0.10;
        
        LASERCA__Trade_Accounts__c trdacc2 = new LASERCA__Trade_Accounts__c();
        trdacc2.Name = 'TestManualAccount988751';
        trdacc2.LASERCA__Account_Identifier__c = '1234';
        trdacc2.Credit_Loan_Type_pick__c = 'Mortgage';
        trdacc2.To_Be_Paid_Off__c = TRUE;
        trdacc2.Lien_Position__c  = '2';
        trdacc2.Amount_To_Pay_Off2__c = 5000;
        trdacc2.LASERCA__Monthly_Payment__c = 10000;
        trdacc2.LASERCA__Account_Balance__c = 5000;
        trdacc2.LASERCA__Personal_Credit_Report__c = PCR1.Id;
        trdacc2.Target_Pct_Value_Of_Home__c = 0.10;
        insert new List<LASERCA__Trade_Accounts__c> { trdacc, trdacc2 };
            
        Test.startTest();
        
        LASERCA__Personal_Credit_Report__c PCR2 = new LASERCA__Personal_Credit_Report__c(Name = 'Test PCR2');
        PCR2.LASERCA__Credit_Score_Equifax__c = '619';
        PCR2.LASERCA__Credit_Score_Experian__c = '619';
        PCR2.LASERCA__Credit_Score_TransUnion__c = '619';
        PCR2.Opportunity__c = newOpportunity.Id;
        insert PCR2;
        
        Test.stopTest();

        //Verify results
		
        LASERCA__Trade_Accounts__c resultTAClone = [SELECT Id, Manual_TA_Copied__c FROM LASERCA__Trade_Accounts__c WHERE LASERCA__Personal_Credit_Report__c = :PCR2.Id LIMIT 1];
        System.assertEquals(false, resultTAClone.Manual_TA_Copied__c);
        
        LASERCA__Trade_Accounts__c resultTACopied = [SELECT Id, Manual_TA_Copied__c FROM LASERCA__Trade_Accounts__c WHERE Id = :trdacc.Id LIMIT 1];
        System.assertEquals(true, resultTACopied.Manual_TA_Copied__c);
        
        LASERCA__Trade_Accounts__c resultTARemain = [SELECT Id, LASERCA__Personal_Credit_Report__c FROM LASERCA__Trade_Accounts__c WHERE Id = :trdacc2.Id];
        System.assertEquals(pcr1.Id, resultTARemain.LASERCA__Personal_Credit_Report__c);
    }

}