objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGh</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Broker/Owner</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Editor/Producer</fullName>
                </value>
                <value>
                    <fullName>Escrow</fullName>
                </value>
                <value>
                    <fullName>Escrow Assistant</fullName>
                </value>
                <value>
                    <fullName>Flood Insurance</fullName>
                </value>
                <value>
                    <fullName>Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Journalist</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Loan Officer - Reverse</fullName>
                </value>
                <value>
                    <fullName>Loan Ops</fullName>
                </value>
                <value>
                    <fullName>Non-Agent</fullName>
                </value>
                <value>
                    <fullName>Non-LO</fullName>
                </value>
                <value>
                    <fullName>Other Household Role</fullName>
                </value>
                <value>
                    <fullName>Title</fullName>
                </value>
                <value>
                    <fullName>Title Assistant</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Managing Member</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Chairman</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lender</fullName>
        <active>true</active>
        <description>012E00000002OGw</description>
        <label>Lender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Source__c</fullName>
        <description>Owen check with Jessica to get context As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Campaign source (e.g. Bing, Google, Facebook)</inlineHelpText>
        <label>Campaign Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Net_Promoter_Measurement__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Answers__c</fullName>
        <label>Additional Answers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permalink__c</fullName>
        <label>Permalink</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Net Promoter Measurement</label>
    <nameField>
        <displayFormat>NPM-{0000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Net Promoter Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelightedTests.cls
@isTest
public class DelightedTests {

    @isTest
    public static void TestSendLead(){
        
        // Data setup
        Lead l = new Lead();
        l.FirstName = 'RealFirstName';
        l.LastName = 'RealLastName923078';
        l.Email = 'AnEmail.email923078@example.com';
        l.Company = 'Company923078';
        l.Campaign_Source__c = 'web';
        insert l;
        
        Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
        npm.Status__c = 'Draft';
        npm.Lead__c = l.Id;
        insert npm;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
        
        // Run the code
        Test.startTest();
        DelightedHelper.SendSurveyLead(npm.Id, l.Id);
        Test.stopTest();
        
        // Verify Results
        System.assertEquals(1, [SELECT COUNT() FROM Net_Promoter_Measurement__c WHERE Lead__c = :l.Id]);
    }
    
    @isTest
    public static void TestSendOpportunity(){
        
        // Data setup
        Account a = new Account();
        a.Name = 'Totally a Real Account';
        insert a;
        
        Opportunity o = new Opportunity();
        o.Name = 'Opportunity923079';
        o.StageName = 'Introduction';
        o.CloseDate = Date.today();
        o.AccountId = a.Id;
        insert o;
        
        Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
        npm.Status__c = 'Draft';
        npm.Opportunity__c = o.Id;
        insert npm;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
        
        // Run the code
        Test.startTest();
        DelightedHelper.SendSurveyOpportunity(npm.Id, o.Id);
        Test.stopTest();
        
        // Verify Results
        System.assertEquals(1, [SELECT COUNT() FROM Net_Promoter_Measurement__c WHERE Opportunity__c = :o.Id]);
    }

	@isTest
    public static void TestSendContact(){
        
        // Data setup
        Account a = new Account();
        a.Name = 'Totally a Real Account';
        insert a;
        
		Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('contact').getDescribe();
        Id rtId = describeResult.getRecordTypeInfosByName().get('Lender').getRecordTypeId();

        contact con = new Contact(FirstName = 'fname', LastName = 'LName', Email='lname@test.com', AccountId = a.Id,
									RecordTypeId= rtId, Contact_Role__c = 'Loan Officer');
		insert con;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
        
        // Run the code
        Test.startTest();
        DelightedHelper.SendSurveyLOContact(con);
        Test.stopTest();
        
        // Verify Results
        System.assertEquals(1, [SELECT COUNT() FROM Net_Promoter_Measurement__c WHERE Contact__c = :con.Id]);
    }
    
    @isTest
    public static void TestWebhook(){
        
        // Data setup
        Lead l = new Lead();
        l.FirstName = 'RealFirstName90210';
        l.LastName = 'RealLastName90210';
        l.Email = 'email90210@example.com';
        l.Company = 'Company90210';
        l.Campaign_Source__c = 'web';
        insert l;
        
        Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
        npm.Lead__c = l.Id;
        insert npm;
                
        // Run the code
        Test.startTest();
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestBody = Blob.valueOf('{ ' +
                                              '"event_type": "survey_response.updated", ' +
                                              '"event_id": "b8d057c59327541d7ec2104c0a9a255ad1997fb00831b9c6bbf09561e6d5cbd0", ' +
                                              '"event_data": { ' +
                                                '"id": "5435", ' +
                                                '"person": { ' +
                                                  '"id": "5975", ' +
                                                  '"email": "charlie_gravis@example.com", ' +
                                                  '"name": "Charlie Gravis", ' +
                                                  '"created_at": 1553182454 ' +
                                                '}, ' +
                                                '"survey_type": "nps", ' +
                                                '"score": 9, ' +
                                                '"comment": "Your service is fast and flawless!", ' +
                                                '"permalink": "https://delighted.com/r/5pFDpmlyC8GUc5oxU6USto5VonSKAqOa", ' +
                                                '"created_at": 1553182514, ' +
                                                '"updated_at": 1553183114, ' +
                                                '"person_properties": { "lead" : "' + l.Id + '" }, ' +
                                                '"notes": [], ' +
                                                '"tags": [], ' +
                                                '"additional_answers": [ ' +
                                                  '{ ' +
                                                    '"id": "4", ' +
                                                    '"value": { ' +
                                                      '"free_response": null, ' +
                                                      '"scale": null, ' +
                                                      '"select_one": null, ' +
                                                      '"select_many": [ ' +
                                                        '{ ' +
                                                          '"id": "DxmjNj", ' +
                                                          '"text": "Convenience" ' +
                                                        '}, ' +
                                                        '{ ' +
                                                          '"id": "uNQIig", ' +
                                                          '"text": "Friendly staff" ' +
                                                        '} ' +
                                                      '] ' +
                                                    '}, ' +
                                                    '"question": { ' +
                                                      '"id": "enum_z9EvYV", ' +
                                                      '"type": "select_many", ' +
                                                      '"text": "What specifically did you enjoy about your experience with us?" ' +
                                                    '} ' +
                                                  '}, ' +
                                                  '{ ' +
                                                    '"id": "5", ' +
                                                    '"value": { ' +
                                                      '"free_response": null, ' +
                                                      '"scale": null, ' +
                                                      '"select_one": { ' +
                                                        '"id": "tp0Q4K", ' +
                                                        '"text": "Yes" ' +
                                                      '}, ' +
                                                      '"select_many": null ' +
                                                    '}, ' +
                                                    '"question": { ' +
                                                      '"id": "enum_caUUdY", ' +
                                                      '"type": "select_one", ' +
                                                      '"text": "Have you purchased from us in the past?" ' +
                                                    '} ' +
                                                  '}, ' +
                                                  '{ ' +
                                                    '"id": "6", ' +
                                                    '"value": { ' +
                                                      '"free_response": null, ' +
                                                      '"scale": 4, ' +
                                                      '"select_one": null, ' +
                                                      '"select_many": null ' +
                                                    '}, ' +
                                                    '"question": { ' +
                                                      '"id": "integer_buwb3w", ' +
                                                      '"type": "scale", ' +
                                                      '"text": "How often do you shop at one of our stores?" ' +
                                                    '} ' +
                                                  '}, ' +
                                                  '{ ' +
                                                    '"id": "7", ' +
                                                    '"value": { ' +
                                                      '"free_response": "A friend recommended you to me!", ' +
                                                      '"scale": null, ' +
                                                      '"select_one": null, ' +
                                                      '"select_many": null ' +
                                                    '}, ' +
                                                    '"question": { ' +
                                                      '"id": "text_BJPEm0", ' +
                                                      '"type": "free_response", ' +
                                                      '"text": "How did you hear about us?" ' +
                                                    '} ' +
                                                  '} ' +
                                                '] ' +
                                              '} ' +
                                            '}');
        DelightedWebhook.doPost(); 
        Test.stopTest();
        
        // Verify Results
        npm = [SELECT Comment__c, PermaLink__c, Score__c, Additional_Answers__c FROM Net_Promoter_Measurement__c WHERE Lead__c = :l.Id];
        System.assertEquals('Your service is fast and flawless!', npm.Comment__c);
        System.assertEquals(9, npm.Score__c);
        System.assertEquals('https://delighted.com/r/5pFDpmlyC8GUc5oxU6USto5VonSKAqOa', npm.PermaLink__c);
        System.debug(npm.Additional_Answers__c);
    }
}