objects/Appraisal__c.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Status__c</fullName>
        <label>Appraisal Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appraisals</relationshipLabel>
        <relationshipName>Appraisals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MercuryAWSHelperTest.cls
/**
 * Created by Ivan Garcia on 5/22/2019.
 */

@IsTest public with sharing class MercuryAWSHelperTest {
    @testSetup static void setup(){
        Account acc  = new Account(Name = 'acc test');
        insert acc;

        Opportunity opp  = new opportunity(Name = 'opp test', AccountId = acc.Id, StageName= 'Closed Won', CloseDate = System.today());
        insert opp;

        Appraisal__c tmpApp = new Appraisal__c(Appraisal_Status__c = 'Ordered', Opportunity__c = opp.Id);
        insert tmpApp;
    }

    @isTest private static void test0(){
        Test.setMock(HttpCalloutMock.class, new HttpMockTest());
        Test.startTest();
        Appraisal__c tmpApp = [SELECT id FROM Appraisal__c LIMIT 1];
        MercuryAWSHelper.CallAWS(tmpApp.id);
        Test.stopTest();
    }
}