objects/Appraisal__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appraisals</relationshipLabel>
        <relationshipName>Appraisals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <formula>Opportunity__r.Property_County__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>Opportunity__r.Property_State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <formula>Opportunity__r.Property_Street_Number_and_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Street Number and Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <formula>Opportunity__r.Property_Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Zip Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Appraisals</relationshipLabel>
        <relationshipName>Appraisals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MercuryCredential__mdt.object
<CustomObject>
    <description>Stores credentials for Salesforce to access Mercury</description>
    <fields>
        <fullName>EntityID__c</fullName>
        <label>EntityID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>MercuryCredential</label>
    <pluralLabel>MercuryCredentials</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted_Close_Date__c</fullName>
        <label>Converted Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single-family detached</fullName>
    </customValue>
    <customValue>
        <fullName>Condominium</fullName>
    </customValue>
    <customValue>
        <fullName>2-4 Family</fullName>
    </customValue>
    <customValue>
        <fullName>PUD</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Detached</fullName>
        <isActive>false</isActive>
        <label>Detached</label>
    </customValue>
    <masterLabel>Property Type</masterLabel>
</GlobalValueSet>

classes/Opp_Mercury_EXTTest.cls
@isTest
public class Opp_Mercury_EXTTest {
    

    @testSetup static void setup(){
        MercuryCredential__mdt MercCred = new MercuryCredential__mdt();
        Map<String, Object> fields = (Map<String,Object>) JSON.deserializeUntyped(JSON.serializePretty(MercCred));
        fields.put(MercuryCredential__mdt.Username__c.getDescribe().getName(),'test@testingtong.com');
        fields.put(MercuryCredential__mdt.URL__c.getDescribe().getName(),'www.test.com');
        fields.put(MercuryCredential__mdt.Password__c.getDescribe().getName(),'test group');
        fields.put(MercuryCredential__mdt.EntityID__c.getDescribe().getName(),121314);
        MercCred=(MercuryCredential__mdt) JSON.deserialize(JSON.serialize(fields), MercuryCredential__mdt.class);
                     Account acc = new Account();
             acc.Name = 'test';
             insert acc;
             Contact con = new Contact();
             con.LastName = 'test1';
             con.FirstName = 'test1';
             insert con;
             Contact con1 = new Contact();
             con1.lastName = 'test1';
             con1.FirstName = 'test1';
             insert con1;
             Opportunity opp = new Opportunity();
             opp.Ownerid = userinfo.getuserid();
             opp.Name = 'test';
             opp.AccountId = acc.Id;
             opp.StageName = 'Submit to Ops';
             opp.CloseDate = system.today();
             opp.Property_Type__c = '2-4 Family';
             opp.Converted_Close_Date__c = system.today();
             opp.Encompass_Loan_Number__c = '67';
             opp.Applicant__c = con.Name;
             opp.Co_Applicant__c = con1.Name;
             opp.Final_OAV_Calculation__c = 56.09;
             opp.Lien_First_Lender_Balance__c = 56.00;
             opp.Property_Street_Number_and_Name__c = '34 st';
             opp.Property_City__c = 'Albany';
             opp.Property_State__c = 'NY';
             opp.Property_Zip_Code__c = '12345';
             opp.Property_County__c = 'US';
             opp.IA_OAV_Override__c = 2;
             insert opp;
             Success_Factor__c sf = new Success_Factor__c();
             sf.Status__c = 'In Progress';             
             insert sf;
             Current_Conditions__c requirement1 = new Current_Conditions__c();
             requirement1.Opportunity__c = opp.Id;
             requirement1.Code__c = 'R1008';
             requirement1.Requirement__c = 'Appraisal - 1st';
             requirement1.Success_Factor__c = sf.Id;
             insert requirement1;
        	Current_Conditions__c requirement2 = new Current_Conditions__c();
             requirement2.Opportunity__c = opp.Id;
             requirement2.Code__c = 'R1009';
             requirement2.Requirement__c = 'Appraisal - 2nd';
             requirement2.Success_Factor__c = sf.Id;
             requirement2.Appraisal_Genesis__c = 'Greenlight Requested';
             insert requirement2;
        	Current_Conditions__c requirement3 = new Current_Conditions__c();
             requirement3.Opportunity__c = opp.Id;
             requirement3.Code__c = 'R1009';
             requirement3.Requirement__c = 'Appraisal - 2nd';
             requirement3.Success_Factor__c = sf.Id;
             requirement3.Appraisal_Genesis__c = 'Greenlight Requested';
             insert requirement3;
             Appraisal__c newAppraisal = new Appraisal__c();
            newAppraisal.Appraisal_Ordered_Date__c = Date.today();
            newAppraisal.Source__c = '--none--';
            newAppraisal.Opportunity__c = opp.Id;

            insert newAppraisal;
    }
 
    static testMethod void mercuryTest2(){

    Test.setMock(HttpCalloutMock.class, new SpruceCalloutMock());
			Opportunity opp=[Select Id from Opportunity Limit 1];
            ApexPages.StandardController sc = new ApexPages.StandardController(opp);
            Opp_Mercury_EXT mercuryExt = new Opp_Mercury_EXT(sc);
            PageReference pageRef = Page.Opp_Mercury_VF;
            Test.setCurrentPage(pageRef);
        	//List<SelectOption> ListOption=mercuryExt.amcCompanies;
            //mercuryExt.selectedProduct = 'FNMA 2055 Exterior';
            //mercuryExt.selectedAmcCompany = '--None--';

            mercuryExt.checkConfirmation();
            mercuryExt.confirmationProvided();
            mercuryExt.confirmationRefused();
            mercuryExt.BackToOppty();
            try{
                mercuryExt.generateOrderAppraisal();
            }catch(Exception e){}
            try{
                mercuryExt.generateOrderAppraisalStep2();
            }catch(Exception e){} 
        	System.assertNotEquals(null, opp);
    }
 
}