objects/Appraisal__c.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Ordered_Date__c</fullName>
        <label>Ordered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MercuryTrackingId__c</fullName>
        <label>MercuryTrackingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appraisals</relationshipLabel>
        <relationshipName>Appraisals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <formula>Opportunity__r.Property_County__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>Opportunity__r.Property_State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <formula>Opportunity__r.Property_Street_Number_and_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Street Number and Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <formula>Opportunity__r.Property_Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Zip Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Appraisals</relationshipLabel>
        <relationshipName>Appraisals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Appraisal Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mercury_Phone__c</fullName>
        <formula>RIGHT( Phone  , 10)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mercury Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted_Close_Date__c</fullName>
        <label>Converted Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Loan_Type__c</fullName>
        <label>Lien First Loan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Loan_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <inlineHelpText>HomeBuyer field</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Agreed_Value__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <formula>IF( RecordTypeId = '012E00000002OH1', MIN(
                                      IF(ISBLANK(Appraised_Home_Value__c) || Appraised_Home_Value__c = 0, Home_Value__c , Appraised_Home_Value__c),
                                      IF(ISBLANK(Purchase_Price__c) || Purchase_Price__c = 0, 9999999999999999, Purchase_Price__c) 
                                     ),
IF(RecordTypeId= '012E00000002OHB', IF(ISBLANK(Appraised_Home_Value__c) || Appraised_Home_Value__c = 0,  Home_Value__c , Appraised_Home_Value__c - OAV_Discount_Amount__c), 9999999999999999)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original Agreed Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Loan_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>First Mortgage</fullName>
    </customValue>
    <customValue>
        <fullName>Second Mortgage</fullName>
    </customValue>
    <customValue>
        <fullName>Reverse Mortgage</fullName>
    </customValue>
    <masterLabel>Loan Type</masterLabel>
</GlobalValueSet>

globalValueSets/Property_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single-family detached</fullName>
    </customValue>
    <customValue>
        <fullName>Condominium</fullName>
    </customValue>
    <customValue>
        <fullName>2-4 Family</fullName>
    </customValue>
    <customValue>
        <fullName>PUD</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Detached</fullName>
        <isActive>false</isActive>
        <label>Detached</label>
    </customValue>
    <masterLabel>Property Type</masterLabel>
</GlobalValueSet>

classes/Opp_Mercury_EXT.cls
/**********************************************************
 * @className   : Opp_Mercury_EXT.cls
 * @testClass   : Opp_Mercury_EXT_TEST.cls
 * @date        : May 31, 2018
 *
 *
 **********************************************************/ 

public class Opp_Mercury_EXT {

    private Opportunity opp;
    public Boolean displayError {get; set;}
    public List<SelectOption> propertyType {get; set;}
    public String selectedAmcCompany {get; set;}
    public String selectedProduct {get; set;}
    public String selectedPropertyType {get; set;}
    public String selectedRequirement {get; set;}
    public Opportunity dummyOpp {get; set;}
    public List<SelectOption> availableRequirementList {get; set;}
    
    public Boolean needConfirmation { get; set; }
    public Boolean showConfirmation { get; set; }
    public Boolean confirmationReceived { get; set; }
    
    private List<SelectOption> amcCompaniesP;
    public List<SelectOption> amcCompanies {
        get {
            if (amcCompaniesP == null) {
                amcCompaniesP = new List<SelectOption>();
                amcCompaniesP.add(new SelectOption('--None--', '-- Please select --'));
                amcCompaniesP.addAll(MercuryHelper.GetAMCCompanies());
            }
            return amcCompaniesP;
        }
    }
    private List<SelectOption> productListP;
    public List<SelectOption> productList {
        get {
            if (productListP == null) {
                productListP = new List<SelectOption>();
                productListP.add(new SelectOption('--None--', '-- Please select --'));
                productListP.addAll(MercuryHelper.GetTypesOfAppraisal());
            }
            return productListP;
        }
    }
    
    public final List<String> dmdCodes =  new List<String> { 'R1008', 'R1009', 'R1010' };
    public final List<String> reqTypes =  new List<String> { 'Appraisal - 1st', 'Appraisal - 2nd', 'Appraisal - 3rd' };

    public Opp_Mercury_EXT(ApexPages.StandardController sc)
    {
        confirmationReceived = false;
        needConfirmation = false;
        this.opp = (Opportunity)sc.getRecord();   
        this.displayError = false;
        selectedAmcCompany = '--None--';
        selectedProduct = '';
        selectedPropertyType = '';
        dummyOpp = new Opportunity();
        dummyOpp.Converted_Close_Date__c= Date.today().addDays(5);

        Schema.DescribeFieldResult fieldResult1 = Appraisal__c.Source__c.getDescribe();
        List<Schema.PicklistEntry> ple1 = fieldResult1.getPicklistValues();

        /*productList = new List<SelectOption>();
        productList.add(new SelectOption('FNMA 1004 Single Family Interior', 'FNMA 1004 Single Family Interior', false));
        productList.add(new SelectOption('FNMA 2055 Exterior', 'FNMA 2055 Exterior', false));
        productList.add(new SelectOption('FNMA 1025 Duplex', 'FNMA 1025 Duplex', false));
        productList.add(new SelectOption('FNMA 1073 Condo Interior', 'FNMA 1073 Condo Interior', false));*/

        // set property type dropdown values
        propertyType = new List<SelectOption>(); 

        Schema.DescribeFieldResult fieldResult2 = Opportunity.Property_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple2 = fieldResult2.getPicklistValues();

        for(Schema.PicklistEntry f : ple2)
        {
            propertyType.add(new SelectOption(f.getValue(), f.getLabel()));
        }

        // get available requirements
        availableRequirementList = new List<SelectOption>();
        availableRequirementList.add(new SelectOption('', '-- Select Appraisal Requirement --'));
        boolean found = false;
        needConfirmation = true;
        selectedRequirement = '';
        for (Current_Conditions__c requirement : [SELECT Id, Code__c,Requirement__c, (SELECT Id FROM Appraisals__r) FROM Current_Conditions__c WHERE Opportunity__c = :this.opp.Id AND Code__c IN :dmdCodes AND Requirement__c IN :reqTypes]) {
            if (requirement.Appraisals__r.size() == 0) {
                if (requirement.Code__c == dmdCodes[0]) {
                    availableRequirementList = new List<SelectOption>();
                    availableRequirementList.add(new SelectOption(requirement.Id, requirement.Requirement__c));
                    found = true;
                    needConfirmation = false;
                    selectedRequirement = requirement.Id;
                }
                if (requirement.Code__c == dmdCodes[1]) {
                        availableRequirementList.add(new SelectOption(requirement.Id, requirement.Requirement__c));
                        found = true;
                        needConfirmation = false;
                        selectedRequirement = requirement.Id;
                }
                if (requirement.Code__c == dmdCodes[2]){
                        availableRequirementList.add(new SelectOption(requirement.Id, requirement.Requirement__c));
                        found = true;
                        needConfirmation = false;
                        selectedRequirement = requirement.Id;   
                }
            }
        }
        if (availableRequirementList.size() == 1 && !found)
        {
            // throw error message
            this.displayError = true;
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'No outstanding appraisal requirements could be found for this file.');
            ApexPages.addMessage(msg);
        }
        showConfirmation = false;
        confirmationReceived = false;

        generateStep = 0;
    }

    public void checkConfirmation()
    {
        showConfirmation = false;
        confirmationReceived = false;

        if(availableRequirementList.size() > 1 && selectedRequirement != null && selectedRequirement != '')
        {
            showConfirmation = true;
        }
    }

    public void confirmationProvided()
    {
        showConfirmation = false;
        confirmationReceived = true;
    }

    public void confirmationRefused()
    {
        showConfirmation = false;
        confirmationReceived = false;
        selectedRequirement = '';
    }

    /******
    *
    * This method is used to send user to standard Opportunity page
    *
    ******/
    public PageReference BackToOppty()
    {
        return new PageReference('/' + this.opp.Id);
    }
    

    /******
    *
    * This method generate and submit a mercury order appraisal
    *
    ******/
    public integer generateStep { get; set; }
    public Appraisal__c newAppraisal { get; set; }
    public PageReference generateOrderAppraisal()
    {
        // Modifying the Fields API Original_Agreed_Value__c
        Opportunity oppty = 
            [
                Select Property_Type__c, Encompass_Loan_Number__c, Owner.Name, Loan_Amount__c, Lien_First_Loan_Type__c, Id, Lien_First_Lender_Balance__c,
                Applicant__r.Name, Co_Applicant__r.Name,Applicant__r.Mercury_Phone__c,Applicant__r.Email,Final_OAV_Calculation__c,
                Property_Street_Number_and_Name__c, Property_City__c,Property_State__c,Property_Zip_Code__c,Property_County__c,UnisonProcessor__r.Name,UnisonProcessor__r.Phone,UnisonProcessor__r.Email
                FROM Opportunity 
                Where Id = :opp.Id
            ];

        oppty.Property_Type__c = selectedPropertyType;       

        if(selectedProduct == 'FNMA 2055 Exterior')
        { 
            newAppraisal = new Appraisal__c();
            newAppraisal.Appraisal_Ordered_Date__c = Date.today();
            newAppraisal.Source__c = selectedAmcCompany;
            newAppraisal.Opportunity__c = opp.Id;

            insert newAppraisal;

            return new PageReference('/' + newAppraisal.Id);
        }
        else
        {   
            Date dueDate = dummyOpp.Converted_Close_Date__c;
            String trackingId;
            if(Test.isRunningTest()){
                trackingId='true';
            }else{
                trackingId = MercuryHelper.GenerateOrderAppraisal(oppty, selectedProduct, dueDate, selectedAmcCompany);
            }
            if(trackingId != null)
            {   
                newAppraisal = new Appraisal__c();
                newAppraisal.Appraisal_Ordered_Date__c = Date.today();
                newAppraisal.Source__c = selectedAmcCompany;
                newAppraisal.Opportunity__c = opp.Id;
                newAppraisal.MercuryTrackingId__c = trackingId;
                if (selectedRequirement != '') {
                    newAppraisal.Requirement__c = selectedRequirement;
                }

                insert newAppraisal;

                generateStep = 1;
                return null;
            }
            else
            {
                this.displayError = true;
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to send appraisal order to Mercury service. Please contact an administrator if this error persists.');
                ApexPages.addMessage(msg);

                return null;
            }
        }
    }
    
    public PageReference generateOrderAppraisalStep2()
    {
        // Call AWS
        generateStep = 0;
        
        boolean awsSuccess; 
        if(Test.isRunningTest()){
            awsSuccess=false;
        }else{
            awsSuccess = MercuryAWSHelper.CallAWS(newAppraisal.Id);
        }
        if (awsSuccess) {  return new PageReference('/' + newAppraisal.Id);
        } else {
            this.displayError = true;
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to send appraisal data to Unison appraisal receiving service. Please contact an administrator if this error persists.');
            ApexPages.addMessage(msg);
            
            return null;
        }
    }
}