objects/Box_API_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Id__c</fullName>
        <label>Enterprise Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Id__c</fullName>
        <label>Folder_Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JWT_Private_Key__c</fullName>
        <label>JWT Private Key</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JWT_Public_Key_Id__c</fullName>
        <label>JWT Public Key Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Box API Setting</label>
    <pluralLabel>Box API Settings</pluralLabel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Box_File_Id__c</fullName>
        <label>Box File Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Box_File_URL__c</fullName>
        <label>Box File URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Box_Folder_Id__c</fullName>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Box_Folder_Id__c</fullName>
        <description>The id in the URL of the folder in Box that holds all of the documents. As of
            Q4 2019, Box is still actively used. Used for the tracking the Box Folder Id. As of
            Q4-2019, this field has been identified by Business Systems (and relevant stakeholders)
            as used or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Box FolderID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoxAttachmentRetrievalQueueable.cls
/**
 * Created by Eliot Rojas on 5/22/2019.
 */

public with sharing class BoxAttachmentRetrievalQueueable implements Queueable, Database.AllowsCallouts {
    public static Map<Id, List<Attachment>> leadFilesMap = new Map<Id, List<Attachment>>();
    public static Box_API_Setting__mdt settings = new Box_API_Setting__mdt();
    public Map<Id, Lead> leadMap;

    public BoxAttachmentRetrievalQueueable(Map<Id, Lead> leadMap) {
        this.leadMap = leadMap;
    }

    public void execute(QueueableContext context) {
        try {
            // Get Box API Settings
            settings = getBoxAPISettings();
            // Make API call to get file information and their contents
            for(Document_MetaData__c documentMetaData : [SELECT Id, Lead__c, Box_File_Id__c, Box_Folder_Id__c, Box_File_URL__c
            FROM Document_MetaData__c WHERE Lead__c IN : leadMap.keySet()
            AND Box_File_Id__c != null]) {
                if(leadMap.get(documentMetaData.Lead__c).Id != null) {
                    getAttachments(documentMetaData.Box_File_Id__c, leadMap.get(documentMetaData.Lead__c).Id);
                }
            }
            system.debug('++ leadFilesMap: ' + leadFilesMap);

            // Insert Attachment records
            List<Attachment> attachmentsToInsert = new List<Attachment>();
            for(String leadId : leadFilesMap.keySet()) {
                if(leadFilesMap.get(leadId).isEmpty() != true) {
                    for(Attachment att : leadFilesMap.get(leadId)) {
                        attachmentsToInsert.add(att);
                    }
                }
            }
            // Insert Attachment records
            if(!attachmentsToInsert.isEmpty()) {
                insert attachmentsToInsert;
            }
         } catch (Exception ex) {
            System.debug('Error Message: ' + ex.getMessage() + ' \nLine: ' + ex.getLineNumber() + ' \nStack: ' + ex.getStackTraceString());
        }
    }

    public static void getAttachments(String boxFileId, Id leadId) {
        Http http = new Http();

        BoxJwtEncryptionPreferences prefs = new BoxJwtEncryptionPreferences();
        prefs.setPublicKeyId(settings.JWT_Public_Key_Id__c);
        prefs.setPrivateKey(settings.JWT_Private_Key__c);
        BoxPlatformApiConnection api = BoxPlatformApiConnection.getAppEnterpriseConnection(settings.Enterprise_Id__c, settings.Client_Id__c, settings.Client_Secret__c, prefs);

        //Get file info, including filename which can be used to create an Attachment
        BoxFile file = new BoxFile(api, boxFileId);
        BoxFile.Info fileInfo = file.getFileInfo();
        system.debug('++ File: ' + fileInfo);


        HttpResponse response = new HttpResponse();

        //Making callouts is not allowd in Tests
        if(!System.Test.isRunningTest()) {
            //Get link to download
            String requestURL = 'https://api.box.com/2.0/files/' + boxFileId + '/content';
            BoxAPIRequest request = new BoxAPIRequest(api, requestURL, BoxApiRequest.METHOD_GET);
            request.setTimeout(api.getTimeout());

            response = request.send();
            system.debug('++ response: ' + response);
            system.debug('++ response StatusCode: ' + response.getStatusCode());
        }

        // if (response.getStatusCode() == 302) {
        Attachment att = new Attachment();
        att.ParentId = leadId;
        att.Name = fileInfo.name;
        att.Body = response.getBodyAsBlob();

        List<Attachment> temp = new List<Attachment>();
        if ((temp = leadFilesMap.get(leadId)) == null) {
            leadFilesMap.put(leadId, temp = new Attachment[0]);
        }
        temp.add(att);
        system.debug('++ temp: ' + temp);
        // }
    }

    @TestVisible private static Box_API_Setting__mdt getBoxAPISettings(){
        return [SELECT DeveloperName, Base_URL__c, Client_Id__c, Client_Secret__c, Enterprise_Id__c, Folder_Id__c, JWT_Public_Key_Id__c, JWT_Private_Key__c
        FROM Box_API_Setting__mdt LIMIT 1];
    }
}