objects/Case.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Back_End_DTI__c</fullName>
        <label>Expected Back End DTI</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Credit Report for the consumer</description>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualifies for New HomeOwner Pricing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opp_to_Case_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_field_API_Name__c</fullName>
        <label>Case field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Value__c</fullName>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Field_API_Name__c</fullName>
        <label>Opp Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opp to Case Mapping</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Back_End_DTI__c</fullName>
        <label>Back-End Ratio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IA_Passbook_Override_Reasons__c</fullName>
        <label>IA Passbook Override Reasons</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High Liquid Reserves</fullName>
                </value>
                <value>
                    <fullName>High liquid Assets</fullName>
                </value>
                <value>
                    <fullName>Strong Credit History</fullName>
                </value>
                <value>
                    <fullName>Confident in Income Profile</fullName>
                </value>
                <value>
                    <fullName>Additional Sources of Income</fullName>
                </value>
                <value>
                    <fullName>Favorable Property Appreciation</fullName>
                </value>
                <value>
                    <fullName>Low Non-Housing Debt</fullName>
                </value>
                <value>
                    <fullName>Just-Over Threshold</fullName>
                </value>
                <value>
                    <fullName>Other (See Notes)</fullName>
                </value>
                <value>
                    <fullName>Lowered MAD Cap</fullName>
                </value>
                <value>
                    <fullName>Low Property Debt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IA_Passbook_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set by IA. Reason field is required.</inlineHelpText>
        <label>IA Passbook Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTV__c</fullName>
        <formula>Proposed_Total_Mortgage_Debt__c / Original_Agreed_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LTV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Code__c</fullName>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Aged</fullName>
                    <isActive>false</isActive>
                    <label>Aged</label>
                </value>
                <value>
                    <fullName>Decline - Credit/Foreclosure Issues</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Credit/Foreclosure Issues</label>
                </value>
                <value>
                    <fullName>Decline - Insufficient Down Payment/Income</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Insufficient Down Payment/Income</label>
                </value>
                <value>
                    <fullName>Decline - Not in Geography</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Not in Geography</label>
                </value>
                <value>
                    <fullName>Decline - Property</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Property</label>
                </value>
                <value>
                    <fullName>Decline - Purchase Offer not Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Purchase Offer not Accepted</label>
                </value>
                <value>
                    <fullName>Decline - Rental or Second Home</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Rental or Second Home</label>
                </value>
                <value>
                    <fullName>Decline - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Unknown</label>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                    <isActive>false</isActive>
                    <label>Unresponsive</label>
                </value>
                <value>
                    <fullName>Withdraw - Already has Lender</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Already has Lender</label>
                </value>
                <value>
                    <fullName>Withdraw - Not Buying Home</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Not Buying Home</label>
                </value>
                <value>
                    <fullName>Withdraw - Prefers Another Product</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Prefers Another Product</label>
                </value>
                <value>
                    <fullName>Withdraw - Too Complicated</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Too Complicated</label>
                </value>
                <value>
                    <fullName>Withdraw - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <defaultValue>IF( $RecordType.Name = 'HomeBuyer','N/A','Pending')</defaultValue>
        <inlineHelpText>Passbook may run once LTV, DTI, and Credit Success Factors are marked Completed</inlineHelpText>
        <label>Current Passbook Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                    <isActive>false</isActive>
                    <label>Exception</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                    <isActive>false</isActive>
                    <label>Reject</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Applicant__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Close_BE_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hard coded</description>
        <inlineHelpText>Post-Close Liabilities Total / Income Total</inlineHelpText>
        <label>Post-Close BE Ratio2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Post_Close_LTV2__c</fullName>
        <description>Hardcoded
This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <inlineHelpText>This is the total proposed mortgage debt on the property as a percentage of the Final OAV. It is expressed as the Post-Close Mortgage Debt divided by the Final OAV. Final OAV can change as more appraisals and other information is gathered.</inlineHelpText>
        <label>Post-Close LTV2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Yodlee_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Yodlee Order Requests</relationshipLabel>
        <relationshipName>Yodlee_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Yodlee_Public_Id__c</fullName>
        <label>Yodlee Public Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OppQualification.cls
public with sharing class OppQualification extends QualificationBase {
    
    public Id oppId { get; set; }
    public Opportunity theOpp { get; set; }
    public Boolean IA_Passbook_Override {get; set;}
    public String passbookResultValue {get; set;}
    public string IA_Passbook_Override_Reasons {get; set;}
    public OppQualification(ApexPages.StandardController ctrl) {
        
        oppId = ctrl.getId();

        /* 4/2/2019 Sundar Subramaniam - LTV__c and Expected_Back_End_DTI__c removed from query for Data Model Cleanup */
       /*  4/5/2019 Neeraja Cherukuri- Replaced Expected_Back_End_DTI__c  with new fields  for Data Model Cleanup */

        Opportunity opp = [SELECT Id,Applicant__c,Co_Applicant__c,  Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c, 
                            Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c,Post_Close_BE_Ratio__c , Qualifies_for_New_HomeOwner_Pricing__c,
                            /*LTV_Denominator__c, LTV_Numerator__c,*/ Estimated_Funding_Amount__c,Post_Close_LTV2__c ,
                           IA_Passbook_Override__c,IA_Passbook_Override_Reasons__c,Passbook_Status__c,
                           (SELECT Yodlee_Public_Id__c FROM Yodlee_Order_Requests__r ORDER BY CreatedDate DESC LIMIT 1)
                        FROM Opportunity WHERE Id = :oppId];
        theOpp = opp;
        system.debug('+++ yoodlee orders' + opp.Yodlee_Order_Requests__r);
       IA_Passbook_Override    = theOpp.IA_Passbook_Override__c;
        IA_Passbook_Override_Reasons = theOpp.IA_Passbook_Override_Reasons__c;
        passbookResultValue = theOpp.Passbook_Status__c;
        
        // Product
        Product = 'HomeOwner';
        if (opp.Qualifies_for_New_HomeOwner_Pricing__c == true)
            Product = 'New HomeOwner';
        system.debug('+++ b4 LTV ' + LTV);
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        // LTV
        LTV = opp.Post_Close_LTV2__c == null ? 0 : opp.Post_Close_LTV2__c ;
        LTV = Math.Round(LTV * 100) / 100;
        system.debug('++LASERCA__Co_Applicant_Credit_Score_Median__c ' + opp.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c);
        system.debug('++LASERCA__Co_Applicant_Credit_Score_Median__c ' + opp.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c);

        // FICO
        FICO = 0;
        if (opp.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c != null && opp.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c > 300) {
            FICO = opp.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c;
        }
        if (opp.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c != null && opp.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c > 300) {
            FICO = Math.Min(FICO, opp.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c);
        }
        FICO = Math.Round(FICO * 100) / 100;
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        /* 4/5/2019 Neeraja Cherukuri- Replaced with new fields  for Data Model Cleanup */
        system.debug('+++ FICO ' + FICO);
        // DTI
        DTI = opp.Post_Close_BE_Ratio__c ;
        DTI = DTI == null ? 0 : Math.Round(DTI * 100) / 100;
        
        calculated = false;
        CreateException = false;
        showOptyButton = false;
    }
    

    //new method for passbook qualification    
    public void passbookCalculate(){  
        System.debug('====IA_Passbook_Override==='+IA_Passbook_Override);  
        PassbookRestHelper passbookHelper = new PassbookRestHelper();
        PassbookRestHelper.passbookJSON passbookJSON = new PassbookRestHelper.passbookJSON();
        passbookJSON.partner_id = theOpp.Applicant__c;
        passbookJSON.product_type = (Product == 'HomeOwner') ? 'HO' : 'HB';
        passbookJSON.mortgage_type = (MortgageType == 'Amortizing') ? 'A' : 'NA';
        passbookJSON.ltv = LTV;
        passbookJSON.fico = integer.valueOf(FICO);
        passbookJSON.dti = DTI;
        passbookJSON.has_co_app = (theOpp.Co_Applicant__c != NULL) ? true : false;
        if(!theOpp.Yodlee_Order_Requests__r.isEmpty()) {
            passbookJSON.yodlee_report_id = theOpp.Yodlee_Order_Requests__r[0].Yodlee_Public_Id__c == null ? 'None' : theOpp.Yodlee_Order_Requests__r[0].Yodlee_Public_Id__c;
        } else {
            passbookJSON.yodlee_report_id = 'None';
        }

        system.debug('+++ passbookJSON ' + JSON.serialize(passbookJSON));
        passbookResponse = (PassbookRestHelper.passbookResponse)json.deserialize(PassbookRestHelper.postToPassbook(passbookJSON), PassbookRestHelper.passbookResponse.class);
        calculated = true; 
        passbookUsed = true;
        passBookResults = true;
        system.debug('+++ passbookResponse ' + JSON.serialize(passbookResponse));

        passbookResult = passbookResponse.response;
        resultT1 = passbookResponse.grid_one_result;
        resultT2 = passbookResponse.grid_two_result;
        if(passbookResult == 'Exception')
        {
            theOpp.Passbook_Status__c = 'Exception';
            CreateException = true; 
            theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
         update theOpp;           
        } 
    }
    
    public pageReference passbookContinueOpp()
    { 
        //Added by Neeraja Cherukuri For Passbook ovveride Functionality
        if(passbookResponse.response == 'Approve')
        {
            
            if(IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c == null 
            || !IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c != null)
            {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'IA Passbook override reason is required if IA Override checkbox is checked.'));  
                return new PageReference('/apex/OppQualification?scontrolCaching=1&id=' + theOpp.Id);     
            }
            theOpp.Passbook_Status__c = 'Approve';
            //theOpp.IA_Passbook_Override_Reasons__c = IA_Passbook_Override_Reasons;
            theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
            update theOpp;
            return new PageReference('/' + theOpp.Id);
        }
        
        else if(passbookResponse.response == 'Decline')
        
        {
        
             //Added by Neeraja Cherukuri For Passbook ovveride Functionality
            if(IA_Passbook_Override || theOpp.IA_Passbook_Override_Reasons__c != null)
            {
                if( IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c == null 
                || !IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c != null)
                {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'IA Passbook override reason is required if IA Override checkbox is checked.')); 
                    return new PageReference('/apex/OppQualification?scontrolCaching=1&id=' + theOpp.Id);     
                }
                 theOpp.Passbook_Status__c = 'Decline';
                theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
              // theOpp.IA_Passbook_Override_Reasons__c = IA_Passbook_Override_Reasons;
                update theOpp;
                return new PageReference('/' + theOpp.Id);    
            }  
            
            theOpp.Passbook_Status__c = 'Decline';
            theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
            update theOpp;
            return new PageReference('/' + theOpp.Id);
        }  
        
        
        if(passbookResponse.response == null)
        {
             //Added by Neeraja Cherukuri For Passbook ovveride Functionality
            if(IA_Passbook_Override || theOpp.IA_Passbook_Override_Reasons__c != null)
            {
                if( (IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c == null)  || (!IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c != null))
                {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'IA Passbook override reason is required if IA Override checkbox is checked.')); 
                    return new PageReference('/apex/OppQualification?scontrolCaching=1&id=' + theOpp.Id);     
                }
                 theOpp.Passbook_Status__c = 'Exception';
                 theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
              // theOpp.IA_Passbook_Override_Reasons__c = IA_Passbook_Override_Reasons;
                update theOpp;
                return new PageReference('/' + theOpp.Id);    
            } 
            theOpp.Passbook_Status__c = 'Exception'; 
            theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
            update theOpp;
            return new PageReference('/' + theOpp.Id); 
        }

        if(passbookResponse.response == 'Exception')
        {
            //Added by Neeraja Cherukuri For Passbook ovveride Functionality
            if(IA_Passbook_Override || theOpp.IA_Passbook_Override_Reasons__c != null)
            {
                if( (IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c == null)  || (!IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c != null))
                {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'IA Passbook override reason is required if IA Override checkbox is checked.'));
                    return new PageReference('/apex/OppQualification?scontrolCaching=1&id=' + theOpp.Id);
                }
                theOpp.Passbook_Status__c = 'Exception';
                theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
                // theOpp.IA_Passbook_Override_Reasons__c = IA_Passbook_Override_Reasons;
                update theOpp;
                return new PageReference('/' + theOpp.Id);
            }
            system.debug('++ theOpp ' + theOpp.IA_Passbook_Override_Reasons__c);
            theOpp.Passbook_Status__c = 'Exception';
            theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
            update theOpp;
            return new PageReference('/' + theOpp.Id);
        }

        System.debug('====response is null === ');
        System.debug('====IA_Passbook_Override==='+IA_Passbook_Override);
        System.debug('====theOpp.IA_Passbook_Override__c==='+theOpp.IA_Passbook_Override__c);
        system.debug('++ IA_Passbook_Override_Reasons__c ' + theOpp.IA_Passbook_Override_Reasons__c);
        
        
        
    /*    if(IA_Passbook_Override || theOpp.IA_Passbook_Override_Reasons__c != null)
        {
            if(IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c == null
             || !IA_Passbook_Override && theOpp.IA_Passbook_Override_Reasons__c != null)
            {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'IA Passbook override reason is required if IA Override checkbox is checked.'));  
                return new PageReference('/apex/OppQualification?scontrolCaching=1&id=' + theOpp.Id);   
            }
            
            theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
            theOpp.IA_Passbook_Override_Reasons__c = IA_Passbook_Override_Reasons;
          // theOpp.Passbook_Status__c = 'Declined';
            update theOpp;
            return new PageReference('/' + theOpp.Id);    
        }
        
        theOpp.IA_Passbook_Override__c = IA_Passbook_Override;
        theOpp.IA_Passbook_Override_Reasons__c = IA_Passbook_Override_Reasons;
       
        update theOpp;  */
        
        return new PageReference('/' + theOpp.Id);
    }  
    
  //Added by Neeraja Cherukuri For Passbook ovveride Functionality
 
    
    public PageReference ContinueOpp() {
        Opportunity opp = [SELECT Id, Passbook_Status__c, IA_Passbook_Override__c, Loss_Type__c, StageName, Loss_Reason_Code__c  FROM Opportunity WHERE Id = :oppId];
        if (ResultT1 == 'Yes' && ResultT2 == 'Yes') {
            //opp.Guideline_Prequalification_Date_Time__c = DateTime.now();
            update opp;
            return new PageReference('/' + opp.Id);
        }
        
        if (ResultT1 == 'Yes' && ResultT2 == 'No') {
            opp.StageName = 'Closed Lost';
            opp.Loss_Type__c = 'Declined';
            opp.Loss_Reason_Code__c = 'Excessive obligations in relation to income';
            update opp;
            return new PageReference('/' + opp.Id);
        }
        
        if (ResultT1 == 'Yes' && ResultT2 == 'Exception') {
            // Should not get to this point
        }
        
        if (ResultT1 == 'No' && ResultT2 == 'Yes') {
            opp.StageName = 'Closed Lost';
            opp.Loss_Type__c = 'Declined';
            opp.Loss_Reason_Code__c = 'Reported credit below our minimum requirement';
            update opp;
            return new PageReference('/' + opp.Id);
        }
        
        if (ResultT1 == 'No' && ResultT2 == 'No') {
            opp.StageName = 'Closed Lost';
            opp.Loss_Type__c = 'Declined';
            opp.Loss_Reason_Code__c = 'Reported credit below our minimum requirement;Excessive obligations in relation to income';
            update opp;
            return new PageReference('/' + opp.Id);
        }
        
        if (ResultT1 == 'No' && ResultT2 == 'Exception') {
            opp.StageName = 'Closed Lost';
            opp.Loss_Type__c = 'Declined';
            opp.Loss_Reason_Code__c = 'Reported credit below our minimum requirement;Excessive obligations in relation to income';
            update opp;
            return new PageReference('/' + opp.Id);
        }
        
        if (ResultT1 == 'Exception' && ResultT2 == 'Yes') {
            // Should not get to this point
        }
        
        if (ResultT1 == 'Exception' && ResultT2 == 'No') {
            opp.StageName = 'Closed Lost';
            opp.Loss_Type__c = 'Declined';
            opp.Loss_Reason_Code__c = 'Reported credit below our minimum requirement;Excessive obligations in relation to income';
            update opp;
            return new PageReference('/' + opp.Id);
        }
        
        if (ResultT1 == 'Exception' && ResultT2 == 'Exception') {
            // Should not get to this point
        }
        if(passbookResult == null)
        {
            opp.Passbook_Status__c = 'Exception';
            
            update opp;  
            return new PageReference('/' + opp.Id);  
        }
        if(passbookResult == 'Exception') {
            system.debug('++ theOpp ' + theOpp);
            system.debug('++ opp to be updated ' + opp);
            opp.Passbook_Status__c = 'Exception';
            opp.IA_Passbook_Override__c = IA_Passbook_Override;
            opp.IA_Passbook_Override_Reasons__c = theOpp.IA_Passbook_Override_Reasons__c;
            update opp;
            return new PageReference('/' + opp.Id);
        }
        return null;
    }
    
    // ******** Exception page elements below ********
   
    /*public PageReference RaiseException() {
        List<String> componentNameList = new List<String>{ 'Case-Exception' };
        List<Metadata.Metadata> components = Metadata.Operations.retrieve(Metadata.MetadataType.Layout, componentNameList);
        
        caseLayout = new LayoutWrapper((Metadata.Layout)components.get(0));
        
        List<Opp_to_Case_Mapping__c> mapFields = [SELECT Case_field_API_Name__c, Opp_Field_API_Name__c, Default_Value__c FROM Opp_to_Case_Mapping__c];
        string query = 'SELECT Id';
        for (Opp_to_Case_Mapping__c mapField : mapFields) {
            if (mapFIeld.Opp_Field_API_Name__c != null && mapField.Opp_Field_API_Name__c != '') {
                    query += ', ' + mapFIeld.Opp_Field_API_Name__c;
            }
        }
        query += ' FROM Opportunity WHERE Id = :oppId';
        System.debug(query);
        
        Opportunity fullOpp = Database.query(query);
        
        newCase = new Case();
        for (Opp_to_Case_Mapping__c mapField : mapFields) {
            if (mapField.Opp_Field_API_Name__c != null && mapField.Opp_Field_API_Name__c != '') {
                if (mapField.Opp_Field_API_Name__c.contains('.')) {
                    if (fullOpp.getSObject(mapField.Opp_Field_API_Name__c.split('\\.')[0]) != null) {
                        newCase.put(mapField.Case_field_API_Name__c, fullOpp.getSObject(mapField.Opp_Field_API_Name__c.split('\\.')[0]).get(mapField.Opp_Field_API_Name__c.split('\\.')[1]));
                    }
                } else {
                    if(fullOpp.get(mapField.Opp_Field_API_Name__c) != null)
                        newCase.put(mapField.Case_field_API_Name__c, fullOpp.get(mapField.Opp_Field_API_Name__c));
                }
            } else if (mapField.Default_Value__c != null && mapField.Default_Value__c != '') {
                newCase.put(mapField.Case_field_API_Name__c, mapField.Default_Value__c);
            }
        }
        newCase.Opportunity__c = fullOpp.Id;
        newCase.Description = MitigatingCircumstances;
        if (ResultT1 == 'Exception' && ResultT2 == 'Exception') {
            newCase.Subject = 'Back-End DTI Post-Funding;Mid FICO' + (MortgageType == 'Reverse Mortgage' ? ';Mortgage Type' : '');
            newCase.Exception_Reason__c = 'Back-End DTI Post-Funding;Mid FICO' + (MortgageType == 'Reverse Mortgage' ? ';Mortgage Type' : '');
        }
        if (ResultT1 == 'Yes' && ResultT2 == 'Exception') {
            newCase.Subject = 'Back-End DTI Post-Funding' + (MortgageType == 'Reverse Mortgage' ? ';Mortgage Type' : '');
            newCase.Exception_Reason__c = 'Back-End DTI Post-Funding' + (MortgageType == 'Reverse Mortgage' ? ';Mortgage Type' : '');
        }
        if (ResultT1 == 'Exception' && ResultT2 == 'Yes') {
            newCase.Subject = 'Mid FICO' + (MortgageType == 'Reverse Mortgage' ? ';Mortgage Type' : '');
            newCase.Exception_Reason__c = 'Mid FICO' + (MortgageType == 'Reverse Mortgage' ? ';Mortgage Type' : '');
        }
        newCase.Mortgage_Type__c = MortgageType == 'Amortizing' ? 'Amortizing' : 'Non-amortizing';
        
        PageReference pr = Page.OppQualificationException;
        pr.setRedirect(false);
        return pr;
    }*/
  
}