objects/Case.object
<CustomObject>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Credit Report for the consumer</description>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualifies for New HomeOwner Pricing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_Tracking_ID__c</fullName>
        <description>There is one application id per application. Unison generates this at lead
            creation. We pushed this data into encompass. As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <displayFormat>FRX-{000000}</displayFormat>
        <label>Application Tracking ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Back_End_Ratio__c</fullName>
        <description>A computed field. As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as used or otherwise relevant to current business
            processes. To be reviewed next Q4 2021.</description>
        <formula>(Payment_Monthly_Total_Housing__c+ Sum_of_Debt_Payments__c)  / (Income_Monthy_Total_Co__c + Income_Monthly_Total__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>(Payment Monthly Total Housing + Sum of Debt Payments) / Total Monthly
            Income</inlineHelpText>
        <label>Back-End Ratio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Unison's Investment Payment. This amount should not exceed Max Offer amount.</inlineHelpText>
        <label>Estimated Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Monthy_Total_Co__c</fullName>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <formula>NULLVALUE(Income_Monthly_Base_Co__c,0) + NULLVALUE(Income_Monthly_Bonuses_Co__c,0) +  NULLVALUE(Income_Monthly_Commissions_Co__c,0) + NULLVALUE(Income_Monthly_Div_Interest_Co__c,0) +  NULLVALUE(Income_Monthly_Other_Co__c,0) +  NULLVALUE(Income_Monthly_Overtime_Co__c,0) +  NULLVALUE(Income_Monthly_Social_Security_Co__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Income field used to determine DTI for the Lead.</inlineHelpText>
        <label>Income Monthly Total (Co)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating whether the applicatoin has a co-applicant. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTV_Denominator__c</fullName>
        <description>used for the LTV DTI calculator As of Q4-2019, this field has been identified
            by Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <formula>IF(RecordType.Name = 'HomeBuyer' || RecordType.Name = 'HomeBuyer Canada', 

MIN( 
IF(ISBLANK(Home_Value__c) || Home_Value__c = 0, 
9999999999999999, 
Home_Value__c 
), 

IF(ISBLANK(Purchase_Price__c) || Purchase_Price__c = 0, 
9999999999999999, 
Purchase_Price__c 
) 
), 

IF(RecordType.Name = 'HomeOwner', 
 
IF(ISBLANK(Home_Value__c) || Home_Value__c = 0, 
9999999999999999, 
Home_Value__c 
), 

9999999999999999 

)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Purchase price or appraised value, whichever is less.</inlineHelpText>
        <label>Original Agreed Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LTV_Numerator__c</fullName>
        <description>Proposed total mortage debt. As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <formula>IF(RecordType.Name ='HomeBuyer', Loan_Amount__c,
IF(RecordType.Name ='HomeOwner', (Proposed_Total_Mortgage_Debt__c- Proposed_Mortgage_Debt_Pay_Down__c ),0)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total mortgage debt for the subject property with debts selected for payoff
            excluded.</inlineHelpText>
        <label>Proposed Total Mortgage Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LTV__c</fullName>
        <description>Post close LTV (Loan to Value ratio) As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <formula>LTV_Numerator__c / LTV_Denominator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>For HomeBuyer, the LTV (Loan-To-Value) ratio is calculated by dividing the Loan Amount by the Purchase Price or Home Value, whichever is lower. For HomeOwner, the LTV is calculated by dividing the Proposed Total Mortgage Debt by the Home Value</inlineHelpText>
        <label>Post Close LTV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Occupancy_Statement_Dropdown__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Occupancy Statement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal Residence</fullName>
                </value>
                <value>
                    <fullName>Second Vacation Home</fullName>
                </value>
                <value>
                    <fullName>Investment Property</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Monthly_Total_Housing__c</fullName>
        <description>This is a calculated field totaling all housing expense payments As of Q4-2019,
            this field has been identified by Business Systems (and relevant stakeholders) as used
            or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <formula>IF( !Second_Lender_Name__r.To_Be_Paid_Off__c, ( Payment_Monthly_First_Mortgage__c  +  Payment_Monthly_HOA__c  +  Payment_Monthly_Insurance__c  + Payment_Monthly_Second_Mortgage__c  + Payment_Monthly_Taxes__c), 

( Payment_Monthly_First_Mortgage__c  +  Payment_Monthly_HOA__c  +  Payment_Monthly_Insurance__c  +  Payment_Monthly_Taxes__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of Payment Monthly First Mortgage, Payment Monthly HOA, Payment Monthly
            Insurance, Payment Monthly Second Mortgage, and Payment Monthly Taxes</inlineHelpText>
        <label>Payment Monthly Total Housing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It's a link to the credit report of the lead contact As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Selected Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Lead__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_Total_Mortgage_Debt__c</fullName>
        <description>the total amount of debt the applicant may have. Numerator for LTV formula As
            of Q4-2019, this field has been identified by Business Systems (and relevant
            stakeholders) as used or otherwise relevant to current business processes. To be
            reviewed next Q4 2021.</description>
        <formula>IF(Second_Lender_Name__r.To_Be_Paid_Off__c, Lien_First_Lender_Balance__c,Total_Mortgage_Debt__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Proposed (post close) debt secured by the subject property</inlineHelpText>
        <label>Proposed Total Mort Debt Intermediary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>greenlight field As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as used or otherwise relevant to current business
            processes. To be reviewed next Q4 2021.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>may keep this field to identify the product/program name for the lead As of
            Q4-2019, this field has been identified by Business Systems (and relevant stakeholders)
            as used or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type (Name)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sum_of_Debt_Payments__c</fullName>
        <description>The sum of debt payments. Used in DTI and LTV calculation As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <inlineHelpText>Sum of Monthly Debt not being Paid Off (excluding monthly mortgage payments)</inlineHelpText>
        <label>Sum of Debt Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Monthly_Income__c</fullName>
        <description>Number field to enter the applicants monthly income As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <formula>Income_Monthly_Total__c  +  Income_Monthy_Total_Co__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of all Applicant/Co-Applicant Income</inlineHelpText>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>HB Lead Status</businessProcess>
        <description>012E00000002OGS</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Yodlee_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Yodlee Order Requests</relationshipLabel>
        <relationshipName>Yodlee_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Yodlee_Public_Id__c</fullName>
        <label>Yodlee Public Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadQualification.cls
public with sharing class LeadQualification extends QualificationBase {
    
    public Id leadId { get; set; }
    public Lead theLead { get; set; }
    public decimal HEPF { get; set; }
    public boolean passbookUsed {get; set; }      
    public List<DecisionBounderyWrapper> decisionBounderyWrapperObjectList {get;set;}
    public String pdRate{get;set;}
    public String passbookScore{get;set;} 
    public String passbookDecision{get;set;} 
    public String decisionExplanation{get;set;} 
    public String errorIssue{get;set;} 
    public boolean errorOccure{get;set;} 
    public Set<String> nonSuccessStringSet = new Set<String>{'Escalate','Decline','Failed'};
    public String dealID{get;set;}
    public String applicantName{get;set;}
    public decimal currentLTV{get;set;}
    public decimal currentDTI{get;set;}
    
        
        public LeadQualification(ApexPages.StandardController ctrl) {
            errorOccure = false;
            string Occupancy_Status;
            Decimal Total_Monthly_Debt_Payment;
            
            leadId = ctrl.getId();
            
            Lead lead = [SELECT Id,Is_there_Co_App__c, LTV__c, Back_End_Ratio__c, Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c,Property_State__c,Application_Tracking_ID__c,Name,
                         Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c,Personal_Credit_Report__r.CreateDateTime__c,Occupancy_Statement_Dropdown__c,Proposed_Total_Mortgage_Debt__c, Qualifies_for_New_HomeOwner_Pricing__c,
                         LTV_Denominator__c,Record_Type_Name__c, Sum_of_Debt_Payments__c,Payment_Monthly_Total_Housing__c,LTV_Numerator__c, Estimated_Funding_Amount__c,Total_Monthly_Income__c,Income_Monthy_Total_Co__c,
                         (SELECT Yodlee_Public_Id__c FROM Yodlee_Order_Requests__r ORDER BY CreatedDate DESC LIMIT 1)
                         FROM Lead WHERE Id = :leadId];
            theLead = lead;
            
            dealID = lead.Application_Tracking_ID__c;
    		applicantName = lead.Name;
    		currentLTV = lead.LTV__c;
    		currentDTI = lead.Back_End_Ratio__c;
            
            // Product
            Product = 'HomeOwner';
            if (lead.Record_Type_Name__c == 'HomeBuyer'){
                Product = 'HomeBuyer';  
            }
            
            // LTV
            LTV = lead.LTV__c;
            
            // FICO
            FICO = 0;
            if (lead.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c != null && lead.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c > 300) {
                FICO = lead.Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c;
            }
            if (lead.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c != null && lead.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c > 300) {
                FICO = Math.Min(FICO, lead.Personal_Credit_Report__r.LASERCA__Co_Applicant_Credit_Score_Median__c);
            }
            FICO = Math.Round(FICO * 100) / 100;
            
            
            // DTI
            DTI = lead.Back_End_Ratio__c;
            
            //Income
            Decimal TotalIncome = lead.Total_Monthly_Income__c+lead.Income_Monthy_Total_Co__c ;
            
            calculated = false;
            CreateException = false;
            
        }
    
    //new method for passbook qualification    
    public void passbookCalculate(){
        pdRate = '';
        passbookScore = '';
        passbookDecision = '';
        decisionExplanation = '';
        PassbookRestHelper passbookHelper = new PassbookRestHelper();
        PassbookRestHelper.passbookJSON passbookJSON = new PassbookRestHelper.passbookJSON();
        PassbookJSON.Origination_Credit_Score = integer.valueOf(FICO);
        PassbookJSON.num_borrowers = (theLead.Is_there_Co_App__c == false) ? 1 : 2;
        PassbookJSON.Income = thelead.Total_Monthly_Income__c + thelead.Income_Monthy_Total_Co__c ;
        PassbookJSON.Origination_Front_End_DTI = DTI;
        PassbookJSON.Original_Loan_Amount = theLead.Proposed_Total_Mortgage_Debt__c;
        PassbookJSON.Property_State = theLead.Property_State__c;
        PassbookJSON.Product_Type = (Product == 'HomeOwner') ? 'C' : 'P';
        PassbookJSON.Origination_CLTV = LTV;
        if(theLead.Occupancy_Statement_Dropdown__c == 'Principal Residence'){
            PassbookJSON.Occupancy_Status = 'P';        
        }else{
            if(theLead.Occupancy_Statement_Dropdown__c == ' Second Vacation Home'){
                PassbookJSON.Occupancy_Status = 'S';        
            }else{
                PassbookJSON.Occupancy_Status = 'I';   
            }
        }
        if(theLead.Personal_Credit_Report__c!=null)
        { 
            PassbookJSON.Cut_Off_Date = theLead.Personal_Credit_Report__r.CreateDateTime__c.date();
        }
        PassbookJSON.Total_Monthly_Debt_Payment = theLead.Payment_Monthly_Total_Housing__c + theLead.Sum_of_Debt_Payments__c;
        
        //restREsponse
        calculated = true;
        String passbookResult = PassbookRestHelper.postToPassbook(passbookJSON);
       	
        System.debug('This is passbookJSON' +passbookJSON);
        System.debug('This is passbookResult' +passbookResult);
        decisionBounderyWrapperObjectList = new List<DecisionBounderyWrapper>();
        Map<String, Object> mapOfObj = (Map<String, Object>) JSON.deserializeUntyped(passbookResult);
        errorIssue = (String)mapOfObj.get('Error_Issues');
        
        //Check whether there is as Error Issue in response 
        if(errorIssue=='None'){
            
            //Get PD Rate, Passbook Score, Passbook Decision, Decision Explanation, Data from response
            pdRate = String.valueOf(mapOfObj.get('PD_Rate'));
            passbookScore = String.valueOf(mapOfObj.get('Passbook_Score'));
            passbookDecision = (String)mapOfObj.get('Passbook_Decision');
            decisionExplanation = (String)mapOfObj.get('Decision_Explanation');
            Object objTemp = mapOfObj.get('Decision_Boundary');
            Map<String, Object> bounderyObjMap =   (Map<String, Object>) JSON.deserializeUntyped(JSON.Serialize(objTemp));
            
            //Iterate through Response to read Decision Boundary 
            for(String boundryVal : bounderyObjMap.keySet()){
                DecisionBounderyWrapper wrapperObj = new DecisionBounderyWrapper();
                wrapperObj.DecisionBounderyValue = boundryVal;
                Map<String, Object> mapOfObjInner = (Map<String, Object>) JSON.deserializeUntyped(JSON.Serialize(bounderyObjMap.get(boundryVal)));
                for(String boundryValInner : mapOfObjInner.keySet()){
                    if(boundryValInner=='Approval DTI Boundary'){
						wrapperObj.ApprovalDTIBoundaryValue= String.ValueOf(mapOfObjInner.get(boundryValInner));
					}else if(boundryValInner=='Escalate DTI Boundary'){
						 wrapperObj.EscalateDTIBoundaryValue= String.valueOf(mapOfObjInner.get(boundryValInner));
					}
                }
                
                decisionBounderyWrapperObjectList.add(wrapperObj);
            }
            if(nonSuccessStringSet.contains(passbookDecision)){
                //exception to handle case creation
                CreateException = true;    
            }
            
            //update to lead
            theLead.Passbook_Status__c = passbookDecision;
            theLead.Passbook_Decision_Explanation__c = decisionExplanation;
            theLead.Approval_Escalation_Boundary__c= JSON.Serialize(objTemp);
            passbookUsed = true;
            calculated = true;
            update theLead;
        }else {
            errorOccure = true;
            theLead.Passbook_Error_Log__c = errorIssue;
            update theLead;
        }      
    }

    
    // ******** Exception page elements below ********
    
    public PageReference RaiseException() {
        List<String> componentNameList = new List<String>{ 'Case-Exception' };
            List<Metadata.Metadata> components = Metadata.Operations.retrieve(Metadata.MetadataType.Layout, componentNameList);
        
        caseLayout = new LayoutWrapper((Metadata.Layout)components.get(0));
        
        List<Lead_to_Case_Mapping__c> mapFields = [SELECT Case_field_API_Name__c, Lead_Field_API_Name__c, Default_Value__c FROM Lead_to_Case_Mapping__c];
        string query = 'SELECT Id';
        for (Lead_to_Case_Mapping__c mapField : mapFields) {
            if (mapFIeld.Lead_Field_API_Name__c != null && mapField.Lead_Field_API_Name__c != '') {
                query += ', ' + mapFIeld.Lead_Field_API_Name__c;
            }
        }
        query += ' FROM Lead WHERE Id = :leadId';
        System.debug(query);
        Lead fullLead = Database.query(query);
        
        newCase = new Case();
        for (Lead_to_Case_Mapping__c mapField : mapFields) {
            if (mapField.Lead_Field_API_Name__c != null && mapField.Lead_Field_API_Name__c != '') {
                if (mapField.Lead_Field_API_Name__c.contains('.')) {
                    if (fullLead.getSObject(mapField.Lead_Field_API_Name__c.split('\\.')[0]) != null) {
                        newCase.put(mapField.Case_field_API_Name__c, fullLead.getSObject(mapField.Lead_Field_API_Name__c.split('\\.')[0]).get(mapField.Lead_Field_API_Name__c.split('\\.')[1]));
                    }
                } else {
                    newCase.put(mapField.Case_field_API_Name__c, fullLead.get(mapField.Lead_Field_API_Name__c));
                }
            } else if (mapField.Default_Value__c != null && mapField.Default_Value__c != '') {
                newCase.put(mapField.Case_field_API_Name__c, mapField.Default_Value__c);
            }
        }
        newCase.Lead__c = fullLead.Id;
        newCase.Description = MitigatingCircumstances;
        if(nonSuccessStringSet.contains(passbookDecision)){
            newCase.Subject = 'Escalation from Passbook';
            newCase.Exception_Reason__c = passbookDecision;
        }
        newCase.Homeowner_Equity_Post_Funding__c = HEPF;
        newCase.Mortgage_Type__c = MortgageType == 'Amortizing' ? 'Amortizing' : 'Non-amortizing';
        
        PageReference pr = Page.LeadQualificationException;
        pr.setRedirect(false);
        return pr;
    }
    
    //class to handle boundary decision matrix return from passbook    
    public class DecisionBounderyWrapper{
        public string DecisionBounderyValue{get;set;}
        public string ApprovalDTIBoundaryValue{get;set;}
        public string EscalateDTIBoundaryValue{get;set;}
        
    }    
}