objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Yodlee_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Yodlee Order Requests</relationshipLabel>
        <relationshipName>Yodlee_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status Code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yodlee_Public_Id__c</fullName>
        <label>Yodlee Public Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Yodlee_YOR_Calls_Ext_TEST.cls
/**********************************************************
 * @className   : Yodlee_YOR_Calls_Ext_TEST.cls
 * @date        : May 11, 2018
 * @description : This class provide test methods for Yodlee_YOR_Calls_Ext.cls
 * @param       :
 * @return      :
 *
 *
 **********************************************************/ 

@isTest 
private class Yodlee_YOR_Calls_Ext_TEST {

	@isTest
	private static void testName() {
		Account acc = new Account(Name = 'New Account');
		insert acc; 

		Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
		                          AccountID = acc.Id);
		insert con;

		Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
		                          AccountID = acc.Id);
		insert con2;

		Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
									CloseDate = Date.today().addDays(20), Is_there_Co_App__c = true, Applicant__c = con.Id,
									Co_Applicant__c = con2.Id);
		insert oppty;

		Yodlee_Order_Request__c yor = new Yodlee_Order_Request__c();
		yor.Opportunity__c = oppty.Id;
		yor.Name = 'YOR Name';
		yor.Yodlee_Public_Id__c = '6f098ce4-a14f-4604-622e-a0ab76d557dd';
		insert yor;

		System.Test.startTest();
			
			ApexPages.currentPage().getParameters().put('id', yor.Id);
			ApexPages.currentPage().getParameters().put('action', 'CheckOrderStatus');
			Yodlee_YOR_Calls_Ext ctrl = new Yodlee_YOR_Calls_Ext();
			ctrl.init();

			ctrl.BackToYOR();

		System.Test.stopTest();

		yor = [Select Id, Status__c from Yodlee_Order_Request__c Where id = :yor.Id];
		System.assertEquals(yor.Status__c, 7);
	}

	@isTest
	private static void testName2() {
		Account acc = new Account(Name = 'New Account');
		insert acc; 

		Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
		                          AccountID = acc.Id);
		insert con;

		Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
		                          AccountID = acc.Id);
		insert con2;

		Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
									CloseDate = Date.today().addDays(20), Is_there_Co_App__c = true, Applicant__c = con.Id,
									Co_Applicant__c = con2.Id);
		insert oppty;

		Yodlee_Order_Request__c yor = new Yodlee_Order_Request__c();
		yor.Opportunity__c = oppty.Id;
		yor.Name = 'YOR Name';
		yor.Yodlee_Public_Id__c = '6f098ce4-a14f-4604-622e-a0ab76d557dd';
		insert yor;

		System.Test.startTest();
			
			ApexPages.currentPage().getParameters().put('id', yor.Id);
			ApexPages.currentPage().getParameters().put('action', 'RetriveOrder');
			Yodlee_YOR_Calls_Ext ctrl = new Yodlee_YOR_Calls_Ext();
			ctrl.init();

			ctrl.BackToYOR();

		System.Test.stopTest();

		yor = [Select Id, Status__c from Yodlee_Order_Request__c Where id = :yor.Id];
		System.assertEquals(yor.Status__c, 7);
	}

	@isTest
	private static void testName3() {
		Account acc = new Account(Name = 'New Account');
		insert acc; 

		Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
		                          AccountID = acc.Id);
		insert con;

		Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
		                          AccountID = acc.Id);
		insert con2;

		Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
									CloseDate = Date.today().addDays(20), Is_there_Co_App__c = true, Applicant__c = con.Id,
									Co_Applicant__c = con2.Id);
		insert oppty;

		Yodlee_Order_Request__c yor = new Yodlee_Order_Request__c();
		yor.Opportunity__c = oppty.Id;
		yor.Name = 'YOR Name';
		yor.Yodlee_Public_Id__c = '6f098ce4-a14f-4604-622e-a0ab76d557dd';
		insert yor;

		System.Test.startTest();
			
			ApexPages.currentPage().getParameters().put('id', yor.Id);
			ApexPages.currentPage().getParameters().put('action', 'SendEmailReissue');
			Yodlee_YOR_Calls_Ext ctrl = new Yodlee_YOR_Calls_Ext();
			ctrl.init();

			ctrl.BackToYOR();

		System.Test.stopTest();
	}
}