objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Parcel_Number__c</fullName>
        <label>Property Parcel Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spruce_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Spruce Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>new</fullName>
                    <default>true</default>
                    <label>new</label>
                </value>
                <value>
                    <fullName>initial_docs_available</fullName>
                    <label>Initial Docs Available</label>
                </value>
                <value>
                    <fullName>title_report_available</fullName>
                    <label>Title Report Available</label>
                </value>
                <value>
                    <fullName>closing_scheduled</fullName>
                    <label>Closing Scheduled</label>
                </value>
                <value>
                    <fullName>closing_confirmed</fullName>
                    <label>Closing Confirmed</label>
                </value>
                <value>
                    <fullName>closing_docs_submitted</fullName>
                    <label>Closing Docs Submitted</label>
                </value>
                <value>
                    <fullName>closing_occurred</fullName>
                    <label>Closing Occurred</label>
                </value>
                <value>
                    <fullName>funded</fullName>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>recorded</fullName>
                    <label>Recorded</label>
                </value>
                <value>
                    <fullName>policy_issued</fullName>
                    <label>Policy Issued</label>
                </value>
                <value>
                    <fullName>Required</fullName>
                    <isActive>false</isActive>
                    <label>Required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetTitleInfoControllerTest.cls
@isTest
private class GetTitleInfoControllerTest 
{	
	@isTest static void test_method_one() 
    { 
        // Data Setup
        Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                                  AccountID = acc.Id);
        insert con2;

        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20), Is_there_Co_App__c = true, Applicant__c = con.Id,
                                    Co_Applicant__c = con2.Id);
        insert oppty;

        Property_Due_Diligence_Reports__c pddr = new Property_Due_Diligence_Reports__c();
        pddr.Spruce_Order_Id__c = 'testOrderInfo';
        pddr.Opportunity__c = oppty.Id;
        pddr.Status__c = 'Ordered';
        insert pddr;

        Property_Due_Diligence_Reports__c pddr2 = new Property_Due_Diligence_Reports__c();
        pddr2.Opportunity__c = oppty.Id;
        pddr2.Status__c = 'Ordered';
        insert pddr2;

        Test.setMock(HttpCalloutMock.class, new SpruceCalloutMock());

        // Run Code
		ApexPages.StandardController sc = new ApexPages.StandardController(pddr);

        PageReference pageRef = Page.GetTitleInfo;
        pageRef.getParameters().put('id', String.valueOf(pddr.Id));
        Test.setCurrentPage(pageRef);

        GetTitleInfoController ctrl = new GetTitleInfoController(sc);
        ctrl.UpdateRecordInfo();
        ctrl.goBack();

        // Verify Result
        List<Property_Due_Diligence_Reports__c> pddrList = 
            [
                SELECT Id, Property_Parcel_Number__c
                FROM Property_Due_Diligence_Reports__c
            ];

        //System.assertEquals(pddrList[0].Property_Parcel_Number__c, '230-110-023');
	}
}