objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>Properties for which customers and indirect channel partners (loan officers, real estate agents, etc) have inquired the investment approval status.</description>
    <fields>
        <fullName>Build_Year__c</fullName>
        <label>Build Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_New_Construction_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Construction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <inlineHelpText>State must be only two characters in length.</inlineHelpText>
        <label>State / Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <inlineHelpText>Property address including street number, street name, suffixes and unit.</inlineHelpText>
        <label>Full Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip  / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spruce_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Spruce Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single-family detached</fullName>
    </customValue>
    <customValue>
        <fullName>Condominium</fullName>
    </customValue>
    <customValue>
        <fullName>2-4 Family</fullName>
    </customValue>
    <customValue>
        <fullName>PUD</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Detached</fullName>
        <isActive>false</isActive>
        <label>Detached</label>
    </customValue>
    <masterLabel>Property Type</masterLabel>
</GlobalValueSet>

classes/testSpruceRestService.cls
@isTest
public class testSpruceRestService {
        @testSetup static void setup(){
        Account acc = new Account(Name = 'New Account');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = acc.Id);
        insert con2;

        /* 4/2/2019 Sundar Subramaniam - Is_there_Co_App__c removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Property_Type__c = '2-4 Family',Probability = 90,
                Co_Applicant__c = con2.Id,Encompass_Loan_Number__c = '10',Final_OAV_Calculation__c=100,Lien_First_Lender_Balance__c = 100);
        insert oppty;
            
            Property__c newprop = new Property__c();
            newprop.Name = 'Test';
            newprop.Property_Type__c = '2-4 Family';
            newprop.Build_Year__c = '2019';
            newprop.Property_New_Construction_Flag__c = True;
            newprop.Property_Street_Number_and_Name__c = 'test asd 123';
            newprop.Property_City__c = 'test asd 123';
            newprop.Property_State__c = 'CA';
            newprop.Property_Zip_Code__c = '12345';
            newprop.Property_County__c = 'test asd 123';
            newprop.Opportunity__c=oppty.Id;
            insert newprop;
            
            Property_Due_Diligence_Reports__c spruceOrder = new Property_Due_Diligence_Reports__c();
            spruceOrder.RecordTypeId = Schema.SObjectType.Property_Due_Diligence_Reports__c.getRecordTypeInfosByName().get(Label.Property_Due_Diligence_Rep_RT_Spruce).getRecordTypeId();
            spruceOrder.Spruce_Order_Id__c = '114360001409';
            spruceOrder.Opportunity__c = oppty.Id;
            insert spruceOrder;
    }
    /*
    @IsTest
    public class MockGetToken implements HttpCalloutMock {
        public HttpResponse respond(HTTPRequest req) {
            Property__c newprop = [SELECT id FROM Property__c LIMIT 1];

            System.debug('newprop'+newprop);
              
            String mockResponseBody = '{"order":{ "order_status": "Ok","order": {"id": "'+spruceOrder.Id+'","order_status": "Ok"}}}';
            
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody(mockResponseBody);

            return res;            
        }
    }*/
    @IsTest
    public static void testrest(){
        
        Property__c newprop = [SELECT id FROM Property__c LIMIT 1];
        System.debug('newprop'+newprop);
        String JSONMsg = '{ "event_id": "35e8609c-7ce4-43fd-9b43-61c0d9ebd1a8","event": "order_status_changed","timestamp": "2019-04-04T14:16:23Z","payload": {"file_number": "114360001409","order_id": "33048c21-3fd8-4182-8b06-1157f6b07979","status": "initial_docs_available"}}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/SpruceRS/*';
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json');
        req.addHeader('apikey', +System.Label.Spruce_Header);
        req.requestBody = Blob.valueof(JSONMsg);
        
        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        String returndopost =SpruceRestService.doPost();
        Test.stopTest();
    }
    @IsTest
    public static void testrest2(){
        
        Property__c newprop = [SELECT id FROM Property__c LIMIT 1];
        System.debug('newprop'+newprop);
        String JSONMsg = '{ "event_id": "35e8609c-7ce4-43fd-9b43-61c0d9ebd1a8","event": "order_status_changed","timestamp": "2019-04-04T14:16:23Z","payload": {"file_number": "null","order_id": "33048c21-3fd8-4182-8b06-1157f6b07979","status": "initial_docs_available"}}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/SpruceRS/*';
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json');
        req.addHeader('apikey', +System.Label.Spruce_Header);
        req.requestBody = Blob.valueof(JSONMsg);
        
        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        String returndopost =SpruceRestService.doPost();
        Test.stopTest();
    }
    
    @IsTest
    public static void testrest3(){
        
        Property__c newprop = [SELECT id FROM Property__c LIMIT 1];
        System.debug('newprop'+newprop);
        String JSONMsg = '{ "event1": "order_status_changed","timestamp": "2019-04-04T14:16:23Z","payloadtest": {"order_id": "33048c21-3fd8-4182-8b06-1157f6b07979","status": "initial_docs_available"}}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/SpruceRS/*';
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json');
        req.addHeader('apikey', +System.Label.Spruce_Header);
        req.requestBody = Blob.valueof(JSONMsg);
        
        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        String returndopost =SpruceRestService.doPost();
        SpruceRestService.RequestWrapper rw = new SpruceRestService.RequestWrapper();
        rw.event_id = '35e8609c-7ce4-43fd-9b43-61c0d9ebd1a8';
        System.assertequals(rw.event_id,'35e8609c-7ce4-43fd-9b43-61c0d9ebd1a8');
        Test.stopTest();
    } 
    
}