objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Marketing_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketing Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delighted_Trigger_Status__c</fullName>
        <formula>IF( 
    MOD(VALUE(Delighted_Index__c), 4)==0 &amp;&amp; ISPICKVAL(StageName, "CAP Sent")  &amp;&amp; RecordTypeId == "012E00000002OH1", "Offer Package Sent for HO",
    IF(
        MOD(VALUE(Delighted_Index__c), 4)==1 &amp;&amp; ISPICKVAL(StageName, "Offer Package Sent")  &amp;&amp; RecordTypeId == "012E00000002OHB", "CAP Sent for HB",
        IF( 
            MOD(VALUE(Delighted_Index__c), 4)==2 &amp;&amp; RSI_Sent__c &amp;&amp; RecordTypeId == "012E00000002OHB" , "RS1 Letter Sent to HO", 
            IF( 
                MOD(VALUE(Delighted_Index__c), 4)==3 &amp;&amp; Estimated_Funding_Amount_Changed__c, "Funding Amount Changed", 
                ""
            )
        ) 
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delighted Trigger Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Code__c</fullName>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMS_Opt_out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelightedFundedOppBatch.cls
global class DelightedFundedOppBatch implements Schedulable, Database.Stateful, Database.AllowsCallouts, Database.Batchable<sObject> {

	global void execute(SchedulableContext SC) {
		Database.executeBatch(new DelightedFundedOppBatch(), 1);
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
        Date sevenDaysAgo = Date.today().addDays(-7);
		return Database.getQueryLocator('SELECT Id, Applicant__r.Email, Applicant__r.Phone, Applicant__r.Name, RecordTypeId, RecordType.Name, OwnerId, ' +
                                        		'StageName, SMS_Opt_out__c, Loss_Reason_Code__c, Delighted_Trigger_Status__c, Owner.Name ' +
                                        	'FROM Opportunity WHERE Wire_to_Agent_Date__c = :sevenDaysAgo AND Applicant__r.Marketing_Opt_Out__c = false');
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope) {
        DelightedHelper.SendSurveyFundedOpp((Opportunity)scope[0]);
	}
	
	global void finish(Database.BatchableContext BC) {
	}
}