objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spruce_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Spruce Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetDocumentsControllerTest.cls
@isTest
private class GetDocumentsControllerTest 
{	
	@isTest static void test_method_one() 
    {
		// Data Setup
        Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                                  AccountID = acc.Id);
        insert con2;

        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20), Is_there_Co_App__c = true, Applicant__c = con.Id,
                                    Co_Applicant__c = con2.Id);
        insert oppty;

        Property_Due_Diligence_Reports__c pddr = new Property_Due_Diligence_Reports__c();
        pddr.Spruce_Order_Id__c = 'testOrderInfo';
        pddr.Opportunity__c = oppty.Id;
        insert pddr;

        GetDocumentsController.DocumentTypeWrapper dtw = new GetDocumentsController.DocumentTypeWrapper();
        dtw.isChecked = true;
        dtw.documentType = 'testDocumentType';

        Test.setMock(HttpCalloutMock.class, new SpruceCalloutMock());

        // Run Code
        ApexPages.StandardController sc = new ApexPages.StandardController(pddr);

        PageReference pageRef = Page.GetDocuments;
        pageRef.getParameters().put('id', String.valueOf(pddr.Id));
        Test.setCurrentPage(pageRef);
		
        GetDocumentsController.getSpruceCredentials();
        GetDocumentsController ctrl = new GetDocumentsController(sc);
        ctrl.GetRecordTypes();
        ctrl.documentTypeWrapperList.add(dtw);
        //ctrl.GetDocuments();
        ctrl.goBack();
       

        // Test Result
        //System.assertEquals(ctrl.attachmentList.size(), 1);*/
	}	
}