objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Invited to Train</fullName>
                </value>
                <value>
                    <fullName>Training Scheduled</fullName>
                </value>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>1st Lead Submitted</fullName>
                </value>
                <value>
                    <fullName>2nd Lead Submitted</fullName>
                </value>
                <value>
                    <fullName>3rd Lead Submitted</fullName>
                </value>
                <value>
                    <fullName>LO Active Converted</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delighted_Error__c</fullName>
        <label>Delighted Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LOP_Contact_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>LOP Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LO_Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LO Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Types of clients</fullName>
                </value>
                <value>
                    <fullName>Loan product</fullName>
                </value>
                <value>
                    <fullName>Moved to unapproved branch</fullName>
                </value>
                <value>
                    <fullName>Don't understand</fullName>
                </value>
                <value>
                    <fullName>Distrust</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Full_Name__c</fullName>
        <description>The first name of the applicant. As of Q4-2019, this field has been identified
            by Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <formula>FirstName &amp;" "&amp;LastName</formula>
        <label>Applicant Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delighted_Error__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and relevant
            stakeholders) as used or otherwise relevant to current business processes. To be
            reviewed next Q4 2021.</description>
        <label>Delighted Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delighted_Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Delighted Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delighted_Trigger_Status__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <formula>IF(
    MOD(VALUE(Delighted_Index__c), 4)==0 &amp;&amp; ISPICKVAL(Credit_Pre_Qualification_Status__c, "Approved"), "Credit Pre Qualification Status is Approved",
    IF(
        MOD(VALUE(Delighted_Index__c), 4)==1 &amp;&amp; ISPICKVAL(Status, "Application Sent"), "Application Sent",
        IF(
            MOD(VALUE(Delighted_Index__c), 4)==2 &amp;&amp; ISPICKVAL(Status, "Submitted"), "Submitted",
            IF(
                MOD(VALUE(Delighted_Index__c), 4)==3 &amp;&amp; !ISBLANK(Time_of_First_Call__c), "First Contacted",
                ""
            )
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delighted Trigger Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Loss Reason Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant does not meet non-credit related application criteria</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Collection action or judgement</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>COVID-19</fullName>
                </value>
                <value>
                    <fullName>Customer information is fake or cannot be used to contact the customer</fullName>
                </value>
                <value>
                    <fullName>Delinquent past or present obligations with others</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income &amp; Insufficient equity in the property</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income &amp; value of property in excess of allowed maximum</fullName>
                </value>
                <value>
                    <fullName>Felony</fullName>
                </value>
                <value>
                    <fullName>First contact - Asked to be removed</fullName>
                </value>
                <value>
                    <fullName>Frustration with Unison</fullName>
                </value>
                <value>
                    <fullName>Garnishment or attachment</fullName>
                </value>
                <value>
                    <fullName>Insufficient equity in the property</fullName>
                </value>
                <value>
                    <fullName>Insufficient savings for purchase price range</fullName>
                </value>
                <value>
                    <fullName>Lack of trust</fullName>
                </value>
                <value>
                    <fullName>Lender (HB only)</fullName>
                </value>
                <value>
                    <fullName>Length of employment</fullName>
                </value>
                <value>
                    <fullName>Length of residence</fullName>
                </value>
                <value>
                    <fullName>No credit file</fullName>
                </value>
                <value>
                    <fullName>Non-English / Non-Spanish Speaker</fullName>
                </value>
                <value>
                    <fullName>Non-owner occupied property</fullName>
                </value>
                <value>
                    <fullName>Notice of default, foreclosure or repossession</fullName>
                </value>
                <value>
                    <fullName>Not operating in requested state</fullName>
                </value>
                <value>
                    <fullName>Number of recent inquiries on credit bureau report</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Reported Credit (single score) below our minimum requirement</fullName>
                </value>
                <value>
                    <fullName>Reported credit below our minimum requirement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Select reason for the lead loss.</inlineHelpText>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Net_Promoter_Measurement__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delighted_Id__c</fullName>
        <label>Delighted Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permalink__c</fullName>
        <label>Permalink</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Net Promoter Measurement</label>
    <nameField>
        <displayFormat>NPM-{0000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Net Promoter Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delighted_Error__c</fullName>
        <label>Delighted Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delighted_Post_Closing_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delighted Post Closing Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delighted_Survey_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delighted Survey Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delighted_Trigger_Status__c</fullName>
        <formula>IF( 
    MOD(VALUE(Delighted_Index__c), 4)==0 &amp;&amp; ISPICKVAL(StageName, "CAP Sent")  &amp;&amp; RecordTypeId == "012E00000002OH1", "Offer Package Sent for HO",
    IF(
        MOD(VALUE(Delighted_Index__c), 4)==1 &amp;&amp; ISPICKVAL(StageName, "Offer Package Sent")  &amp;&amp; RecordTypeId == "012E00000002OHB", "CAP Sent for HB",
        IF( 
            MOD(VALUE(Delighted_Index__c), 4)==2 &amp;&amp; RSI_Sent__c &amp;&amp; RecordTypeId == "012E00000002OHB" , "RS1 Letter Sent to HO", 
            IF( 
                MOD(VALUE(Delighted_Index__c), 4)==3 &amp;&amp; Estimated_Funding_Amount_Changed__c, "Funding Amount Changed", 
                ""
            )
        ) 
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delighted Trigger Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Code__c</fullName>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMS_Opt_out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelightedHelper.cls
public class DelightedHelper {
    
    public static boolean skipCall = false;
    
    public static void SendSurveyLead(Id npmId, Id lId) {

        if (skipCall) return;
        
        Lead l = [SELECT Id, Email, Phone, Applicant_Full_Name__c, RecordTypeId, RecordType.Name, OwnerId, Status, tdc_tsw__SMS_Opt_out__c, Loss_Reason_Type__c, Delighted_Trigger_Status__c, Owner.Name FROM Lead WHERE Id = :lId];

        DelightedAPI.SendSurveyResponse resp = DelightedAPI.SendSurvey(l.Status == 'Closed Lost' ? 'Project' : 'Standard', l.Email, l.Applicant_Full_Name__c, l.Phone, l.OwnerId, l.RecordTypeId, l.RecordType.Name, 'lead', lId, l.Status, l.tdc_tsw__SMS_Opt_out__c, l.Loss_Reason_Type__c, l.Delighted_Trigger_Status__c, l.Owner.Name);

        if (resp.success) {
            l.Delighted_Survey_Sent__c = true;
            l.Delighted_Error__c = '';
            update l;
            
            Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
            npm.Id = npmId;
            npm.Delighted_Id__c = resp.id;
            npm.Status__c = 'Success';
            update npm;
        } else {
            if (resp.error.length() > 32767)
                resp.error = resp.error.substring(0, 32767);
            l.Delighted_Error__c = resp.error;
            update l;
            
            Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
            npm.Id = npmId;
            npm.Status__c = 'Error';
            update npm;
        }
    }

    public static void SendSurveyOpportunity(Id npmId, Id oId) {

        if (skipCall) return;
        
        Opportunity o = [SELECT Id, Applicant__r.Email, Applicant__r.Phone, Applicant__r.Name, RecordTypeId, RecordType.Name, OwnerId, StageName, SMS_Opt_out__c, Loss_Reason_Code__c, Delighted_Trigger_Status__c, Owner.Name FROM Opportunity WHERE Id = :oId];

        DelightedAPI.SendSurveyResponse resp = DelightedAPI.SendSurvey(o.StageName == 'Closed Lost' ? 'Project' : 'Standard', o.Applicant__r.Email, o.Applicant__r.Name, o.Applicant__r.Phone, o.OwnerId, o.RecordTypeId, o.RecordType.Name, 'opportunity', oId, o.StageName, o.SMS_Opt_out__c, o.Loss_Reason_Code__c, o.Delighted_Trigger_Status__c, o.Owner.Name);

        if (resp.success) {
            o.Delighted_Survey_Sent__c = true;
            o.Delighted_Error__c = '';
            update o;
            
            Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
            npm.Id = npmId;
            npm.Delighted_Id__c = resp.id;
            npm.Status__c = 'Success';
            update npm;
        } else {
            if (resp.error.length() > 32767)
                resp.error = resp.error.substring(0, 32767);
            o.Delighted_Error__c = resp.error;
            update o;
            
            Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
            npm.Id = npmId;
            npm.Status__c = 'Error';
            update npm;
        }

    }

    public static void SendSurveyFundedOpp(Opportunity o) {
        
        if (skipCall) return;

        DelightedAPI.SendSurveyResponse resp = DelightedAPI.SendSurvey('Funded_Opp', o.Applicant__r.Email, o.Applicant__r.Name, o.Applicant__r.Phone, o.OwnerId, o.RecordTypeId, o.RecordType.Name, 'opportunity', o.Id, o.StageName, o.SMS_Opt_out__c, o.Loss_Reason_Code__c, o.Delighted_Trigger_Status__c, o.Owner.Name);

        if (resp.success) {
            o.Delighted_Post_Closing_Sent__c = true;
            o.Delighted_Error__c = '';
            update o;
            
            Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
            npm.Opportunity__c = o.Id;
            npm.Delighted_Id__c = resp.id;
            insert npm;
        } else {
            if (resp.error.length() > 32767)
                resp.error = resp.error.substring(0, 32767);
            o.Delighted_Error__c = resp.error;
            update o;
        }
        
    }
    
	public static void SendSurveyLOContact(Contact con){

		DelightedAPI.SendSurveyResponse resp = DelightedAPI.SendLOSurvey(con.Email, con.Name, con.Phone, con.OwnerId, con.Account.Name, con.Contact_Status__c,
													 con.RecordTypeId, con.RecordType.Name, 'contact', con.Id, '', con.tdc_tsw__SMS_Opt_out__c, 
													 con.Loss_Reason__c, 'LO Trained', con.Owner.Name, con.LOP_Contact_Type__c, 'LO_Contact');

        if (resp.success) {
            con.LO_Survey_Sent__c = true;
			con.Delighted_Error__c = '';
            update con;
            
            Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
            npm.Contact__c = con.Id;
            npm.Delighted_Id__c = resp.id;
            insert npm;
        } else {
            if (resp.error.length() > 32767)
                resp.error = resp.error.substring(0, 32767);
            con.Delighted_Error__c = resp.error;
            update con;
        }
	}
    
    public static void HandleWebhook(String webhookBody) {
        System.debug(webhookBody);
        DelightedAPI.SurveyWebhookBody body = (DelightedAPI.SurveyWebhookBody)JSON.deserialize(webhookBody, DelightedAPI.SurveyWebhookBody.class);
        if (body.event_data != null && body.event_data.person_properties != null) {
            Net_Promoter_Measurement__c npm;
            if (body.event_data.person_properties.lead != null && body.event_data.person_properties.lead != '')
                npm = [SELECT Id FROM Net_Promoter_Measurement__c WHERE Lead__c = :body.event_data.person_properties.lead LIMIT 1];
            if (body.event_data.person_properties.opportunity != null && body.event_data.person_properties.opportunity != '')
                npm = [SELECT Id FROM Net_Promoter_Measurement__c WHERE Opportunity__c = :body.event_data.person_properties.opportunity LIMIT 1];
			if (body.event_data.person_properties.contact != null && body.event_data.person_properties.contact != '')
                npm = [SELECT Id FROM Net_Promoter_Measurement__c WHERE Contact__c = :body.event_data.person_properties.contact LIMIT 1];
            if (npm != null) {
                npm.Comment__c = body.event_data.comment;
                npm.Permalink__c = body.event_data.permalink;
                npm.Score__c = body.event_data.score;
                npm.Survey_Type__c = body.event_data.survey_type;
                string additionalAnswers = '';
                if (body.event_data.additional_answers != null) {
                    for (DelightedAPI.SurveyWebhookBodyAnswer aa : body.event_data.additional_answers) {
                        if (aa.question != null && aa.value != null) {
                            if (additionalAnswers != '')
                                additionalAnswers += '\n';
                            additionalAnswers += aa.question.text + ' : ';
                            if (aa.question.type == 'free_response')
                                additionalAnswers += aa.value.free_response;
                            if (aa.question.type == 'scale')
                                additionalAnswers += aa.value.scale;
                            if (aa.question.type == 'select_one' && aa.value.select_one != null)
                                additionalAnswers += aa.value.select_one.text;
                            if (aa.question.type == 'select_many' && aa.value.select_many != null) {
                                string answerCh = '';
                                for (DelightedAPI.SurveyWebhookBodyAnswerChoice ch : aa.value.select_many) {
                                    if (answerCh != '')
                                        answerCh += ', ';
                                    answerCh += ch.text;
                                }
                                additionalAnswers += answerCh;
                            }
                        }
                    }
                }
                npm.Additional_Answers__c = additionalAnswers;
                update npm;
            }
        }
    }

}