objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant_Birth_Date_Free_Response__c</fullName>
        <label>Birth Date (MM/DD/YYYY)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Birth_Date_Free_Response__c</fullName>
        <description>A free text field that cerocds the applicants birthday. Scheduled for deletion
            following field cutover and backfill coordination with Engineering. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Birth Date (MM/DD/YYYY)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant_Credit_Score_Estimate__c</fullName>
        <description>2019-10-18 - The output of the question in the only pre-qual form. As of
            Q4-2019, this field has been identified by Business Systems (and relevant stakeholders)
            as used or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Credit Score Estimate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <description>2019-10-28 - The balance of what is owned to the lender who is in first lien
            position. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_Second_Lender_Balance__c</fullName>
        <description>2019-10-28 - The balance of what is owned to the lender who is in second lien
            position. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Lien Second Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>2019-10-28 - Homebuyer only. How much the person will borrow on their first
            mortgage. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>City of prospective customer's property</inlineHelpText>
        <label>Property Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Zip Code of customer's property</inlineHelpText>
        <label>Property Address Zip/Postal Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <description>Purchase price of the lead property As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <label>Purchase Contract Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LendingTreeWebhook.cls
@RestResource(urlMapping='/LendingTree/*')
global with sharing class LendingTreeWebhook  
{
    @HttpPost
    global static void CreateLead()
    {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String jsonStr = '';


        if (req != null && req.requestBody != null)
        {
            jsonStr = req.requestBody.toString();
            Id homeOwnerRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();

            Dom.Document doc = new Dom.Document();
            doc.load(jsonStr);

            Dom.XMLNode rootXml = doc.getRootElement();
			 
            try 
            { 
                Lead newLead = new Lead();            
     
                newLead.Street = GetAttributeValue('ContactAddress', rootXml, 'ConsumerContactInformation', ''); 
                newLead.City = GetAttributeValue('ContactCity', rootXml, 'ConsumerContactInformation', ''); 
                newLead.State = GetAttributeValue('ContactState', rootXml, 'ConsumerContactInformation', ''); 
                newLead.PostalCode = GetAttributeValue('ContactZip', rootXml, 'ConsumerContactInformation', ''); 
                newLead.Email = GetAttributeValue('EmailAddress', rootXml, 'ConsumerContactInformation', ''); 
                newLead.Phone = GetAttributeValue('ContactPhone', rootXml, 'ConsumerContactInformation', ''); 
                newLead.FirstName = GetAttributeValue('FirstName', rootXml, 'ConsumerContactInformation', ''); 
                newLead.LastName = GetAttributeValue('LastName', rootXml, 'ConsumerContactInformation', ''); 
                newLead.Applicant_Birth_Date_Free_Response__c = GetAttributeValue('DateOfBirth', rootXml, 'ConsumerProfileInformation', ''); 
                newLead.LASERCA__SSN__c = GetAttributeValue('SSN', rootXml, 'ConsumerProfileInformation', ''); 
                newLead.Applicant_Credit_Score_Estimate__c = GetAttributeValue('AssignedCreditValue', rootXml, 'ConsumerProfileInformation', 'Credit'); 
                newLead.Purchase_Price__c = Decimal.valueOf(GetAttributeValue('PropertyPurchasePrice', rootXml, 'ConsumerProfileInformation', 'ProductProfileInformation')); 
                newLead.Home_Value__c = Decimal.valueOf(GetAttributeValue('PropertyValue', rootXml, 'ProductInformation', 'PropertyInformation')); 
                newLead.Property_City__c = GetAttributeValue('PropertyCity', rootXml, 'ProductInformation', 'PropertyInformation'); 
                newLead.Property_State__c = GetAttributeValue('PropertyState', rootXml, 'ProductInformation', 'PropertyInformation'); 
                newLead.Property_Zip_Code__c = GetAttributeValue('PropertyZip', rootXml, 'ProductInformation', 'PropertyInformation');
                if(!String.isBlank(GetAttributeValue('LoanAmount', rootXml, 'LoanInformation', ''))){
                	newLead.Loan_Amount__c = Decimal.valueOf(GetAttributeValue('LoanAmount', rootXml, 'LoanInformation', ''));    
                }
                if(!String.isBlank(GetAttributeValue('FirstMortgageBalance', rootXml, 'LoanInformation', ''))){
                	newLead.Lien_First_Lender_Balance__c = Decimal.valueOf(GetAttributeValue('FirstMortgageBalance', rootXml, 'LoanInformation', ''));    
                }
                if(!String.isBlank(GetAttributeValue('SecondMortgageBalance', rootXml, 'LoanInformation', ''))){
                	newLead.Lien_Second_Lender_Balance__c = Decimal.valueOf(GetAttributeValue('SecondMortgageBalance', rootXml, 'LoanInformation', ''));    
                }
                newLead.RecordTypeId = homeOwnerRecordTypeId;
                newLead.Company = newLead.FirstName + ' ' + newLead.LastName;

                Database.SaveResult[] srList = Database.insert(new Lead[]{newLead}, false);
				
                //res.responseBody = Blob.valueOf('The following record was successfully created: ' + srList[0].getId());
                res.addHeader('Content-Type', 'application/xml');
                res.responseBody = Blob.valueOf('<LTACK><ERRSTATUS><QFNAME>' + GetAttributeValue('TrackingNumber', rootXml, '', '') + '</QFNAME><ERRORNUM>0</ERRORNUM><ERRORDESCRIPTION>The following record was successfully created: ' + srList[0].getId() + '</ERRORDESCRIPTION></ERRSTATUS></LTACK>');
                //insert newLead;
            }
            catch(Exception e)
            {
                //res.responseBody = Blob.valueOf(e.getMessage() + '. Please contact your Salesforce Administrator.');
                res.addHeader('Content-Type', 'application/xml');
                res.responseBody = Blob.valueOf('<LTACK><ERRSTATUS><QFNAME>' + GetAttributeValue('TrackingNumber', rootXml, '', '') + '</QFNAME><ERRORNUM>0</ERRORNUM><ERRORDESCRIPTION>' + e.getMessage() + '. Please contact your Salesforce Administrator.</ERRORDESCRIPTION></ERRSTATUS></LTACK>'); 
            }
        }
    }

    global static String GetAttributeValue(String attributeName, Dom.XMLNode rootXml, String rootSubnode, String rootSubnodeChildren)
    {
        String attributeValue = '';

        if(rootSubnodeChildren == '' && rootSubnode == '')
        {
        	attributeValue = rootXml.getChildElement(attributeName, null).getText();    
        }
        else if(rootSubnodeChildren == '')
        { 
            attributeValue = rootXml.getChildElement(rootSubnode, null).getChildElement(attributeName, null).getText();
        }
        else
        {
            attributeValue = rootXml.getChildElement(rootSubnode, null).getChildElement(rootSubnodeChildren, null).getChildElement(attributeName, null).getText();
        }

        return attributeValue;
    }
}