objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Declaration_Explanation__c</fullName>
        <label>Declaration Explanation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant2)</relationshipLabel>
        <relationshipName>Opportunities_Applicant2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant3</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant3)</relationshipLabel>
        <relationshipName>Opportunities_Applicant3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (CoApplicant2)</relationshipLabel>
        <relationshipName>Opportunities_CoApplicant2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant3</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (CoApplicant3)</relationshipLabel>
        <relationshipName>Opportunities_CoApplicant3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Declaration_Explanation__c</fullName>
        <label>Declaration Explanation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CombinedDeclarations_EXT.cls
public class CombinedDeclarations_EXT {

    //Deprecated --- Not used
    /*
    private final Opportunity theOpp;
    private final Id oppId;    
    
    public CombinedDeclarations_EXT(apexpages.StandardController sc){
        theOpp = (Opportunity)sc.getRecord();
        oppId = sc.getId();
    }
    
    public string getCombinedDeclarations(){
        string toReturn = '';
        for(Opportunity o: [SELECT Applicant__r.Declaration_Explanation__c,
                            Applicant2__r.Declaration_Explanation__c,
                            Applicant3__r.Declaration_Explanation__c,
                            Co_Applicant__r.Declaration_Explanation__c,
                            Co_Applicant2__r.Declaration_Explanation__c,
                            Co_Applicant3__r.Declaration_Explanation__c
                            FROM Opportunity WHERE Id=:this.oppId]){
        	toReturn += (o.Applicant__r.Declaration_Explanation__c != NULL ? 'app1:' + o.Applicant__r.Declaration_Explanation__c  + '<br/><br/>' : '');
        	toReturn += (o.Co_Applicant__r.Declaration_Explanation__c != NULL ? 'co-app1:' +  o.Co_Applicant__r.Declaration_Explanation__c  + '<br/><br/>': '');
        	toReturn += (o.Applicant2__r.Declaration_Explanation__c != NULL ? 'app2:' + o.Applicant2__r.Declaration_Explanation__c  + '<br/><br/>': '');
        	toReturn += (o.Co_Applicant2__r.Declaration_Explanation__c != NULL ? 'co-app2:' + o.Co_Applicant2__r.Declaration_Explanation__c  + '<br/><br/>': '');
        	toReturn += (o.Applicant3__r.Declaration_Explanation__c != NULL ? 'app3:' + o.Applicant3__r.Declaration_Explanation__c  + '<br/><br/>': '');
        	toReturn += (o.Co_Applicant3__r.Declaration_Explanation__c != NULL ? 'co-app3:' + o.Co_Applicant3__r.Declaration_Explanation__c  + '<br/><br/>': '');                                
		}
        return toReturn;
    }
    */
}