objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the Estimated Home Value stated from customer or Unison AVM</description>
        <inlineHelpText>This is the Estimated Home Value stated from customer or Unison AVM</inlineHelpText>
        <label>Estimated Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <inlineHelpText>HomeBuyer field</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recorded_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recorded Information</label>
        <referenceTo>Recorded_Information__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>Properties for which customers and indirect channel partners (loan officers, real estate agents, etc) have inquired the investment approval status.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Legal_Description__c</fullName>
        <label>Legal Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property_Parcel_Number__c</fullName>
        <label>Parcel Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <inlineHelpText>State must be only two characters in length.</inlineHelpText>
        <label>State / Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <inlineHelpText>Property address including street number, street name, suffixes and unit.</inlineHelpText>
        <label>Full Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip  / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Legal_Description__c</fullName>
        <label>Property Legal Description</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property_Parcel_Number__c</fullName>
        <label>Property Parcel Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>new</fullName>
                    <default>true</default>
                    <label>new</label>
                </value>
                <value>
                    <fullName>initial_docs_available</fullName>
                    <label>Initial Docs Available</label>
                </value>
                <value>
                    <fullName>title_report_available</fullName>
                    <label>Title Report Available</label>
                </value>
                <value>
                    <fullName>closing_scheduled</fullName>
                    <label>Closing Scheduled</label>
                </value>
                <value>
                    <fullName>closing_confirmed</fullName>
                    <label>Closing Confirmed</label>
                </value>
                <value>
                    <fullName>closing_docs_submitted</fullName>
                    <label>Closing Docs Submitted</label>
                </value>
                <value>
                    <fullName>closing_occurred</fullName>
                    <label>Closing Occurred</label>
                </value>
                <value>
                    <fullName>funded</fullName>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>recorded</fullName>
                    <label>Recorded</label>
                </value>
                <value>
                    <fullName>policy_issued</fullName>
                    <label>Policy Issued</label>
                </value>
                <value>
                    <fullName>Required</fullName>
                    <isActive>false</isActive>
                    <label>Required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recorded_Information__c.object
<CustomObject>
    <fields>
        <fullName>Applicant1_Name__c</fullName>
        <label>ZZZ Applicant 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZZZ Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZZZ Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Informations (Co-Applicant)</relationshipLabel>
        <relationshipName>Recorded_Informations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Parcel_Number__c</fullName>
        <description>Property_Parcel_Number was used from May to Sept '19. RecInfo Parcel # was used from Oct '19 to Current. Need to combine fields. AM 5/11/20</description>
        <label>Property Parcel Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>Used for Nintex - HO Offer Package to populate Corporate Entity + State</description>
        <label>Property State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Recorded Information</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Recorded Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recorded Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wiring_Information__c.object
<CustomObject>
    <fields>
        <fullName>CustomerState__c</fullName>
        <label>Customer State</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Company__c</fullName>
        <label>Title Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wiring Information</label>
    <nameField>
        <label>Wiring Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiring Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Opp_Spruce_EXT_Test.cls
@isTest
private class Opp_Spruce_EXT_Test 
{   
    @isTest static void test_method_one()
    {
        // Data Setup
        Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                                  AccountID = acc.Id);
        insert con2;
        /* 4/2/2019 Sundar Subramaniam - Field removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Encompass_Loan_Number__c='test01234567890',
                                    Co_Applicant__c = con2.Id, Property_Zip_Code__c = '1223', Property_State__c = 'CA', Property_City__c = 'Las vegas', Property_Street_Number_and_Name__c = 'testStreet', Home_Value__c = 2000, Loan_Amount__c = 2000 );
        insert oppty;
        Opportunity oppty2 = new Opportunity(Name = 'New Oppt2y', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20), Applicant__c = con.Id,
                                    Co_Applicant__c = con2.Id);
        insert oppty2;

        Wiring_Information__c winfo = new Wiring_Information__c(Name = 'FirstNam2e', CustomerState__c = 'CA', Title_Company__c = 'Spruce');
        insert winfo;

        Recorded_Information__c recordedInfo = new Recorded_Information__c();
        recordedInfo.Opportunity__c = oppty.Id;
        recordedInfo.Applicant1_Name__c = 'John';
        recordedInfo.Effective_Date__c = System.today();
        insert recordedInfo;
        
        Property__c prop = new Property__c();
        prop.Property_Parcel_Number__c = '123458';
        prop.Property_Legal_Description__c = 'This is a test';
        prop.Opportunity__c = oppty.Id;
        insert prop;



        // Utility method that can be called by Apex tests to create price book entries.
       // static testmethod void addPricebookEntries() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Settlement Fee',
        Family = 'Hardware');
        insert prod;

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();

        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
        Pricebook2Id = pricebookId, Product2Id = prod.Id,
        UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
        Pricebook2Id = customPB.Id, Product2Id = prod.Id,
        UnitPrice = 12000, IsActive = true);
        insert customPrice;



    // Run Code
        System.Test.startTest();

            ApexPages.StandardController sc = new ApexPages.StandardController(oppty);
            Opp_Spruce_EXT ctrl = new Opp_Spruce_EXT(sc);
            ctrl.createSpruceOrder();
            ctrl.BackToOppty();


        System.Test.stopTest();

        // Test Result
        List<Property_Due_Diligence_Reports__c> pddrList = 
            [
                SELECT Id
                FROM Property_Due_Diligence_Reports__c
            ];

        if(pddrList.size()<1){
        System.assertEquals(0, pddrList.size());
        }
    }

    @isTest static void test_method_two()
    {
        // Data Setup
        Account acc = new Account(Name = 'New Account');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = acc.Id);
        insert con2;
        /* 4/2/2019 Sundar Subramaniam - Field removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,
                Co_Applicant__c = con2.Id, Property_Zip_Code__c = '1223', Property_State__c = 'CA', Property_City__c = 'Las vegas', Property_Street_Number_and_Name__c = 'testStreet', Home_Value__c = 2000, Loan_Amount__c = 2000 );
        insert oppty;
        Opportunity oppty2 = new Opportunity(Name = 'New Oppt2y', AccountId = acc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,
                Co_Applicant__c = con2.Id);
        insert oppty2;

        Recorded_Information__c recordedInfo = new Recorded_Information__c();
        recordedInfo.Opportunity__c = oppty.Id;
        recordedInfo.Applicant1_Name__c = 'John';
        insert recordedInfo;

        Success_Factor__c sf     = new Success_Factor__c();
        sf.Opportunity__c     = oppty.Id;
        sf.Success_Factor__c  = 'Property Ownership';
        sf.Status__c  = 'In Progress';
        sf.Program__c = 'HO';
        insert sf;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = '2-4 Family';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Property_Flood_Zone__c = 'A10';
        newprop.Opportunity__c=oppty.Id;
        insert newprop;

        Wiring_Information__c winfo = new Wiring_Information__c(Name = 'FirstNam2e', CustomerState__c = 'CA', Title_Company__c = 'Spruce');
        insert winfo;
        // Run Code
        System.Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(oppty);
        Opp_Spruce_EXT ctrl = new Opp_Spruce_EXT(sc);
        ctrl.createSpruceOrder();
        ctrl.BackToOppty();


        System.Test.stopTest();

        // Test Result
        List<Property_Due_Diligence_Reports__c> pddrList =
        [
                SELECT Id
                FROM Property_Due_Diligence_Reports__c
        ];


        System.assertEquals(0, pddrList.size());
    }
}