objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <description>Co-applicant's email address As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Email (Co)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_First_Name__c</fullName>
        <description>Co-applicant's first name As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>First Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Last_Name__c</fullName>
        <description>Last name of the co-applicant. As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Last Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Converted_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Converted Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads (Converted Opp)</relationshipLabel>
        <relationshipName>Converted_Opportunity_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating whether the applicatoin has a co-applicant. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <formula>Co_Applicant__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Applicant Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Yodlee_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Yodlee Order Requests</relationshipLabel>
        <relationshipName>Yodlee_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Yodlee Order Requests</relationshipLabel>
        <relationshipName>Yodlee_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Yodlee_Public_Id__c</fullName>
        <label>Yodlee Public Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/YodleeHelper.cls
/**********************************************************
 * @className   : YodleeHelper.cls
 * @testClass   : YodleeHelper_TEST.cls
 * @author      : Omnivo Digital (www.omnivodigital.com)
 * @date        : May 7, 2018
 *
 *
 **********************************************************/ 

public with sharing class YodleeHelper 
{
    public static String yodleeAccessToken {get; set;}

    public static void authenticate()
    {
        yodleeAccessToken = YodleeAPI.authenticate();
    }

    public static Id CreateOrder(Opportunity opp)
    {
        if(yodleeAccessToken == null)
        {
            yodleeAccessToken = YodleeAPI.authenticate();
        }

        YodleeAPI.CreateOrderCallServerRequest request = new YodleeAPI.CreateOrderCallServerRequest();
        request.applicant.first_name = opp.Applicant__r.FirstName;
        request.applicant.last_name = opp.Applicant__r.LastName;
        request.applicant.email = opp.Applicant__r.Email;
        request.product = YodleeAPI.SETTINGS.Product_Code__c; //'1003-o-en' is old value, '1003-uni-o-en' is new value;

        /* 4/2/2019 Sundar Subramaniam - Condition Commented for Data Model Cleanup */
        //if(opp.Is_there_Co_App__c == true)
        {
            YodleeAPI.Co_applicants newCoApplicant = new YodleeAPI.Co_applicants();
            newCoApplicant.first_name = opp.Co_Applicant__r.FirstName;
            newCoApplicant.last_name = opp.Co_Applicant__r.LastName;
            newCoApplicant.email = opp.Co_Applicant__r.Email;

            request.co_applicants.add(newCoApplicant); // add co-applicants
        }

        if (isRequestValid(request)){
            YodleeAPI.CreateOrderResponseWrapper response = YodleeAPI.CreateOrder(request);

            system.debug(response);

            Yodlee_Order_Request__c newYodleeOrderRequest = new Yodlee_Order_Request__c();
            newYodleeOrderRequest.Name = 'Request on ' + Datetime.now();
            newYodleeOrderRequest.Opportunity__c = opp.Id;
            newYodleeOrderRequest.Yodlee_Public_Id__c = response.serverResponse.public_id;
            newYodleeOrderRequest.Error_Message__c = response.errorMessage;
            insert newYodleeOrderRequest;

            return newYodleeOrderRequest.Id;
        }

        return null;
    }

    public static Id CreateOrder(Lead leadRecord)
    {
        if(yodleeAccessToken == null)
        {
            yodleeAccessToken = YodleeAPI.authenticate();
        }

        YodleeAPI.CreateOrderCallServerRequest request = new YodleeAPI.CreateOrderCallServerRequest();
        request.applicant.first_name = leadRecord.FirstName;
        request.applicant.last_name = leadRecord.LastName;
        request.applicant.email = leadRecord.Email;
        request.product = YodleeAPI.SETTINGS.Product_Code__c; //'1003-o-en' is old value, '1003-uni-o-en' is new value;
        
        if(leadRecord.Is_there_Co_App__c)
        {
            YodleeAPI.Co_applicants newCoApplicant = new YodleeAPI.Co_applicants();
            newCoApplicant.first_name = leadRecord.Co_Applicant_First_Name__c;
            newCoApplicant.last_name = leadRecord.Co_Applicant_Last_Name__c;
            newCoApplicant.email = leadRecord.Co_Applicant_Email__c;

            request.co_applicants.add(newCoApplicant);// add co-applicants
        }

        if (isRequestValid(request)){
            YodleeAPI.CreateOrderResponseWrapper response = YodleeAPI.CreateOrder(request);
            system.debug(response);

            Yodlee_Order_Request__c newYodleeOrderRequest = new Yodlee_Order_Request__c();
            newYodleeOrderRequest.Name = 'Request on ' + Datetime.now();
            newYodleeOrderRequest.Lead__c = leadRecord.Id;
            newYodleeOrderRequest.Opportunity__c = leadRecord.Converted_Opportunity__c;
            newYodleeOrderRequest.Yodlee_Public_Id__c = response.serverResponse.public_id;
            newYodleeOrderRequest.Error_Message__c = response.errorMessage;
            insert newYodleeOrderRequest;

            return newYodleeOrderRequest.Id;
        }

        return null;
    }


    /******
    *
    * This method check if a request contains all necesarry informations before submite it.
    *
    ******/
    public static Boolean isRequestValid(YodleeAPI.CreateOrderCallServerRequest request)
    {
        System.debug(' ****YodleeHelper --- isRequestValid(): ');
        System.debug(' ****request: ' + request);
        Boolean isOK = false;
        if (String.isNotBlank(request.applicant.first_name) && String.isNotBlank(request.applicant.last_name)
            && String.isNotBlank(request.applicant.email)){
                isOK = true;
        }

        return isOK;
    }

    public static YodleeAPI.EmailReIssueResponse EmailReIssue(String orderId)
    {
        if(yodleeAccessToken == null)
        {
            yodleeAccessToken = YodleeAPI.authenticate();
        }

        return YodleeAPI.EmailReIssue(orderId);
    }

    public static YodleeAPI.CheckOrderStatusResponse CheckOrderStatus(String orderId)
    {
        if(yodleeAccessToken == null)
        {
            yodleeAccessToken = YodleeAPI.authenticate();
        }

        YodleeAPI.CheckOrderStatusResponse response = YodleeAPI.CheckOrderStatus(orderId, true);
        System.debug('*** YodleeHelper -- CheckOrderStatus:');
        System.debug('***response: ' + response);

        return response;
    }

    public static YodleeAPI.CreateOrderResponseWrapper RetriveOrder(String orderId)
    {
        if(yodleeAccessToken == null)
        {
            yodleeAccessToken = YodleeAPI.authenticate();
        }

        YodleeAPI.CreateOrderResponseWrapper response = YodleeAPI.RetriveOrder(orderId);
        system.debug(response);

        return response;
    }

    public static Blob RetriveReportOrder(String orderId){
        Blob retrivedPdf;

        if(yodleeAccessToken == null)
        {
            yodleeAccessToken = YodleeAPI.authenticate();
        }

        //check order status
        YodleeAPI.CheckOrderStatusResponse orderRespSts = YodleeAPI.CheckOrderStatus(orderId, false);
        System.debug('***orderRespSts: ' + orderRespSts);

        if (orderRespSts != null && orderRespSts.value == '7'){ //The order must be submitted and COMPLETED - 7
            retrivedPdf = YodleeAPI.RetriveReport(orderId);
        }

        return retrivedPdf;
    }
}