objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wiring_Information__c.object
<CustomObject>
    <fields>
        <fullName>CustomerState__c</fullName>
        <label>Customer State</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Company__c</fullName>
        <label>Title Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wire_Zipcode__c</fullName>
        <label>Wire Zipcode</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Wiring Information</label>
    <nameField>
        <label>Wiring Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiring Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Opp_VantagePoint_EXT_Test.cls
@isTest
private class Opp_VantagePoint_EXT_Test 
{	
	@isTest static void test_method_one() 
    {
        // Data Setup
		Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                                  AccountID = acc.Id);
        insert con2;

        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20), Is_there_Co_App__c = true, Applicant__c = con.Id,
                                    Property_State__c = 'Vantage Point',Co_Applicant__c = con2.Id);
        insert oppty;

        Wiring_Information__c winfo = new Wiring_Information__c(Name='Test winfo',
                                                                Wire_Zipcode__c='92109',
                                                                CustomerState__c='Vantage Point',
                                                                Title_Company__c='Vantage Point');
        insert winfo;



        // Run Code
        System.Test.startTest();

            ApexPages.StandardController sc = new ApexPages.StandardController(oppty);
            Opp_VantagePoint_EXT ctrl = new Opp_VantagePoint_EXT(sc);
            ctrl.createVantagePointOrder();
            ctrl.BackToOppty();

        System.Test.stopTest();

        /*// Test Results
        List<Property_Due_Diligence_Reports__c> pddrList = 
            [
                SELECT Id 
                FROM Property_Due_Diligence_Reports__c
            ];
            
        System.assert(pddrList.size() == 0);
	    */
    }
}