objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Additional_Applicant_Income__c</fullName>
        <label>Additional Income From Other Applicants</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_App1__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of applicant income including base, bonus', commission, div/interest, overtime, social security, rental, and other. See values on Application object for reference.</inlineHelpText>
        <label>Applicant Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Co_App1__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of co-applicant income including base, bonus', commission, div/interest, overtime, social security, rental, and other. See values on Application object for reference.</inlineHelpText>
        <label>Co-Applicant Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <inlineHelpText>Manually entered percentage for OAV discount</inlineHelpText>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Post_Close_BE_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hard coded</description>
        <inlineHelpText>Post-Close Liabilities Total / Income Total</inlineHelpText>
        <label>Post-Close BE Ratio2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Post_Close_FE_Ratio2__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hard coded</description>
        <inlineHelpText>Post-Close Monthly Total Housing / Income Total</inlineHelpText>
        <label>Post-Close FE Ratio2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Post_Close_LTV2__c</fullName>
        <description>Hardcoded
This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <inlineHelpText>This is the total proposed mortgage debt on the property as a percentage of the Final OAV. It is expressed as the Post-Close Mortgage Debt divided by the Final OAV. Final OAV can change as more appraisals and other information is gathered.</inlineHelpText>
        <label>Post-Close LTV2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Post_Close_Mortgage_Debt__c</fullName>
        <description>Hard coded</description>
        <inlineHelpText>HomeOwner: Sum of the proposed (target) balance of all liens on the subject property
HomeBuyer: Loan Amount</inlineHelpText>
        <label>Post-Close Mortgage Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pre_Close_BE_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Pre-Close Liabilities Total / Income Total</inlineHelpText>
        <label>Pre-Close BE Ratio2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pre_Close_LTV2__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hard coded</description>
        <inlineHelpText>This is the total current mortgage debt on the property as a percentage of the Final OAV. It is expressed as the Pre-Close Mortgage Debt divided by the Final OAV. Final OAV can change as more appraisals and other information is gathered.</inlineHelpText>
        <label>Pre-Close LTV2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Present_Total_Mortgage_Debt__c</fullName>
        <description>Hardcoded - SUM Tradeline.LASERCA__Account_Balance__c IF Tradeline.Credit_Loan_Type_pick__c IN (Mortgage, Other Lien)</description>
        <inlineHelpText>From the tradeline objects on the credit report, sum up the account balance for mortgage and Other Lien tradelines</inlineHelpText>
        <label>Pre-Close Total Mortgage Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Success_Factor_Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success Factor Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary_Appraised_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>DLRS</description>
        <inlineHelpText>The average of Final_Value from all Appraisal Objects associated with the Opportunity.</inlineHelpText>
        <label>Summary Appraised Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>Properties for which customers and indirect channel partners (loan officers, real estate agents, etc) have inquired the investment approval status.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <inlineHelpText>Pricing Ratio based on Unison Program</inlineHelpText>
        <label>Inquiry Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single-family detached</fullName>
    </customValue>
    <customValue>
        <fullName>Condominium</fullName>
    </customValue>
    <customValue>
        <fullName>2-4 Family</fullName>
    </customValue>
    <customValue>
        <fullName>PUD</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Detached</fullName>
        <isActive>false</isActive>
        <label>Detached</label>
    </customValue>
    <masterLabel>Property Type</masterLabel>
</GlobalValueSet>

classes/OpportunityServiceTest.cls
/************************************************************************************
 Apex Class Name     : OpportunityServiceTest
 Version             : 1.0
 Created Date        : 3rd March 2019
 Function            : Test Class for OpportunityService class
 Author              : Neeraja Cherukuri
 
 Modification Log    :To Handle Fomulas Calculations ,We are using the Service class.
* Developer                   Date                    Description
*
*
----------------------------------------------------------------------------------
* Neeraja Cherukuri            02/20/2019                Original Version
*************************************************************************************
*/
@isTest
public class OpportunityServiceTest {
    private static testMethod void validateWithouthOAV(){
        Account objAcc = new Account(Name = 'New Account');
        insert objAcc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = objAcc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = objAcc.Id);
        insert con2;

        /* 4/2/2019 Sundar Subramaniam - Is_there_Co_App__c removed from query for Data Model Cleanup */
        Opportunity objOpp = new Opportunity(Name = 'New Oppty', AccountId = objAcc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Property_Type__c = '2-4 Family',
                Co_Applicant__c = con2.Id,Encompass_Loan_Number__c = '10',Pricing_Ratio__c = 4,Final_OAV_Calculation__c=100,Lien_First_Lender_Balance__c = 100, Summary_Appraised_Value__c = 10, Purchase_Price__c = 10);
        Insert objOpp;

        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = objOpp.Id;
        sf1.Success_Factor__c  = 'LTV';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        Insert sf1;

        try{
            objOpp.Purchase_Price__c = 5000000;
            objOpp.Summary_Appraised_Value__c= 6000000;
            objOpp.IA_OAV_Override__c = 456456;
            objOpp.OAV_Discount_Pct__c = 30;
            objOpp.Purchase_Price__c = 200;
            objOpp.StageName = 'Investment Due Diligence';
            objOpp.Success_Factor_Cleared__c = False;
            update objOpp;
        }catch(Exception e){}
    }

    private static testMethod void validateForHomeOwner(){
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty1 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,

                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty1.Post_Close_Mortgage_Debt__c= 10000;
        objOpty1.Present_Total_Mortgage_Debt__c = 20000;
        objOpty1.Final_OAV_Calculation__c = 500000;
        objOpty1.Pricing_Ratio__c = 4;
        objOpty1.Post_Close_BE_Ratio__c = 90;
        objOpty1.Pre_Close_BE_Ratio__c = 80;
        objOpty1.Post_Close_LTV2__c = 80;
        objOpty1.Pre_Close_LTV2__c = 80;
        objOpty1.Income_App1__c  = 10000;
        insert objOpty1;
    }

    private static testMethod void validateForHomeOwner_Qualifies_IsNoo1(){
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeOwnerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty1 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,

                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty1.Post_Close_Mortgage_Debt__c= 1576695;
        objOpty1.Present_Total_Mortgage_Debt__c = 1576695;
        objOpty1.Additional_Applicant_Income__c = 0;
        objOpty1.Income_App1__c = 4854.83;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Final_OAV_Calculation__c = 3500000;
        objOpty1.IA_OAV_Override__c = 3500000;
        objOpty1.Pricing_Ratio__c = 6;
        objOpty1.Post_Close_BE_Ratio__c = 45.05;
        objOpty1.Pre_Close_BE_Ratio__c = 45.05;
        objOpty1.Post_Close_FE_Ratio2__c = 45.05;
        objOpty1.Pre_Close_FE_Ratio2__c = 45.05;
        objOpty1.Post_Close_LTV2__c = 45.05;
        objOpty1.Pre_Close_LTV2__c = 45.05;
        objOpty1.Income_App1__c  = 10000;
        objOpty1.Qualifies_for_New_HomeOwner_Pricing__c = true;
        objOpty1.Is_NOO__c = false;
        insert objOpty1;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = 'Condominium';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Property_Number_of_Units__c = 2;
        newprop.Opportunity__c=objOpty1.Id;
        insert newprop;

        objOpty1.Is_NOO__c = true;
        update objOpty1;

        // RecordType = HomeOwner && Qualifies_for_New_HomeOwner_Pricing__c == true && Is_NOO__c == false
        // then use .95 for calculation
        Opportunity updatedOppty = [SELECT Id, Post_Close_LTV2__c, Pricing_Ratio__c, Final_OAV_Calculation__c, Estimated_Funding_Amount__c ,OIP_Maximum__c FROM Opportunity WHERE Id =: objOpty1.Id LIMIT 1];
        system.assert(updatedOppty.OIP_Maximum__c == 408333.00);
    }

    private static testMethod void validateForHomeOwner_Qualifies_IsNoo2(){
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeOwnerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty1 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,

                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty1.Post_Close_Mortgage_Debt__c= 1576695;
        objOpty1.Present_Total_Mortgage_Debt__c = 1576695;
        objOpty1.Additional_Applicant_Income__c = 0;
        objOpty1.Income_App1__c = 4854.83;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Final_OAV_Calculation__c = 3200000;
        objOpty1.IA_OAV_Override__c = 3200000;
        objOpty1.Pricing_Ratio__c = 6;
        objOpty1.Post_Close_BE_Ratio__c = 45.05;
        objOpty1.Pre_Close_BE_Ratio__c = 45.05;
        objOpty1.Post_Close_FE_Ratio2__c = 45.05;
        objOpty1.Pre_Close_FE_Ratio2__c = 45.05;
        objOpty1.Post_Close_LTV2__c = 45.05;
        objOpty1.Pre_Close_LTV2__c = 45.05;
        objOpty1.Income_App1__c  = 10000;
        objOpty1.Is_NOO__c = true;
        objOpty1.Qualifies_for_New_HomeOwner_Pricing__c = false;
        insert objOpty1;

        // RecordType = HomeOwner && Qualifies_for_New_HomeOwner_Pricing__c == false && Is_NOO__c == true
        // then use .80 for calculation
        Opportunity updatedOppty = [SELECT Id, Post_Close_LTV2__c, Pricing_Ratio__c, Final_OAV_Calculation__c, Estimated_Funding_Amount__c ,OIP_Maximum__c FROM Opportunity WHERE Id =: objOpty1.Id LIMIT 1];
        system.assert(updatedOppty.OIP_Maximum__c == 373333.00);
    }

    private static testMethod void validateForHomeOwner_Qualifies_IsNoo3(){
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeOwnerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty1 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,

                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty1.Post_Close_Mortgage_Debt__c= 1576695;
        objOpty1.Present_Total_Mortgage_Debt__c = 1576695;
        objOpty1.Additional_Applicant_Income__c = 0;
        objOpty1.Income_App1__c = 4854.83;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Final_OAV_Calculation__c = 4500000;
        objOpty1.IA_OAV_Override__c = 4500000;
        objOpty1.Pricing_Ratio__c = 6;
        objOpty1.Post_Close_BE_Ratio__c = 45.05;
        objOpty1.Pre_Close_BE_Ratio__c = 45.05;
        objOpty1.Post_Close_FE_Ratio2__c = 45.05;
        objOpty1.Pre_Close_FE_Ratio2__c = 45.05;
        objOpty1.Post_Close_LTV2__c = 45.05;
        objOpty1.Pre_Close_LTV2__c = 45.05;
        objOpty1.Income_App1__c  = 10000;
        objOpty1.Qualifies_for_New_HomeOwner_Pricing__c = true;
        objOpty1.Is_NOO__c = true;
        insert objOpty1;

        // RecordType = HomeOwner && Qualifies_for_New_HomeOwner_Pricing__c == true && Is_NOO__c == true
        // then use 87.5 for calculation
        Opportunity updatedOppty = [SELECT Id, Post_Close_LTV2__c, Pricing_Ratio__c, Final_OAV_Calculation__c, Estimated_Funding_Amount__c ,OIP_Maximum__c FROM Opportunity WHERE Id =: objOpty1.Id LIMIT 1];
        // 500k cap if oip max > $500,000.00
        system.assert(updatedOppty.OIP_Maximum__c == 500000.00);
    }


    private static testMethod void validateForHomeBuyer()
    {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 3500000;
        objOpty2.Pricing_Ratio__c = 6;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 45.05;
        objOpty2.Pre_Close_LTV2__c = 45.05;
        objOpty2.Income_App1__c  = 10000;
        insert objOpty2;
    }

    private static testMethod void validateForHomeBuyer_Qualifies_IsNoo1()
    {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Record_Type_Name__c = 'HomeBuyer';
        objOpty2.Is_NOO__c = true;
        objOpty2.Sum_of_Debt_to_be_Paid_Off__c = 0;
        objOpty2.Summary_Appraised_Value__c = 0;
        objOpty2.Purchase_Price__c = 10;
        objOpty2.OAV_Discount_Pct__c = 20;
        objOpty2.Post_Close_LTV_Redux_Sum__c = null;
        objOpty2.Post_Close_Mortgage_Debt__c= 1576695;
        objOpty2.Present_Total_Mortgage_Debt__c = 1576695;
        objOpty2.Additional_Applicant_Income__c = 0;
        objOpty2.Income_App1__c = 4854.83;
        objOpty2.Income_Co_App1__c = 3052.50;
        objOpty2.Income_Co_App1__c = 3052.50;
        objOpty2.Final_OAV_Calculation__c = 3130000;
        objOpty2.IA_OAV_Override__c = 3130000;
        objOpty2.Pricing_Ratio__c = 6;
        objOpty2.Post_Close_BE_Ratio__c = 45.05;
        objOpty2.Pre_Close_BE_Ratio__c = 45.05;
        objOpty2.Post_Close_FE_Ratio2__c = 45.05;
        objOpty2.Pre_Close_FE_Ratio2__c = 45.05;
        objOpty2.Post_Close_LTV2__c = 45.05;
        objOpty2.Pre_Close_LTV2__c = 45.05;
        insert objOpty2;

        // RecordType = HomeBuyer && Is_NOO__c == false
        // then use .95 for calculation
        Opportunity updatedOppty = [SELECT Id, Post_Close_LTV2__c, Pricing_Ratio__c, Final_OAV_Calculation__c, Estimated_Funding_Amount__c ,OIP_Maximum__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        system.assert(updatedOppty.OIP_Maximum__c == 365167.00);
    }

    private static testMethod void validateForHomeBuyer_Qualifies_IsNoo2()
    {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Record_Type_Name__c = 'HomeBuyer';
        objOpty2.Post_Close_Mortgage_Debt__c= 1576695;
        objOpty2.Present_Total_Mortgage_Debt__c = 1576695;
        objOpty2.Additional_Applicant_Income__c = 0;
        objOpty2.Income_App1__c = 4854.83;
        objOpty2.Income_Co_App1__c = 3052.50;
        objOpty2.Income_Co_App1__c = 3052.50;
        objOpty2.Final_OAV_Calculation__c = 3160000;
        objOpty2.IA_OAV_Override__c = 3160000;
        objOpty2.Pricing_Ratio__c = 6;
        objOpty2.Post_Close_BE_Ratio__c = 45.05;
        objOpty2.Pre_Close_BE_Ratio__c = 45.05;
        objOpty2.Post_Close_FE_Ratio2__c = 45.05;
        objOpty2.Pre_Close_FE_Ratio2__c = 45.05;
        objOpty2.Post_Close_LTV2__c = 45.05;
        objOpty2.Pre_Close_LTV2__c = 45.05;
        objOpty2.Is_NOO__c = true;
        objOpty2.Sum_of_Debt_to_be_Paid_Off__c = 0;
        objOpty2.Summary_Appraised_Value__c = 10;
        objOpty2.Purchase_Price__c = 0;
        objOpty2.OAV_Discount_Pct__c = 20;
        insert objOpty2;

        // RecordType = HomeBuyer && Is_NOO__c == true
        // then use 87.5 for calculation
        Opportunity updatedOppty = [SELECT Id, Post_Close_LTV2__c, Pricing_Ratio__c, Final_OAV_Calculation__c, Estimated_Funding_Amount__c ,OIP_Maximum__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        system.assert(updatedOppty.OIP_Maximum__c == 368667.00);
    }

    private static testMethod void validateForHomeBuyer_Number_Of_Units_Null()
    {
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeOwnerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty1 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,

                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty1.Post_Close_Mortgage_Debt__c= 1576695;
        objOpty1.Present_Total_Mortgage_Debt__c = 1576695;
        objOpty1.Additional_Applicant_Income__c = 0;
        objOpty1.Income_App1__c = 4854.83;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Income_Co_App1__c = 3052.50;
        objOpty1.Final_OAV_Calculation__c = 3500000;
        objOpty1.IA_OAV_Override__c = 3500000;
        objOpty1.Pricing_Ratio__c = 6;
        objOpty1.Post_Close_BE_Ratio__c = 45.05;
        objOpty1.Pre_Close_BE_Ratio__c = 45.05;
        objOpty1.Post_Close_FE_Ratio2__c = 45.05;
        objOpty1.Pre_Close_FE_Ratio2__c = 45.05;
        objOpty1.Post_Close_LTV2__c = 45.05;
        objOpty1.Pre_Close_LTV2__c = 45.05;
        objOpty1.Income_App1__c  = 10000;
        objOpty1.Qualifies_for_New_HomeOwner_Pricing__c = false;
        objOpty1.Is_NOO__c = true;
        insert objOpty1;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = 'Condominium';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Property_Number_of_Units__c = null;
        newprop.Opportunity__c=objOpty1.Id;
        insert newprop;

        objOpty1.Is_NOO__c = false;
        update objOpty1;

        // RecordType = HomeOwner && Qualifies_for_New_HomeOwner_Pricing__c == true && Is_NOO__c == false
        // then use .95 for calculation
        Opportunity updatedOppty = [SELECT Id, Post_Close_LTV2__c, Pricing_Ratio__c, Final_OAV_Calculation__c, Estimated_Funding_Amount__c ,OIP_Maximum__c FROM Opportunity WHERE Id =: objOpty1.Id LIMIT 1];
        system.assertEquals(updatedOppty.OIP_Maximum__c, 408333.00);
    }

    private static testMethod void validateRoundOIP_beforeInsert()
    {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 500000;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 80;
        objOpty2.Pre_Close_LTV2__c = 80;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 20.66;
        insert objOpty2;
        system.debug(' afterInsert ' + objOpty2.Estimated_Funding_Amount__c);

        Opportunity roundedOIP_Opportunity = [SELECT Id, Estimated_Funding_Amount__c FROM Opportunity WHERE Id =: objOpty2.Id];
        system.assert(roundedOIP_Opportunity.Estimated_Funding_Amount__c == 21);
    }

    private static testMethod void validateRoundOIP_beforeUpdate()
    {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 500000;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 80;
        objOpty2.Pre_Close_LTV2__c = 80;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 20.66;
        insert objOpty2;

        Opportunity roundedOIP_Opportunity = [SELECT Id, Estimated_Funding_Amount__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        roundedOIP_Opportunity.Estimated_Funding_Amount__c = 55.66;
        update roundedOIP_Opportunity;

        Opportunity roundedOIP_OpportunityAfterUpdate = [SELECT Id, Estimated_Funding_Amount__c FROM Opportunity WHERE Id =: roundedOIP_Opportunity.Id LIMIT 1];
        system.assert(roundedOIP_OpportunityAfterUpdate.Estimated_Funding_Amount__c == 56);
    }

    private static testMethod void validateProgramFloor_1() {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 500000;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 80;
        objOpty2.Pre_Close_LTV2__c = 80;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 20.66;
        objOpty2.Opportunity_Created_From_Lead__c = true;
        insert objOpty2;

        Test.startTest();
        Opportunity updateProgramFloor = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        updateProgramFloor.Is_NOO__c = true;
        update updateProgramFloor;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: updateProgramFloor.Id LIMIT 1];
        system.assert(opportunityAfterUpdate.Program_Floor__c == '5 Year');
    }

    private static testMethod void validateProgramFloor_HB() {
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeBuyerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeBuyerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 500000;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 80;
        objOpty2.Pre_Close_LTV2__c = 80;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 20.66;
        objOpty2.Opportunity_Created_From_Lead__c = true;
        objOpty2.Is_NOO__c = true;
        insert objOpty2;

        Test.startTest();
        Opportunity updateProgramFloor = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        updateProgramFloor.Is_NOO__c = false;
        update updateProgramFloor;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: updateProgramFloor.Id LIMIT 1];
        system.debug('programFloor ' + opportunityAfterUpdate.Program_Floor__c);
        system.assert(opportunityAfterUpdate.Program_Floor__c == '3 Year');
    }

    private static testMethod void validateProgramFloor_HO_1() {
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 500000;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 80;
        objOpty2.Pre_Close_LTV2__c = 80;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 20.66;
        objOpty2.Opportunity_Created_From_Lead__c = true;
        insert objOpty2;

        Test.startTest();
        Opportunity updateProgramFloor = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        updateProgramFloor.Qualifies_for_New_HomeOwner_Pricing__c = true;
        updateProgramFloor.Is_NOO__c = false;
        update updateProgramFloor;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: updateProgramFloor.Id LIMIT 1];
        system.assert(opportunityAfterUpdate.Program_Floor__c == '3 Year');
    }

    private static testMethod void validateProgramFloor_HO_2() {
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Post_Close_Mortgage_Debt__c= 10000;
        objOpty2.Present_Total_Mortgage_Debt__c = 20000;
        objOpty2.Final_OAV_Calculation__c = 500000;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Post_Close_BE_Ratio__c = 70;
        objOpty2.Pre_Close_BE_Ratio__c = 60;
        objOpty2.Post_Close_LTV2__c = 80;
        objOpty2.Pre_Close_LTV2__c = 80;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 20.66;
        objOpty2.Opportunity_Created_From_Lead__c = true;
        insert objOpty2;

        Test.startTest();
        Opportunity updateProgramFloor = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        updateProgramFloor.Qualifies_for_New_HomeOwner_Pricing__c = false;
        updateProgramFloor.Is_NOO__c = false;
        update updateProgramFloor;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: updateProgramFloor.Id LIMIT 1];
        system.assert(opportunityAfterUpdate.Program_Floor__c == '3 Year');
    }

    private static testMethod void validateProgramFloor_HO_3() {
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Final_OAV_Calculation__c = 4000.0;
        objOpty2.IA_OAV_Override__c = 4000.0;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 500000;
        objOpty2.Opportunity_Created_From_Lead__c = true;
        objOpty2.Qualifies_for_New_HomeOwner_Pricing__c = true;
        insert objOpty2;

        Test.startTest();
        Opportunity updateProgramFloor = [SELECT Id, Program_Floor__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        updateProgramFloor.Qualifies_for_New_HomeOwner_Pricing__c = false;
        update updateProgramFloor;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, Program_Floor__c, Equity_less_than_origination__c, OIP_Percentage__c, Final_OAV_Calculation__c, Post_Close_LTV2_Converted__c FROM Opportunity WHERE Id =: updateProgramFloor.Id LIMIT 1];
        system.assert(opportunityAfterUpdate.Program_Floor__c == '5 Year');
    }

    private static testMethod void validateIADeclineReason() {
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeOwnerRecId);
        Account objAcc1 = new Account (Name='Test Account');
        insert objAcc1;
        Opportunity objOpty2 = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc1.Id,RecordTypeId=optyHomeOwnerRecId,
                StageName = 'Property in Contract', CloseDate = System.today());

        objOpty2.Final_OAV_Calculation__c = 4000.0;
        objOpty2.IA_OAV_Override__c = 4000.0;
        objOpty2.Pricing_Ratio__c = 4;
        objOpty2.Income_App1__c  = 10000;
        objOpty2.Estimated_Funding_Amount__c = 500000;
        objOpty2.Opportunity_Created_From_Lead__c = true;
        objOpty2.Qualifies_for_New_HomeOwner_Pricing__c = true;
        objOpty2.IA_Decline_Reason__c = 'C5 rating';

        Test.startTest();
        insert objOpty2;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, PS_Decline_Reasons__c, AA_Letter_Decline_Reasons__c FROM Opportunity WHERE Id =: objOpty2.Id LIMIT 1];
        system.assert(opportunityAfterUpdate.PS_Decline_Reasons__c == '\u2022 Poor Condition');
        system.assert(opportunityAfterUpdate.AA_Letter_Decline_Reasons__c == '\u2022 Type, condition, or typicality of property unacceptable');
    }
}