objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>House_Canary_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>ZZZHouse Canary Order Id</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>House_Canary_Order_Validation_Results__c</fullName>
        <label>ZZZHouse Canary Order Validation Results</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>House_Canary_Status__c</fullName>
        <label>ZZZHouse Canary Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>ClientReview</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Webhook_Log__c.object
<CustomObject>
    <label>Webhook Log</label>
    <nameField>
        <displayFormat>WH-Log-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webhook Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HCRestService_TEST.cls
/**********************************************************
 * Class        : HCRestService_TEST.cls
 * Created Date : February 20, 2018
 * Modified by  : -
 * Modified Date: -
 * Objective    : This class provide test methods for HCRestService.cls
 *
 *
 **********************************************************/ 

@isTest 
private class HCRestService_TEST {

    @isTest
    private static void testName() {
        
		DelightedHelper.skipCall = true;
        
        Account acc = new Account(Name = 'New Account');
        insert acc; 
        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;
        
        Opportunity oppty = new Opportunity(Name = 'test oppty', AccountId = acc.Id, StageName = 'Submit to Ops', CloseDate = Date.today());
        insert oppty;

        Property_Due_Diligence_Reports__c pddrRep = new Property_Due_Diligence_Reports__c();
        pddrRep.House_Canary_Order_Id__c = '27';
        pddrRep.House_Canary_Status__c = 'ClientReview';
        pddrRep.Opportunity__c = oppty.ID;
        insert pddrRep;

        OrdersRestHelper.HC_Message hcmessage = new OrdersRestHelper.HC_Message();
        hcmessage.order_id = '27';
        hcmessage.message_id = '13840';
        hcmessage.new_status = 'ClientReview';
        hcmessage.customer_item_id = pddrRep.Id;

        System.Test.startTest();

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/HouseCanary/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(hcmessage));
        RestContext.request = req;
        RestContext.response = res;

        HCRestService.OrderValidation();

        System.Test.stopTest();

        List<Property_Due_Diligence_Reports__c> pddrList = [Select Id, House_Canary_Order_Validation_Results__c FROM Property_Due_Diligence_Reports__c
                                                                                    WHERE Id= :pddrRep.Id];
        System.assert(pddrList.get(0).House_Canary_Order_Validation_Results__c != null);

        List<Webhook_Log__c> logs = [Select Id from Webhook_Log__c];
        System.assert(logs.size() > 0);
                            
    }
}