objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Contact_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <inlineHelpText>Assign a value if this contact can be an Escrow for Spruce or Vantage Point.</inlineHelpText>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spruce</fullName>
                </value>
                <value>
                    <fullName>Vantage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Code__c</fullName>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Aged</fullName>
                    <isActive>false</isActive>
                    <label>Aged</label>
                </value>
                <value>
                    <fullName>Decline - Credit/Foreclosure Issues</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Credit/Foreclosure Issues</label>
                </value>
                <value>
                    <fullName>Decline - Insufficient Down Payment/Income</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Insufficient Down Payment/Income</label>
                </value>
                <value>
                    <fullName>Decline - Not in Geography</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Not in Geography</label>
                </value>
                <value>
                    <fullName>Decline - Property</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Property</label>
                </value>
                <value>
                    <fullName>Decline - Purchase Offer not Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Purchase Offer not Accepted</label>
                </value>
                <value>
                    <fullName>Decline - Rental or Second Home</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Rental or Second Home</label>
                </value>
                <value>
                    <fullName>Decline - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Unknown</label>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                    <isActive>false</isActive>
                    <label>Unresponsive</label>
                </value>
                <value>
                    <fullName>Withdraw - Already has Lender</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Already has Lender</label>
                </value>
                <value>
                    <fullName>Withdraw - Not Buying Home</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Not Buying Home</label>
                </value>
                <value>
                    <fullName>Withdraw - Prefers Another Product</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Prefers Another Product</label>
                </value>
                <value>
                    <fullName>Withdraw - Too Complicated</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Too Complicated</label>
                </value>
                <value>
                    <fullName>Withdraw - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>House_Canary_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>ZZZHouse Canary Order Id</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>ZZZOrder Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>inspectAndEvaluate</fullName>
                </value>
                <value>
                    <fullName>devFakeInspectAndFakeEvaluate</fullName>
                </value>
                <value>
                    <fullName>devFakeInspectAndEvaluate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PDDR_Cancel_Order_Ctrl_TEST.cls
/**********************************************************
 * @className   : PDDR_Cancel_Order_Ctrl_TEST.cls
 * @date        : April 10, 2018
 * @description : This class provides test methods for PDDR_Cancel_Order_Ctrl.cls
 * @param       :
 * @return      :
 *
 *
 **********************************************************/ 

@isTest 
private class PDDR_Cancel_Order_Ctrl_TEST {

    @isTest
    private static void testName() {
        /*Account acc = new Account(Name = 'New Account');
        insert acc; 
        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        String homBuyerRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        Opportunity oppty = new Opportunity();
        oppty.Name = 'Oppty Name';
        oppty.AccountId = acc.Id;
        oppty.RecordTypeId = homBuyerRTId;
        oppty.StageName = 'Closed Lost';
        oppty.CloseDate = Date.today().addDays(20);
        oppty.Loss_Type__c = 'Withdrawn';
        oppty.Loss_Reason_Code__c = 'Customer information is fake or cannot be used to contact the customer';
        oppty.Property_Street_Number_and_Name__c = 'street 1';
        oppty.Property_City__c = 'San Francisco';
        oppty.Property_State__c = 'CA';
        oppty.Property_Zip_Code__c = '12354';
        *//* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup *//*
        //oppty.Property_Type__c = 'Single-family detached';
        insert oppty;*/

        Account acc = new Account(Name = 'New Account');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = acc.Id);
        insert con2;

        /* 4/2/2019 Sundar Subramaniam - Is_there_Co_App__c removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Property_Type__c = '2-4 Family',
                Co_Applicant__c = con2.Id,Encompass_Loan_Number__c = '10',Final_OAV_Calculation__c=100,Lien_First_Lender_Balance__c = 100);
        insert oppty;

        Property_Due_Diligence_Reports__c pddr = new Property_Due_Diligence_Reports__c();
        pddr.Opportunity__c = oppty.Id;
        pddr.House_Canary_Order_Id__c = '255';
        pddr.Order_Type__c = 'devFakeInspectAndEvaluate';
        pddr.Name = 'Property Test1';
        insert pddr;

        System.Test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(pddr);
            PDDR_Cancel_Order_Ctrl ctrl = new PDDR_Cancel_Order_Ctrl(sc);
            ctrl.CancelOrder();
            ctrl.isCancelled = true;
            ctrl.CancelOrder();
        System.Test.stopTest();
    }
}