objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mercury_Phone__c</fullName>
        <formula>RIGHT( Phone  , 10)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mercury Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MercuryHelperTest.cls
/**
 * Created by Ivan Garcia on 5/22/2019.
 */

@IsTest public with sharing class MercuryHelperTest {
    @testSetup static void setup(){
        Account acc = new Account(Name = 'New Account');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',Phone = '1234567891',
                AccountID = acc.Id);
        insert con2;

        /* 4/2/2019 Sundar Subramaniam - Is_there_Co_App__c removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Property_Type__c = '2-4 Family',
                Co_Applicant__c = con2.Id,Encompass_Loan_Number__c = '10',Final_OAV_Calculation__c=100,Lien_First_Lender_Balance__c = 100,Property_Street_Number_and_Name__c='1256 Fisher St',Property_City__c='SanFrancisco',Property_State__c='CA',Property_Zip_Code__c='95687',Property_County__c='San SanFrancisco');
        insert oppty;
    }

    @isTest private static void test0(){
        Test.setMock(HttpCalloutMock.class, new SpruceCalloutMock());
        Opportunity tmpOpp = [SELECT id,Property_Type__c,Encompass_Loan_Number__c,Applicant__r.Name,Applicant__r.Mercury_Phone__c,Applicant__r.Email,Co_Applicant__r.Name,Final_OAV_Calculation__c,Lien_First_Lender_Balance__c, Owner.Name,Property_Street_Number_and_Name__c,Property_State__c,Property_County__c,Property_Zip_Code__c FROM Opportunity LIMIT 1];

        Test.startTest();
        try{
            MercuryHelper.GetAMCCompanies();
        }catch(Exception e){}

        try{
            MercuryHelper.GetTypesOfAppraisal();
        }catch(Exception e){}

        try{
            String xml = '<root xmlns="http://alamode.com/"><to>Tove</to><bResult>true</bResult><TrackingID>Reminder</TrackingID><body><bResult>true</bResult><TrackingID>Reminder</TrackingID></body></root>';
            MercuryAPICustom.PlaceAppraisalOrderEx(xml);
        }catch(Exception e){}
        try{
            MercuryAPICustom.GetTypesOfAppraisal();
        }catch(Exception e){}



        try{
            MercuryHelper.GetCurrentStatus('132456789');
        }catch(Exception e){}

        try{
            MercuryHelper.GenerateXMLPost(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}

        tmpOpp.Property_Type__c = 'Condominium';
        update tmpOpp;
        try{
            MercuryHelper.GenerateXMLPost(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}

        tmpOpp.Property_Type__c = 'PUD';
        update tmpOpp;
        try{
            MercuryHelper.GenerateXMLPost(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}

        tmpOpp.Property_Type__c = 'Other';
        update tmpOpp;
        try{
            MercuryHelper.GenerateXMLPost(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}

        tmpOpp.Property_Type__c = 'Single-family detached';
        update tmpOpp;
        try{
            MercuryHelper.GenerateXMLPost(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}

        tmpOpp.Property_Type__c = 'Townhouse';
        update tmpOpp;
        try{
            MercuryHelper.GenerateXMLPost(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}


        Test.stopTest();
    }

    @isTest static void GenerateOrderAppraisalTest(){
        Test.setMock(HttpCalloutMock.class, new SpruceCalloutMock());
        Opportunity tmpOpp = [SELECT id,Property_Type__c,Encompass_Loan_Number__c,Property_City__c,Property_State__c,Property_County__c,Property_Zip_Code__c,Applicant__r.Name,Co_Applicant__r.Name,Final_OAV_Calculation__c,Lien_First_Lender_Balance__c, Owner.Name,Property_Street_Number_and_Name__c FROM Opportunity LIMIT 1];

        Test.startTest();
        try{
        MercuryHelper.GenerateOrderAppraisal(tmpOpp,'test product', System.Today(),'TestAmc');
        }catch(Exception e){}
        Test.stopTest();


    }
}