objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opp_Lookup_Helper__c</fullName>
        <description>Opportunity Contact Lookup helper to help with multiple contacts conversion process mapping</description>
        <label>Opp_Lookup_Helper</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_History__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <label>Maximum Authorized DTI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <label>Maximum Authorized LTV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Histories</relationshipLabel>
        <relationshipName>Deal_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Deal History</label>
    <nameField>
        <label>Deal History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been ordered by Origination Ops</description>
        <label>Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been received</description>
        <label>Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DMA_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in DocGen to include the Deferred Maintenance Addendum if &gt; 0</description>
        <inlineHelpText>Total count of all DMA records</inlineHelpText>
        <label>DMA Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been ordered by Origination Ops</description>
        <label>Home Inspection Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been received</description>
        <label>Home Inspection Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Investment_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Investment Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Authorized BE DTI</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <inlineHelpText>Manual entry for IA. Influences MAD Pct.</inlineHelpText>
        <label>Max Authorized LTV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <inlineHelpText>Manually entered percentage for OAV discount</inlineHelpText>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Program_Knowledge_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</description>
        <inlineHelpText>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</inlineHelpText>
        <label>Program Knowledge Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Report_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Report_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recorded_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recorded Information</label>
        <referenceTo>Recorded_Information__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary_Appraised_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>DLRS</description>
        <inlineHelpText>The average of Final_Value from all Appraisal Objects associated with the Opportunity.</inlineHelpText>
        <label>Summary Appraised Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recorded_Information__c.object
<CustomObject>
    <fields>
        <fullName>Applicant1_Name__c</fullName>
        <label>ZZZ Applicant 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZZZ Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZZZ Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Informations (Co-Applicant)</relationshipLabel>
        <relationshipName>Recorded_Informations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity2</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations (Opportunity2)</relationshipLabel>
        <relationshipName>Recorded_Informations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recorded Information</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Recorded Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recorded Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityChatterUpdatesTest.cls
/**
 * Created by Eliot Rojas on 4/30/2019.
 */

@IsTest
private class OpportunityChatterUpdatesTest {
    @testSetup static void setup() {
        Account newAcc = new Account (Name='Test Account');
        insert newAcc;
        Id homeOwnerRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();

        Contact con = new Contact(FirstName = 'FirstName', Opp_Lookup_Helper__c = 'test', LastName = 'LastName',  Phone = '4123156', Email = 'fisrtName.lastName@test.com',
                AccountID = newAcc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Phone = '4123156', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = newAcc.Id);
        insert con2;
/*
        Opportunity newOppty = new Opportunity();
        newOppty.Name = 'Test Opportunity';
        newOppty.AccountId = newAcc.Id;
        newOppty.Applicant__c = con.Id;
        newOppty.Co_Applicant__c = con2.Id;
        newOppty.Applicant__c = con.Id;
        newOppty.StageName = 'Submit to Ops';
        newOppty.CloseDate = System.today();
        newOppty.UnisonProcessor__c = UserInfo.getUserId();
        newOppty.Investment_Analyst2__c = UserInfo.getUserId();
        newOppty.Process_Program_Knowledge_Review__c = false;
        newOppty.Appraisal_Received__c = false;
        newOppty.Appraisal_Ordered__c = false;
        newOppty.Second_Appraisal_Ordered__c = false;
        newOppty.Second_Appraisal_Received__c = false;
        newOppty.Home_Inspection_Ordered__c = false;
        newOppty.Home_Inspection_Received__c = false;
        newOppty.Property_Report_Ordered__c = false;
        newOppty.Property_Report_Received__c = false;
        newOppty.IA_OAV_Override__c = 10.0;
        newOppty.Estimated_Funding_Amount__c = 11.0;
        newOppty.Pricing_Ratio__c = 10.0;
        newOppty.CloseDate = system.today() + 2;
        newOppty.DMA_Count__c = 0;
        newOppty.RecordTypeId = homeOwnerRT;
        insert newOppty;*/
    }

    @IsTest
    static void testBehaviorInsert() {
        Account newAcc = new Account (Name='Test Account');
        insert newAcc;
        Id homeOwnerRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();

        Contact con = new Contact(FirstName = 'FirstName', Opp_Lookup_Helper__c = 'test', LastName = 'LastName',  Phone = '12341', Email = 'fisrtName.lastName@test.com',
                AccountID = newAcc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Phone = '12341', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = newAcc.Id);
        insert con2;

        Opportunity newOppty = new Opportunity();
        newOppty.Name = 'Test Opportunity';
        newOppty.Applicant__c = con.Id;
        newOppty.Co_Applicant__c = con2.Id;
        newOppty.AccountId = newAcc.Id;
        newOppty.StageName = 'Submit to Ops';
        newOppty.CloseDate = System.today();
        newOppty.UnisonProcessor__c = UserInfo.getUserId();
        newOppty.Investment_Analyst2__c = UserInfo.getUserId();
        newOppty.Process_Program_Knowledge_Review__c = true;
        newOppty.RecordTypeId = homeOwnerRT;
        newOppty.Process_Program_Knowledge_Review__c = true;
        newOppty.Appraisal_Received__c = true;
        newOppty.Appraisal_Ordered__c = true;
        newOppty.Second_Appraisal_Ordered__c = true;
        newOppty.Second_Appraisal_Received__c = true;
        newOppty.Home_Inspection_Ordered__c = true;
        newOppty.Home_Inspection_Received__c = true;
        newOppty.Property_Report_Ordered__c = true;
        newOppty.Property_Report_Received__c = true;
        newOppty.DMA_Count__c = 3;
        newOppty.CloseDate = system.today() + 5;
        newOppty.Summary_Appraised_Value__c = 120;
        newOppty.OAV_Discount_Pct__c = 20;
        newOppty.Wire_to_Agent_Date__c = system.today();
        newOppty.Pricing_Ratio__c = 15.0;
        newOppty.Maximum_Authorized_DTI__c = 15.0;
        newOppty.Maximum_Authorized_LTV__c = 16.0;
        newOppty.Final_OAV_Calculation__c = 10.0;
        newOppty.Wire_to_Agent_Date__c = system.today();
        newOppty.Estimated_Funding_Amount__c = 110.0;
        newOppty.Maximum_Authorized_DTI__c = 15.0;
        newOppty.Maximum_Authorized_LTV__c = 16.0;
        Test.startTest();
        insert newOppty;
        Test.stopTest();

    }

    @IsTest
    static void testBehaviorUpdate() {
        /*
        Recorded_Information__c recordedInfo = new Recorded_Information__c();
        recordedInfo.Opportunity2__c = newOppty.Id;
        recordedInfo.Applicant1_Name__c = 'John';
        insert recordedInfo;

        Success_Factor__c SF = new Success_Factor__c();
        SF.Opportunity__c = newOppty.Id;
        SF.Success_Factor__c = 'Cash to Consumer';
        SF.Program__c = 'HO';
        SF.Status__c = 'Completed';
        insert SF;

        Deal_History__c DH = new Deal_History__c();
        DH.Opportunity__c = newOppty.Id;
        DH.Passbook_Status__c = 'Approved';
        insert DH;*/
/*
     Recorded_Information__c ri = [SELECT Id, Opportunity2__c, Opportunity2__r.Final_OAV_Calculation__c, Opportunity2__r.Investor_Percentage__c, Opportunity2__r.Estimated_Funding_Amount__c,
        Opportunity2__r.Pricing_Ratio__c, Option_Agreement_Expiration__c, Option_Purchase_Price__c, Option_Purchase_Price_Balance__c FROM Recorded_Information__c WHERE Opportunity2__c =: newOppty.Id LIMIT 1];
        system.debug('RECORDED INFO');
        system.debug(ri.Opportunity2__r.Final_OAV_Calculation__c); // 0
        system.debug(ri.Opportunity2__r.Investor_Percentage__c);// null ((Estimated_Funding_Amount__c * Pricing_Ratio__c) / Final_OAV_Calculation__c)
        system.debug(ri.Opportunity2__r.Estimated_Funding_Amount__c); // 11.00
        system.debug(ri.Opportunity2__r.Pricing_Ratio__c); // 10.00
        system.debug(ri.Option_Purchase_Price__c); // null
        system.debug(ri.Option_Purchase_Price_Balance__c); // null
*/
/*

        Opportunity refreshedOpp = [SELECT Id, Recorded_Information__c, Applicant__c, Applicant__r.Email, (SELECT Id, Opportunity2__c, Option_Purchase_Price_Balance__c FROM Recorded_Informations__r) FROM Opportunity WHERE
        Id =: newOppty.Id];

        refreshedOpp.StageName = 'Investment Due Diligence';
        system.debug('refreshedOpp ' + refreshedOpp.Recorded_Informations__r);
        update refreshedOpp;

*/
        Account newAcc = new Account (Name='Test Account');
        insert newAcc;

        Contact con = new Contact(FirstName = 'FirstName', Opp_Lookup_Helper__c = 'test', LastName = 'LastName',  Phone = '4123156', Email = 'fisrtName.lastName@test.com',
                AccountID = newAcc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Phone = '4123156', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = newAcc.Id);
        insert con2;

        Opportunity opp = new Opportunity();
        opp.AccountId = newAcc.Id;
        opp.Name = 'test opp';
        opp.StageName = 'Investment Due Diligence';
        opp.CloseDate = System.today();
        opp.Investment_Analyst2__c = UserInfo.getUserId();
        opp.UnisonProcessor__c = UserInfo.getUserId();
        opp.Maximum_Authorized_DTI__c = 19;
        opp.Maximum_Authorized_LTV__c = 19;
        opp.Estimated_Funding_Amount__c = 0.6;
        opp.Final_OAV_Calculation__c = 1;
        opp.Pricing_Ratio__c = 1;
        insert opp;


     //   Opportunity refreshedOpp2 = [SELECT Id, Recorded_Information__c, Applicant__c, Co_Applicant__c, Applicant__r.Email, (SELECT Id, Opportunity2__c, Option_Purchase_Price_Balance__c FROM Recorded_Informations__r) FROM Opportunity WHERE
   //    Name = 'Test Opportunity' LIMIT 1];
       /* Opportunity opp = new Opportunity();
        opp.AccountId = newAcc.Id;
        opp.Name = 'test opp';
        opp.StageName = 'Investment Due Diligence';
        opp.CloseDate = System.today();
        opp.Maximum_Authorized_DTI__c = 19;
        opp.Maximum_Authorized_LTV__c = 19;
        opp.Estimated_Funding_Amount__c = 0.6;
        opp.Final_OAV_Calculation__c = 1;
        opp.Pricing_Ratio__c = 1;
        insert opp;*/


        /* // refreshedOpp2.Applicant__c = con.Id;
         // refreshedOpp2.Co_Applicant__c = con2.Id;
          refreshedOpp2.Process_Program_Knowledge_Review__c = true;
          refreshedOpp2.Appraisal_Received__c = true;
          //refreshedOpp2.StageName = 'Final Approval';
          refreshedOpp2.Appraisal_Ordered__c = true;
          refreshedOpp2.Second_Appraisal_Ordered__c = true;
          refreshedOpp2.Second_Appraisal_Received__c = true;
          refreshedOpp2.Home_Inspection_Ordered__c = true;
          refreshedOpp2.Home_Inspection_Received__c = true;
          refreshedOpp2.Property_Report_Ordered__c = true;
          refreshedOpp2.Property_Report_Received__c = true;
          refreshedOpp2.DMA_Count__c = 3;
        //  refreshedOpp2.CloseDate = system.today() + 5;
          refreshedOpp2.Wire_to_Agent_Date__c = system.today();
          refreshedOpp2.Maximum_Authorized_DTI__c = 15.0;
          refreshedOpp2.Maximum_Authorized_LTV__c = 16.0;*/

        Test.startTest();
        opp.Home_Inspection_Received__c = true;
        opp.Property_Report_Ordered__c = true;
        opp.Property_Report_Received__c = true;
        opp.Second_Appraisal_Received__c = true;
        opp.Second_Appraisal_Ordered__c = true;
        opp.Appraisal_Received__c = true;
        opp.Process_Program_Knowledge_Review__c = true;
        Map<Id, Opportunity> mymap = new Map<Id, Opportunity>();
        List<Opportunity> mylist = new List<Opportunity>();
        mylist.add(opp);
        mymap.put(opp.Id, opp);
        OpportunityChatterUpdates.doChatterUpdates(mylist,mymap);
        update opp;
        Test.stopTest();
    }
}