objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DMA_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in DocGen to include the Deferred Maintenance Addendum if &gt; 0</description>
        <inlineHelpText>Total count of all DMA records</inlineHelpText>
        <label>DMA Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Title_Held__c</fullName>
        <label>Final Title to be Held</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individually</fullName>
                </value>
                <value>
                    <fullName>Jointly</fullName>
                </value>
                <value>
                    <fullName>In Trust</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <defaultValue>IF( $RecordType.Name = 'HomeBuyer','N/A','Pending')</defaultValue>
        <inlineHelpText>Passbook may run once LTV, DTI, and Credit Success Factors are marked Completed</inlineHelpText>
        <label>Current Passbook Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                    <isActive>false</isActive>
                    <label>Exception</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                    <isActive>false</isActive>
                    <label>Reject</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recorded_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recorded Information</label>
        <referenceTo>Recorded_Information__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_Held__c</fullName>
        <label>Title Held</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individually</fullName>
                </value>
                <value>
                    <fullName>Jointly</fullName>
                </value>
                <value>
                    <fullName>In Trust</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recorded_Information__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZZZ Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZZZ Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Informations (Co-Applicant)</relationshipLabel>
        <relationshipName>Recorded_Informations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fund_Number__c</fullName>
        <label>Fund Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity2</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations (Opportunity2)</relationshipLabel>
        <relationshipName>Recorded_Informations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recorded Information</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Recorded Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recorded Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityUtilityClassTest.cls
/*****************************************************************
 *   ------------------------------------------------------------------------
 *  Author: Neeraja Cherukuri
 *  Create date:  June 06 2019
 *   Details
 *  -------------------------------------------------------------------------
 *  Have re written the Test Class to optimize Code Coverage and cleaned up unused Code.
 *  ----------------------------------------------------------------------------
 *  
 * ---------------------------------------------------------------------------
 ************************************************************************************/


@isTest
private class OpportunityUtilityClassTest
{
    @IsTest static void  sfgating()
    {
        
        Test.startTest();
        Account acc = new Account(Name = 'New Account');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = acc.Id);
        insert con2;

        Opportunity opp = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Investment Due Diligence',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Property_Type__c = 'PUD',
                Co_Applicant__c = con2.Id,Encompass_Loan_Number__c = '10',Final_OAV_Calculation__c=100,
                                          IA_OAV_Override__c =100,Lien_First_Lender_Balance__c = 100,DMA_Count__c = 100,
                                          Title_Held__c = 'In Trust',Passbook_Status__c = 'Approved');
        insert opp;
        
        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = opp.Id;
        sf1.Success_Factor__c  = 'DTI';
        insert sf1; 
        
        sf1.Status__c = 'Completed';
        Update sf1;

        Recorded_Information__c rec= new Recorded_Information__c();
        rec.Fund_Number__c = 1;
        rec.Opportunity__c = opp.id;
        rec.Opportunity2__c = opp.id;
        insert rec;

       
        List<Opportunity> lstOpty = new List<Opportunity>();
        lstOpty.add(opp);
        
        opp.Final_Title_Held__c = 'Individually';
        opp.StageName = 'Final Approval';
        opp.Recorded_Information__c = rec.id;
        update opp;
        
        
        Test.stopTest();
        
        
       
    }

    
     @IsTest static void  sfgating_negative()
    {
        
        Test.startTest();
        Account acc = new Account(Name = 'New Account1');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstNam3e', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam4e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = acc.Id);
        insert con2;

        Opportunity opp = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Investment Due Diligence',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id,Property_Type__c = 'PUD',
                Co_Applicant__c = con2.Id,Encompass_Loan_Number__c = '10',Final_OAV_Calculation__c=100,
                                          IA_OAV_Override__c =100,Lien_First_Lender_Balance__c = 100,DMA_Count__c = 100,
                                          Title_Held__c = 'In Trust');
        insert opp;
        
        Success_Factor__c sf1  = new Success_Factor__c();
        sf1.Opportunity__c     = opp.Id;
        sf1.Success_Factor__c  = 'DTI';
        insert sf1; 
        
        sf1.Status__c = 'Completed';
        Update sf1;

        Recorded_Information__c rec= new Recorded_Information__c();
        rec.Fund_Number__c = 1;
        rec.Opportunity__c = opp.id;
        rec.Opportunity2__c = opp.id;
        insert rec;
       
        List<Opportunity> lstOpty = new List<Opportunity>();
        lstOpty.add(opp);
        
        opp.Final_Title_Held__c = 'Individually';        
        opp.StageName = 'Final Approval';
        opp.IA_Passbook_Override_Reasons__c = 'Decline';
        opp.IA_Passbook_Override__c  = false;
        opp.Recorded_Information__c = rec.id;
 
        update opp;
        
        
        Test.stopTest();
        
        
       
    }
 
    @isTest
	public static void Test_switchAppraisalReqs() {
		
		// Data setup
        Opportunity opp = new Opportunity();
        opp.Name = 'Test836532';
        opp.CloseDate = Date.today();
        opp.StageName = LABEL.Ready_for_Ops;
        opp.New_HomeOwner_Purchase_Date__c = Date.today().addDays(-100);
        opp.NHO_Expected_Close_Date__c = Date.today().addDays(400);
        // should set opp.Qualifies_for_New_HomeOwner_Pricing__c = false;
        insert opp;

        Success_Factor__c sf1 = new Success_Factor__c();
        sf1.Opportunity__c = opp.Id;
        sf1.Success_Factor__c = 'OAV';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        insert sf1;
        
        opp.StageName = LABEL.Investment_Due_Diligence;
        update opp;

        List<Current_Conditions__c> reqsForInsert = new List<Current_Conditions__c>();
        reqsForInsert.add(new Current_Conditions__c(Opportunity__c = opp.Id, Code__c = 'R1008'));
        reqsForInsert.add(new Current_Conditions__c(Opportunity__c = opp.Id, Code__c = 'R1040'));
        insert reqsForInsert;
		
		// Run the code
        Test.startTest();
        
        opp.NHO_Expected_Close_Date__c = Date.today().addDays(200);
        // should set opp.Qualifies_for_New_HomeOwner_Pricing__c = true;
        update opp;

        integer reqs2 = [SELECT COUNT() FROM Current_Conditions__c WHERE Opportunity__c = :opp.Id AND Code__c = 'R1125'];
        
        opp.NHO_Expected_Close_Date__c = Date.today().addDays(400);
        // should set opp.Qualifies_for_New_HomeOwner_Pricing__c = false;
        update opp;
		
		Test.stopTest();
		
        // Verify Results
        System.assertEquals(1, reqs2);
    }
    
    @isTest
	public static void Test_waivingR1125() {
		
		// Data setup
        Opportunity opp = new Opportunity();
        opp.Name = 'Test836533';
        opp.CloseDate = Date.today();
        opp.StageName = LABEL.Ready_for_Ops;
        opp.New_HomeOwner_Purchase_Date__c = Date.today().addDays(-100);
        opp.NHO_Expected_Close_Date__c = Date.today().addDays(400);
        // should set opp.Qualifies_for_New_HomeOwner_Pricing__c = false;
        insert opp;

        Success_Factor__c sf1 = new Success_Factor__c();
        sf1.Opportunity__c = opp.Id;
        sf1.Success_Factor__c = 'OAV';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        insert sf1;

        List<Current_Conditions__c> reqsForInsert = new List<Current_Conditions__c>();
        reqsForInsert.add(new Current_Conditions__c(Opportunity__c = opp.Id, Code__c = 'R1125'));
        insert reqsForInsert;
		
		// Run the code
        Test.startTest();
        
        opp.StageName = LABEL.Investment_Due_Diligence;
        update opp;
		
		Test.stopTest();
		
	}

}