objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Contact_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <inlineHelpText>Assign a value if this contact can be an Escrow for Spruce or Vantage Point.</inlineHelpText>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spruce</fullName>
                </value>
                <value>
                    <fullName>Vantage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Converted_Close_Date__c</fullName>
        <label>Converted Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Code__c</fullName>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Aged</fullName>
                    <isActive>false</isActive>
                    <label>Aged</label>
                </value>
                <value>
                    <fullName>Decline - Credit/Foreclosure Issues</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Credit/Foreclosure Issues</label>
                </value>
                <value>
                    <fullName>Decline - Insufficient Down Payment/Income</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Insufficient Down Payment/Income</label>
                </value>
                <value>
                    <fullName>Decline - Not in Geography</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Not in Geography</label>
                </value>
                <value>
                    <fullName>Decline - Property</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Property</label>
                </value>
                <value>
                    <fullName>Decline - Purchase Offer not Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Purchase Offer not Accepted</label>
                </value>
                <value>
                    <fullName>Decline - Rental or Second Home</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Rental or Second Home</label>
                </value>
                <value>
                    <fullName>Decline - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Unknown</label>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                    <isActive>false</isActive>
                    <label>Unresponsive</label>
                </value>
                <value>
                    <fullName>Withdraw - Already has Lender</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Already has Lender</label>
                </value>
                <value>
                    <fullName>Withdraw - Not Buying Home</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Not Buying Home</label>
                </value>
                <value>
                    <fullName>Withdraw - Prefers Another Product</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Prefers Another Product</label>
                </value>
                <value>
                    <fullName>Withdraw - Too Complicated</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Too Complicated</label>
                </value>
                <value>
                    <fullName>Withdraw - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>ZZZOrder Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>inspectAndEvaluate</fullName>
                </value>
                <value>
                    <fullName>devFakeInspectAndFakeEvaluate</fullName>
                </value>
                <value>
                    <fullName>devFakeInspectAndEvaluate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home Inspection</fullName>
                </value>
                <value>
                    <fullName>Title/Property Report</fullName>
                </value>
                <value>
                    <fullName>Combo Appraisal Inspection</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Spruce Refinance Transaction Title Order</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <isActive>false</isActive>
                    <label>Appraisal</label>
                </value>
                <value>
                    <fullName>Inspection</fullName>
                    <isActive>false</isActive>
                    <label>Inspection</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateSubmitOrdersCtrl_TEST.cls
/**********************************************************
 * @className   : CreateSubmitOrdersCtrl_TEST.cls
 * @date        : March 6, 2018
 * @description : This class provides test methods for CreateSubmitOrdersCtrl.cls
 * @param       :
 * @return      :
 *
 *
 **********************************************************/

@isTest
private class CreateSubmitOrdersCtrl_TEST {

    @isTest
    private static void testName() {
        Test.setMock(HttpCalloutMock.class, new HCCalloutMockImpl());

        Account acc = new Account(Name = 'New Account');
        insert acc;
        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        String homBuyerRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        Opportunity oppty = new Opportunity();
        oppty.Name = 'Oppty Name';
        oppty.AccountId = acc.Id;
        oppty.RecordTypeId = homBuyerRTId;
        oppty.StageName = 'Closed Lost';
        oppty.CloseDate = Date.today().addDays(20);
        oppty.Loss_Type__c = 'Withdrawn';
        oppty.Loss_Reason_Code__c = 'Customer information is fake or cannot be used to contact the customer';
        oppty.Property_Street_Number_and_Name__c = 'street 1';
        oppty.Property_City__c = 'San Francisco';
        oppty.Property_State__c = 'CA';
        oppty.Property_Zip_Code__c = '12354';
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        //oppty.Property_Type__c = 'Single-family detached';
        try {
            insert oppty;
        }
        catch (exception e){}

        System.Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(oppty);
        CreateSubmitOrdersCtrl ctrl = new CreateSubmitOrdersCtrl(sc);
        ctrl.InsertPddrItem();
        ctrl.createAndSubmitOrders();
        ctrl.result = '{"id":232,"customer_order_id":"a1P2F000000ZX9vUAG","name":"Property Test1","order_type":"devFakeInspectAndEvaluate","intended_use":"test","inspection_partner":4,"valuation_partner":5,"special_comments":null,"client_name":"Unison Home Ownership Investments","client_address":"650 California St","client_city":"San Francisco","client_state":"CA","client_zipcode":"94108","client_phone":"(415) 992-4200","lender_name":null,"lender_address":null,"lender_city":null,"lender_state":null,"lender_zipcode":null,"lender_phone":null,"desired_delivery_date":"2018-02-21","label":"Appraisal","items":[{"id":260,"customer_item_id":"a1P2F000000ZX9vUAG","address":"741 Venice Way Apt 7","unit":null,"city":"Inglewood","state":"CA","zipcode":"90302","property_type":"condo"}]}';
        ctrl.createAndSubmitOrders();


       /* Property_Due_Diligence_Reports__c tmpPDDR = new Property_Due_Diligence_Reports__c(Name = 'Property Test1', Type__c = 'Inspection', Order_Type__c = 'devFakeInspectAndEvaluate', Opportunity__c = oppty.id);
        insert tmpPDDR;
        ctrl.pddr = tmpPDDR;
        ctrl.createAndSubmitOrders();*/
        System.Test.stopTest();
    }

    @isTest
    private static void testCreateandSubmit() {
        Test.setMock(HttpCalloutMock.class, new HCCalloutMockImpl());

        Account acc = new Account(Name = 'New Account');
        insert acc;
        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Opportunity o = new Opportunity();
        o.AccountId = acc.Id;
        o.Name = 'Test Opp';
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        //o.Converted_Close_Date__c = System.Today().addMonths(3);
        o.CloseDate = System.Today().addMonths(3);
        o.StageName = 'Submit to Ops';
        o.Qualifies_for_New_HomeOwner_Pricing__c = false;
        o.Estimated_Funding_Amount__c = 1000;
        insert o;
        System.Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(o);
        CreateSubmitOrdersCtrl ctrl = new CreateSubmitOrdersCtrl(sc);

        ctrl.result = '{"id":232,"customer_order_id":"a1P2F000000ZX9vUAG","name":"Property Test1","order_type":"devFakeInspectAndEvaluate","intended_use":"test","inspection_partner":4,"valuation_partner":5,"special_comments":null,"client_name":"Unison Home Ownership Investments","client_address":"650 California St","client_city":"San Francisco","client_state":"CA","client_zipcode":"94108","client_phone":"(415) 992-4200","lender_name":null,"lender_address":null,"lender_city":null,"lender_state":null,"lender_zipcode":null,"lender_phone":null,"desired_delivery_date":"2018-02-21","label":"Appraisal","items":[{"id":260,"customer_item_id":"a1P2F000000ZX9vUAG","address":"741 Venice Way Apt 7","unit":null,"city":"Inglewood","state":"CA","zipcode":"90302","property_type":"condo"}]}';

        Property_Due_Diligence_Reports__c tmpPDDR = new Property_Due_Diligence_Reports__c(Name = 'Property Test1', Order_Type__c = 'devFakeInspectAndEvaluate', Opportunity__c = o.id);
        insert tmpPDDR;
        ctrl.pddr = tmpPDDR;
        ctrl.createAndSubmitOrders();
        System.Test.stopTest();
    }

    @isTest
    private static void testCreateandSubmit2() {
        Test.setMock(HttpCalloutMock.class, new HCCalloutMockImpl());

        Account acc = new Account(Name = 'New Account');
        insert acc;
        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Opportunity o = new Opportunity();
        o.AccountId = acc.Id;
        o.Name = 'Test Opp';
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        //o.Converted_Close_Date__c = System.Today().addMonths(3);
        o.CloseDate = System.Today().addMonths(3);
        o.StageName = 'Submit to Ops';
        o.Qualifies_for_New_HomeOwner_Pricing__c = false;
        o.Estimated_Funding_Amount__c = 1000;
        insert o;
        System.Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(o);
        CreateSubmitOrdersCtrl ctrl = new CreateSubmitOrdersCtrl(sc);


        Property_Due_Diligence_Reports__c tmpPDDR = new Property_Due_Diligence_Reports__c(Name = 'Property Test1', Order_Type__c = 'devFakeInspectAndEvaluate', Opportunity__c = o.id);
        insert tmpPDDR;
        ctrl.pddr = tmpPDDR;
        ctrl.createAndSubmitOrders();
        System.Test.stopTest();
    }
}