objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Unison's Investment Payment. This amount should not exceed Max Offer amount.</inlineHelpText>
        <label>Estimated Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Monthly_Base__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Income field used to determine DTI for the Lead: Base Income of the
            Applicant.</inlineHelpText>
        <label>Income Monthly Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <description>The maximum authorized debt-to-income ratio. It is a constraint set by the IA
            in which the DTI for the deal cannot exceed (Debt to Income is total liabilities over
            total income for the applicants) As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Maximum Authorized DTI</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <description>The maximum authorized loan-to-value ratio. It is a constraint set by the IA in
            which the LTV for the deal cannot exceed (Loan-to-Value is the mortgage amount over
            total home value) As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Maximum Authorized LTV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Pricing Ratio based on Unison Program</inlineHelpText>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>custom record type that indicate the type of deal the lead is As of Q4-2019,
            this field has been identified by Business Systems (and relevant stakeholders) as used
            or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
                <value>
                    <fullName>REX HomeBuyer</fullName>
                    <isActive>false</isActive>
                    <label>REX HomeBuyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been ordered by Origination Ops</description>
        <label>Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been received</description>
        <label>Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DMA_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in DocGen to include the Deferred Maintenance Addendum if &gt; 0</description>
        <inlineHelpText>Total count of all DMA records</inlineHelpText>
        <label>DMA Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been ordered by Origination Ops</description>
        <label>Home Inspection Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been received</description>
        <label>Home Inspection Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investment_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Investment Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Authorized BE DTI</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <inlineHelpText>Manual entry for IA. Influences MAD Pct.</inlineHelpText>
        <label>Max Authorized LTV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <inlineHelpText>Manually entered percentage for OAV discount</inlineHelpText>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Program_Knowledge_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</description>
        <inlineHelpText>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</inlineHelpText>
        <label>Program Knowledge Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Report_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Report_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary_Appraised_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>DLRS</description>
        <inlineHelpText>The average of Final_Value from all Appraisal Objects associated with the Opportunity.</inlineHelpText>
        <label>Summary Appraised Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectTasksDocumentNotificationTest.cls
/**
 * Created by Eliot Rojas on 5/2/2019.
 */

@IsTest
private class ProjectTasksDocumentNotificationTest {

    @testSetup static void setup() {
        /*     EmailTemplate e = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'Pest_Inspection_Received');
             insert e;
     */
        Id homeOwnerRT_Lead = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        Lead newLead = new Lead();
        newLead.LastName = 'Doe';
        newLead.Company = 'TestCo';
        newLead.RecordTypeId = homeOwnerRT_Lead;
        newLead.Income_Monthly_Base__c = 100;
        insert newLead;

        Account newAcc = new Account (Name='Test Account');
        insert newAcc;
        Id homeOwnerRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();

        Opportunity newOppty = new Opportunity();
        newOppty.Name = 'Test Opportunity';
        newOppty.AccountId = newAcc.Id;
        newOppty.StageName = 'Submit to Ops';
        newOppty.CloseDate = System.today();
        newOppty.UnisonProcessor__c = UserInfo.getUserId();
        newOppty.Investment_Analyst2__c = UserInfo.getUserId();
        newOppty.Process_Program_Knowledge_Review__c = true;
        newOppty.RecordTypeId = homeOwnerRT;
        newOppty.Process_Program_Knowledge_Review__c = true;
        newOppty.Appraisal_Received__c = true;
        newOppty.Appraisal_Ordered__c = true;
        newOppty.Second_Appraisal_Ordered__c = true;
        newOppty.Second_Appraisal_Received__c = true;
        newOppty.Home_Inspection_Ordered__c = true;
        newOppty.Home_Inspection_Received__c = true;
        newOppty.Property_Report_Ordered__c = true;
        newOppty.Property_Report_Received__c = true;
        newOppty.DMA_Count__c = 3;
        newOppty.CloseDate = system.today() + 5;
        newOppty.Summary_Appraised_Value__c = 120;
        newOppty.OAV_Discount_Pct__c = 20;
        newOppty.Wire_to_Agent_Date__c = system.today();
        newOppty.Pricing_Ratio__c = 15.0;
        newOppty.Maximum_Authorized_DTI__c = 15.0;
        newOppty.Maximum_Authorized_LTV__c = 16.0;
        newOppty.Final_OAV_Calculation__c = 10.0;
        newOppty.Wire_to_Agent_Date__c = system.today();
        newOppty.Estimated_Funding_Amount__c = 110.0;
        newOppty.Maximum_Authorized_DTI__c = 15.0;
        newOppty.Maximum_Authorized_LTV__c = 16.0;
        insert newOppty;

        Success_Factor__c SF = new Success_Factor__c();
        SF.Success_Factor__c = 'LTV';
        SF.Program__c = 'HO';
        SF.Opportunity__c = newOppty.Id;
        SF.Lead__c = newLead.Id;
        SF.Status__c = 'In Progress';
        insert SF;

        Current_Conditions__c newReq = new Current_Conditions__c();
        newReq.Opportunity__c = newOppty.Id;
        newReq.Requirement__c = '1040';
        newReq.Success_Factor__c = SF.Id;
        newReq.Status__c = 'Ready to Review';
        insert newReq;

        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT2';
        PT.Code__c = 'T10156';
        //PT.Completed__c = false;
        PT.Status__c = 'In Progress';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        insert PT;
    }

    // ON INSERT
    @IsTest
    static void testBehaviorInsert_Pest_Inspection() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10156';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_Appraisal_1004D() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10105';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_Natural_Hazard_Disclosure() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10093';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_HOA_Questionaire() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10010';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_Vesting_Addendum() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10079';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_Lender_Final_1003() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10196';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_Lender_Final_1008() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10113';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_RSI_Letter() {
        Opportunity newOppty = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Current_Conditions__c newReq = [SELECT Id, Opportunity__c FROM Current_Conditions__c WHERE  Opportunity__c =: newOppty.Id LIMIT 1];
        Project_Task__c PT = new Project_Task__c();
        PT.Name = 'TestPT';
        PT.Code__c = 'T10182';
        //PT.Completed__c = true;
        PT.Status__c = 'Completed';
        PT.Requirement__c = newReq.Id;
        PT.Opportunity__c = newOppty.Id;
        Test.startTest();
        insert PT;
        Test.stopTest();
    }

    // ON UPDATE
    @IsTest
    static void testBehaviorUpdate_Occupancy() {
        Test.startTest();
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId, Opportunity__c,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];

        // Related Req
        Current_Conditions__c req = [SELECT Id, Status__c, Opportunity__c FROM Current_Conditions__c WHERE Opportunity__c =: refreshedPT.Opportunity__c LIMIT 1];
        req.Status__c = '';
        req.Requirement__c = 'Certificate of Occupancy';


        refreshedPT.Code__c = 'T10158';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';


        update req;
        upsert refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Pest_Inspection() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];

        refreshedPT.Code__c = 'T10156';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        upsert refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Appraisal_1004D() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10158';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Natural_Hazard_Disclosure() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10158';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_HOA_Questionaire() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10158';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Vesting_Addendum() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10196';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Lender_Final_1003() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10084';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Lender_Final_1008() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10086';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_RSI_Letter() {
        Project_Task__c refreshedPT = [SELECT Id, Name, Code__c, /*Completed__c*/Status__c, Requirement__r.Success_Factor__c, Requirement__r.Success_Factor__r.OwnerId,
                Requirement__r.Success_Factor__r.Lead__r.OwnerId,
                Requirement__r.Status__c, Requirement__r.Opportunity__r.Account.OwnerId FROM Project_Task__c WHERE Name = 'TestPT2'];
        refreshedPT.Code__c = 'T10084';
        //refreshedPT.Completed__c = true;
        refreshedPT.Status__c = 'Completed';

        Test.startTest();
        update refreshedPT;
        Test.stopTest();
    }
}