objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Code__c</fullName>
        <label>Document Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Requirements (MRD)</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Box_File_Id__c</fullName>
        <label>Box File Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Box_File_URL__c</fullName>
        <label>Box File URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Box_Folder_Id__c</fullName>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Code__c</fullName>
        <label>Document Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Document MetaData</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>See workflow rule: DMD Upload</description>
        <inlineHelpText>If Box File ID and Box URL has a value, checkbox updates to 'True'</inlineHelpText>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Box_Folder_Id__c</fullName>
        <description>The id in the URL of the folder in Box that holds all of the documents. As of
            Q4 2019, Box is still actively used. Used for the tracking the Box Folder Id. As of
            Q4-2019, this field has been identified by Business Systems (and relevant stakeholders)
            as used or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Box FolderID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>HB Lead Status</businessProcess>
        <description>012E00000002OGS</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complete_By_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complete By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date_Time_Stamp__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Upload_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Document Upload Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DMDTriggerHandler.cls
/************************************************************************************
 Apex Class Name     :  DMDTriggerHandler
 Version             : 1.0
 Created Date        : 4th Dec 2018
 Function            : To accomodate Auto Completion of Tasks Related to Document Metadata whenever a
                        Document has been uploaded and Document_Upload_Needed__c checkbox is marked True on the Project Tasks.
 Author              : Neeraja Cherukuri
 
 Modification Log    :
* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Neeraja Cherukuri            12/04/2018                Original Version
*************************************************************************************
*/


public class DMDTriggerHandler {

    //Constants 
    
    public static void handleBeforeInsert(List<Document_MetaData__c> newList){
        
        
        
    }
    
    public static void handleAfterInsert(List<Document_MetaData__c> lstDMDs)
    {
        
     
    }
    /*
    private static void UpdateUploadedOnRequirement(List<id> lstReqUploadedIds)
    {
        ID IDHomeBuyer = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        ID IDHomeOwner = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();

        //Ticket: https://unison-technology.atlassian.net/browse/BUS-155109402

        List<current_conditions__c> lstReqs = [ select id, name, lead__c,
                                            lead__r.name, lead__r.status,
                                            lead__r.RecordTypeId, Uploaded__c
                                            from current_conditions__c
                                            where
                                            (id in :lstReqUploadedIds) and
                                            ((lead__r.RecordTypeId = :IDHomeOwner and lead__r.status = 'Application Received') or
                                            (lead__r.RecordTypeId = :IDHomeBuyer and lead__r.status = 'Pending Submission'))
                                            ];

        for (current_conditions__c cc: lstReqs)
        {
            cc.Uploaded__c = true;
        }

        update lstReqs;
    }*/

    public static void handleAfterUpdate(List<Document_MetaData__c> newList, Map<Id, Document_MetaData__c> oldMap)
    {
        
        List<Id> lstReqIds = new List<Id>();
        List<Id> lstReqUploadedIds = new List<Id>();
        List<Project_Task__c> lstPTForUpdate = new List<Project_Task__c>();
        
        for(Document_MetaData__c objDMD : newList)
        
        {
            if((objDMD.Requirement__c != null && objDMD.Box_Folder_Id__c != null && objDMD.Box_File_URL__c != null) &&
               (oldMap.get(objDMD.Id).Box_Folder_Id__c != objDMD.Box_Folder_Id__c  || 
               oldMap.get(objDMD.Id).Box_File_URL__c != objDMD.Box_File_URL__c   || 
               oldMap.get(objDMD.Id).Box_File_Id__c != objDMD.Box_File_Id__c)  ) 
            {
                lstReqIds.add(objDMD.Requirement__c);
            }
            if(objDMD.Uploaded__c == true)
                lstReqUploadedIds.add(objDMD.Requirement__c);
        }
        
        for(Project_Task__c objProjTask : [SELECT Id,Requirement__c FROM Project_Task__c WHERE Requirement__c IN: lstReqIds and Document_Upload_Needed__c = true])
        {
              //Project_Task__c objPT = new Project_Task__c(Id= objProjTask);
              //objProjTask.Completed__c = true;
              objProjTask.Status__c = 'Completed';
              objProjTask.Complete_By_User__c = UserInfo.getUserId();
              objProjTask.Completed_Date_Time_Stamp__c = System.now();
            // objProjTask.Requirement__c 
          
              
              lstPTForUpdate.add(objProjTask);    
        }
        
        if(!lstPTForUpdate.isEmpty())
        {
            try
            {
                update lstPTForUpdate;    
            }
            catch(Exception ex)
            {
               System.debug('=====Exception on update== '+ex.getStackTraceString());
            }
            
        } 
        
        System.debug('===='+lstReqIds.size());
   /*     if(lstReqIds.size() == 0 )
        {
            List<Id> lstPTIds = new List<Id>();
            List<Document_MetaData__c> lstValidDMDs = new List<Document_MetaData__c>();
            Map<String, String> mapDMDCode_ProjectCode = new Map<String, String>();
            Map<String,String> DMD_mdt = new Map<String,String>();
        //    List<Project_Task__c> lstPTForUpdate = new List<Project_Task__c>();
            Map<Id, Id> mapDMDId_ProjectTaskId = new Map<Id, Id>();
            Map<Id, Project_Task__c> mapPTId_ProjectTask = new Map<Id, Project_Task__c>(); 
            
            for(Document_MetaData__c objDMD : newList)
            {
                if(oldMap.get(objDMD.Id).Box_Folder_Id__c != objDMD.Box_Folder_Id__c  || oldMap.get(objDMD.Id).Box_File_URL__c != objDMD.Box_File_URL__c   || oldMap.get(objDMD.Id).Box_File_Id__c != objDMD.Box_File_Id__c  )
                {
                    if(objDMD.Box_File_Id__c != null 
                            && objDMD.Box_File_URL__c != null 
                            && objDMD.Box_Folder_Id__c != null 
                            && objDMD.Document_Code__c != null
                            && objDMD.ProjectTask__c != null)
                        
                            lstPTIds.add(objDMD.ProjectTask__c); 
                            lstValidDMDs.add(objDMD);   
                }
            }
            System.debug('====lstPTIds==='+lstPTIds);
            if(lstPTIds.size() > 0 )
            {
                for(Project_Task__c objPT : [SELECT Id,DMD__c,DMD__r.Document_Code__c ,Code__c FROM Project_Task__c WHERE Id IN : lstPTIds])
                {
                    
                    if(objPT.Code__c != null && objPT.DMD__r.Document_Code__c != null)
                       // mapProjectCode_DMDCode.put(objPT.Code__c, objPT.DMD__r.Document_Code__c); 
                        mapDMDCode_ProjectCode.put(objPT.DMD__r.Document_Code__c, objPT.Code__c); 
                        mapPTId_ProjectTask.put(objPT.Id, objPT);
                        mapDMDId_ProjectTaskId.put(objPT.DMD__c, objPT.Id);  
                }
            }
            for(DMD_Complete_Project_Task__mdt objDMD_mdt : [SELECT Document_Code__c, Projet_Code__c FROM DMD_Complete_Project_Task__mdt])
            {
                DMD_mdt.put(objDMD_mdt.Document_Code__c, objDMD_mdt.Projet_Code__c);
            }
                      
            Project_Task__c objPT = new Project_Task__c();
            for(Document_MetaData__c objDMD : lstValidDMDs)
            {
                if(objDMD.Box_File_Id__c != null && objDMD.Box_File_URL__c != null && objDMD.Box_Folder_Id__c != null && objDMD.Document_Code__c != null)
                {
                    if(DMD_mdt.containsKey(objDMD.Document_Code__c) 
                                && mapDMDCode_ProjectCode.containsKey(objDMD.Document_Code__c))
                    {
                        if(DMD_mdt.get(objDMD.Document_Code__c).equalsIgnoreCase(mapDMDCode_ProjectCode.get(objDMD.Document_Code__c)))
                        {
                            objPT = new Project_Task__c(Id=mapDMDId_ProjectTaskId.get(objDMD.Id)); 
                            objPT.Completed__c = true;
                            objPT.Complete_By_User__c = UserInfo.getUserId();
                            objPT.Completed_Date_Time_Stamp__c = System.now();
                            
                            lstPTForUpdate.add(objPT);          
                        }
                    }   
            }
            System.debug('======lstPTForUpdate====='+lstPTForUpdate);
            if(!lstPTForUpdate.isEmpty())
            {
               //Update lstPTForUpdate;
            }
        }         
    }*/

        //Caro Veliz: Commented temporaly while we fix antoher problem
        //UpdateUploadedOnRequirement(lstReqUploadedIds);

    }  
    
    public static void handlebeforeUpdate(Map<Id, Document_MetaData__c> newMap, Map<Id, Document_MetaData__c> oldMap){
        
    }
}