objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Urgent Property Fix</fullName>
                    <label>Gather Information on Urgent Property Fix</label>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DMA__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>DMAs</relationshipLabel>
        <relationshipName>DMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>DMAs</relationshipLabel>
        <relationshipName>DMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <displayFormat>DMA-{000000}</displayFormat>
        <label>DMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <defaultValue>IF( $RecordType.Name = 'HomeBuyer','N/A','Pending')</defaultValue>
        <inlineHelpText>Passbook may run once LTV, DTI, and Credit Success Factors are marked Completed</inlineHelpText>
        <label>Current Passbook Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                    <isActive>false</isActive>
                    <label>Exception</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                    <isActive>false</isActive>
                    <label>Reject</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DMATriggerHandlerTest.cls
@isTest
public class DMATriggerHandlerTest {
    @testSetup
    private static void testData() {
        Account acc            = new Account();
        acc.Name           = 'acctest';
        insert acc;
        
        Opportunity opp        = new Opportunity();
        opp.Name           = 'opptest';
        opp.StageName      = 'final approval';
        opp.Passbook_Status__c  = 'Approve';
        opp.CloseDate      = System.today();
        opp.Estimated_Funding_Amount__c = 0.6;
        opp.Final_OAV_Calculation__c = 1;
        opp.Pricing_Ratio__c = 1;
                //opp.Account        = acc.Id;
        insert opp;


        Success_Factor__c Sft   = new Success_Factor__c();
        sft.opportunity__c      = opp.Id;
        sft.Success_Factor__c   = 'Post-Closing';
        insert sft;

       /* Current_Conditions__c req = new Current_Conditions__c();
        req.Opportunity__c = opp.Id;
        req.Requirement__c = 'Urgent Property Fix';
        req.Code__c = 'R1046';
        req.Category__c = 'Mortgage';
        req.Internal_vs_External__c = 'Internal';
        //req.Assigned_To__c = 'PS'; /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup 
        req.Success_Factor__c = sft.Id;
        insert req;*/

        /*Project_Task__c tmpPJ = new Project_Task__c(Name='Request documentation of completion and/or payment confirmation', Requirement__c =req.id , Opportunity__c = opp.id);
        Project_Task__c tmpPJ1 = new Project_Task__c(Name='Receive documentation of completion and/or payment confirmation', Requirement__c =req.id, Opportunity__c = opp.id);
        Project_Task__c tmpPJ2 = new Project_Task__c(Name='Request contractor bid for escrow holdback', Requirement__c =req.id, Opportunity__c = opp.id);
        Project_Task__c tmpPJ3 = new Project_Task__c(Name='Upload contractor bid for escrow holdback', Requirement__c =req.id, Opportunity__c = opp.id);
        List<Project_Task__c> tmpPJList = new List<Project_Task__c>();
        tmpPJList.add(tmpPJ);
        tmpPJList.add(tmpPJ1);
        tmpPJList.add(tmpPJ2);
        tmpPJList.add(tmpPJ3);
        insert tmpPJList;*/
        
    }
    
    @isTest
    private static void dmaCreation() {
        Opportunity opp = [Select Id, (Select Id,Total_Number_of_Pages__c,Inspection_Date__c, Urgent_Fix_Type__c from DMAs__r) from Opportunity LIMIT 1];
        DMA__c dma1    = new DMA__c();
        dma1.Inspection_Date__c          = System.today();
        dma1.Total_Number_of_Pages__c    = 50;
        dma1.Opportunity__c              = opp.Id;
        
        insert dma1;
       
    }
    
    @isTest
    private static void dmaUpdate() {
        Opportunity opp = [Select Id, (Select Id,Total_Number_of_Pages__c,Inspection_Date__c, Urgent_Fix_Type__c from DMAs__r) from Opportunity LIMIT 1];
        DMA__c dma2    = new DMA__c();
        dma2.Inspection_Date__c          = System.today();
        dma2.Total_Number_of_Pages__c    = 50;
        dma2.Opportunity__c              = opp.Id;
        dma2.Urgent_Fix_Type__c          = 'Pre-Close'; 
        insert dma2;
        
        dma2.Total_Number_of_Pages__c = 51;
        dma2.Urgent_Fix_Type__c = 'Escrow Holdback';
        update dma2;
    }
    @isTest
    private static void multipleinsert(){
        Opportunity opp = [Select Id, (Select Id,Total_Number_of_Pages__c,Inspection_Date__c, Urgent_Fix_Type__c from DMAs__r) from Opportunity LIMIT 1];
        DMA__c dma1    = new DMA__c();
        dma1.Inspection_Date__c          = System.today();
        dma1.Total_Number_of_Pages__c    = 50;
        dma1.Opportunity__c              = opp.Id;
        insert dma1; 
        
        DMA__c dma2    = new DMA__c();
        dma2.Inspection_Date__c          = System.today();
        dma2.Total_Number_of_Pages__c    = 50;
        dma2.Opportunity__c              = opp.Id;
        //dma2.Urgent_Fix_Type__c        = 'Pre-Close';
        insert dma2;
    }

    @isTest
    private static void ElseLine42(){
        Opportunity opp = [Select Id, (Select Id,Total_Number_of_Pages__c,Inspection_Date__c, Urgent_Fix_Type__c from DMAs__r) from Opportunity LIMIT 1];
        DMA__c dma1    = new DMA__c();
        dma1.Inspection_Date__c          = System.today();
        dma1.Total_Number_of_Pages__c    = 50;
        dma1.Opportunity__c              = opp.Id;
        insert dma1;
        Test.setCreatedDate(dma1.id, system.today()-60);
        DMA__c dma2    = new DMA__c();
        dma2.Inspection_Date__c          = System.today();
        dma2.Total_Number_of_Pages__c    = 20;
        dma2.Opportunity__c              = opp.Id;
        insert dma2;
        Test.setCreatedDate(dma2.id, system.today()+10);
        DMA__c dma3    = new DMA__c();
        dma3.Inspection_Date__c          = System.today();
        dma3.Total_Number_of_Pages__c    = 10;
        dma3.Opportunity__c              = opp.Id;
        insert dma3;
        Test.setCreatedDate(dma3.id, system.today()+60);
        DMA__c dma4    = new DMA__c();
        dma4.Inspection_Date__c          = System.today();
        dma4.Total_Number_of_Pages__c    = 1;
        dma4.Opportunity__c              = opp.Id;
        insert dma4;
        Test.setCreatedDate(dma4.id, system.today()-10);
    }

  
    
}