objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_NOO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Investment Property Guidelines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>Property categories for Appraisal &lt;&gt; Unison reporting. To be deprecated and maintained on Property object.</description>
        <inlineHelpText>Property categories for Appraisal &lt;&gt; Unison reporting.</inlineHelpText>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recorded_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recorded Information</label>
        <referenceTo>Recorded_Information__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>Properties for which customers and indirect channel partners (loan officers, real estate agents, etc) have inquired the investment approval status.</description>
    <fields>
        <fullName>Is_NOO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>New product features with launch of fund in April. This field needs to be captured</description>
        <label>Is Non-Owner-Occupied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>County Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Flood_Zone__c</fullName>
        <label>Flood Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>A1</fullName>
                </value>
                <value>
                    <fullName>A10</fullName>
                </value>
                <value>
                    <fullName>A11</fullName>
                </value>
                <value>
                    <fullName>A12</fullName>
                </value>
                <value>
                    <fullName>A13</fullName>
                </value>
                <value>
                    <fullName>A14</fullName>
                </value>
                <value>
                    <fullName>A15</fullName>
                </value>
                <value>
                    <fullName>A16</fullName>
                </value>
                <value>
                    <fullName>A17</fullName>
                </value>
                <value>
                    <fullName>A18</fullName>
                </value>
                <value>
                    <fullName>A19</fullName>
                </value>
                <value>
                    <fullName>A1-A30</fullName>
                </value>
                <value>
                    <fullName>A2</fullName>
                </value>
                <value>
                    <fullName>A20</fullName>
                </value>
                <value>
                    <fullName>A21</fullName>
                </value>
                <value>
                    <fullName>A22</fullName>
                </value>
                <value>
                    <fullName>A23</fullName>
                </value>
                <value>
                    <fullName>A24</fullName>
                </value>
                <value>
                    <fullName>A25</fullName>
                </value>
                <value>
                    <fullName>A26</fullName>
                </value>
                <value>
                    <fullName>A27</fullName>
                </value>
                <value>
                    <fullName>A28</fullName>
                </value>
                <value>
                    <fullName>A29</fullName>
                </value>
                <value>
                    <fullName>A3</fullName>
                </value>
                <value>
                    <fullName>A30</fullName>
                </value>
                <value>
                    <fullName>A4</fullName>
                </value>
                <value>
                    <fullName>A5</fullName>
                </value>
                <value>
                    <fullName>A6</fullName>
                </value>
                <value>
                    <fullName>A7</fullName>
                </value>
                <value>
                    <fullName>A8</fullName>
                </value>
                <value>
                    <fullName>A9</fullName>
                </value>
                <value>
                    <fullName>A99</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AH</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>V1</fullName>
                </value>
                <value>
                    <fullName>V10</fullName>
                </value>
                <value>
                    <fullName>V11</fullName>
                </value>
                <value>
                    <fullName>V12</fullName>
                </value>
                <value>
                    <fullName>V13</fullName>
                </value>
                <value>
                    <fullName>V14</fullName>
                </value>
                <value>
                    <fullName>V15</fullName>
                </value>
                <value>
                    <fullName>V16</fullName>
                </value>
                <value>
                    <fullName>V17</fullName>
                </value>
                <value>
                    <fullName>V18</fullName>
                </value>
                <value>
                    <fullName>V19</fullName>
                </value>
                <value>
                    <fullName>V2</fullName>
                </value>
                <value>
                    <fullName>V20</fullName>
                </value>
                <value>
                    <fullName>V21</fullName>
                </value>
                <value>
                    <fullName>V22</fullName>
                </value>
                <value>
                    <fullName>V23</fullName>
                </value>
                <value>
                    <fullName>V24</fullName>
                </value>
                <value>
                    <fullName>V25</fullName>
                </value>
                <value>
                    <fullName>V26</fullName>
                </value>
                <value>
                    <fullName>V27</fullName>
                </value>
                <value>
                    <fullName>V28</fullName>
                </value>
                <value>
                    <fullName>V29</fullName>
                </value>
                <value>
                    <fullName>V3</fullName>
                </value>
                <value>
                    <fullName>V30</fullName>
                </value>
                <value>
                    <fullName>V4</fullName>
                </value>
                <value>
                    <fullName>V5</fullName>
                </value>
                <value>
                    <fullName>V6</fullName>
                </value>
                <value>
                    <fullName>V7</fullName>
                </value>
                <value>
                    <fullName>V8</fullName>
                </value>
                <value>
                    <fullName>V9</fullName>
                </value>
                <value>
                    <fullName>VE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Number_of_Units__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Number of Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <inlineHelpText>State must be only two characters in length.</inlineHelpText>
        <label>State / Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <inlineHelpText>Property address including street number, street name, suffixes and unit.</inlineHelpText>
        <label>Full Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip  / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recorded_Information__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>Used for Nintex - HO Offer Package to populate Corporate Entity + State</description>
        <label>Property State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Recorded Information</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Recorded Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recorded Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single-family detached</fullName>
    </customValue>
    <customValue>
        <fullName>Condominium</fullName>
    </customValue>
    <customValue>
        <fullName>2-4 Family</fullName>
    </customValue>
    <customValue>
        <fullName>PUD</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Townhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Detached</fullName>
        <isActive>false</isActive>
        <label>Detached</label>
    </customValue>
    <masterLabel>Property Type</masterLabel>
</GlobalValueSet>

classes/PropertyTriggerHandler.cls
/**
 *  About
 *  -----
 *  Author: Sundar Subramaniam
 *  Create date: Tue Apr 16 2019
 *
  *  Details
 *  -----
 *  Apex class to handle all the events raised by PropertyTrigger
 *
 *  Update History
 *  -----
 *
 *
 *  -----
 *
 **/
public class PropertyTriggerHandler{
    /**
     *  About
     *  -----
     *  Author: Sundar Subramaniam
     *
     *  Details
     *  -----
     *  Method to take care of all functionalities when AFTER INSERT fires
    **/
    // Dictionary added for: https://unison-technology.atlassian.net/browse/BUS-155110785
    private static final Set<String> floodZoneCodes = new Set<String> {'A','AE','AH','AO','AR','A1','A2','A3','A4','A5','A6','A7','A8','A9','A10',
            'A11','A12','A13','A14','A15','A16','A17','A18','A19','A20','A21','A22','A23','A24','A25','A26','A27','A28','A29','A30',
            'A99','V','VE','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18', 'V19','V20',
            'V21','V22','V23','V24','V25','V26','V27','V28','V29','V30'};
    public static void handleAfterInsert(List<Property__c> newList){
        Set<Id> oppId = new Set<Id>();
        Map<Id,Opportunity> oppMap = new Map<Id,Opportunity>();
        List<Opportunity> updateOppList = new List<Opportunity>();
        Set<Id> opportunityIds = new Set<Id>();
        List<Property__c> propertiesForFloodZone = new List<Property__c>();

        for(Property__c rec: newList){
            if(rec.Opportunity__c != null)
            oppId.add(rec.Opportunity__c);

            if(rec.Is_NOO__c == true) {
                if(rec.Opportunity__c != null) {
                    opportunityIds.add(rec.Opportunity__c);
                }
            }

            if(rec.Property_Flood_Zone__c != null && rec.Opportunity__c != null && floodZoneCodes.contains(rec.Property_Flood_Zone__c)) {
                propertiesForFloodZone.add(rec);
            }
        }

        if(!propertiesForFloodZone.isEmpty()) {
            createFloorInsuranceRequirement(propertiesForFloodZone);
        }

        if(!opportunityIds.isEmpty()) {
            checkIsNOO(opportunityIds);
        }

        if(oppId.size() > 0){
            oppMap = new Map<Id,Opportunity>([SELECT Id, Name, Property_Street_Number_and_Name__c, Property_City__c, Property_State__c,Property_Zip_Code__c,Property_County__c,Property_Type__c, Probability, Property__c FROM Opportunity WHERE Id IN: oppId]);
        }

        for(Property__c rec: newList){
            if(rec.Opportunity__c != null){
                Opportunity opp = new Opportunity();
                opp.Id = rec.Opportunity__c;
                boolean flag = false;
                if(oppMap.containsKey(rec.Opportunity__c) && rec.Property_Type__c == oppMap.get(rec.Opportunity__c).Property_Type__c && oppMap.get(rec.Opportunity__c).Probability > 0 && oppMap.get(rec.Opportunity__c).Probability < 100){
                    if(rec.Opportunity__c != NULL && oppMap.get(rec.Opportunity__c).Property__c == NULL){
                        opp.Property__c = rec.Id;
                        flag = true;
                    }
                    if(rec.Property_Street_Number_and_Name__c != null ){
                        opp.Property_Street_Number_and_Name__c = rec.Property_Street_Number_and_Name__c;
                        flag = true;
                    }
                    if(rec.Property_City__c != null ){
                        opp.Property_City__c = rec.Property_City__c;
                        flag = true;
                    }
                    if(rec.Property_State__c != null ){
                        opp.Property_State__c = rec.Property_State__c;
                        flag = true;
                    }
                    if(rec.Property_Zip_Code__c != null){
                        opp.Property_Zip_Code__c = rec.Property_Zip_Code__c;
                        flag = true;
                    }
                    if(rec.Property_County__c != null){
                        opp.Property_County__c = rec.Property_County__c;
                        flag = true;
                    }

                    if(flag){
                        updateOppList.add(opp);
                    }
                }
            }
        }

        if(updateOppList.size() > 0){
            update updateOppList;
        }
    }

     /**
     *  About
     *  -----
     *  Author: Sundar Subramaniam
     *
     *  Details
     *  -----
     *  Method to take care of all functionalities when AFTER UPDATE fires
     *
    **/
    public static void handleAfterUpdate(List<Property__c> newList, Map<Id, Property__c> oldMap) {
        Set<Id> oppId = new Set<Id>();
        Map<Id,Opportunity> oppMap = new Map<Id,Opportunity>();
        List<Opportunity> updateOppList = new List<Opportunity>();
        List<Recorded_Information__c> updateRecInfList = new List<Recorded_Information__c>();
        Set<Id> opportunityIds = new Set<Id>();
        List<Property__c> propertiesForFloodZone = new List<Property__c>();

        for(Property__c rec: newList){
            if(rec.Opportunity__c != null)
            oppId.add(rec.Opportunity__c);

            if(rec.Property_Number_of_Units__c != null && rec.Property_Number_of_Units__c != oldMap.get(rec.Id).Property_Number_of_Units__c
                    && rec.Property_Number_of_Units__c > 2) {
                if(rec.Opportunity__c != null) {
                    opportunityIds.add(rec.Opportunity__c);
                }
            }

            if(rec.Property_Flood_Zone__c != null && oldMap.get(rec.Id).Property_Flood_Zone__c != rec.Property_Flood_Zone__c
                    && rec.Opportunity__c != null && floodZoneCodes.contains(rec.Property_Flood_Zone__c)) {
                propertiesForFloodZone.add(rec);
            }
        }

        if(!propertiesForFloodZone.isEmpty()) {
            createFloorInsuranceRequirement(propertiesForFloodZone);
        }

        if(!opportunityIds.isEmpty()) {
            checkIsNOO(opportunityIds);
        }

        if(oppId.size() > 0){
            oppMap = new Map<Id,Opportunity>([SELECT Id, Name, Property_Street_Number_and_Name__c, Recorded_Information__c, Property_City__c, Property_State__c,Property_Zip_Code__c,Property_County__c,Property_Type__c, Probability FROM Opportunity WHERE Id IN: oppId]);
        }

        for(Property__c rec: newList){
            if(rec.Opportunity__c != null){
                Opportunity opp = new Opportunity();
                opp.Id = rec.Opportunity__c;
                SYSTEM.debug('- - opp - -');
                SYSTEM.debug(opp);
                boolean flag = false;
                if(oppMap.containsKey(rec.Opportunity__c) && rec.Property_Type__c == oppMap.get(rec.Opportunity__c).Property_Type__c && oppMap.get(rec.Opportunity__c).Probability > 0 && oppMap.get(rec.Opportunity__c).Probability < 100){
                    if(rec.Property_Street_Number_and_Name__c != null && rec.Property_Street_Number_and_Name__c != oldMap.get(rec.Id).Property_Street_Number_and_Name__c){
                        opp.Property_Street_Number_and_Name__c = rec.Property_Street_Number_and_Name__c;
                        flag = true;
                    }
                    if(rec.Property_City__c != null && rec.Property_City__c != oldMap.get(rec.Id).Property_City__c){
                        opp.Property_City__c = rec.Property_City__c;
                        flag = true;
                    }
                    system.debug('- before update -');
                    system.debug( rec );
                    if(rec.Property_State__c != null && rec.Property_State__c != oldMap.get(rec.Id).Property_State__c){
                        system.debug( '-- state --' );
                        system.debug( opp.Property_State__c );
                        system.debug( rec.Property_State__c );
                        system.debug( oldMap.get(rec.Id).Property_State__c );



                        opp.Property_State__c = rec.Property_State__c;

                        Id riID  = oppMap.get(rec.Opportunity__c).Recorded_Information__c;

                        system.debug( 'riID' );
                        system.debug( riID );

                        if ( riID != null) {
                            Recorded_Information__c recInf = new Recorded_Information__c( id=riID, Property_State__c = rec.Property_State__c);
                            system.debug( 'recInf' );
                            system.debug( recInf );
                            updateRecInfList.add(recInf);
                        }

                        flag = true;
                    }
                    if(rec.Property_Zip_Code__c != null && rec.Property_Zip_Code__c != oldMap.get(rec.Id).Property_Zip_Code__c){
                        opp.Property_Zip_Code__c = rec.Property_Zip_Code__c;
                        flag = true;
                    }
                    if(rec.Property_County__c != null && rec.Property_County__c != oldMap.get(rec.Id).Property_County__c){
                        opp.Property_County__c = rec.Property_County__c;
                        flag = true;
                    }
                    if(flag){
                        updateOppList.add(opp);
                    }
                }
            }
        }

        if(updateOppList.size() > 0){
            update updateOppList;

            system.debug( 'updateOppList');
            system.debug( updateOppList);
            system.debug( 'updateRecInfList');
            system.debug( updateRecInfList);
            if(updateOppList.size() > 0) {
                update updateRecInfList;
            }
            /*
            system.debug( 'recs');
            system.debug( recs );

            if ( recs.size()>0 ) {
                for (Recorded_Information__c ri : recs) {
                    ri.Property_State__c = oppMap.get(ri.Opportunity__c).Property_State__c;
                }
                system.debug( 'recs');
                system.debug( recs );
                update recs;
            }*/
        }
    }

    // Added for: https://unison-technology.atlassian.net/browse/BUS-155110473
    private static void checkIsNOO (Set<Id> oppIds) {
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([SELECT Id, Is_NOO__c FROM Opportunity WHERE Id IN : oppIds]);
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        for(Opportunity currentOpportunity : opportunityMap.values()) {
            currentOpportunity.Is_NOO__c = true;
            oppsToUpdate.add(currentOpportunity);
        }

        if(!oppsToUpdate.isEmpty()) {
            update oppsToUpdate;
        }
    }

    // Added for: https://unison-technology.atlassian.net/browse/BUS-155110785
    private static void createFloorInsuranceRequirement(List<Property__c> properties) {
        Set<Id> oppIds = new Set<Id>();
        for(Property__c prop : properties) {
            oppIds.add(prop.Opportunity__c);
        }

        // Create Flood Insurance Requirement if there aren't any created
        List<Current_Conditions__c> reqsToInsert = new List<Current_Conditions__c>();
        Map<Id, List<Current_Conditions__c>> opptyReqsMap = new Map<Id, List<Current_Conditions__c>>();
        for(Current_Conditions__c req : [SELECT Id, Requirement__c, Status__c, Opportunity__c
        FROM Current_Conditions__c WHERE Opportunity__c IN : oppIds AND Requirement__c = 'Flood Insurance']) {
            if(opptyReqsMap.containsKey(req.Opportunity__c)) {
                List<Current_Conditions__c> reqs = opptyReqsMap.get(req.Opportunity__c);
                reqs.add(req);
                opptyReqsMap.put(req.Opportunity__c, reqs);
            } else {
                opptyReqsMap.put(req.Opportunity__c, new List<Current_Conditions__c> { req });
            }
        }
        for(Id oppId : oppIds) {
            if(!opptyReqsMap.containsKey(oppId)) {
                reqsToInsert.add(new Current_Conditions__c(Opportunity__c = oppId, Code__c = 'R1031'));
            }
        }

        if(!reqsToInsert.isEmpty()) {
            insert reqsToInsert;
        }
    }
}