objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Requirements (MRD)</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Document_Description__c</fullName>
        <label>Document Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Upload_Date__c</fullName>
        <label>Upload Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>See workflow rule: DMD Upload</description>
        <inlineHelpText>If Box File ID and Box URL has a value, checkbox updates to 'True'</inlineHelpText>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOS_Requirements__mdt.object
<CustomObject>
    <description>Updated 5.14.19</description>
    <fields>
        <fullName>RequirementName__c</fullName>
        <label>Requirement Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional Appraisal Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Assets Verification Required</fullName>
                </value>
                <value>
                    <fullName>Additional Lien Information</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Application Required for All Parties on Title</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1st</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 2nd</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Cert of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 1st Lender</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 2nd Lender</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 3rd Lender</fullName>
                </value>
                <value>
                    <fullName>Closing Agent Prelim / Title Report</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Condo Rider Executed</fullName>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Custom MAD Cap</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EOS Requirements</label>
    <pluralLabel>EOS Requirements</pluralLabel>
</CustomObject>

classes/LeadUploadDMD.cls
/**
 * Created by Carolina Veliz on 5/31/2019.
 */

public with sharing class LeadUploadDMD {

    public Document_MetaData__c theDMD  {get;set;}
    public ContentVersion theDocument  {get;set;}
    public transient blob theBlob  {get;set;}
    public string FileNameToAttach {get;set;}
    private final id theLeadId;
    public string selectedValue { get; set; }

    public List<SelectOption> conditionList{
        get {
            conditionList = new List<SelectOption>();
            conditionList.add(new SelectOption('-None-','-None-'));

            List<EOS_Requirements__mdt> eosReq = [select label, RequirementName__c
            from EOS_Requirements__mdt
            order by RequirementName__c];
            if (eosReq.size()>0 ){
                Map<string,string>  reqMDs = new Map<string,string>();
                for ( EOS_Requirements__mdt r : eosReq)
                {
                    reqMDs.put(r.label, r.RequirementName__c);
                }

                for(Current_Conditions__c item : [SELECT id, name, code__c, Requirement__c FROM Current_Conditions__c WHERE Lead__c =: theLeadid]){
                    string reqMD = reqMDs.get(item.code__c);
                    if (string.isNotEmpty(reqMD)) {
                        conditionList.add(new SelectOption(item.id, reqMD));
                    }
                    else{
                        if(item.Code__c == null || item.Code__c == '') {
                            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Requirement: '+ item.Requirement__c + ' code is missing.');
                            ApexPages.addMessage(msg);
                        } else {
                            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Requirement: '+ item.Requirement__c + ' Code: ' + item.code__c + ', does not exist in EOS Requirement' );
                            ApexPages.addMessage(msg);
                        }
                    }
                }
            }
            return conditionList;
        }
        set;
    }

    public LeadUploadDMD(ApexPages.StandardController sc){
        theDMD = new  Document_MetaData__c ();
        theLeadId = System.currentPagereference().getParameters().get('LeadId');

        this.theDMD  = (Document_MetaData__c)sc.getRecord();
        theDMD.Lead__c = theLeadId;
        theDocument = new ContentVersion();

    }

    public PageReference save(){
        List<ContentDocumentLink> contentDocumentLink = [SELECT ContentDocumentId, LinkedEntityId
        FROM ContentDocumentLink
        WHERE LinkedEntityId =: theLeadId];
        Set<Id> contentDocIds = new Set<Id>();
        for(ContentDocumentLink cdl : contentDocumentLink) {
            contentDocIds.add(cdl.ContentDocumentId);
        }
        ContentDocument contentDocument = [SELECT Id, CreatedDate FROM ContentDocument
        WHERE Id IN : contentDocIds
        ORDER BY CreatedDate DESC LIMIT 1];
        system.debug('contentDocument ' + contentDocument);

        //if(String.isNotEmpty(FileNameToAttach)) {
        theDMD.Upload_Date__c = system.now();
        theDMD.Uploaded__c = true;
        if (string.isEmpty(theDMD.Document_Description__c))
            theDMD.Document_Description__c = FileNameToAttach;
        if (selectedValue != '-None-') {
            theDMD.Requirement__c = selectedValue;
        }
        if(theDMD.Requirement__c == null) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Requirement must be selected to upload a document.');
            ApexPages.addMessage(msg);
            return null;
        }
        insert theDMD;
        //ContentDocumentLink cdlToDelete = new ContentDocumentLink();
        for(ContentDocumentLink cdl : contentDocumentLink) {
            if(cdl.ContentDocumentId == contentDocument.Id) {
                //cdlToDelete.Id = cdl.Id;
                ContentDocumentLink newCDL = new ContentDocumentLink();
                newCDL.ShareType = 'V';
                newCDL.Visibility = 'AllUsers';
                newCDL.LinkedEntityId = theDMD.Id;
                newCDL.ContentDocumentId = contentDocument.Id;

                if(!test.isRunningTest()) {
                    insert newCDL;
                }
            }
        }
        //delete cdlToDelete;
        return new PageReference('/' + theLeadId);

        /*   theDocument.VersionData = theBlob;
           system.debug('theBlob: ' + theBlob);
           system.debug('theDocument.VersionData: ' + theDocument.VersionData);

           theDocument.ContentLocation = 'S';
           theDocument.Title = FileNameToAttach;
           theDocument.PathOnClient = FileNameToAttach;
           //insert theDocument;*/

        //Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :theDocument.Id].ContentDocumentId;
        //    ContentDocumentLink cdl = new ContentDocumentLink();
        // cdl.ContentDocumentId = conDoc;
        //   cdl.LinkedEntityId = theDMD.Id;
        //  cdl.ShareType = 'V';
        // cdl.Visibility = 'AllUsers';
        //if( !test.isRunningTest())
        // insert cdl;
        // return new PageReference('/' + theDMD.Lead__c);
        /*}
        else if(theBlob == null){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Please select a file to upload.');
                ApexPages.addMessage(msg);
                return null;
        }*/


        /*  }else{
              ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Please select a file.');
              ApexPages.addMessage(msg);
              return null;
          }*/
        //return null;
        //   return new PageReference('/' + theLeadId);
    }

    public PageReference cancel(){
        return new PageReference('/' + theLeadid );
    }
}