objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prevent_Rollback_from_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent if task is in status completed, not moved back to any other status</description>
        <label>Prevent Rollback from Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectTaskStatusUpdate.cls
global class ProjectTaskStatusUpdate implements Database.Batchable<sObject> {   
    
    global List <String> codes = new List <String> {'T10011','T10009','T10201','T10017','T10080','T10092','T10157','T10172','T10180','T10013','T10186','T10015','T10190','T10104'};
    global List <String> stages = new List <String> {'Funded Won', 'Closed Won', 'Post-Closing', 'Closed Lost'};
    global String idt = 'a4wP00000005H9A';
        
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        String query = 'select Completed__c, Status__c, requirement__r.Status__c, Code__c, Prevent_Rollback_from_Complete__c from Project_Task__c where Status__c = null and opportunity__r.stagename not in :stages';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List <Project_Task__c> tasks) {
        
        for (Project_Task__c task: tasks){
            
            if(codes.contains(task.Code__c)){
                task.Prevent_Rollback_from_Complete__c = true;
            }
    
            if(task.Requirement__r.Status__c == 'Waived'){
                task.Status__c = 'Waived';
            }
            else if (task.Completed__c){        
                task.Status__c = 'Completed';
            }
            else{        
                task.Status__c = 'In Progress';
            }
            System.debug(task);
        }
        
        update tasks;
    }

    global void finish(Database.BatchableContext bc) {
       
    }    
    
}