objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Code__c</fullName>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Aged</fullName>
                    <isActive>false</isActive>
                    <label>Aged</label>
                </value>
                <value>
                    <fullName>Decline - Credit/Foreclosure Issues</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Credit/Foreclosure Issues</label>
                </value>
                <value>
                    <fullName>Decline - Insufficient Down Payment/Income</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Insufficient Down Payment/Income</label>
                </value>
                <value>
                    <fullName>Decline - Not in Geography</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Not in Geography</label>
                </value>
                <value>
                    <fullName>Decline - Property</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Property</label>
                </value>
                <value>
                    <fullName>Decline - Purchase Offer not Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Purchase Offer not Accepted</label>
                </value>
                <value>
                    <fullName>Decline - Rental or Second Home</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Rental or Second Home</label>
                </value>
                <value>
                    <fullName>Decline - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Decline - Unknown</label>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                    <isActive>false</isActive>
                    <label>Unresponsive</label>
                </value>
                <value>
                    <fullName>Withdraw - Already has Lender</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Already has Lender</label>
                </value>
                <value>
                    <fullName>Withdraw - Not Buying Home</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Not Buying Home</label>
                </value>
                <value>
                    <fullName>Withdraw - Prefers Another Product</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Prefers Another Product</label>
                </value>
                <value>
                    <fullName>Withdraw - Too Complicated</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Too Complicated</label>
                </value>
                <value>
                    <fullName>Withdraw - Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Withdraw - Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Applicant__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RequirementsControllerTest.cls
/************************************************************************************
 Apex Class Name     : RequirementsControllerTest
 Version             : 1.0
 Created Date        : 20th Jan 2019
 Function            : Test Class for RequirementsController class
 Author              : Neeraja Cherukuri
 
 Modification Log    :
* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Neeraja Cherukuri            01/20/2019                Original Version
* Jason Sun                    08/26/2019                Updated requirements name and opportunity names
*************************************************************************************
*/
@isTest
private class RequirementsControllerTest
{  
  @isTest static void test_method_one() 
    {
	//TO-DO: Find out if there is another proper HTTP mock to use.  Maybe this is calling out to Delighted?
	Test.setMock(HttpCalloutMock.class, new UnisonRequirementUpsertHttpCalloutMock());                 
    Opportunity opp = new Opportunity();
        opp.Name = 'Tiest opp 436342';
        opp.StageName = 'Introduction';
        opp.CloseDate = Date.today();
        opp.Qualifies_for_New_HomeOwner_Pricing__c = false;
        opp.Estimated_Funding_Amount__c = 1000;
                    opp.Estimated_Funding_Amount__c = 2;
            opp.Pricing_Ratio__c = 2;
            opp.Final_OAV_Calculation__c = 4;
        insert opp;
        
        /*opp.StageName = 'Investment Due Diligence';
       // opp.Loss_Type__c = 'Withdrawn';
      //  opp.Loss_Reason_Code__c   = 'Appraisal value is below customer expectation';
       // opp.Personal_Credit_Report__c = pcr.Id;
       // opp.FeeManagment__c = fmc.Id;
        update opp;
        */
        Success_Factor__c sf1 = new Success_Factor__c();
        sf1.Opportunity__c = opp.ID;
        sf1.Success_Factor__c = 'DTI';
        sf1.Program__c = 'HO';
        
        Insert sf1;
        
        /*Success_Factor__c sf2 = new Success_Factor__c();
        sf2.Opportunity__c = opp.ID;
        sf2.Success_Factor__c = 'Credit';
        Insert sf2;*/
        

        Current_Conditions__c req1 = new Current_Conditions__c();
        //req1.Success_Factor__c = sf1.Id;
        req1.Requirement__c = '1040';
        req1.Opportunity__c = opp.id;
            req1.Code__c            = 'R1111';
            req1.Category__c        = 'Credit';
        	req1.Internal_vs_External__c = 'Internal';
        try {
            Insert req1;
        }
        catch(exception e)
        {}
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(req1);
        RequirementsController ext = new RequirementsController(sc);
        ext.getSuccessFactorValue();
        
       }
    @isTest static void test_method_two() 
    {
        //TO-DO: Find out if there is another proper HTTP mock to use for ConnectAPI/Chatter callouts
        Test.setMock(HttpCalloutMock.class, new UnisonRequirementUpsertHttpCalloutMock());         
        Opportunity opp = new Opportunity();
        opp.Name = 'Tiest Opp 49382';
        opp.StageName = 'Introduction';
        opp.CloseDate = Date.today();
        opp.Qualifies_for_New_HomeOwner_Pricing__c = false;
        opp.Estimated_Funding_Amount__c = 1000;
                            opp.Estimated_Funding_Amount__c = 2;
            opp.Pricing_Ratio__c = 2;
            opp.Final_OAV_Calculation__c = 4;
        insert opp;
        
       /* opp.StageName = 'Investment Due Diligence';
        update opp;*/
        
        Success_Factor__c sf1 = new Success_Factor__c();
       	//sf1.Opportunity__c = opp.ID;
        sf1.Success_Factor__c = 'OAV';
                sf1.Program__c = 'HO';
        Insert sf1;
       
        Current_Conditions__c req1 = new Current_Conditions__c();
        req1.Success_Factor__c = sf1.Id;
        req1.Requirement__c = '1065';
        req1.Opportunity__c = opp.id;
                    req1.Code__c            = 'R1111';
            req1.Category__c        = 'Credit';
        	req1.Internal_vs_External__c = 'Internal';

            Insert req1;


        ApexPages.StandardController sc = new ApexPages.StandardController(req1);
        RequirementsController ext = new RequirementsController(sc);
        ext.getSuccessFactorValue();
        
       }
}