objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been ordered by Origination Ops</description>
        <label>Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been received</description>
        <label>Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DMA_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in DocGen to include the Deferred Maintenance Addendum if &gt; 0</description>
        <inlineHelpText>Total count of all DMA records</inlineHelpText>
        <label>DMA Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been ordered by Origination Ops</description>
        <label>Home Inspection Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been received</description>
        <label>Home Inspection Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Authorized BE DTI</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <inlineHelpText>Manual entry for IA. Influences MAD Pct.</inlineHelpText>
        <label>Max Authorized LTV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <inlineHelpText>Manually entered percentage for OAV discount</inlineHelpText>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payment_Monthly_First_Mortgage__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Pulled from Application</inlineHelpText>
        <label>Payment Monthly First Mortgage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Program_Knowledge_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</description>
        <inlineHelpText>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</inlineHelpText>
        <label>Program Knowledge Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Report_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Report_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary_Appraised_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>DLRS</description>
        <inlineHelpText>The average of Final_Value from all Appraisal Objects associated with the Opportunity.</inlineHelpText>
        <label>Summary Appraised Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UnisonMasterNotificationsTest.cls
/**
 * Created by Eliot Rojas on 6/28/2019.
 */
@isTest
private with sharing class UnisonMasterNotificationsTest {

    @testSetup static void setup() {
        Account newAcc = new Account (Name='Test Account');
        insert newAcc;
        Id homeOwnerRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();

        Opportunity newOppty = new Opportunity();
        newOppty.Name = 'Test Opportunity';
        newOppty.AccountId = newAcc.Id;
        newOppty.StageName = 'Ready for Ops';
        newOppty.CloseDate = System.today();
        newOppty.Process_Program_Knowledge_Review__c = false;
        newOppty.RecordTypeId = homeOwnerRT;
        newOppty.Appraisal_Received__c = true;
        newOppty.Appraisal_Ordered__c = true;
        newOppty.Second_Appraisal_Ordered__c = true;
        newOppty.Second_Appraisal_Received__c = true;
        newOppty.Home_Inspection_Ordered__c = true;
        newOppty.Home_Inspection_Received__c = true;
        newOppty.Property_Report_Ordered__c = true;
        newOppty.Property_Report_Received__c = true;
        newOppty.DMA_Count__c = 3;
        newOppty.CloseDate = system.today() + 5;
        newOppty.Summary_Appraised_Value__c = 120;
        newOppty.OAV_Discount_Pct__c = 20;
        newOppty.Pricing_Ratio__c = 15.0;
        newOppty.Maximum_Authorized_DTI__c = 15.0;
        newOppty.Maximum_Authorized_LTV__c = 16.0;
        newOppty.Final_OAV_Calculation__c = 10.0;
        newOppty.Estimated_Funding_Amount__c = 110.0;
        newOppty.Maximum_Authorized_DTI__c = 15.0;
        newOppty.Maximum_Authorized_LTV__c = 16.0;
        newOppty.Payment_Monthly_First_Mortgage__c = 1.0;
        insert newOppty;

        Success_Factor__c SF = new Success_Factor__c();
        SF.Success_Factor__c = 'LTV';
        SF.Program__c = 'HO';
        SF.Opportunity__c = newOppty.Id;
        SF.Status__c = 'In Progress';
        insert SF;
    }

    @IsTest
    static void testBehaviorInsert_Requirement() {
        Opportunity myOpportunity = [SELECT Id, Name FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Success_Factor__c successFactor = [SELECT Id, Name, Opportunity__c FROM Success_Factor__c WHERE Opportunity__c =: myOpportunity.Id LIMIT 1];
        Current_Conditions__c newReq = new Current_Conditions__c();
        newReq.Opportunity__c = myOpportunity.Id;
        newReq.Code__c = 'R1048';
        newReq.Success_Factor__c = successFactor.Id;
        newReq.Status__c = 'Ready to Review';

        Test.startTest();
        insert newReq;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_Requirement() {
        Opportunity myOpportunity = [SELECT Id, Name FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Success_Factor__c successFactor = [SELECT Id, Name, Opportunity__c FROM Success_Factor__c WHERE Opportunity__c =: myOpportunity.Id LIMIT 1];
        Current_Conditions__c newReq = new Current_Conditions__c();
        newReq.Opportunity__c = myOpportunity.Id;
        newReq.Code__c = 'R1048';
        newReq.Success_Factor__c = successFactor.Id;
        newReq.Status__c = 'Ready to Review';
        insert newReq;

        Test.startTest();
        newReq.Status__c = 'Waived';
        update newReq;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_ProjectTask_Completed() {
        Opportunity myOpportunity = [SELECT Id, Name FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Success_Factor__c successFactor = [SELECT Id, Name, Opportunity__c FROM Success_Factor__c WHERE Opportunity__c =: myOpportunity.Id LIMIT 1];
        Current_Conditions__c newReq = new Current_Conditions__c();
        newReq.Opportunity__c = myOpportunity.Id;
        newReq.Code__c = 'R1048';
        newReq.Success_Factor__c = successFactor.Id;
        newReq.Status__c = 'Ready to Review';
        insert newReq;

        Project_Task__c pTask = new Project_Task__c();
        pTask.Opportunity__c = myOpportunity.Id;
        pTask.Name = 'TestPT2';
        pTask.Code__c = 'T10013';
        pTask.Requirement__c = newReq.Id;
        insert pTask;

        Test.startTest();
	/*Caro Veliz: BUS-155110073*/
        //pTask.Completed__c = true;
        pTask.Status__c = 'Completed';
        update pTask;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_SuccessFactor_Status() {
        Opportunity myOpportunity = [SELECT Id, Name FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Success_Factor__c successFactor = [SELECT Id, Name, Opportunity__c, Status__c FROM Success_Factor__c WHERE Opportunity__c =: myOpportunity.Id LIMIT 1];

        Test.startTest();
        successFactor.Status__c = '';
        update successFactor;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_SuccessFactor_Completed() {
        Opportunity myOpportunity = [SELECT Id, Name FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Success_Factor__c successFactor = [SELECT Id, Name, Opportunity__c, Status__c FROM Success_Factor__c WHERE Opportunity__c =: myOpportunity.Id LIMIT 1];

        Test.startTest();
        successFactor.Status__c = 'Completed';
        update successFactor;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_FieldChanges() {
        Opportunity myOpportunity = [SELECT Id, Name, StageName, MAD__c, Pricing_Ratio__c, Program_Floor__c, Estimated_Funding_Amount__c,
                UnisonProcessor__c, Investment_Analyst2__c, Final_OAV_Calculation__c, Wire_to_Agent_Date__c, Post_Close_Specialist__c, Sales_Director__c
        FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];

        Test.startTest();
        myOpportunity.MAD__c = 120;
        myOpportunity.Pricing_Ratio__c = 13;
        myOpportunity.Program_Floor__c = '';
        myOpportunity.Estimated_Funding_Amount__c = 1;
        myOpportunity.Wire_to_Agent_Date__c = system.today() + 2;
        myOpportunity.Final_OAV_Calculation__c = 122;
        myOpportunity.UnisonProcessor__c = UserInfo.getUserId();
        myOpportunity.Investment_Analyst2__c = UserInfo.getUserId();
        myOpportunity.Post_Close_Specialist__c = UserInfo.getUserId();
        myOpportunity.Sales_Director__c = UserInfo.getUserId();
        myOpportunity.Approval_Status__c = 'Approved';
        update myOpportunity;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorUpdate_FieldChanges2() {
        Opportunity myOpportunity = [SELECT Id, Name, StageName, MAD__c, Pricing_Ratio__c, Program_Floor__c, Estimated_Funding_Amount__c,
                UnisonProcessor__c, Investment_Analyst2__c, Final_OAV_Calculation__c, Wire_to_Agent_Date__c, Post_Close_Specialist__c, Sales_Director__c
        FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];

        Test.startTest();
        myOpportunity.Approval_Status__c = 'Denied';
        myOpportunity.Process_Program_Knowledge_Review__c = true;
        myOpportunity.StageName = 'Closed Lost';
        myOpportunity.Loss_Type__c = 'Declined';
        myOpportunity.Loss_Reason_Code__c = 'Bankruptcy';
        myOpportunity.Wire_to_Agent_Date__c = system.today();
        update myOpportunity;
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorInsert_StageChange() {
        Opportunity myOpportunity = [SELECT Id, Name, StageName, MAD__c, Pricing_Ratio__c, Program_Floor__c, Estimated_Funding_Amount__c,
                UnisonProcessor__c, Investment_Analyst2__c, Final_OAV_Calculation__c, Wire_to_Agent_Date__c, Post_Close_Specialist__c, Sales_Director__c, OwnerId
        FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];

        myOpportunity.StageName = 'Investment Due Dilligence';
        update myOpportunity;

        Test.startTest();
        UnisonMasterNotificationsWrapper.ManageNotificationsForOpportunityStage(new List<Opportunity> { myOpportunity });
        Test.stopTest();
    }
    @IsTest
    static void testStipulations() {
        Opportunity myOpportunity = [SELECT Id, Name, StageName, MAD__c, Pricing_Ratio__c, Program_Floor__c, Estimated_Funding_Amount__c,
                UnisonProcessor__c, Investment_Analyst2__c, Final_OAV_Calculation__c, Wire_to_Agent_Date__c, Post_Close_Specialist__c, Sales_Director__c, OwnerId
        FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];

        UnisonMasterNotifications.ManageNotificationsForStipulations(myOpportunity.id,'Post to chatter');

    }


}