objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Requirements (MRD)</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EOS_Requirements__mdt.object
<CustomObject>
    <description>Updated 5.14.19</description>
    <fields>
        <fullName>RequirementName__c</fullName>
        <label>Requirement Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional Appraisal Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Assets Verification Required</fullName>
                </value>
                <value>
                    <fullName>Additional Lien Information</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Application Required for All Parties on Title</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1st</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 2nd</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Cert of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 1st Lender</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 2nd Lender</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 3rd Lender</fullName>
                </value>
                <value>
                    <fullName>Closing Agent Prelim / Title Report</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Condo Rider Executed</fullName>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Custom MAD Cap</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OAV</fullName>
                    <default>true</default>
                    <label>OAV</label>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Net Cash to Partner</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EOS Requirements</label>
    <pluralLabel>EOS Requirements</pluralLabel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RequirementsController.cls
/************************************************************************************
 Apex Class Name     : RequirementsController
 Version             : 1.0
 Created Date        : 8th Jan 2019
 Function            : Controller class for VF page (RequirementPredefault). 
                       This Class has business logic and executes it.
 Author              : Neeraja Cherukuri
 
 Modification Log    :
* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Neeraja Chekuri            01/8/2018                Original Version
* Jason Sun            		08/29/2018                Fixed out-of-control queries returning > 50k records
*************************************************************************************
*/

public without sharing class RequirementsController{
    public Current_Conditions__c req{get;set;}
    public RequirementsController(ApexPages.StandardController controller)
    {
       req = new Current_Conditions__c();
       this.req = (Current_Conditions__c)controller.getRecord();
       String successFactorName = 'DTI'; //TO-DO:  Why is this hard coded???
       List<Success_Factor__c> lstSF = new List<Success_Factor__c>();
    
		if(req.Opportunity__c != null || req.Lead__c != null)
		{
            if(req.Opportunity__c != NULL){
				lstSF = [SELECT Id FROM Success_Factor__c WHERE Opportunity__c =: req.Opportunity__c
                                       AND Success_Factor__c =: successFactorName LIMIT 1];
            }
            else if(req.Lead__c != NULL){
				lstSF = [SELECT Id FROM Success_Factor__c WHERE Lead__c =: req.Lead__c
                                       AND Success_Factor__c =: successFactorName LIMIT 1];                
            }
		}
		if(lstSF.size() > 0)
		{
			req.Success_Factor__c = lstSF[0].Id;     
		}        
    }
    public void getSuccessFactorValue()
    {
        String successFactorName = 'DTI'; //TO-DO:  Why is this hard coded???
        Map<String, String> mapPicklistValues = new Map<String, String>();
        Map<String, EOS_Requirements__mdt> mapEOSReq = new Map<String, EOS_Requirements__mdt>();
        
        //fetching label and API names for Requirement__c picklist field. 
        for( Schema.PicklistEntry v : Current_Conditions__c.Requirement__c.getDescribe().getPicklistValues()) 
        { 
            mapPicklistValues.put(v.getValue(),v.getLabel());
        }
        //fetching details from EOS Custom Metadata
        for(EOS_Requirements__mdt objMDT : [SELECT MasterLabel, DeveloperName, RequirementName__c, Success_Factor__c FROM EOS_Requirements__mdt WHERE RequirementName__c=: mapPicklistValues.get(req.Requirement__c)])
        {
            mapEOSReq.put(objMDT.RequirementName__c, objMDT);
        }
        
       List<Success_Factor__c> lstSF = new List<Success_Factor__c>();
       if(req.Opportunity__c != null || req.Lead__c != null)
       {
           system.debug('*******req.Requirement__c*******'+req.Requirement__c);
           if(mapEOSReq.containsKey(mapPicklistValues.get(req.Requirement__c)))
           {
                if(req.Opportunity__c != NULL){
                	lstSF = [SELECT Id FROM Success_Factor__c WHERE Opportunity__c =: req.Opportunity__c
                                       AND Success_Factor__c =: mapEOSReq.get(mapPicklistValues.get(req.Requirement__c)).Success_Factor__c LIMIT 1];    
                }    
                else if(req.Lead__c != NULL){
                	lstSF = [SELECT Id FROM Success_Factor__c WHERE Lead__c=: req.Lead__c
                                       AND Success_Factor__c =: mapEOSReq.get(mapPicklistValues.get(req.Requirement__c)).Success_Factor__c LIMIT 1];                   
                }                
           }
           System.debug('*******lstSF*******'+lstSF);
           //Checking if the List size is greater than zero
           if(lstSF.size() > 0)
           {
               req.Success_Factor__c = lstSF[0].Id;
               req.Code__c = mapEOSReq.containsKey(mapPicklistValues.get(req.Requirement__c))? mapEOSReq.get(mapPicklistValues.get(req.Requirement__c)).DeveloperName :null;
           }
           else
           {	
               if(req.Opportunity__c != NULL){
					lstSF = [SELECT Id FROM Success_Factor__c WHERE Opportunity__c =: req.Opportunity__c AND Success_Factor__c =: successFactorName LIMIT 1];                   
               }
               else if(req.Lead__c != NULL){
                   lstSF = [SELECT Id FROM Success_Factor__c WHERE Lead__c =: req.Lead__c AND Success_Factor__c =: successFactorName LIMIT 1];                   
               }
               if(lstSF.size() > 0)
               {
                   req.Success_Factor__c = lstSF[0].Id;   
                   req.Code__c = mapEOSReq.containsKey(mapPicklistValues.get(req.Requirement__c))? mapEOSReq.get(mapPicklistValues.get(req.Requirement__c)).DeveloperName :null;
               }                        
           }
        }
    }

}