objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Who is the applicant?</inlineHelpText>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DMA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DMA</label>
        <referenceTo>DMA__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>Urgent Property Fix</fullName>
                    <label>Gather Information on Urgent Property Fix</label>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Data Request or Stipulation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Requirement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Data Request</fullName>
                </value>
                <value>
                    <fullName>Stipulation</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DMA__c.object
<CustomObject>
    <fields>
        <fullName>Inspection_Date__c</fullName>
        <label>Inspection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>DMAs</relationshipLabel>
        <relationshipName>DMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_Number__c</fullName>
        <label>Page Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>DMAs</relationshipLabel>
        <relationshipName>DMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Pages__c</fullName>
        <label>Total Number of Pages</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <displayFormat>DMA-{000000}</displayFormat>
        <label>DMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DMA_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in DocGen to include the Deferred Maintenance Addendum if &gt; 0</description>
        <inlineHelpText>Total count of all DMA records</inlineHelpText>
        <label>DMA Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA_Required_f_del__c</fullName>
        <formula>IF (  DMA_Count__c   &gt; 0, TRUE, FALSE)</formula>
        <inlineHelpText>Underwriting or Ops has determined DMA is required for the file.</inlineHelpText>
        <label>DMA Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Close_Home_Inspection_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A Stipulation will be created once the Check is being checked.</description>
        <label>Post Close Home Inspection Check</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DMATriggerHandler.cls
/*****************************************************************
 *   ------------------------------------------------------------------------
 *  Author: Raga Sindhu
 *  Create date:  Dec 17 2018
 *  Details
 *  -------------------------------------------------------------------------
 *  Apex class to handle all creating Requirements +Project Tasks 
 *  Update History
 *  ----------------------------------------------------------------------------
 *  Neeraja Cherukuri 4/12/2019-->Updated onAfterInsert + onAfterUpdate Methods.
 * ---------------------------------------------------------------------------
 ************************************************************************************/


public class DMATriggerHandler
{
    public static boolean createdDMAReqflag = false;
    public static String TASK_CODE_801 = 'Task-081';
    public static String TASK_CODE_802 = 'Task-082';
    public static String TASK_CODE_803 = 'Task-083';
    public static String TASK_CODE_804 = 'Task-084';

    public static String TASK_Name_1 = 'Request documentation of completion and/or payment confirmation';
    public static String TASK_Name_2 = 'Receive documentation of completion and/or payment confirmation';
    public static String TASK_Name_3 = 'Request contractor bid for escrow holdback';
    public static String TASK_Name_4 = 'Upload contractor bid for escrow holdback';

    public static void onbeforeInsert(List<DMA__c> dmalist)
    {
        set<Id> oppids  = new set<Id>();
        for(DMA__c dopp: dmalist) {
            if(dopp.Opportunity__c != Null) {
                oppids.add(dopp.opportunity__c);
            }
        }

        if(oppids.size() > 0){
            Map<Id, DMA__c> dmamap = new Map<Id, DMA__c>();
            for(DMA__c dma : [Select Id,Opportunity__c, Inspection_Date__c, Total_Number_of_Pages__c, lastmodifieddate,createddate  from DMA__c where Opportunity__c =: oppids]) {
                if(!dmamap.keyset().contains(dma.Opportunity__c)){
                    dmamap.put(dma.Opportunity__c,dma);
                }else {
                    DMA__c tempdma = dmamap.get(dma.Opportunity__c);
                    system.debug('dma.createddate: '+dma.createddate);
                    system.debug('tempdma.createddate: '+tempdma.createddate);
                    if(dma.createddate < tempdma.createddate){
                        dmamap.put(dma.Opportunity__c,dma);
                    }
                }
            }

            if(dmamap.keyset().size() > 0){
                for(DMA__c dopp: dmalist) {
                    if(dmamap.keyset().contains(dopp.Opportunity__c) && dmamap.get(dopp.Opportunity__c) != Null){
                        if(dmamap.get(dopp.Opportunity__c).Inspection_Date__c != Null) {
                            dopp.Inspection_Date__c  =  dmamap.get(dopp.Opportunity__c).Inspection_Date__c;
                        }
                        if(dmamap.get(dopp.Opportunity__c).Total_Number_of_Pages__c != Null) {
                            dopp.Page_Number__c      =  dmamap.get(dopp.Opportunity__c).Total_Number_of_Pages__c;
                        }
                    }
                }
            }
        }
    }

   /* public static void onAfterInsert(List<DMA__c> lstDMA)
    {
        Set<Id> oppIds  = new Set<Id>();
        Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>();
        Map<Id, Integer> mapOptyId_DMACount = new Map<Id, Integer>();

        for(DMA__c objDMA: lstDMA)
        {
            if(objDMA.Opportunity__c != Null)
            {
                oppIds.add(objDMA.opportunity__c);
            }
        }
        System.debug('This is the size of the oppIds: '+ oppIds.size());
        if(oppIds.size()>0)
        {
            for(Opportunity objOpty : [ SELECT Id, DMA_Required_f_del__c, DMA_Count__c, Post_Close_Home_Inspection_Check__c, (select Id from DMAs__r) FROM Opportunity WHERE Id IN: oppIds] )
            {
                mapOpportunities.put(objOpty.Id, objOpty);
                Integer i = 0;
                for(DMA__c objD :  objOpty.DMAs__r)
                {
                    i++;
                }
                mapOptyId_DMACount.put(objOpty.Id, i);
            }
            //mapOpportunities = new Map<Id, Opportunity>([SELECT Id, DMA_Required_f_del__c, DMA_Count__c, Post_Close_Home_Inspection_Check__c FROM Opportunity WHERE Id IN: oppIds]);    
        }

        List<Current_Conditions__c> lstRequirements = new List<Current_Conditions__c>();
        // Query giving no rows for assignment to SObject
        //Id successFactoryId = [SELECT Id FROM Success_Factor__c WHERE Success_Factor__c =: 'Post-Closing' LIMIT 1].Id;
        // Start Change
        Success_Factor__c[] successFactories = [SELECT Id FROM Success_Factor__c WHERE Success_Factor__c = 'Post-Closing' LIMIT 1];
        if(successFactories.size()>0) {
            Id successFactoryId = successFactories[0].id;

            for(DMA__c objDMA: lstDMA)
            {

                if(objDMA.Opportunity__c != Null  && mapOptyId_DMACount.get(objDMA.Opportunity__c) == 1 )
                {
                    Current_Conditions__c objRequirements = new Current_Conditions__c();
                    objRequirements.Opportunity__c = objDMA.Opportunity__c;
                    objRequirements.Requirement__c = 'DMA Required';
                    objRequirements.Success_Factor__c = successFactoryId;
                    objRequirements.DMA__c  = objDMA.Id;
                    objRequirements.Type__c  = 'Stipulation';
                    objRequirements.Applicant_Type__c = 'Applicant';
                    objRequirements.Category__c = 'Home Condition';
                    objRequirements.Code__c  = 'CON-0206';
                    objRequirements.Internal_vs_External__c  = 'External';

                    // objRequirements.Assigned_To__c = 'TS';


                    lstRequirements.add(objRequirements);
                }

            }
            //End Change
        }
        System.debug('====lstRequirements=='+lstRequirements);
        if(lstRequirements.size()>0)

        {
            // createdDMAReqflag = True;
            //Insert lstRequirements;
        }
        //createProjectTasks(lstDMA, null);
    }*/

    /*
    public static void onAfterUpdate(List<DMA__c> lstDMA,Map<Id,DMA__c> oldMap)
    {
        createProjectTasks(lstDMA, oldMap);
    }

    public static void createProjectTasks(List<DMA__c> lstDMA,Map<Id,DMA__c> oldMap)
    {
        Set<Id> oppIds  = new Set<Id>();
        Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>();
        Map<Id, Integer> mapOptyId_DMACount = new Map<Id, Integer>();
        Map<String, Current_Conditions__c > mapReqName_ReqId = new Map<String, Current_Conditions__c >();
        List<Id> reqIds  = new List<Id>();
        Set<String> setPTNames = new Set<String>();

        for(DMA__c objDMA: lstDMA)
        {
            if(oldMap != null && objDMA.Urgent_Fix_Type__c   != oldMap.get(objDMA.Id).Urgent_Fix_Type__c)
            {
                if(objDMA.Opportunity__c != Null)
                {
                    oppIds.add(objDMA.opportunity__c);
                }
            }
            else
            {
                if(objDMA.Opportunity__c != Null)
                {
                    oppIds.add(objDMA.opportunity__c);
                }
            }
        }
        System.debug('=========+oppIds'+oppIds);
        for(Project_Task__c objPT  : [SELECT Id, Name FROM Project_Task__c WHERE Opportunity__c IN: oppIds])
        {
            setPTNames.add(objPT.Name);
        }
        System.debug('=====setPTNames==='+setPTNames);
        System.debug('=====setPTNames size==='+setPTNames.size());
        List<Id> lstreq = new List<Id>();
        Map<Id, Id> mapOptyId_ReqId = new Map<Id, Id>();
        for(Current_Conditions__c objReq: [Select Id, Requirement__c, Opportunity__c ,Opportunity__r.UnisonProcessor__c
        FROM Current_Conditions__c
        WHERE Opportunity__c in :oppIds])
        {
            if(objReq.Requirement__c == 'Urgent Property Fix')
            {
                lstreq.add(objReq.id);
                mapOptyId_ReqId.put(objReq.Opportunity__c, objReq.Id);
            }
        }
        System.debug('=========+lstreq'+lstreq);
        System.debug('=========mapOptyId_ReqId==='+mapOptyId_ReqId);

        List<Project_Task__c> lstProjectTasksForInsert = new List<Project_Task__c>();


        for(DMA__c objDMA :[SELECT Id,Urgent_Fix_Type__c, Opportunity__c,  Opportunity__r.UnisonProcessor__c FROM DMA__c
        WHERE Opportunity__c IN: oppIds] ) // and Requirement__c  in:lstreq
        {
            if(objDMA.Urgent_Fix_Type__c == 'Pre-Close' && mapOptyId_ReqId.containsKey(objDMA.Opportunity__c))
            {
                if(!setPTNames.contains(TASK_Name_1))
                {
                    lstProjectTasksForInsert.add(ProjectTasksUtil.createProjectTasks(TASK_Name_1,TASK_CODE_801,objDMA.Opportunity__c,mapOptyId_ReqId.get(objDMA.Opportunity__c),objDMA.Opportunity__r.UnisonProcessor__c)); //
                    setPTNames.add(TASK_Name_1);
                }
                if(!setPTNames.contains(TASK_Name_2))
                {
                    lstProjectTasksForInsert.add(ProjectTasksUtil.createProjectTasks(TASK_Name_2,TASK_CODE_802,objDMA.Opportunity__c,mapOptyId_ReqId.get(objDMA.Opportunity__c),objDMA.Opportunity__r.UnisonProcessor__c));
                    setPTNames.add(TASK_Name_2);
                }

            }
            else if(objDMA.Urgent_Fix_Type__c == 'Escrow Holdback' && mapOptyId_ReqId.containsKey(objDMA.Opportunity__c))
            {
                if(!setPTNames.contains(TASK_Name_3))
                {
                    lstProjectTasksForInsert.add(ProjectTasksUtil.createProjectTasks(TASK_Name_3,TASK_CODE_803,objDMA.Opportunity__c,mapOptyId_ReqId.get(objDMA.Opportunity__c),objDMA.Opportunity__r.UnisonProcessor__c));
                    setPTNames.add(TASK_Name_3);
                }
                if(!setPTNames.contains(TASK_Name_4))
                {
                    lstProjectTasksForInsert.add(ProjectTasksUtil.createProjectTasks(TASK_Name_4,TASK_CODE_804,objDMA.Opportunity__c,mapOptyId_ReqId.get(objDMA.Opportunity__c),objDMA.Opportunity__r.UnisonProcessor__c));
                    setPTNames.add(TASK_Name_4);
                }
            }
        }

        System.debug('=========+lstProjectTasksForInsert'+lstProjectTasksForInsert);
        if(lstProjectTasksForInsert.size()>0)

        {
            createdDMAReqflag = True;
            // Insert lstProjectTasksForInsert;
        }

    } */
    


}