objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor_Type__c</fullName>
        <formula>TEXT(Success_Factor__r.Success_Factor__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Factor Type</label>
        <type>Text</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Additional_Applicant_Income__c</fullName>
        <label>Additional Income From Other Applicants</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Amount_f__c</fullName>
        <formula>BLANKVALUE(Summary_Appraised_Value__c, 0) * BLANKVALUE(OAV_Discount_Pct__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summary Appraised Value * OAV Discount Pct</inlineHelpText>
        <label>ZZZ OAV Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <inlineHelpText>Manually entered percentage for OAV discount</inlineHelpText>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Original_Agreed_Value__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <formula>IF( RecordTypeId = '012E00000002OH1', MIN(
                                      IF(ISBLANK(Appraised_Home_Value__c) || Appraised_Home_Value__c = 0, Home_Value__c , Appraised_Home_Value__c),
                                      IF(ISBLANK(Purchase_Price__c) || Purchase_Price__c = 0, 9999999999999999, Purchase_Price__c) 
                                     ),
IF(RecordTypeId= '012E00000002OHB', IF(ISBLANK(Appraised_Home_Value__c) || Appraised_Home_Value__c = 0,  Home_Value__c , Appraised_Home_Value__c - OAV_Discount_Amount__c), 9999999999999999)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original Agreed Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Opp_OAV_Lock_Screen_EXT.cls
/*****************************************************************
 *   ------------------------------------------------------------------------
 *  Author: Neeraja Cherukuri
 *  Create date:  March 17 2019
 *   Details
 *  -------------------------------------------------------------------------
 *  Apex Extension Class to accomodate Final OAV values.
 *   
 *  Update History
 *  ----------------------------------------------------------------------------
 *  Neeraja Cherukuri 4/12/2019--> Modified the OpportunityUtilityClass by addind new Methods for Closing+PostClosing+Passbook+SFGating.
 * ---------------------------------------------------------------------------
 ************************************************************************************/

public with sharing class Opp_OAV_Lock_Screen_EXT
{
    private final Id oppId;
    public Opportunity theOpp {get; set;} 
    public ApexPages.StandardController sc;
    public Opp_OAV_Lock_Screen_EXT(ApexPages.StandardController sc)
    {
        this.oppId = sc.getId(); 
        this.sc = sc;
            
        init();    
    }
    private void init()
    //Original_Agreed_Value__c,Appraised_Home_Value_f__c
    {      
        String query = 'SELECT Id,Additional_Applicant_Income__c,Purchase_Price__c,Final_OAV_Calculation__c,OAV_Discount_Pct__c, OAV_Discount_Amount_f__c, IA_OAV_Override__c FROM Opportunity WHERE Id=\'' + this.oppId + '\'LIMIT 1';
        this.theOpp = Database.query(query);
    }    
    public PageReference Save()
    {
        System.debug('===theOpp.IA_OAV_Override__c==='+theOpp.IA_OAV_Override__c);
        upsert theOpp;
        return sc.view();
    }
    
    public void updateclass(){
        
        //Start : Updating 'Final OAV' value with 'IA OAV Override' value
        //Jason Sun - 2019-09-06 - Commented this out because validRecordTypeIds is never even used again
        /*
        Set<Id> validRecordTypeIds = new Set<Id>();
        for(RecordType objRec : [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND (Name=:'HomeBuyer' OR Name =: 'HomeOwner')])
        {
            validRecordTypeIds.add(objRec.Id);
        }
        System.debug('===validRecordTypeIds=='+validRecordTypeIds);
        */       
    }
    public void doAction()
    {
        List<Current_Conditions__c>  lstReqWithOAV = new List<Current_Conditions__c>();
        lstReqWithOAV = [SELECT Id, Status__c from Current_Conditions__c WHERE Opportunity__c =: theOpp.Id 
                         AND Success_Factor_Type__c='OAV' AND (Status__c != 'Completed')];
        if(lstReqWithOAV.size() > 0)
        {
           ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'The OAV Success Factors Related Requirements needs to be Completed before calculating FINAL OAV .'));
        }
    }
}