objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSI_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSI Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>RSI Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RequestRSIController.cls
public class RequestRSIController {

    public boolean errormsg { get; set; }
    public Id recordid;
    public boolean dataexist {get;set;}
    public boolean datasaved {get;set;}
    public boolean datanotvalid {get;set;}
    public boolean dataupdate {get;set;}
    public String orderPropertyReports {get;set;}
    public String completeReportsTask {get;set;}
    public boolean isPropertyReportCompleted {get;set;}
    public List<Current_Conditions__c> reqlist {get;set;}
    public Project_Task__c prjtask {get;set;}
    public List<Project_Task__c> notifyPropertyReportTask {get;set;}


    public RequestRSIController(){
        system.debug('******inside constructor******');
        datasaved = false;
        isPropertyReportCompleted = false;
        dataexist = false;
        datanotvalid = false;
        errormsg = false;
        recordid = ApexPages.currentPage().getParameters().get('Id');
        orderPropertyReports = ApexPages.currentPage().getParameters().get('orderPropertyReport');
        completeReportsTask = ApexPages.currentPage().getParameters().get('completeReportsTask');
        system.debug('******recordid******'+recordid);
        reqlist = [select Id, Requirement__c, Reason__c from Current_Conditions__c
        where Opportunity__c =: recordid
        and Reason__c = Null and RSI_Eligible__c = True and Status__c = 'Document Received, In progress'];

        notifyPropertyReportTask = [select Id, Status__c, Requirement__c from Project_Task__c
        where Opportunity__c =: recordid AND Code__c = 'T10211'];
        system.debug('******reqlist******'+reqlist);
        if(reqlist != Null && reqlist.size() > 0){
            dataexist = true;
        }else{
            if(completeReportsTask != 'true') {
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'There are no requirements that needed to be updated'));
                errormsg = true;
            } else {
                if(notifyPropertyReportTask.isEmpty()) {
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'This task does not exist'));
                    errormsg = true;
                } else if(notifyPropertyReportTask[0].Status__c == 'Completed') {
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'Notify TS Property Reports are Ready to Order task is already completed'));
                    errormsg = true;
                    isPropertyReportCompleted = true;
                }
            }
        }
        system.debug('****errormsg***'+errormsg);
    }

    public void saveReq(){
        if(reqlist != Null && reqlist.size() > 0){
            for(Current_Conditions__c req : reqlist){
                if(req.Reason__c == Null){
                    datanotvalid = true;
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.ERROR,'Please fill all the Reasons'));
                    errormsg = true;
                    break;
                }

            }


            if(!datanotvalid){
                update reqlist;
                datanotvalid = false;
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.CONFIRM,'Reasons are successfully updated'));
                datasaved = true;
                errormsg = true;

            }
            datanotvalid = false;
            //return null;

        }
        //return null;
    }

    public void completeProjectTask() {
        system.debug('********recordid*******'+recordid);
        dataupdate = false;
        Current_Conditions__c rsireq = [Select Id, Requirement__c, Opportunity__c, (Select Id from Project_Tasks__r where Name IN ('Notify file is ready for RSI', 'Notify TS Property Reports are Ready to Order')) from Current_Conditions__c where Opportunity__c =: recordid AND Requirement__c = 'RSI Letter' limit 1];
        system.debug('********rsireq *******'+rsireq);
        if(!dataupdate){
            for(Project_Task__c ptask: rsireq.Project_Tasks__r) {
                /*Caro Veliz: BUS-155110073*/
                //prjtask.Completed__c  = True;
                ptask.Status__c = 'Completed';
            }

            if(rsireq.Project_Tasks__r != Null) {
                update rsireq.Project_Tasks__r;
                dataupdate = true;
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.CONFIRM,'"Notify file is ready for RSI" is Completed'));
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.CONFIRM,'"Notify TS Property Reports are Ready to Order" is Completed'));
            }

        }
    }

    public void propertyReportIsReady() {
        system.debug('********recordid*******'+recordid);
        dataupdate = false;
        Current_Conditions__c rsireq = [Select Id, Requirement__c, Opportunity__c, (Select Id from Project_Tasks__r where Name = 'Notify TS Property Reports are Ready to Order') from Current_Conditions__c where Opportunity__c =: recordid AND Requirement__c = 'RSI Letter' limit 1];
        system.debug('********rsireq *******'+rsireq);
        if(!dataupdate){
            for(Project_Task__c ptask: rsireq.Project_Tasks__r) {
                /*Caro Veliz: BUS-155110073*/
                //prjtask.Completed__c  = True;
                ptask.Status__c = 'Completed';
            }

            if(rsireq.Project_Tasks__r != Null) {
                update rsireq.Project_Tasks__r;
                dataupdate = true;
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.CONFIRM,'"Notify TS Property Reports are Ready to Order" is Completed'));
            }

        }
    }

    public void completeRSIOnly() {
        system.debug('********recordid*******'+recordid);
        dataupdate = false;
        Current_Conditions__c rsireq = [Select Id, Requirement__c, Opportunity__c, (Select Id from Project_Tasks__r where Name = 'Notify file is ready for RSI') from Current_Conditions__c where Opportunity__c =: recordid AND Requirement__c = 'RSI Letter' limit 1];
        system.debug('********rsireq *******'+rsireq);
        if(!dataupdate){
            for(Project_Task__c ptask: rsireq.Project_Tasks__r) {
                /*Caro Veliz: BUS-155110073*/
                //prjtask.Completed__c  = True;
                ptask.Status__c = 'Completed';
            }

            if(rsireq.Project_Tasks__r != Null) {
                update rsireq.Project_Tasks__r;
                dataupdate = true;
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.CONFIRM,'"Notify file is ready for RSI" is Completed'));
            }

        }
    }
}