objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Requirements (MRD)</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Upload_Date__c</fullName>
        <label>Upload Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>See workflow rule: DMD Upload</description>
        <inlineHelpText>If Box File ID and Box URL has a value, checkbox updates to 'True'</inlineHelpText>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadUploadDMD_Lightning.cls
public class LeadUploadDMD_Lightning {    
    @AuraEnabled public static String objectName {get;set;}
    @AuraEnabled public static String recordName {get;set;}
    
    @AuraEnabled
    public static Id createDocument(Document_MetaData__c theDMD, Id recordId, String objectType) {    
        try {
            List<ContentDocumentLink> contentDocumentLink = [SELECT ContentDocumentId, LinkedEntityId
                                                             FROM ContentDocumentLink
                                                             WHERE LinkedEntityId =: recordId];
            Set<Id> contentDocIds = new Set<Id>();
            for(ContentDocumentLink cdl : contentDocumentLink) {
                contentDocIds.add(cdl.ContentDocumentId);
            }
            ContentDocument contentDocument = [SELECT Id, CreatedDate FROM ContentDocument
                                               WHERE Id IN : contentDocIds
                                               ORDER BY CreatedDate DESC LIMIT 1];
            if(objectType == 'Lead') {
                theDMD.Lead__c = recordId;
            } else if (objectType == 'Opportunity') {
                theDMD.Opportunity__c = recordId;
            }
            theDMD.Upload_Date__c = system.now();
            theDMD.Uploaded__c = true;
            insert theDMD;
            
            for(ContentDocumentLink cdl : contentDocumentLink) {
                if(cdl.ContentDocumentId == contentDocument.Id) {
                    ContentDocumentLink newCDL = new ContentDocumentLink();
                    newCDL.ShareType = 'V';
                    newCDL.Visibility = 'AllUsers';
                    newCDL.LinkedEntityId = theDMD.Id;
                    newCDL.ContentDocumentId = contentDocument.Id;
                    
                    if(!test.isRunningTest()) {
                        insert newCDL;
                    }
                }
            }
            return theDMD.Id;
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage()); 
        }
    }
    
    @AuraEnabled
    public static String getRecordName(Id recordId) {
        Schema.sObjectType sObjType = recordId.getSObjectType();
        objectName = sObjType != null ? String.valueOf(sObjType) : '';
        recordName = '';
        if(objectName == 'Lead') {
            recordName = [SELECT Id, Name FROM Lead WHERE Id =: recordId LIMIT 1].Name;
        } else if(objectName == 'Opportunity') {
            recordName = [SELECT Id, Name FROM Opportunity WHERE Id =: recordId LIMIT 1].Name;
        }
        return recordName;
    }

    @AuraEnabled
    public static String getSObjectType(Id recordId) {
        Schema.sObjectType sObjType = recordId.getSObjectType();
        objectName = sObjType != null ? String.valueOf(sObjType) : '';
        return objectName;
    }
    
    @AuraEnabled
    public static List<Current_Conditions__c> getRequirements(Id recordId) {
        Schema.sObjectType sObjType = recordId.getSObjectType();
        objectName = sObjType != null ? String.valueOf(sObjType) : '';
        List<Current_Conditions__c> reqs = new List<Current_Conditions__c>();
        if(objectName == 'Lead') { 
            reqs = [SELECT Id, Name, Code__c, Requirement__c, Lead__c FROM Current_Conditions__c WHERE Lead__c =: recordId];
        } else if(objectName == 'Opportunity') {
            reqs = [SELECT Id, Name, Code__c, Requirement__c, Opportunity__c FROM Current_Conditions__c WHERE Opportunity__c =: recordId];
        }
        return reqs;
    }

    @AuraEnabled
    public static DMDUploadWrapper init(Id recordId) {
        DMDUploadWrapper wrapper = new DMDUploadWrapper();
        wrapper.recordName = getRecordName(recordId);
        wrapper.objectType = getSObjectType(recordId);
        wrapper.requirements = getRequirements(recordId);
        return wrapper;
    }

    public class DMDUploadWrapper {
        @AuraEnabled public Document_MetaData__c theDMD {get;set;}
        @AuraEnabled public List<Current_Conditions__c> requirements {get;set;}
        @AuraEnabled public String recordName {get;set;}
        @AuraEnabled public String objectType {get;set;}

        DMDUploadWrapper() {
            theDMD = new Document_MetaData__c();
            requirements = new List<Current_Conditions__c>();
            recordName = '';
            objectType = '';
        }
    }
}