objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Requirement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Application Package</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debt Reduction</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>HB Application Package</fullName>
                </value>
                <value>
                    <fullName>Home Condition</fullName>
                </value>
                <value>
                    <fullName>Income</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Investment Due Diligence</fullName>
                </value>
                <value>
                    <fullName>Liabilities</fullName>
                </value>
                <value>
                    <fullName>Lien</fullName>
                </value>
                <value>
                    <fullName>MAD</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
                <value>
                    <fullName>Property</fullName>
                    <label>Property Ownership</label>
                </value>
                <value>
                    <fullName>Rider</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Stage</fullName>
                    <label>Stage Tasks</label>
                </value>
                <value>
                    <fullName>Title</fullName>
                </value>
                <value>
                    <fullName>Unison Documents</fullName>
                </value>
                <value>
                    <fullName>Valuation</fullName>
                </value>
                <value>
                    <fullName>Verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
                <value>
                    <fullName>HB Closing Tasks</fullName>
                    <label>HB Closing Documents</label>
                </value>
                <value>
                    <fullName>Closing</fullName>
                    <label>HO Closing Documents</label>
                </value>
                <value>
                    <fullName>Offer Package</fullName>
                </value>
                <value>
                    <fullName>RSI Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1040</fullName>
                </value>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Application Required for All Parties on Title</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Third Appraisal</fullName>
                    <label>Appraisal - 3rd</label>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share Information</fullName>
                </value>
                <value>
                    <fullName>Bank Statement</fullName>
                </value>
                <value>
                    <fullName>Brokerage Statement</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Client must pay down mortgage</fullName>
                    <label>Client Must Pay Down Mortgage - 1st Lender</label>
                </value>
                <value>
                    <fullName>Client must pay down mortgage - 2nd Lender</fullName>
                    <label>Client Must Pay Down Mortgage - 2nd Lender</label>
                </value>
                <value>
                    <fullName>Client must pay down mortgage - 3rd Lender</fullName>
                    <label>Client Must Pay Down Mortgage - 3rd Lender</label>
                </value>
                <value>
                    <fullName>Client must pay off outstanding past due liability</fullName>
                    <label>Client Must Pay Off Outstanding Past Due Liability</label>
                </value>
                <value>
                    <fullName>Client must pay off specific liabilities</fullName>
                    <label>Client Must Pay Off Specific Liabilities</label>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Closing - Assignment of Unison Agreement</fullName>
                </value>
                <value>
                    <fullName>Closing - Closing Statement</fullName>
                </value>
                <value>
                    <fullName>Closing - Curative Grant Deeds</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing - Final Executed Closing Package</fullName>
                </value>
                <value>
                    <fullName>Closing - Memorandum of Unison Agreement</fullName>
                </value>
                <value>
                    <fullName>Offer Package</fullName>
                </value>
                <value>
                    <fullName>RSI Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentLinkTriggerHandler.cls
public class ContentDocumentLinkTriggerHandler{

    public static void onAfterInsert(List<ContentDocumentLink> newcdllist){
        List<ContentDocumentLink> cdllist = new List<ContentDocumentLink>();
        Set<Id> cId = new Set<Id>();
        Set<Id> oppids = new Set<Id>();
        List<Document_MetaData__c> dmdlist = new List<Document_MetaData__c>();
        System.debug('*****inside Trigger****');
        List<Opportunity> updopplist = new List<Opportunity>();
        for(ContentDocumentLink cdl: newcdllist){
            system.debug('*****cdl*******'+cdl);
            //String Id = cdl.LinkedEntityId;
            System.debug('****checking LinkedEntityId*****');
            if(cdl.LinkedEntityId != Null && String.valueOf(cdl.LinkedEntityId.getSobjectType()) == 'Opportunity') {
                cId.add(cdl.ContentDocumentId);
                oppids.add(cdl.LinkedEntityId);                                   
            }           
        }
        system.debug('*****cId*******'+cId);
        system.debug('*****oppids*******'+oppids);
        
        if(cId.size() > 0 && oppids.size() > 0){
            System.debug('**** Querying CDL for Title****'); 
            List<ContentDocumentLink> docList = [Select ContentDocumentId, linkedentityid, ContentDocument.Title 
                                                 from ContentDocumentLink 
                                                 Where ContentDocumentId =: cId and linkedentityid =: oppids];
           system.debug('******docList*****'+docList);
                                                      
               List<Current_Conditions__c> reqlist = [Select Id, Requirement__c, Opportunity__c from Current_Conditions__c where opportunity__c =: oppids];
                
                for(ContentDocumentLink cdl: docList){
                    for(Current_Conditions__c req: reqlist) {
                        
                        system.debug('******cdl*****'+cdl);
                        if(cdl.ContentDocument.Title.contains('ClosingDocuments') && req.Requirement__c == 'Closing') {
                                      
                            Document_MetaData__c d = new Document_MetaData__c();
                            d.Requirement__c           = req.Id;
                            d.Document_Type__c         = 'Closing Documents';
                            //d.Category__c              = 'Credit';
                            d.Opportunity__c           = req.Opportunity__c;
                            dmdlist.add(d);
            
                        }  else if(cdl.ContentDocument.Title.contains('HOOfferPackage') && req.Requirement__c == 'Offer Package') {
                                      
                            Document_MetaData__c d = new Document_MetaData__c();
                            d.Requirement__c           = req.Id;
                            d.Document_Type__c         = 'Offer Package';
                            //d.Category__c              = 'Credit';
                            d.Opportunity__c           = req.Opportunity__c;
                            dmdlist.add(d);
            
                        } else if(cdl.ContentDocument.Title.contains('RSI Letter') && req.Requirement__c == 'RSI Letter') {
                                      
                            Document_MetaData__c d = new Document_MetaData__c();
                            d.Requirement__c           = req.Id;
                            d.Document_Type__c         = 'RSI Letter';
                            //d.Category__c              = 'Credit';
                            d.Opportunity__c           = req.Opportunity__c;
                            dmdlist.add(d);
            
                        } else if(cdl.ContentDocument.Title.contains('HBCAP') && req.Requirement__c == 'CAP Completed') {
                                      
                            Document_MetaData__c d = new Document_MetaData__c();
                            d.Requirement__c           = req.Id;
                            d.Document_Type__c         = 'CAP Completed';
                            //d.Category__c              = 'Credit';
                            d.Opportunity__c           = req.Opportunity__c;
                            dmdlist.add(d);
            
                        } else if(cdl.ContentDocument.Title.contains('ClosingDocuments') && req.Requirement__c == 'HB Closing Tasks') {
                                      
                            Document_MetaData__c d = new Document_MetaData__c();
                            d.Requirement__c           = req.Id;
                            d.Document_Type__c         = 'Closing Documents';
                            //d.Category__c              = 'Credit';
                            d.Opportunity__c           = req.Opportunity__c;
                            dmdlist.add(d);
            
                        }
                   }  
                   
                   if(dmdlist.size() > 0) {
                       insert dmdlist;
                   }
                   
                   for(Document_MetaData__c d: dmdlist) {
                       if(cdl.ContentDocument.Title.contains('ClosingDocuments') && d.Document_Type__c == 'Closing Documents') {
                            ContentDocumentLink cd = new ContentDocumentLink();
                            cd.ContentDocumentId = cdl.ContentdocumentId;
                            cd.LinkedEntityId = d.id;
                            cd.ShareType = 'V';
                            cd.Visibility = 'AllUsers';
                            cdllist.add(cd);
                            
                            /*Opportunity opp = new Opportunity();
                            opp.Id = cdl.LinkedEntityid;
                            opp.Closing_Document_Created_Date_Time__c = system.Now();
                            updopplist.add(opp);  */  
                       } else if(cdl.ContentDocument.Title.contains('HOOfferPackage') && d.Document_Type__c == 'Offer Package') {
                            ContentDocumentLink cd = new ContentDocumentLink();
                            cd.ContentDocumentId = cdl.ContentdocumentId;
                            cd.LinkedEntityId = d.id;
                            cd.ShareType = 'V';
                            cd.Visibility = 'AllUsers';
                            cdllist.add(cd);
                            
                            /*Opportunity opp = new Opportunity();
                            opp.Id = cdl.LinkedEntityid;
                            opp.Closing_Document_Created_Date_Time__c = system.Now();   
                            updopplist.add(opp); */
                       } else if(cdl.ContentDocument.Title.contains('RSI Letter') && d.Document_Type__c == 'RSI Letter') {
                            ContentDocumentLink cd = new ContentDocumentLink();
                            cd.ContentDocumentId = cdl.ContentdocumentId;
                            cd.LinkedEntityId = d.id;
                            cd.ShareType = 'V';
                            cd.Visibility = 'AllUsers';
                            cdllist.add(cd);
                               
                       } else if(cdl.ContentDocument.Title.contains('HBCAP') && d.Document_Type__c == 'CAP Completed') {
                            ContentDocumentLink cd = new ContentDocumentLink();
                            cd.ContentDocumentId = cdl.ContentdocumentId;
                            cd.LinkedEntityId = d.id;
                            cd.ShareType = 'V';
                            cd.Visibility = 'AllUsers';
                            cdllist.add(cd);
                            
                           /* Opportunity opp = new Opportunity();
                            opp.Id = cdl.LinkedEntityid;
                            opp.Closing_Document_Created_Date_Time__c = system.Now(); 
                            updopplist.add(opp);   */
                       } else if(cdl.ContentDocument.Title.contains('ClosingDocuments') && d.Document_Type__c == 'Closing Documents') {
                            ContentDocumentLink cd = new ContentDocumentLink();
                            cd.ContentDocumentId = cdl.ContentdocumentId;
                            cd.LinkedEntityId = d.id;
                            cd.ShareType = 'V';
                            cd.Visibility = 'AllUsers';
                            cdllist.add(cd);
                            
                            /*Opportunity opp = new Opportunity();
                            opp.Id = cdl.LinkedEntityid;
                            opp.Closing_Document_Created_Date_Time__c = system.Now();
                            updopplist.add(opp);  */  
                       }
                   }
               } 
                   
           }           
           
               
       // system.debug('******updopplist*****'+updopplist);
        //system.debug('******cdllist*****'+cdllist);        
       /* if(updopplist.size()>0){
            update updopplist;
        } */
        
        if(cdllist.size() > 0){       
            insert cdllist;
        }             
    }

}