objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This provides the trade account related to the stipulation</description>
        <inlineHelpText>This provides the trade account related to the stipulation</inlineHelpText>
        <label>Trade Account</label>
        <referenceTo>LASERCA__Trade_Accounts__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Data Request or Stipulation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Requirement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Data Request</fullName>
                </value>
                <value>
                    <fullName>Stipulation</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EOS_Requirements__mdt.object
<CustomObject>
    <description>Updated 5.14.19</description>
    <fields>
        <fullName>RequirementName__c</fullName>
        <label>Requirement Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional Appraisal Requested</fullName>
                </value>
                <value>
                    <fullName>Additional Assets Verification Required</fullName>
                </value>
                <value>
                    <fullName>Additional Lien Information</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Application Required for All Parties on Title</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 1st</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 2nd</fullName>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Cert of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 1st Lender</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 2nd Lender</fullName>
                </value>
                <value>
                    <fullName>Client Must Pay Down Mortgage - 3rd Lender</fullName>
                </value>
                <value>
                    <fullName>Closing Agent Prelim / Title Report</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Condo Rider Executed</fullName>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Custom MAD Cap</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Data Request</fullName>
                    <default>true</default>
                    <label>Data Request</label>
                </value>
                <value>
                    <fullName>Stipulation</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EOS Requirements</label>
    <pluralLabel>EOS Requirements</pluralLabel>
</CustomObject>

classes/StipulationsHelper.cls
/**
 * Created by Carolina Veliz on 12/2/2019.
 */

global with sharing class StipulationsHelper {

    webservice static String newStipulations(string opportunityID,
            string tradeAcc,
            string tradeAccName,
            string code,
            string stipulation,
            boolean isSubordination


    ) {
        UnisonMasterNotifications.postStipulations = false;

        system.debug('****new stipulations****');
        system.debug('opportunityID');
        system.debug(opportunityID);
        system.debug('tradeAcc');
        system.debug(tradeAcc);
        system.debug('stipulation');
        system.debug(stipulation);
        system.debug('isSubordination');
        system.debug(isSubordination);

        string result='';

        current_conditions__c req;
        list<current_conditions__c> reqs;

        if (isSubordination){
            reqs = [
                    select id, name, status__c, code__c
                    from current_conditions__c
                    where Trade_Account__c = :tradeAcc and code__c = 'R1107' and status__c <> 'Waived' limit 1];
        }
        else {
            reqs = [
                    select id, name, status__c, code__c
                    from current_conditions__c
                    where Trade_Account__c = :tradeAcc and code__c <> 'R1107' and status__c <> 'Waived' limit 1];
        }




        if (reqs.size()>0) {req = reqs[0];}
        else{
            reqs = [
                    select id, name, status__c
                    from current_conditions__c
                    where Trade_Account__c = :tradeAcc and status__c = 'Waived' limit 1];
            if (reqs.size()>0) {req = reqs[0];}
        }

        if (req == null) {
            EOS_Requirements__mdt reqMetadata =[Select MasterLabel, RequirementName__c
            from EOS_Requirements__mdt
            where type__c = 'Stipulation' and RequirementName__c = :stipulation];

            if (reqMetadata != null){
                AddNewStipulation( opportunityID, tradeAcc, stipulation);
                result = 'Stipulation ['+ stipulation + '] for trade account [' + tradeAccName +'] was created.';
            }

        }
        else {
            if (req.status__c == 'Waived'){
                AddNewStipulation( opportunityID, tradeAcc, stipulation);
                result = 'Stipulation ['+ stipulation + '] for trade account [' + tradeAccName +'] was created, prior Stipulation is waived.';
            }
            /*else if (toBePaidOff == false){
                req.status__c = 'Waived';
                update req;
                result = 'Stipulation ['+ stipulation + '] for trade account [' + tradeAccName +'] was changed to waived.';
            }*/
            else {
                code = getCode(stipulation);
                if (string.isNotEmpty(code) &&  req.code__c != code ) {
                    req.code__c = code;
                    req.requirement__c = stipulation;
                    update req;
                    result = 'Stipulation ['+ stipulation + '] for trade account [' + tradeAccName +'] was updated.';
                }
            }
        }

        return result;
    }


    webservice static String waiveStipulations( string stipulationID ) {
        UnisonMasterNotifications.postStipulations = false;
        system.debug('****new stipulations****');
        system.debug('stipulation');
        system.debug(stipulationID);


        string result='nothing happened';

        list<current_conditions__c> reqs = [
                select id, name, requirement__c, status__c,
                        trade_account__r.name
                from current_conditions__c
                where id = :stipulationID and status__c <> 'Waived'];


        for( current_conditions__c req : reqs){
            req.status__c = 'Waived';
            result = 'Stipulation ['+ req.requirement__c + '] for trade account [' + req.trade_account__r.name +'] was waived.';
        }

        update reqs;

        return result;
    }
    webservice static string postToChatter( string post ) {
        return 'posted to chatter';

    }

    private static string getCode(string stipulation){
        List<EOS_Requirements__mdt> reqMetadataList =[Select MasterLabel, RequirementName__c
        from EOS_Requirements__mdt
        where type__c = 'Stipulation' and RequirementName__c = :stipulation limit 1];

        string code;
        if (reqMetadataList.size()>0){
            if (reqMetadataList[0].MasterLabel != null){
                code = reqMetadataList[0].MasterLabel;
            }
        }
        return code;
    }

    private static void AddNewStipulation(string opportuniID,
                                            string tradeAcc,
                                            string stipulation
                                            ){

        current_conditions__c req = new current_conditions__c();
        string code = getCode(stipulation);

        if (string.isNotEmpty(code)){
            req.code__c = code;
            req.Trade_Account__c = tradeAcc;
            req.opportunity__c = opportuniID;
            system.debug(req);
            if (!Test.isRunningTest()) 
                insert req;
        }
    }
    /*
    private static List<Current_Conditions__c> processStipulations(List<Current_Conditions__c> reqlist) {

        Map<string, Current_Conditions__c> existingReqsMap = new Map<string, Current_Conditions__c>();
        List<Current_Conditions__c> reqsFromOpp = new List<Current_Conditions__c>();
        List<Current_Conditions__c> reqToProcess = new List<Current_Conditions__c>();
        Set<string> opps = new set<string>();

        for (Current_Conditions__c req : reqlist) {
            if (req.Opportunity__c != null) {
                reqsFromOpp.add(req);
                opps.add(req.Opportunity__c);
            }
        }

        List<Current_Conditions__c> existingReqs = [
                select createddate, id, requirement__c, code__c, Type__c, status__c, Trade_Account__c, opportunity__c
                from current_conditions__c
                where opportunity__c in :opps
                and type__c = 'Stipulation'
                order by createddate
        ];

//Find if there is a
        for (Current_Conditions__c req : existingReqs) {
            existingReqsMap.put(req.opportunity__c + '-' + req.Trade_Account__c, req);
        }



        for (Current_Conditions__c req : reqlist) {
            if ((req.code__c == '__skuid') ||
                    (req.code__c == '__skuidWaive')) {

//If the request comes from Skuid, we need to find out if the stipulation already exists
                Current_Conditions__c tempReq = existingReqsMap.get(req.opportunity__c + '-' + req.Trade_Account__c);
                if (tempReq != null) {
                    req.id = tempReq.id;
                }

                if (req.code__c == '__skuid') {
                    string code = resMap.get(req.Requirement__c);
                    system.debug(code);
                    if (code != null) {
                        req.code__c = code;
                        reqToProcess.add(req);
                    }
                } else {
//The trade accounts that are not to be paid off, should waived their stipulations,
//so the stipulations must exist
                    if (tempReq != null) {
                        req.status__c = 'Waived';
                    }
                    reqToProcess.add(req);
                }
            } else {
                reqToProcess.add(req);
            }
        }


        system.debug('*** reqToProcess ***');
        system.debug(reqToProcess.size());
        system.debug(reqToProcess);
        return reqToProcess;
    }


    @TestVisible private static List<EOS_Requirements__mdt> getStipulations() {
        return [
                Select MasterLabel, RequirementName__c
                from EOS_Requirements__mdt
                where type__c = 'Stipulation'
        ];
    }
    */

}