objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_History__c.object
<CustomObject>
    <fields>
        <fullName>FICO__c</fullName>
        <label>FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Investor_Percentage__c</fullName>
        <label>Investor Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <label>Maximum Authorized DTI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <label>Maximum Authorized LTV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Histories</relationshipLabel>
        <relationshipName>Deal_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <label>Passbook Status</label>
        <type>TextArea</type>
    </fields>
    <label>Deal History</label>
    <nameField>
        <label>Deal History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Cash_to_Homeowner__c</fullName>
        <description>OIP -  Gross Transaction Fees - Waived Fees (if applicable) - Amount of Lien Paydown - 	
Sum of Debt to Be Paid Off</description>
        <formula>IF( Record_Type_Name__c = "HomeBuyer",  Estimated_Funding_Amount__c ,

(BLANKVALUE(Estimated_Funding_Amount__c, 0) - BLANKVALUE(Lien_Pay_Off_Sum__c, 0) - BLANKVALUE(Sum_of_Debt_to_be_Paid_Off__c, 0)- BLANKVALUE(Customer_Transaction_Fee__c, 0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>OIP -  Gross Transaction Fees - Waived Fees (if applicable) - Amount of Lien Paydown - 	
Sum of Debt to Be Paid Off</inlineHelpText>
        <label>Net Cash to Partner</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FICO__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <inlineHelpText>Lower of the two scores between the Applicant Credit Score (Median) and Co-Applicant Score (Median).</inlineHelpText>
        <label>FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the Estimated Home Value stated from customer or Unison AVM</description>
        <inlineHelpText>This is the Estimated Home Value stated from customer or Unison AVM</inlineHelpText>
        <label>Estimated Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Investor_Percentage__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <formula>ROUND((Estimated_Funding_Amount__c * Pricing_Ratio__c) /  Final_OAV_Calculation__c, 4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>(Pricing Ratio divided by OAV) x OIP</inlineHelpText>
        <label>Investor Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MAD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Max LTV; ELSE 1) Post-Close LTV if HB, or 2) MAX(Post-Close LTV, 70%) with a cap at 75% if HO</description>
        <inlineHelpText>This value defaults to the value in Maximum Authorized LTV. If Maximum Authorized LTV does not exist, for HO it is the larger % between Post-Close LTV and 70% with a cap at 75%, and for HB, it is Post-Close LTV.</inlineHelpText>
        <label>MAD %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_DTI__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Authorized BE DTI</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_Debt_Final__c</fullName>
        <formula>MAD__c * Final_OAV_Calculation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the dollar amount of the MAD. It is the MAD Percentage times the OAV.</inlineHelpText>
        <label>MAD Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Authorized_LTV__c</fullName>
        <inlineHelpText>Manual entry for IA. Influences MAD Pct.</inlineHelpText>
        <label>Max Authorized LTV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OAV_Discount_Pct__c</fullName>
        <inlineHelpText>Manually entered percentage for OAV discount</inlineHelpText>
        <label>OAV Discount Pct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity_Tracking_ID__c</fullName>
        <description>Unique identifier associated with Opportunity (FRX)</description>
        <displayFormat>FRX-{000000}</displayFormat>
        <inlineHelpText>Unique identifier associated with Opportunity (FRX)</inlineHelpText>
        <label>Application Tracking ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <defaultValue>IF( $RecordType.Name = 'HomeBuyer','N/A','Pending')</defaultValue>
        <inlineHelpText>Passbook may run once LTV, DTI, and Credit Success Factors are marked Completed</inlineHelpText>
        <label>Current Passbook Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                    <isActive>false</isActive>
                    <label>Exception</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                    <isActive>false</isActive>
                    <label>Reject</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_Program_Knowledge_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</description>
        <inlineHelpText>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</inlineHelpText>
        <label>Program Knowledge Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Requirements_Vs_SuccessFactor__mdt.object
<CustomObject>
    <description>Metadata that stores what Success Factor each Requirement is for.</description>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Requirements Vs SuccessFactor</label>
    <pluralLabel>Requirements Vs SuccessFactors</pluralLabel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SuccessFactorsTriggerPC.cls
public class SuccessFactorsTriggerPC {

    //Constants 
 
    public static void handleBeforeInsert(List<Success_Factor__c> newList){
        
       
    }
    
    public static void handleAfterInsert(List<Success_Factor__c> lstDMDs)
    {
        
       List<Current_Conditions__c> lstReqForUpdate  = new List<Current_Conditions__c> ();
        Current_Conditions__c  objNewRequirement;
        
        Map<String, String> cmdMap = new Map<String, String>();
        
        for(Requirements_Vs_SuccessFactor__mdt objMDT : getMetadata())
        {
            cmdMap.put(objMDT.MasterLabel, objMDT.Success_Factor__c);
        }
        
        System.debug('****objNewRequirement****'+objNewRequirement);
         System.debug('****lstReqForUpdate****'+lstReqForUpdate);
        System.debug('****cmdMap****'+cmdMap);     
    }
    
    public static void handleAfterUpdate(List<Success_Factor__c> newList, Map<Id, Success_Factor__c> oldMap)
    {
        Set<Id> sfoppids = new Set<Id>();
        List<Deal_History__c> deallist = new List<Deal_History__c>();
        for(Success_Factor__c sf: newList) {
            if(sf.Status__c != Null 
                && sf.Opportunity__c != Null 
                && oldMap.get(sf.Id).Status__c != Null 
                && oldMap.get(sf.Id).Status__c != sf.Status__c){
                sfoppids.add(sf.Opportunity__c);    
            }
        }  
        for(Opportunity opp: [Select Id,Home_Value__c,FICO__c,Final_OAV_Calculation__c,Investor_Percentage__c,
            Maximum_Authorized_Debt_Final__c,MAD__c,Maximum_Authorized_DTI__c,Maximum_Authorized_LTV__c,Opportunity_Tracking_ID__c,
            Estimated_Cash_to_Homeowner__c,OAV_Discount_Pct__c,Estimated_Funding_Amount__c,Process_Program_Knowledge_Review__c,
            Passbook_Status__c,Post_Close_BE_Ratio__c,Post_Close_LTV2__c,Pre_Close_BE_Ratio__c,Pre_Close_LTV2__c,Pricing_Ratio__c,
            Purchase_Price__c,StageName from Opportunity where Id =: sfoppids]) {
            
            Deal_History__c dealh = new Deal_History__c();
            dealh.Name                         = 'Deal History'+'-'+opp.Opportunity_Tracking_ID__c;
            dealh.Opportunity__c               = opp.Id;
            dealh.Estimated_OAV__c             = opp.Home_Value__c;
            dealh.FICO__c                      = opp.FICO__c;
            dealh.Final_OAV__c                 = opp.Final_OAV_Calculation__c;
            dealh.Investor_Percentage__c       = opp.Investor_Percentage__c;
            dealh.MAD_Amount__c                = opp.Maximum_Authorized_Debt_Final__c;
            dealh.MAD_Pct__c                   = opp.MAD__c;
            dealh.Maximum_Authorized_DTI__c    = opp.Maximum_Authorized_DTI__c;
            dealh.Maximum_Authorized_LTV__c    = opp.Maximum_Authorized_LTV__c;
            dealh.Net_Cash_to_Homeowner__c     = opp.Estimated_Cash_to_Homeowner__c;
            dealh.OAV_Discount_Pct__c          = opp.OAV_Discount_Pct__c;
            dealh.OIP__c                       = opp.Estimated_Funding_Amount__c;
            dealh.PKR_Done__c                  = opp.Process_Program_Knowledge_Review__c;
            dealh.Passbook_Status__c           = opp.Passbook_Status__c;
            dealh.Post_Close_DTI__c            = opp.Post_Close_BE_Ratio__c;
            dealh.Post_Close_LTV__c            = opp.Post_Close_LTV2__c;
            dealh.Pre_Close_DTI__c             = opp.Pre_Close_BE_Ratio__c;
            dealh.Pre_Close_LTV__c             = opp.Pre_Close_LTV2__c;
            dealh.Pricing_Ratio__c             = opp.Pricing_Ratio__c;
            dealh.Purchase_Price__c            = opp.Purchase_Price__c;
            dealh.Stage__c                     = opp.StageName;
            deallist.add(dealh);
        }
        
        if(deallist.size() > 0){
            insert deallist;
        }

        opportunityPassbook(newList, oldMap);
        UnisonMasterNotifications.ManageNotificationsForSuccessFactorStatusChanges(newList, oldMap);
    }  
    
    public static void handlebeforeUpdate(Map<Id, Success_Factor__c> newMap, Map<Id, Success_Factor__c> oldMap){
        
    }

    private static void opportunityPassbook(List<Success_Factor__c> newList, Map<Id, Success_Factor__c> oldMap) {
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        Set<Id> oppIds = new Set<Id>();

        for(Success_Factor__c sF : newList){
            if(sF.Success_Factor__c == 'Credit' || sF.Success_Factor__c == 'DTI' || sF.Success_Factor__c == 'LTV') {
                if(oldMap.get(sF.Id).Status__c == 'Completed' && (sF.Status__c != 'Blocked' || sF.Status__c != 'In Progress')){
                    if(sF.Opportunity__c != null) {
                        oppIds.add(sF.Opportunity__c);
                    }
                }
            }
        }

        for(Id optyId : oppIds) {
            Opportunity opp = new Opportunity(Id = optyId);
            opp.IA_Passbook_Override_Reasons__c = '';
            opp.IA_Passbook_Override__c = false;
            opp.Passbook_Status__c = 'Pending';
            oppsToUpdate.add(opp);
        }

        if(!oppsToUpdate.isEmpty()) {
            update oppsToUpdate;
        }
    }

    @TestVisible private static List<Requirements_Vs_SuccessFactor__mdt> getMetadata(){
        return [SELECT MasterLabel, Success_Factor__c FROM Requirements_Vs_SuccessFactor__mdt];
    }
}