objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor_Type__c</fullName>
        <formula>TEXT(Success_Factor__r.Success_Factor__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Factor Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Document_MetaData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UnisonAPITest.cls
@isTest
private class UnisonAPITest {
    @isTest static  void testFutureSendMRDUpsert() {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock()); 
        
        Test.startTest();
        UnisonAPI.fSendMRDUpsert('mrdId');
        Test.stopTest();
    }
    
    @isTest static void testSendMRDUpsert() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse response = UnisonAPI.SendMRDUpsert('mrdId');
        // Verify that the response received contains fake values
        String contentType = response.getHeader('Content-Type');
        System.assert(contentType == 'text/xml');
        String actualValue = response.getBody();
        System.debug(response.getBody());
        String expectedValue = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><notificationsResponse xmlns="http://soap.sforce.com/2005/09/outbound"><Ack>true</Ack></notificationsResponse></soapenv:Body></soapenv:Envelope>';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, response.getStatusCode());
    }
    
    @isTest static void testSendMRDUpsertError() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UnisonAPIErrorHttpCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        
        HttpResponse response = UnisonAPIErrorHttpCalloutMock.respond(new HTTPRequest());
        // Verify that the response received contains fake values
        String contentType = response.getHeader('Content-Type');
        System.assertEquals('application/json',contentType);
        String actualValue = response.getBody();
        System.debug(response.getBody());
        String expectedValue = '{ "message": "error" }';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(500, response.getStatusCode());
    }   
    
    @isTest static  void testFutureSendRequirementUpsert() {
        Test.setMock(HttpCalloutMock.class, new UnisonRequirementUpsertHttpCalloutMock()); 
        
        /*List<Current_Conditions__c> data = new List<Current_Conditions__c>();
        Current_Conditions__c req = new Current_Conditions__c();
        //req.id = '1';
        data.add(req);*/
                    Account acc = new Account();
             acc.Name = 'test';
             insert acc;
             Opportunity opp = new Opportunity();
             opp.Name = 'test';
             opp.AccountId = acc.Id;
             opp.StageName = 'Submit to Ops';
             opp.CloseDate = system.today();
             insert opp;
             Success_Factor__c sf = new Success_Factor__c();
             sf.Status__c = 'In Progress';             
             insert sf;
             List<Current_Conditions__c> data = new List<Current_Conditions__c>();
             Current_Conditions__c req = new Current_Conditions__c();
             req.Opportunity__c = opp.Id;
             req.Code__c = 'R1002';
             req.Requirement__c = '1099';
             //req.Success_Factor_Type__c 'OAV';
             req.Success_Factor__c = sf.Id;
             data.add(req);
        Test.startTest();
          UnisonAPI.SendRequirementUpsert(data);
        Test.stopTest();
    }

    @isTest static void testSendRequirementUpsert() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UnisonRequirementUpsertHttpCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        String expectedValue = '[{"foo":"bar"}]';
        HttpResponse response = UnisonAPI.SendRequirementUpsertRequest(expectedValue);
        // Verify that the response received contains fake values
        String contentType = response.getHeader('Content-Type');
        System.assert(contentType == 'application/json');
        String actualValue = response.getBody();
        System.debug(response.getBody());
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, response.getStatusCode());
    }
        
    @isTest static void testSendRequirementUpsertError() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UnisonAPIErrorHttpCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse response = UnisonAPI.SendRequirementUpsertRequest('{}');
        // Verify that the response received contains fake values
        System.assertEquals(500, response.getStatusCode());
    }   

    @isTest static  void testFutureSendDocumentUpsert() {
        Test.setMock(HttpCalloutMock.class, new UnisonDocumentUpsertHttpCalloutMock()); 
        
        List<Document_MetaData__c> data = new List<Document_MetaData__c>();
        Document_MetaData__c doc = new Document_MetaData__c();
        //doc.id = '1';
        data.add(doc);
        
        Test.startTest();
        UnisonAPI.SendDocumentUpsert(data);
        Test.stopTest();
    }

    @isTest static void testSendDocumentUpsert() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UnisonDocumentUpsertHttpCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        String expectedValue = '[{"foo":"bar"}]';
        HttpResponse response = UnisonAPI.SendDocumentUpsertRequest(expectedValue);
        // Verify that the response received contains fake values
        String contentType = response.getHeader('Content-Type');
        //System.assert(contentType == 'application/json');
        String actualValue = response.getBody();
        System.debug(response.getBody());
        //System.assertEquals(actualValue, expectedValue);
        //System.assertEquals(200, response.getStatusCode());
    }
        
    @isTest static void testSendDocumentUpsertError() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UnisonAPIErrorHttpCalloutMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse response = UnisonAPI.SendDocumentUpsertRequest('{}');
        // Verify that the response received contains fake values
        System.assertEquals(500, response.getStatusCode());
    }   
}