objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSI_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSI Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSI_Letter_Text_Insert__c</fullName>
        <label>RSI Letter Text Insert</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Add Applicant to Title at Closing</fullName>
                </value>
                <value>
                    <fullName>Additional_Assets_Verification_Required</fullName>
                    <label>Additional Assets Verification Required</label>
                </value>
                <value>
                    <fullName>Additional lien information</fullName>
                    <label>Additional Lien Information</label>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Title holder application</fullName>
                    <label>Application Required for All Parties on Title</label>
                </value>
                <value>
                    <fullName>Appraisal - 1004D</fullName>
                </value>
                <value>
                    <fullName>Appraisal</fullName>
                    <label>Appraisal - 1st</label>
                </value>
                <value>
                    <fullName>Second Appraisal</fullName>
                    <label>Appraisal - 2nd</label>
                </value>
                <value>
                    <fullName>Appraisal - 3rd</fullName>
                </value>
                <value>
                    <fullName>Appraisal Desk Review</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Authorization to Share</fullName>
                </value>
                <value>
                    <fullName>CAP Completed</fullName>
                </value>
                <value>
                    <fullName>Certificate of Occupancy</fullName>
                </value>
                <value>
                    <fullName>Certified Documents</fullName>
                </value>
                <value>
                    <fullName>Change Vesting Type</fullName>
                </value>
                <value>
                    <fullName>Closing Documents</fullName>
                </value>
                <value>
                    <fullName>Closing Documents Executed</fullName>
                </value>
                <value>
                    <fullName>Condo rider executed</fullName>
                    <label>Condo Rider Executed</label>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Credit Supplement</fullName>
                </value>
                <value>
                    <fullName>Death Certificate</fullName>
                </value>
                <value>
                    <fullName>Disability Award Letter</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>DMA Required</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Escrow Holdback for Item that Must</fullName>
                    <label>Escrow Holdback for Item that Must be Repaired</label>
                </value>
                <value>
                    <fullName>Estimated Settlement Statement</fullName>
                </value>
                <value>
                    <fullName>Final Hazard Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>RSI_Count__c</fullName>
        <label>RSI Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Tasks_Vs_Task_Codes__mdt.object
<CustomObject>
    <description>Metadata that stores project tasks API names</description>
    <fields>
        <fullName>Task_Code__c</fullName>
        <label>Task Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Project Tasks Vs Task Code</label>
    <pluralLabel>Project Tasks Vs Task Codes</pluralLabel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RSILetterTextController.cls
/*************************************
    Owner :- Unison
    Developer:- Sundar Subramaniam
    Created Date:- 04/26/2019
    Modified Date:- 
     Description:-This class is as a controller for RequirementListOfOpportunity Page
*************************************/
public class RSILetterTextController {
    // Declaration for StandardController fields
    public string opportunityid{get;set;}
    public List<Current_Conditions__c> todisplay{get;set;}
    public Boolean errorhasoccured{get;set;}
    public string errormessage{get;set;}
    public Opportunity mainopportunity{get;set;}
    public RSILetterTextController()
    {
        errorhasoccured=false;
        errormessage = '';
        //Retreiving id passed by parameter
        opportunityid = Apexpages.currentPage().getParameters().get('Id');
        //Retreiving the Opportunity to check RSI Count
        mainopportunity = [select id,RSI_Count__c,Name from Opportunity where id =:opportunityid ];
        todisplay = new List<Current_Conditions__c>();
        //Retreiving the all the Requirements with the neccasary conditions
        todisplay = [select id,Name,RSI_Letter_Text_Insert__c,Requirement__c from Current_Conditions__c where Opportunity__c =:opportunityid AND Status__c= 'Document Received, In progress' AND RSI_Eligible__c = TRUE];
        system.debug('todisplay==>'+todisplay);
    }
    //Function to update the Requirements and the task
    public void updaterequirements()
    {
        Set<String> requirementids = new Set<String>();
        List<Project_Task__c> listoftasks = new List<Project_Task__c>();
        errorhasoccured=true;
        errormessage = '';
        Project_Tasks_Vs_Task_Codes__mdt metadata = [select Task_Code__c,Label from Project_Tasks_Vs_Task_Codes__mdt where Label = 'Send RSI Letter'];
        for(Current_Conditions__c obj:todisplay)
        {
            requirementids.add(obj.id);
            //Condition to check if all the RSI Letter Text Insert is entered.
            if(obj.RSI_Letter_Text_Insert__c == null || obj.RSI_Letter_Text_Insert__c == '')
            {
                errormessage = 'One or more RSI Eligible Requirement reasons has not been populated.';
                system.debug('Error on==>'+obj);
                //errorhasoccured=TRUE;
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'One or more RSI Eligible Requirement reasons has not been populated.'));                
                return;
            }
        }
        //Update Requirements
        system.debug('todisplay==>'+todisplay);
        errorhasoccured=false;
        update todisplay;
        //Update 'Notify file is ready for RSI' Task to completed
        List<Project_Task__c> projectlist = [select id,Requirement__c from Project_Task__c where Requirement__c in:requirementids AND completed__c = FALSE AND Code__c = 'Task-380' AND Name = 'Notify file is ready for RSI'];
        if(projectlist.size()>0)
        {
            for(Project_Task__c obj:projectlist)
            {
                obj.completed__c = true;
                Project_Task__c newTask = new Project_Task__c();
                newTask.Name = metadata.Label;
                newTask.Requirement__c = obj.Requirement__c;
                newTask.Code__c = metadata.Task_Code__c;
                listoftasks.add(newTask);
            }
            update projectlist;
            insert listoftasks;
             
        }
    }
}