objects/Current_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Current_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document Received, In progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Document Ready for Review</fullName>
                    <label>Ready to Review</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <referenceTo>Success_Factor__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{00000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DMA__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>DMAs</relationshipLabel>
        <relationshipName>DMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DMA</label>
    <nameField>
        <displayFormat>DMA-{000000}</displayFormat>
        <label>DMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DMAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Investment_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Investment Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <defaultValue>IF( $RecordType.Name = 'HomeBuyer','N/A','Pending')</defaultValue>
        <inlineHelpText>Passbook may run once LTV, DTI, and Credit Success Factors are marked Completed</inlineHelpText>
        <label>Current Passbook Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                    <isActive>false</isActive>
                    <label>Exception</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                    <isActive>false</isActive>
                    <label>Reject</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Monthly_First_Mortgage__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Pulled from Application</inlineHelpText>
        <label>Payment Monthly First Mortgage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Monthly_HOA__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Pulled from Application</inlineHelpText>
        <label>Payment Monthly HOA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SEND_TO_ENCOMPASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Used for EOS go live only. May be deleted after Encompass LOS system is no longer used</inlineHelpText>
        <label>SEND_TO_ENCOMPASS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Held__c</fullName>
        <label>Title Held</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individually</fullName>
                </value>
                <value>
                    <fullName>Jointly</fullName>
                </value>
                <value>
                    <fullName>In Trust</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Scheduled Training</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <description>Properties for which customers and indirect channel partners (loan officers, real estate agents, etc) have inquired the investment approval status.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <inlineHelpText>Pricing Ratio based on Unison Program</inlineHelpText>
        <label>Inquiry Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandlerTest.cls
/************************************************************************************
 Apex Class Name     : OpportunityTriggerHandlerTest
 Version             : 1.0
 Created Date        : 20th Feb 2019
 Function            : Test Class for OpportunityTriggerHandler class
 Author              : Neeraja Cherukuri
 
 Modification Log    :I have Deprecated all the Test methods that were Commented by the Prior Teams.

* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Neeraja Cherukuri            02/20/2019                Original Version
*************************************************************************************
*/



@isTest
public class OpportunityTriggerHandlerTest 
{
    @testSetup
    static void setup() {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock());
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'My TestOpp', AccountId = objAcc.Id,
                StageName = 'Ready for Ops', CloseDate = System.today(),RecordTypeId=optyHomeBuyerRecId,
                UnisonProcessor__c=u.id,Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 2,Title_Held__c= 'In Trust',SEND_TO_ENCOMPASS__c = False,
                IA_OAV_Override__c =2, Passbook_Status__c = 'Approved', Payment_Monthly_HOA__c = 0, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;

        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = objOpty.Id;
        sf1.Success_Factor__c  = 'Program';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        Insert sf1;


        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Revised CAP';
        req2.Success_Factor__c  = sf1.Id;
        req2.opportunity__c      = objOpty.id;
        req2.Code__c = 'R1115';

        Insert req2;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = '2-4 Family';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Opportunity__c=objOpty.Id;
        newprop.Property_Condo_PUD_Name__c = 'Condo PUD Name';        
        insert newprop;
        
        DMA__c dma = new DMA__c();
        dma.Opportunity__c = objOpty.Id;
        insert dma;

    }

   private static testMethod void test() {       
       test.startTest();

       Opportunity myOpp = [SELECT Id, StageName, Passbook_Status__c FROM Opportunity WHERE Name = 'My TestOpp' LIMIT 1];
        myOpp.StageName = 'Closing';
        myOpp.Payment_Monthly_HOA__c = 200;
        update myOpp;
       List<Opportunity> opplist = new List<Opportunity>();
       opplist.add(myOpp);

       OpportunityUtilityClass.createClosingOppRequirements(oppList);

        test.stopTest();
    }

   private static testMethod void test_OfferPrevent() {       
       test.startTest();

       Opportunity myOpp = [SELECT Id, StageName, Passbook_Status__c FROM Opportunity WHERE Name = 'My TestOpp' LIMIT 1];
       
        myOpp.StageName = 'Offer';
        update myOpp;
       OpportunityUtilityClass.createOfferOppRequirements(new List<Opportunity> { myOpp });
        myOpp.StageName = 'Closing';
        update myOpp;
       
        test.stopTest();
    }

    private static testMethod void validateForHomeOwner4()
    {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock());
        test.startTest();
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                StageName = 'Ready for Ops', CloseDate = System.today(),RecordTypeId=optyHomeOwnerRecId,
                UnisonProcessor__c=u.id,Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 2,Title_Held__c= 'In Trust',SEND_TO_ENCOMPASS__c = False,
                IA_OAV_Override__c =2,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;

        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = objOpty.Id;
        sf1.Success_Factor__c  = 'Program';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        Insert sf1;


        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Revised CAP';
        req2.Success_Factor__c  = sf1.Id;
        req2.opportunity__c      = objOpty.id;
        req2.Code__c = 'R1115';

        Insert req2;

        req2.Status__c = 'Cleared';
        update req2;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = 'Condominium';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Opportunity__c=objOpty.Id;
        insert newprop;

        Property__c newprop2 = new Property__c();
        newprop2.Name = 'Test';
        newprop2.Property_Type__c = 'PUD';
        newprop2.Build_Year__c = '2019';
        newprop2.Property_New_Construction_Flag__c = True;
        newprop2.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop2.Property_City__c = 'test asd 123';
        newprop2.Property_State__c = 'CA';
        newprop2.Property_Zip_Code__c = '12345';
        newprop2.Property_County__c = 'test asd 123';
        newprop2.Opportunity__c=objOpty.Id;
        insert newprop2;

        // Utility method that can be called by Apex tests to create price book entries.
        // static testmethod void addPricebookEntries() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Acquisition Fee',
                Family = 'Hardware');
        insert prod;

        Product2 prod2 = new Product2(Name = 'Transaction Fee',
                Family = 'Hardware');
        insert prod2;

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();

        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                UnitPrice = 12000, IsActive = true);
        insert customPrice;




        objOpty.StageName = 'Investment Due Diligence';
        update objOpty;
        List<Opportunity> opplist = new List<Opportunity>();
        opplist.add(objOpty);
        //cv//OpportunityTriggerHandler.handleAfterInsert(opplist);

        try {
            OpportunityUtilityClass.createIDDOppRequirements(oppList);
        }
        catch(Exception e){

        }
        test.stopTest();
    }


    private static testMethod void validateForHomeBuyer()
    {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock());
        test.startTest();
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                                            StageName = 'Ready for Ops', CloseDate = System.today(),RecordTypeId=optyHomeBuyerRecId,
                                            UnisonProcessor__c=u.id,Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                                            Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 2,Title_Held__c= 'In Trust',SEND_TO_ENCOMPASS__c = False,
                                            IA_OAV_Override__c =2,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;

        Success_Factor__c sf1     = new Success_Factor__c();
            sf1.Opportunity__c     = objOpty.Id;
            sf1.Success_Factor__c  = 'Program';
            sf1.Status__c = 'In Progress';
            sf1.Program__c = 'HO';
        Insert sf1;
        
                
        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Revised CAP';   
        req2.Success_Factor__c  = sf1.Id; 
        req2.opportunity__c      = objOpty.id;
        req2.Code__c = 'R1115';

        Insert req2;
        
        req2.Status__c = 'Cleared';
        update req2;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = 'Condominium';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Opportunity__c=objOpty.Id;
        insert newprop;

        Property__c newprop2 = new Property__c();
        newprop2.Name = 'Test';
        newprop2.Property_Type__c = 'PUD';
        newprop2.Build_Year__c = '2019';
        newprop2.Property_New_Construction_Flag__c = True;
        newprop2.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop2.Property_City__c = 'test asd 123';
        newprop2.Property_State__c = 'CA';
        newprop2.Property_Zip_Code__c = '12345';
        newprop2.Property_County__c = 'test asd 123';
        newprop2.Opportunity__c=objOpty.Id;
        insert newprop2;

        // Utility method that can be called by Apex tests to create price book entries.
        // static testmethod void addPricebookEntries() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Acquisition Fee',
                Family = 'Hardware');
        insert prod;

        Product2 prod2 = new Product2(Name = 'Transaction Fee',
                Family = 'Hardware');
        insert prod2;

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();

        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                UnitPrice = 12000, IsActive = true);
        insert customPrice;




        objOpty.StageName = 'Investment Due Diligence';
        update objOpty;
        List<Opportunity> opplist = new List<Opportunity>();
        opplist.add(objOpty);
        //cv//OpportunityTriggerHandler.handleAfterInsert(opplist);

        try {
            OpportunityUtilityClass.createIDDOppRequirements(oppList);
        }
        catch(Exception e){

        }
        test.stopTest();
    } 
    private static testMethod void validateWitoutOAVValue()
    {        
        test.startTest();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,Pricing_Ratio__c = 4,
                                                            StageName = 'Property in Contract', CloseDate = System.today(),Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;
        
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        /* 4/5/2019 Neeraja Cherukuri - Replaced with New Fieldsfor Data Model Clean Up */

        objOpty.Summary_Appraised_Value__c= 0;

        update objOpty;

        test.stopTest();
    }
    private static testMethod void validateForHomeOwner()
    {        
        test.startTest();
        
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeOwnerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        System.debug('=====optyHomeBuyerRecId===='+optyHomeOwnerRecId);
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,RecordTypeId=optyHomeOwnerRecId,
                                                            StageName = 'Property in Contract', CloseDate = System.today(),UnisonProcessor__c=u.id,
                                                            Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                                                            Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 2,
                                                            Post_Close_Home_Inspection_Check__c = True,
                                                            IA_OAV_Override__c =2,
                                                            Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;


        Success_Factor__c sf1     = new Success_Factor__c();
            sf1.Opportunity__c     = objOpty.Id;
            sf1.Success_Factor__c  = 'Cash to Consumer';
           // sf1.Status__c = 'Completed';
            sf1.Status__c = 'In Progress';
        Insert sf1; 
        
        
          
        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Natural Hazard Disclosure';   
        req2.Success_Factor__c  = sf1.Id; 
        req2.opportunity__c      = objOpty.id;
        Insert req2;
        
        req2.Status__c = 'Document Ready for Review';
        update req2;
        
        
        //sf1.Status__c = 'Completed';
        //update sf1;
        /* 4/2/2019 Sundar Subramaniam - Commented for Data Model Cleanup */
        /* 4/5/2019 Neeraja Cherukuri - Replaced fo new fields in Data Model Cleanup */

        objOpty.Summary_Appraised_Value__c= 0;
      //  objOpty.StageName = 'Final Approval';
        update objOpty;
        test.stopTest();
    }


    private static testMethod void validateForHomeOwner2()
    {        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());        
        test.startTest();
        OpportunityTriggerHandler.createdRequirements = true;
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                StageName = 'Closing', CloseDate = System.today(),RecordTypeId=optyHomeBuyerRecId,
                UnisonProcessor__c=u.id,Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 2,Title_Held__c= 'In Trust',SEND_TO_ENCOMPASS__c = False,
                IA_OAV_Override__c =2,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0, OIP_Confirmed__c = true);

        insert objOpty;

        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = objOpty.Id;
        sf1.Success_Factor__c  = 'Cash to Consumer';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        Insert sf1;


        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Revised CAP';
        req2.Success_Factor__c  = sf1.Id;
        req2.opportunity__c      = objOpty.id;
        req2.Code__c = 'R1115';
        Insert req2;

        req2.Status__c = 'Cleared';
        update req2;


        // Utility method that can be called by Apex tests to create price book entries.
        // static testmethod void addPricebookEntries() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Acquisition Fee',
                Family = 'Hardware');
        insert prod;

        Product2 prod2 = new Product2(Name = 'Transaction Fee',
                Family = 'Hardware');
        insert prod2;

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();

        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                UnitPrice = 12000, IsActive = true);
        insert customPrice;



        //objOpty.IA_OAV_Override__c = 456456;
        // objOpty.StageName = 'Investment Due Diligence';
        update objOpty;
        List<Opportunity> opplist = new List<Opportunity>();
        opplist.add(objOpty);
        //cv//OpportunityTriggerHandler.handleAfterInsert(opplist);

        try {
            //OpportunityTriggerHandler.createRequirementsatStages(oppList);
        }
        catch(Exception e){

        }
        test.stopTest();
    }


    private static testMethod void validateForHomeOwner3()
    {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock());
        test.startTest();
        OpportunityTriggerHandler.createdRequirements = true;
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                StageName = 'Investment Due Diligence', CloseDate = System.today(),RecordTypeId=optyHomeBuyerRecId,
                UnisonProcessor__c=u.id,Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 4,Title_Held__c= 'In Trust',IA_OAV_Override__c =2,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;

        Success_Factor__c sf1     = new Success_Factor__c();
        sf1.Opportunity__c     = objOpty.Id;
        sf1.Success_Factor__c  = 'Program';
        sf1.Status__c = 'In Progress';
        sf1.Program__c = 'HO';
        Insert sf1;


        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Revised CAP';
        req2.Success_Factor__c  = sf1.Id;
        req2.opportunity__c      = objOpty.id;
        req2.Code__c = 'R1115';
        Insert req2;

        req2.Status__c = 'Cleared';
        update req2;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = 'Condominium';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Opportunity__c=objOpty.Id;
        insert newprop;

        Property__c newprop2 = new Property__c();
        newprop2.Name = 'Test';
        newprop2.Property_Type__c = 'PUD';
        newprop2.Build_Year__c = '2019';
        newprop2.Property_New_Construction_Flag__c = True;
        newprop2.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop2.Property_City__c = 'test asd 123';
        newprop2.Property_State__c = 'CA';
        newprop2.Property_Zip_Code__c = '12345';
        newprop2.Property_County__c = 'test asd 123';
        newprop2.Opportunity__c=objOpty.Id;
        insert newprop2;


        // Utility method that can be called by Apex tests to create price book entries.
        // static testmethod void addPricebookEntries() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Acquisition Fee',
                Family = 'Hardware');
        insert prod;

        Product2 prod2 = new Product2(Name = 'Transaction Fee',
                Family = 'Hardware');
        insert prod2;

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();

        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                UnitPrice = 12000, IsActive = true);
        insert customPrice;



        objOpty.IA_OAV_Override__c = 456456;
        // objOpty.StageName = 'Investment Due Diligence';
        update objOpty;
        List<Opportunity> opplist = new List<Opportunity>();
        opplist.add(objOpty);

        OpportunityTriggerHandler.handleAfterInsert(opplist);

        try {
            //OpportunityTriggerHandler.createRequirementsatStages(oppList);
        }
        catch(Exception e){

        }
        test.stopTest();
    }

    /*
    private static testMethod void requirementStagesInvestmentDueDiligence()
    {
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                StageName = 'Investment Due Diligence', CloseDate = System.today());
        insert objOpty;

        objOpty.Summary_Appraised_Value__c= 0;

        update objOpty;

        List<Opportunity> opplist = new List<Opportunity>();
        opplist.add(objOpty);

        OpportunityUtilityClass.createIDDOppRequirements(oppList);

    }*/

    private static testMethod void test1()
    {        
        test.startTest();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                StageName = 'Property in Contract', CloseDate = System.today(), Pricing_Ratio__c = 4,
                Opportunity_Created_From_Lead__c=true,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;

        objOpty.Summary_Appraised_Value__c= 0;
        objOpty.Payment_Monthly_HOA__c=150;
        update objOpty;
        test.stopTest();

    }
    
    @istest
    private static void updateFinalAmounttest(){        
        test.startTest();
        Product2 prod1 = new Product2(Name = 'Transaction Fee',
                Family = 'Hardware');
        insert prod1;

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod1.Id,
                UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod1.Id,
                UnitPrice = 12000, IsActive = true);
        insert customPrice;


        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                StageName = 'Property in Contract', CloseDate = System.today(),Pricing_Ratio__c = 4,
                Opportunity_Created_From_Lead__c=true,Estimated_Funding_Amount__c=50,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;


        OpportunityLineItem oli1 = new OpportunityLineItem(OpportunityId=objOpty.Id, PricebookEntryId=customPrice.Id,UnitPrice=100, Quantity=1);
        //insert oli1;


        objOpty.Estimated_Funding_Amount__c= 100;

        update objOpty;

        test.stopTest();
    }
        
    private static testMethod void test_PostClosingRequirements()
    {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock());
        test.startTest();
        User u = [Select id from User where Id = :UserInfo.getUserId()];
        Id optyHomeBuyerRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        Account objAcc = new Account (Name='Test Account');
        insert objAcc;
        Opportunity objOpty = new Opportunity(Name = 'Test Opportunity', AccountId = objAcc.Id,
                                            StageName = 'Ready for Ops', CloseDate = System.today(),RecordTypeId=optyHomeBuyerRecId,
                                            UnisonProcessor__c=u.id,Investment_Analyst2__c=u.id,Estimated_Funding_Amount__c = 2,
                                            Final_OAV_Calculation__c = 2, Pricing_Ratio__c = 2,Title_Held__c= 'In Trust',SEND_TO_ENCOMPASS__c = False,
                                            IA_OAV_Override__c =2,Payment_Monthly_HOA__c = 25, Payment_Monthly_First_Mortgage__c = 1.0);
        insert objOpty;

        Success_Factor__c sf1     = new Success_Factor__c();
            sf1.Opportunity__c     = objOpty.Id;
            sf1.Success_Factor__c  = 'Program';
            sf1.Status__c = 'In Progress';
            sf1.Program__c = 'HO';
        Insert sf1;
        
                
        Current_Conditions__c req2 = new Current_Conditions__c();
        req2.Requirement__c     = 'Revised CAP';   
        req2.Success_Factor__c  = sf1.Id; 
        req2.opportunity__c      = objOpty.id;
        req2.Code__c = 'R1115';

        Insert req2;
        
        req2.Status__c = 'Cleared';
        update req2;

        Property__c newprop = new Property__c();
        newprop.Name = 'Test';
        newprop.Property_Type__c = 'Condominium';
        newprop.Build_Year__c = '2019';
        newprop.Property_New_Construction_Flag__c = True;
        newprop.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop.Property_City__c = 'test asd 123';
        newprop.Property_State__c = 'CA';
        newprop.Property_Zip_Code__c = '12345';
        newprop.Property_County__c = 'test asd 123';
        newprop.Opportunity__c=objOpty.Id;
        insert newprop;

        Property__c newprop2 = new Property__c();
        newprop2.Name = 'Test';
        newprop2.Property_Type__c = 'PUD';
        newprop2.Build_Year__c = '2019';
        newprop2.Property_New_Construction_Flag__c = True;
        newprop2.Property_Street_Number_and_Name__c = 'test asd 123';
        newprop2.Property_City__c = 'test asd 123';
        newprop2.Property_State__c = 'CA';
        newprop2.Property_Zip_Code__c = '12345';
        newprop2.Property_County__c = 'test asd 123';
        newprop2.Opportunity__c=objOpty.Id;
        insert newprop2;

        // Utility method that can be called by Apex tests to create price book entries.
        // static testmethod void addPricebookEntries() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Acquisition Fee',
                Family = 'Hardware');
        insert prod;

        Product2 prod2 = new Product2(Name = 'Transaction Fee',
                Family = 'Hardware');
        insert prod2;

        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();

        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
        insert standardPrice;

        // Create a custom price book
        Pricebook2 customPB = new Pricebook2(Name='Fee', isActive=true);
        insert customPB;

        // 2. Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                UnitPrice = 12000, IsActive = true);
        insert customPrice;

        objOpty.StageName = 'Post-Closing';
        update objOpty;
        List<Opportunity> opplist = new List<Opportunity>();
        opplist.add(objOpty);

        //try
        {
            OpportunityUtilityClass.createPostClosingOppRequirements(oppList);
        }
        //catch(Exception e)
    {

        }
        test.stopTest();
    }        
    /*
    private static testMethod void test_SetQualifiesforNewHOPricing()
    {

        Test.startTest();

        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test287836';
        opp1.StageName = 'Investment Due Diligence';
        opp1.CloseDate = Date.today();
        opp1.New_HomeOwner_Purchase_Date__c = Date.today();
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Test287837';
        opp2.StageName = 'Investment Due Diligence';
        opp2.CloseDate = Date.today();
        opp2.New_HomeOwner_Purchase_Date__c = Date.today().addYears(2);

        insert new List<Opportunity> { opp1, opp2 };

        Test.stopTest();

        opp1 = [SELECT Qualifies_for_New_HomeOwner_Pricing__c FROM Opportunity WHERE Id = :opp1.Id];
        System.assertEquals(true, opp1.Qualifies_for_New_HomeOwner_Pricing__c);
        opp2 = [SELECT Qualifies_for_New_HomeOwner_Pricing__c FROM Opportunity WHERE Id = :opp2.Id];
        System.assertEquals(false, opp2.Qualifies_for_New_HomeOwner_Pricing__c);

    }*/        
}