objects/Deal_History__c.object
<CustomObject>
    <fields>
        <fullName>FICO__c</fullName>
        <label>FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Histories</relationshipLabel>
        <relationshipName>Deal_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <label>Passbook Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Post_Close_LTV__c</fullName>
        <label>Post-Close LTV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Deal History</label>
    <nameField>
        <label>Deal History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been ordered by Origination Ops</description>
        <label>Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Appraisal has been received</description>
        <label>Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DMA_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in DocGen to include the Deferred Maintenance Addendum if &gt; 0</description>
        <inlineHelpText>Total count of all DMA records</inlineHelpText>
        <label>DMA Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FICO__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <inlineHelpText>Lower of the two scores between the Applicant Credit Score (Median) and Co-Applicant Score (Median).</inlineHelpText>
        <label>FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been ordered by Origination Ops</description>
        <label>Home Inspection Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Home Inspection has been received</description>
        <label>Home Inspection Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Investment_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Investment Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passbook_Status__c</fullName>
        <defaultValue>IF( $RecordType.Name = 'HomeBuyer','N/A','Pending')</defaultValue>
        <inlineHelpText>Passbook may run once LTV, DTI, and Credit Success Factors are marked Completed</inlineHelpText>
        <label>Current Passbook Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                    <isActive>false</isActive>
                    <label>Exception</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                    <isActive>false</isActive>
                    <label>Reject</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Program_Knowledge_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</description>
        <inlineHelpText>Marked Complete by Program Specialist when customer has completed the PKR. The PKR can be be completed at any point during the Lead or Opportunity life cycle.</inlineHelpText>
        <label>Program Knowledge Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Report_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Report_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Report Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Appraisal_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Appraisal Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DealHistoryTriggerHandlerTest.cls
/**
 * Created by Ivan Garcia on 5/21/2019.
 */

@IsTest public with sharing class DealHistoryTriggerHandlerTest {
    @TestSetup private static void Testdata() {
        Account newAcc = new Account (Name='Test Account');
        insert newAcc;
        Id homeOwnerRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        Opportunity newOppty = new Opportunity();
        newOppty.Name = 'Test Opportunity';
        newOppty.AccountId = newAcc.Id;
        newOppty.StageName = 'Investment Due Diligence';
        newOppty.CloseDate = System.today();
        newOppty.UnisonProcessor__c = UserInfo.getUserId();
        newOppty.Investment_Analyst2__c = UserInfo.getUserId();
        newOppty.Process_Program_Knowledge_Review__c = false;
        newOppty.Appraisal_Received__c = false;
        newOppty.Appraisal_Ordered__c = false;
        newOppty.Second_Appraisal_Ordered__c = false;
        newOppty.Second_Appraisal_Received__c = false;
        newOppty.Home_Inspection_Ordered__c = false;
        newOppty.Home_Inspection_Received__c = false;
        newOppty.Property_Report_Ordered__c = false;
        newOppty.Property_Report_Received__c = false;
        newOppty.IA_OAV_Override__c = 10.0;
        newOppty.Estimated_Funding_Amount__c = 11.0;
        newOppty.Pricing_Ratio__c = 10.0;
        newOppty.CloseDate = system.today() + 2;
        newOppty.DMA_Count__c = 0;
        newOppty.RecordTypeId = homeOwnerRT;
        insert newOppty;

        Success_Factor__c tmpSucc = new Success_Factor__c(Success_Factor__c = 'Final Approval', Opportunity__c = newOppty.id);
        insert tmpSucc;

        Deal_History__c DH = new Deal_History__c();
        DH.Opportunity__c = newOppty.Id;
        DH.Passbook_Status__c = 'Approved';
        DH.Post_Close_LTV__c = 10;
        insert DH;
    }

    @IsTest private static void mainTest() {
        Opportunity tmpOpp = [SELECT id,recordtype.name FROM Opportunity LIMIT 1];
        Id RT = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        tmpOpp.RecordTypeId = RT;
        update tmpOpp;
        system.debug('tmpOpp: '+tmpOpp);

        Deal_History__c tmpDH = [SELECT id,Passbook_Status__c FROM Deal_History__c LIMIT 1];
        tmpDH.FICO__c = 1;
        tmpDH.Post_Close_LTV__c = 11;
        update tmpDH;
    }
}