objects/Deal_Stage_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Deal Stage Tracker</relationshipLabel>
        <relationshipName>Deal_Stage_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_Integration_Status__c</fullName>
        <label>Segment Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Stage Tracker</label>
    <nameField>
        <displayFormat>DST-{0000000000}</displayFormat>
        <label>Deal Stage Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Stage Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendToSegmentAPITest.cls
@isTest
public class SendToSegmentAPITest {
    
    @isTest
	public static void TestSuccess(){
        // Data setup
		Lead l = new Lead();
        l.LastName = 'Test 686483';
        l.Company = 'test 286830';
        insert l;

        Deal_Stage_Tracker__c dst = new Deal_Stage_Tracker__c();
        dst.Lead__c = l.Id;
        dst.Event_Name__c = 'Registration';
        insert dst;
		
        Test.setMock(HttpCalloutMock.class, new SegmentAPIMock());

		// Run the code
		Test.startTest();
        SendToSegmentAPI ctrl = new SendToSegmentAPI(new ApexPages.StandardController(dst));
        ctrl.Send();
        ctrl.GoBack();
		Test.stopTest();
		
		// Verify Results
		dst = [SELECT Id, Segment_Integration_Status__c FROM Deal_Stage_Tracker__c WHERE Id = :dst.Id];
        System.assertEquals('Success', dst.Segment_Integration_Status__c);
    }

    @isTest
	public static void TestError(){
        // Data setup
		Lead l = new Lead();
        l.LastName = 'Test 686483';
        l.Company = 'test 286830';
        insert l;

        Deal_Stage_Tracker__c dst = new Deal_Stage_Tracker__c();
        dst.Lead__c = l.Id;
        dst.Event_Name__c = 'Registration';
        
        Test.setMock(HttpCalloutMock.class, new SegmentAPIMock());

		// Run the code
		Test.startTest();
        SendToSegmentAPI ctrl = new SendToSegmentAPI(new ApexPages.StandardController(dst));
        ctrl.Send();
        ctrl.GoBack();
		Test.stopTest();
		
		// Verify Results
        System.assertEquals(ApexPages.Severity.ERROR, Apexpages.getMessages().get(0).getSeverity());
    }
}