objects/Document_MetaData__c.object
<CustomObject>
    <fields>
        <fullName>Box_File_URL__c</fullName>
        <label>Box File URL</label>
        <type>Url</type>
    </fields>
    <label>Document MetaData</label>
    <nameField>
        <displayFormat>DMD-{000000000}</displayFormat>
        <label>Document MetaData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document MetaData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomIterable.cls
global class CustomIterable implements Iterator<ContentDocumentLink>
{ 

   List<ContentDocumentLink> lstCDL {get; set;} 
   Integer i {get; set;} 
   Date d = System.today() - Integer.valueOf(Label.No_of_Days_to_Delete_Files);
   public CustomIterable()
   { 
       
       lstCDL = [SELECT ContentDocumentId, LinkedEntityId  FROM ContentDocumentLink where LinkedEntityId in ( SELECT Id FROM Document_MetaData__c WHERE Box_File_URL__c != Null AND  Createddate >= :d) and LinkedEntity.Type='Document_MetaData__c'];
       i = 0;      
   }   

   global boolean hasNext()
   { 
       if(i >= lstCDL.size()) 
       {
           return false; 
       } else 
       {
           return true; 
       }
   }    

   global ContentDocumentLink next()
   {  
       if(i == 200){return null;} 
       i++; 
       return lstCDL[i-1]; 
   } 
}