objects/Exception_DTI_Guideline__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DTI__c</fullName>
        <inlineHelpText>DTI Min Value</inlineHelpText>
        <label>DTI</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LTV__c</fullName>
        <inlineHelpText>LTV Min Value</inlineHelpText>
        <label>LTV</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status should have one of the 3 values: "Yes", "No", "Exception".</inlineHelpText>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Exception DTI Guideline</label>
</CustomObject>

objects/Exception_Fico_Guideline__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FICO__c</fullName>
        <inlineHelpText>FICO Min values</inlineHelpText>
        <label>FICO</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LTV__c</fullName>
        <inlineHelpText>LTV Min value</inlineHelpText>
        <label>LTV</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status should have one of the 3 values: "Yes", "No", "Exception".</inlineHelpText>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Exception Fico Guideline</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Unison's Investment Payment. This amount should not exceed Max Offer amount.</inlineHelpText>
        <label>Estimated Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Monthly_Base__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Income field used to determine DTI for the Lead: Base Income of the
            Applicant.</inlineHelpText>
        <label>Income Monthly Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LTV__c</fullName>
        <description>Post close LTV (Loan to Value ratio) As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <formula>LTV_Numerator__c / LTV_Denominator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>For HomeBuyer, the LTV (Loan-To-Value) ratio is calculated by dividing the Loan Amount by the Purchase Price or Home Value, whichever is lower. For HomeOwner, the LTV is calculated by dividing the Proposed Total Mortgage Debt by the Home Value</inlineHelpText>
        <label>Post Close LTV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It's a link to the credit report of the lead contact As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Selected Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Lead__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>greenlight field As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as used or otherwise relevant to current business
            processes. To be reviewed next Q4 2021.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_to_Case_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_field_API_Name__c</fullName>
        <label>Case field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Value__c</fullName>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Field_API_Name__c</fullName>
        <label>Lead Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead to Case Mapping</label>
</CustomObject>

classes/LeadQualification_TEST.cls
@isTest
public class LeadQualification_TEST {

    @isTest
    private static void testYes() {

        // Data setup
        Exception_Fico_Guideline__c fico1 = new Exception_Fico_Guideline__c();
        fico1.Name = 'fico1';
        fico1.FICO__c = 720;
        fico1.LTV__c = 0.60;
        fico1.Status__c = 'Yes';
        fico1.Type__c = 'HO';
        insert fico1;
        Exception_Dti_Guideline__c dti1 = new Exception_Dti_Guideline__c();
        dti1.Name = 'dti1';
        dti1.DTI__c = 0.30;
        dti1.LTV__c = 0.60;
        dti1.Status__c = 'Yes';
        dti1.Type__c = 'HO';
        insert dti1;
        
        Lead_to_Case_Mapping__c map1 = new Lead_to_Case_Mapping__c();
        map1.Name = 'Map1';
        map1.Case_field_API_Name__c = 'OwnerId';
        map1.Lead_Field_API_Name__c = 'OwnerId';
        Lead_to_Case_Mapping__c map2 = new Lead_to_Case_Mapping__c();
        map2.Name = 'Map2';
        map2.Case_field_API_Name__c = 'Subject';
        map2.Default_Value__c = 'Test 232899';
        insert new List<Lead_to_Case_Mapping__c> { map1, map2 };
        
        Lead l = new Lead();
        l.LastName = 'John Class';
        l.Company = 'Class Company';
        l.Qualifies_for_New_HomeOwner_Pricing__c = false;
        l.Estimated_Funding_Amount__c = 1000;
        l.status = 'Credit Qualified';
        l.Income_Monthly_Base__c = 5000;
        l.Home_Value__c = 500000;
        insert l;
        
        LASERCA__Personal_Credit_Report__c pcr = new LASERCA__Personal_Credit_Report__c();
        pcr.LASERCA__Lead__c = l.Id;
        insert pcr;
        
        l.Personal_Credit_Report__c = pcr.Id;
        update l;
        
        // Run the code
        Test.startTest();
        LeadQualification ctrl = new LeadQualification(new ApexPages.StandardController(l));
        ctrl.MortgageType = 'Amortizing';
        //ctrl.Calculate();
        //ctrl.ContinueLead();
        ctrl.RaiseException();
        ctrl.SaveCase();
        //ctrl.passbookContinueLead();
        ctrl.passbookCalculate();
        Test.stopTest();
        
    }
    
    /*@isTest
    private static void testOther() {

        // Data setup
        Lead l = new Lead();
        l.LastName = 'Test 436343';
        l.Company = 'Test 450990';
        l.Qualifies_for_New_HomeOwner_Pricing__c = false;
        l.Estimated_Funding_Amount__c = 1000;
        insert l;
        
        LASERCA__Personal_Credit_Report__c pcr = new LASERCA__Personal_Credit_Report__c();
        pcr.LASERCA__Lead__c = l.Id;
        insert pcr;
        
        l.Personal_Credit_Report__c = pcr.Id;
        update l;
        
        // Run the code
        Test.startTest();
        LeadQualification ctrl = new LeadQualification(new ApexPages.StandardController(l));
        ctrl.ResultT1 = 'Yes';
        ctrl.ResultT2 = 'No';
        //ctrl.ContinueLead();
        ctrl.ResultT1 = 'No';
        ctrl.ResultT2 = 'Yes';
        //ctrl.ContinueLead();
        ctrl.ResultT1 = 'Exception';
        ctrl.ResultT2 = 'No';
        //ctrl.ContinueLead();
        ctrl.ResultT1 = 'No';
        ctrl.ResultT2 = 'Exception';
        //ctrl.ContinueLead();
        ctrl.ResultT1 = 'No';
        ctrl.ResultT2 = 'No';
        //ctrl.ContinueLead();
        ctrl.SaveCase();
        
        Test.stopTest();
    }*/
    
}