objects/GreenLight_API_Log__c.object
<CustomObject>
    <label>GreenLight API Log</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>GreenLight API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GreenLight API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Greenlight_Id__c</fullName>
        <description>The unique identifier for the Greenlight inquiry. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Greenlight Inquiry ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Monthly_Base__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Income field used to determine DTI for the Lead: Base Income of the
            Applicant.</inlineHelpText>
        <label>Income Monthly Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inquiry_Sequence_ID__c</fullName>
        <description>Unique identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made. As this field has direct effects on calls made to the Property Service, do not deprecate or otherwise alter without the express consent of the Engineering team.</description>
        <inlineHelpText>Unique Identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made.</inlineHelpText>
        <label>Inquiry Sequence ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Construction_Dropdown__c</fullName>
        <description>Deprecate As of Q4-2019, this field has been identified by Business Systems
            (and relevant stakeholders) as used or otherwise relevant to current business processes.
            To be reviewed next Q4 2021.</description>
        <label>Property New Construction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupancy_Statement_Dropdown__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Occupancy Statement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal Residence</fullName>
                </value>
                <value>
                    <fullName>Second Vacation Home</fullName>
                </value>
                <value>
                    <fullName>Investment Property</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>City of prospective customer's property</inlineHelpText>
        <label>Property Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Property Street Number and Street Name</inlineHelpText>
        <label>Property Address Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Zip Code of customer's property</inlineHelpText>
        <label>Property Address Zip/Postal Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GreenLightInquiryTest.cls
@isTest
public class GreenLightInquiryTest {
    
    public static testMethod void TestSendInquiry() {
        
        // Data setup
        Lead le1 = new Lead();
        le1.LastName = 'Test937153';
        le1.Status = 'Pending Qualification';
        le1.Company = 'Test983729';
        le1.Property_Street_Number_and_Name__c = '1234 Sesamy Street';
        le1.Property_City__c = 'Los Angeles';
        le1.Property_State__c = 'CA';
        le1.Property_Zip_Code__c = '00000';
        le1.New_Construction_Dropdown__c = 'Yes';
        le1.Occupancy_Statement_Dropdown__c = 'Principal Residence';
        le1.Property_Type__c = 'Townhouse';
		le1.Income_Monthly_Base__c  = 6000;
		le1.Home_Value__c =100000;        
        insert le1;

        Test.setMock(HttpCalloutMock.class, new GreenLightTest.MockClass());
        
        // Run the code
        Test.startTest();

        GreenLightInquiry ctrl = new GreenLightInquiry(new Apexpages.StandardController(le1));
        ctrl.MakeCall();
        Lead le2 = [SELECT Greenlight_Id__c, Inquiry_Sequence_ID__c FROM Lead WHERE Id = :le1.Id];

        Test.stopTest();
        
        // Verify Results
        System.assertEquals('test276834', le2.Greenlight_Id__c);
        System.assertEquals('test276835', le2.Inquiry_Sequence_ID__c);
        if (GreenLightAPI.Settings.Save_Logs__c)
            System.assertEquals(1, [SELECT COUNT() FROM GreenLight_API_Log__c]);
        
    }

    public static testMethod void TestSendInquiry_Errors() {
        
        // Data setup
        Lead le1 = new Lead();
        le1.LastName = 'Test937153';
        le1.Status = 'Pending Qualification';
        le1.Company = 'Test983729';
		le1.Income_Monthly_Base__c  = 6000;
		le1.Home_Value__c =100000;        
        insert le1;

        Test.setMock(HttpCalloutMock.class, new GreenLightTest.MockClass());
        
        // Run the code
        Test.startTest();

        GreenLightInquiry ctrl = new GreenLightInquiry(new Apexpages.StandardController(le1));
        ctrl.MakeCall();
        Lead le2 = [SELECT Greenlight_Id__c, Inquiry_Sequence_ID__c FROM Lead WHERE Id = :le1.Id];

        Test.stopTest();
        
        // Verify Results
        System.assertEquals(null, le2.Greenlight_Id__c);
        System.assertEquals(null, le2.Inquiry_Sequence_ID__c);
        
    }
}