objects/GreenLight_Decision_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>GreenLight_Decision__c</fullName>
        <label>GreenLight Decision</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Status__c</fullName>
        <label>Qualification Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>GreenLight Decision Mapping</label>
    <pluralLabel>GreenLight Decision Mappings</pluralLabel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_Tracking_ID__c</fullName>
        <description>There is one application id per application. Unison generates this at lead
            creation. We pushed this data into encompass. As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <displayFormat>FRX-{000000}</displayFormat>
        <label>Application Tracking ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Core_Logic_Property_Id__c</fullName>
        <description>The CoreLogic id of the property. As of Q4-2019, this field has been identified
            by Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Core Logic Property Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Median__c</fullName>
        <description>Forumula to get data from PCR object As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <formula>Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Score (Median)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Greenlight_Decision_Notes__c</fullName>
        <description>Text returned by Greenlight providing additional notes on pricing and/or the
            approval decision. As of Q4-2019, this field has been identified by Business Systems
            (and relevant stakeholders) as used or otherwise relevant to current business processes.
            To be reviewed next Q4 2021.</description>
        <label>Greenlight Decision Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Greenlight_Id__c</fullName>
        <description>The unique identifier for the Greenlight inquiry. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Greenlight Inquiry ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inquiry_Sequence_ID__c</fullName>
        <description>Unique identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made. As this field has direct effects on calls made to the Property Service, do not deprecate or otherwise alter without the express consent of the Engineering team.</description>
        <inlineHelpText>Unique Identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made.</inlineHelpText>
        <label>Inquiry Sequence ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Construction_Dropdown__c</fullName>
        <description>Deprecate As of Q4-2019, this field has been identified by Business Systems
            (and relevant stakeholders) as used or otherwise relevant to current business processes.
            To be reviewed next Q4 2021.</description>
        <label>Property New Construction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupancy_Statement_Dropdown__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Occupancy Statement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal Residence</fullName>
                </value>
                <value>
                    <fullName>Second Vacation Home</fullName>
                </value>
                <value>
                    <fullName>Investment Property</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Pricing Ratio based on Unison Program</inlineHelpText>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>City of prospective customer's property</inlineHelpText>
        <label>Property Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Pre_Qualification_Status__c</fullName>
        <description>status of the pre-qual As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Property Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Pre_Qualification_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Property Street Number and Street Name</inlineHelpText>
        <label>Property Address Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Zip Code of customer's property</inlineHelpText>
        <label>Property Address Zip/Postal Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>greenlight field As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as used or otherwise relevant to current business
            processes. To be reviewed next Q4 2021.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Pre_Qualification_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Not Enough Information</fullName>
    </customValue>
    <masterLabel>Property Pre-Qualification Status</masterLabel>
</GlobalValueSet>

classes/GreenLightHelper.cls
public class GreenLightHelper {
    
    // For test class purposes, just set this to true
    public static boolean skipCall = false;

    public static InquiryResponse SendInquiry(Id leadId) {

        Lead lead = [SELECT Id, Home_Value__c,RecordType.Name,Credit_Score_Median__c, Greenlight_Id__c,Pricing_Ratio__c, Inquiry_Sequence_ID__c, Occupancy_Statement_Dropdown__c, 
                            New_Construction_Dropdown__c, Application_Tracking_ID__c, Qualifies_for_New_HomeOwner_Pricing__c, 
                            Property_Street_Number_and_Name__c, Property_City__c, Property_State__c, Property_Zip_Code__c, Property_Type__c
                        FROM Lead WHERE Id = :leadId];

        InquiryResponse toReturn = SendInquiry(lead);

        if (toReturn.success) {
            try {
                update lead;
            } catch (Exception ex) {
                toReturn.success = false;
                toReturn.error = new InquiryResponseError();
                toReturn.error.statusCode = 200;
                toReturn.error.error = 'Callout succeded but the lead update failed';
                toReturn.error.message = ex.getMessage();
            }
        }

        return toReturn;
    }

    public static InquiryResponse SendInquiry(Lead lead) {

        if (skipCall)
            return new InquiryResponse(false, 'GreenLightHelper.skipCall is true');

        GreenLightAPI.AutoSaveLogs = true;

        if (lead.Greenlight_Id__c == null || lead.Greenlight_Id__c.trim() == '' || lead.Inquiry_Sequence_ID__c == null || lead.Inquiry_Sequence_ID__c.trim() == '') {
            // POST
            GreenLightAPI.PostInquiryRequest req = new GreenLightAPI.PostInquiryRequest();
            req.tracking_id = lead.Application_Tracking_ID__c;
            req.program_type = lead.RecordType.Name.toLowerCase();
            req.lead_id = lead.Id;
            req.property.property_type = lead.Property_Type__c;
            req.property.input_address.delivery_line = lead.Property_Street_Number_and_Name__c;
            req.property.input_address.city = lead.Property_City__c;
            req.property.input_address.state_abbreviation = lead.Property_State__c;
            req.property.input_address.postal_code = lead.Property_Zip_Code__c;
            req.property.occupancy_status = lead.Occupancy_Statement_Dropdown__c;
            req.property.is_new_construction = (lead.New_Construction_Dropdown__c == 'Yes') ? true : false;
            req.program.Qualifies_for_New_HomeOwner_Pricing_c_c = lead.Qualifies_for_New_HomeOwner_Pricing__c;
            req.financial.origination_credit_score = lead.Credit_Score_Median__c;

            GreenLightAPI.InquiryResponse res = GreenLightAPI.PostInquiry(req);

            System.debug(res);

            if (res.success) {
                lead.Greenlight_Id__c = res.inquiry_id;
                lead.Inquiry_Sequence_ID__c = res.inquiry_sequence_id;
                lead.Property_Pre_Qualification_Status__c = TransformStatus(res.decision);
                lead.Core_Logic_Property_Id__c = res.property.cl_property_id;
                lead.Pricing_Ratio__c = res.program.Pricing_Ratio_c_c;
                lead.Greenlight_Decision_Notes__c = res.notes.greenlight.finalNotes;
                lead.Home_Value__c = res.estimated_valuation;
                return new InquiryResponse(true, null);
            } else {
                return new InquiryResponse(false, res.error);
            }
        } else {
            // PUT
            GreenLightAPI.PutInquiryRequest req = new GreenLightAPI.PutInquiryRequest();
            req.inquiry_id = lead.Greenlight_Id__c;
            req.inquiry_sequence_id = lead.Inquiry_Sequence_ID__c;
            req.tracking_id = lead.Application_Tracking_ID__c;
            req.lead_id = lead.Id;
            req.property.property_type = lead.Property_Type__c;
            req.property.input_address.delivery_line = lead.Property_Street_Number_and_Name__c;
            req.property.input_address.city = lead.Property_City__c;
            req.property.input_address.state_abbreviation = lead.Property_State__c;
            req.property.input_address.postal_code = lead.Property_Zip_Code__c;
            req.property.occupancy_status = lead.Occupancy_Statement_Dropdown__c;
            req.property.is_new_construction = (lead.New_Construction_Dropdown__c == 'Yes') ? true : false;
            req.program.Qualifies_for_New_HomeOwner_Pricing_c_c = lead.Qualifies_for_New_HomeOwner_Pricing__c;
            req.financial.origination_credit_score = lead.Credit_Score_Median__c;            

            GreenLightAPI.InquiryResponse res = GreenLightAPI.PutInquiry(req);

            System.debug(res);

            if (res.success) {
                lead.Property_Pre_Qualification_Status__c = TransformStatus(res.decision);
                lead.Core_Logic_Property_Id__c = res.property.cl_property_id;
                lead.Pricing_Ratio__c = res.program.Pricing_Ratio_c_c; 
                lead.Greenlight_Decision_Notes__c = res.notes.greenlight.finalNotes;
                lead.Home_Value__c = res.estimated_valuation;
                return new InquiryResponse(true, null);
            } else {
                return new InquiryResponse(false, res.error);
            }
        }
    }

    private static Map<String, String> decisionMapping;
    private static string TransformStatus(string decision) {
        if (decisionMapping == null) {
            decisionMapping = new Map<String, String>();
            for (GreenLight_Decision_Mapping__mdt mdt : [SELECT GreenLight_Decision__c, Qualification_Status__c FROM GreenLight_Decision_Mapping__mdt]) {
                decisionMapping.put(mdt.GreenLight_Decision__c, mdt.Qualification_Status__c);
            }
        }
        if (decisionMapping.containsKey(decision))
            return decisionMapping.get(decision);
        return 'Not Enough Information';
    }

    public class InquiryResponse {
        public boolean success { get; set; }
        public InquiryResponseError error { get; set; }
        public InquiryResponse(boolean success, string response) {
            this.success = success;
            if (!success)
                this.error = (InquiryResponseError)JSON.deserialize(response, InquiryResponseError.class);
        }
    }
    public class InquiryResponseError {
        public integer statusCode { get; set; }
        public string error { get; set; }
        public string message { get; set; }
    }

}