objects/GreenLight_API_Log__c.object
<CustomObject>
    <label>GreenLight API Log</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>GreenLight API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GreenLight API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Greenlight_Id__c</fullName>
        <description>The unique identifier for the Greenlight inquiry. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Greenlight Inquiry ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Monthly_Base__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Income field used to determine DTI for the Lead: Base Income of the
            Applicant.</inlineHelpText>
        <label>Income Monthly Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inquiry_Sequence_ID__c</fullName>
        <description>Unique identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made. As this field has direct effects on calls made to the Property Service, do not deprecate or otherwise alter without the express consent of the Engineering team.</description>
        <inlineHelpText>Unique Identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made.</inlineHelpText>
        <label>Inquiry Sequence ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Pricing Ratio based on Unison Program</inlineHelpText>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Pre_Qualification_Status__c</fullName>
        <description>status of the pre-qual As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Property Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Pre_Qualification_Status</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Pre_Qualification_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Not Enough Information</fullName>
    </customValue>
    <masterLabel>Property Pre-Qualification Status</masterLabel>
</GlobalValueSet>

classes/GreenLightTest.cls
@isTest
public class GreenLightTest {
    
    public class MockClass implements HttpCalloutMock {
    
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse resp = new HTTPResponse();
            if (req.getEndpoint().contains('api/v3/inquiries')) {
                resp.setBody('{ ' +
                                '"inquiry_id": "test276834", ' +
                                '"inquiry_sequence_id": "test276835", ' +
                                '"decision": "approved", ' +
                                '"program": { ' +
                                    '"Pricing_Ratio__c": 4 ' +
                                '}, ' +  
                                '"notes": { ' +
                                    '"greenlight":{  ' +  
                                    	'"finalNotes":"Approved as HomeOwner, Owner-Occupied, Not New Construction."' +                             
                                	'} ' +                                
                                '}, ' +                                
                                '"property": { ' +
                                    '"cl_property_id": "test276836" ' +
                                '} ' +
                            '}');
            }
            resp.setStatusCode(200);
            return resp;
        }

    }
    
    public static testMethod void TestSendInquiry_Post() {
        
        // Data setup
        Lead le1 = new Lead();
        le1.LastName = 'Test937153';
        le1.Status = 'Pending Qualification';
        le1.Company = 'Test983729';
		le1.Income_Monthly_Base__c  = 6000;
		le1.Home_Value__c =100000;        
        insert le1;

        Test.setMock(HttpCalloutMock.class, new MockClass());
        
        // Run the code
        Test.startTest();

        GreenLightHelper.SendInquiry(le1.Id);
        Lead le2 = [SELECT Greenlight_Id__c, Inquiry_Sequence_ID__c FROM Lead WHERE Id = :le1.Id];

        Test.stopTest();
        
        // Verify Results
        System.assertEquals('test276834', le2.Greenlight_Id__c);
        System.assertEquals('test276835', le2.Inquiry_Sequence_ID__c);
        if (GreenLightAPI.Settings.Save_Logs__c)
            System.assertEquals(1, [SELECT COUNT() FROM GreenLight_API_Log__c]);
        
    }

    public static testMethod void TestSendInquiry_Put() {
        
        // Data setup
        Lead le1 = new Lead();
        le1.LastName = 'Test937153';
        le1.Status = 'Pending Qualification';
        le1.Company = 'Test983729';
        le1.Greenlight_Id__c = 'test276834';
        le1.Inquiry_Sequence_ID__c = 'test276835';
		le1.Income_Monthly_Base__c  = 6000;
		le1.Home_Value__c =100000;            
        insert le1;

        Test.setMock(HttpCalloutMock.class, new MockClass());
        
        // Run the code
        Test.startTest();

        GreenLightHelper.SendInquiry(le1.Id);
        Lead le2 = [SELECT Property_Pre_Qualification_Status__c FROM Lead WHERE Id = :le1.Id];

        Test.stopTest();
        
        // Verify Results
        System.assertEquals('Approved', le2.Property_Pre_Qualification_Status__c);
        if (GreenLightAPI.Settings.Save_Logs__c)
            System.assertEquals(1, [SELECT COUNT() FROM GreenLight_API_Log__c]);
        
    }

}