objects/Invalid_State_County__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decline_Error_Message__c</fullName>
        <label>Decline Error Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Type__c</fullName>
        <label>Loss Reason Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <label>Loss Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Invalid State/County</label>
    <pluralLabel>Invalid State/County</pluralLabel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Autopilot_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Autopilot Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Loss Reason Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant does not meet non-credit related application criteria</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Collection action or judgement</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>COVID-19</fullName>
                </value>
                <value>
                    <fullName>Customer information is fake or cannot be used to contact the customer</fullName>
                </value>
                <value>
                    <fullName>Delinquent past or present obligations with others</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income &amp; Insufficient equity in the property</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income &amp; value of property in excess of allowed maximum</fullName>
                </value>
                <value>
                    <fullName>Felony</fullName>
                </value>
                <value>
                    <fullName>First contact - Asked to be removed</fullName>
                </value>
                <value>
                    <fullName>Frustration with Unison</fullName>
                </value>
                <value>
                    <fullName>Garnishment or attachment</fullName>
                </value>
                <value>
                    <fullName>Insufficient equity in the property</fullName>
                </value>
                <value>
                    <fullName>Insufficient savings for purchase price range</fullName>
                </value>
                <value>
                    <fullName>Lack of trust</fullName>
                </value>
                <value>
                    <fullName>Lender (HB only)</fullName>
                </value>
                <value>
                    <fullName>Length of employment</fullName>
                </value>
                <value>
                    <fullName>Length of residence</fullName>
                </value>
                <value>
                    <fullName>No credit file</fullName>
                </value>
                <value>
                    <fullName>Non-English / Non-Spanish Speaker</fullName>
                </value>
                <value>
                    <fullName>Non-owner occupied property</fullName>
                </value>
                <value>
                    <fullName>Notice of default, foreclosure or repossession</fullName>
                </value>
                <value>
                    <fullName>Not operating in requested state</fullName>
                </value>
                <value>
                    <fullName>Number of recent inquiries on credit bureau report</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Reported Credit (single score) below our minimum requirement</fullName>
                </value>
                <value>
                    <fullName>Reported credit below our minimum requirement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Select Lead Loss Type (Decline, Invalid, or No Sale)</inlineHelpText>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <description>The property’s county. Mapped to the Property object
            (property.Property_County__c) at lead conversion.</description>
        <inlineHelpText>The property’s county.</inlineHelpText>
        <label>Property County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/leadDeclineHelper.cls
/************************************************************************************
 Apex Class Name     : leadDeclineHelper
 Version             : 1.0
 Created Date        : 27th August 2019
 Function            : Helper APEX class for Lead Before trigger context to process cases
						where leads should be auto-declined
 Author              : Jason Sun
 
 Modification Log    :
* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Jason Sun           	08/27/2019                Original Version
*************************************************************************************
* Caro Veliz :
* To implement ticket:
* https://unison-technology.atlassian.net/browse/BUS-155110006
*/
public class leadDeclineHelper {

    private static Map<string,Invalid_State_County__mdt> invalidList;
    public static void autoDeclineLeads(List<Lead> beforeTriggerLeads){
        for(Lead l: beforeTriggerLeads){
            declineTestLead(l);
            declineCounty(l);
        }
    }
    
    //Logic to auto-decline test leads.  Replaces TestLead Process Builder
    private static void declineTestLead(Lead theLead){
        if((theLead.FirstName != NULL &&theLead.FirstName.containsIgnoreCase('test')) || theLead.LastName.containsIgnoreCase('test')){
            theLead.Autopilot_Sync__c = false;
            theLead.Loss_Reason_Type__c = LABEL.CustomerInformationFake;
            theLead.Status = LABEL.Closed_Lost;
            theLead.Loss_Type__c = LABEL.Invalid;
        }
    }
    
    private static string getStateCountyKey(string state, string county){
        return state + '-' + county;
    }
    private static void getInvalidStateCounty(){
        invalidList = new Map<string,Invalid_State_County__mdt>();
        for( Invalid_State_County__mdt invalidStateCounty: [ select
                                                        MasterLabel,
                                                        DeveloperName,
                                                        County__c,
                                                        State__c,
                                                        Loss_Type__c,
                                                        Loss_Reason_Type__c,
                                                        Decline_Error_Message__c
                                                        from Invalid_State_County__mdt
                                                        where active__c = true]){
            invalidList.put( getStateCountyKey(invalidStateCounty.State__c, invalidStateCounty.County__c ),  invalidStateCounty);
        }
    }
    private static void declineCounty(Lead theLead){
        getInvalidStateCounty();

        string key = getStateCountyKey(theLead.Property_State__c, theLead.Property_County__c);
        Invalid_State_County__mdt invalidStateCounty = invalidList.get(key);
        system.debug(invalidStateCounty);
        if (invalidStateCounty != null) {
            theLead.Status = 'Closed Lost';
            theLead.Loss_Type__c = invalidStateCounty.Loss_Type__c;
            theLead.Loss_Reason_Type__c = invalidStateCounty.Loss_Reason_Type__c;
            system.debug(theLead.Status);
            system.debug(theLead.Loss_Type__c);
            system.debug(theLead.Loss_Reason_Type__c);
        }
    }
    
}