objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Unison's Investment Payment. This amount should not exceed Max Offer amount.</inlineHelpText>
        <label>Estimated Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tune_Offer_Id__c</fullName>
        <label>Tune Offer Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tune_Transaction_Id__c</fullName>
        <label>Tune Transaction Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tune_Offer_Id__c</fullName>
        <label>Tune Offer Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tune_Transaction_Id__c</fullName>
        <label>Tune Transaction Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tune_Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tune Integration Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Tune Integration Log No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tune Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tune_Integration_URL__mdt.object
<CustomObject>
    <fields>
        <fullName>Tune_Goal_Name__c</fullName>
        <label>Tune Goal Name</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tune_Offer_Id__c</fullName>
        <label>Tune Offer Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tune Integration URL</label>
    <pluralLabel>Tune Integration URLs</pluralLabel>
</CustomObject>

classes/TuneIntegration.cls
public class TuneIntegration {

    private static Map<string, string> urlSettingsP;
    public static Map<string, string> urlSettings {
        get {
            if (urlSettingsP == null) {
                urlSettingsP = new Map<string, string>();
                for (Tune_Integration_URL__mdt stg : [SELECT Tune_Goal_Name__c, Tune_Offer_Id__c, URL__c FROM Tune_Integration_URL__mdt]) {
                    urlSettingsP.put(stg.Tune_Goal_Name__c + '~' + stg.Tune_Offer_Id__c, stg.URL__c);
                }
            }
            return urlSettingsP;
        }
    }
    
    private static List<Tune_Integration_Log__c> logList;
    
    @future(callout=true)
    public static void SendLeadsToTune(Map<Id, String> leadIds) {
        
        for (Lead l : [SELECT Tune_Transaction_Id__c, Tune_Offer_Id__c FROM Lead WHERE Id IN :leadIds.keyset()]) {
            MakeCall(l.Id, leadIds.get(l.Id), l.Tune_Offer_Id__c, l.Tune_Transaction_Id__c, '', '');
        }
        
        if (logList != null && logList.size() > 0) {
            insert logList;
            logList = new List<Tune_Integration_Log__c>();
        }
        
    }
    
    @future(callout=true)
    public static void SendOppsToTune(Map<Id, String> oppIds) {
        
        for (Opportunity o : [SELECT Tune_Transaction_Id__c, Tune_Offer_Id__c, Estimated_Funding_Amount__c, Wire_to_Agent_Date__c FROM Opportunity WHERE Id IN :oppIds.keyset()]) {
            MakeCall(o.Id, oppIds.get(o.Id), o.Tune_Offer_Id__c, o.Tune_Transaction_Id__c, 
                     		o.Estimated_Funding_Amount__c == null ? '' : string.valueOf(o.Estimated_Funding_Amount__c), 
                     		o.Wire_to_Agent_Date__c == null ? '' : string.valueOf(o.Wire_to_Agent_Date__c));
        }
        
        if (logList != null && logList.size() > 0) {
            insert logList;
            logList = new List<Tune_Integration_Log__c>();
        }
        
    }
    
    public static void MakeCall(Id recordId, string goalName, string offerId, string transactionId, string amount, string agentDate) {
        
        if (!urlSettings.containsKey(goalName + '~' + offerId))
            return;
        
        string url = urlSettings.get(goalName + '~' + offerId).replace('{{recordId}}', recordId)
            												  .replace('{{transactionId}}', transactionId)
            												  .replace('{{amount}}', amount)
            												  .replace('{{agentDate}}', agentDate);
        
        Http h = new Http();
    
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');
    
        HttpResponse res = h.send(req);
        
        if (logList == null) {
            logList = new List<Tune_Integration_Log__c>();
        }
        Tune_Integration_Log__c log = new Tune_Integration_Log__c();
        log.URL__c = url;
        if (log.URL__c != null && log.URL__c.length() > 254)
            log.URL__c = log.URL__c.substring(0, 250) + '...';
        log.Response_Code__c = res.getStatusCode();
        log.Response_Body__c = res.getBody();
        if (log.Response_Body__c != null && log.Response_Body__c.length() > 32767)
            log.Response_Body__c = log.Response_Body__c.substring(0, 32760) + '...';
        logList.add(log);
        
    }
    
}