objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Autopilot_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Autopilot Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss_Reason_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Loss Reason Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Loss_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant does not meet non-credit related application criteria</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Collection action or judgement</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>COVID-19</fullName>
                </value>
                <value>
                    <fullName>Customer information is fake or cannot be used to contact the customer</fullName>
                </value>
                <value>
                    <fullName>Delinquent past or present obligations with others</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income &amp; Insufficient equity in the property</fullName>
                </value>
                <value>
                    <fullName>Excessive obligations in relation to income &amp; value of property in excess of allowed maximum</fullName>
                </value>
                <value>
                    <fullName>Felony</fullName>
                </value>
                <value>
                    <fullName>First contact - Asked to be removed</fullName>
                </value>
                <value>
                    <fullName>Frustration with Unison</fullName>
                </value>
                <value>
                    <fullName>Garnishment or attachment</fullName>
                </value>
                <value>
                    <fullName>Insufficient equity in the property</fullName>
                </value>
                <value>
                    <fullName>Insufficient savings for purchase price range</fullName>
                </value>
                <value>
                    <fullName>Lack of trust</fullName>
                </value>
                <value>
                    <fullName>Lender (HB only)</fullName>
                </value>
                <value>
                    <fullName>Length of employment</fullName>
                </value>
                <value>
                    <fullName>Length of residence</fullName>
                </value>
                <value>
                    <fullName>No credit file</fullName>
                </value>
                <value>
                    <fullName>Non-English / Non-Spanish Speaker</fullName>
                </value>
                <value>
                    <fullName>Non-owner occupied property</fullName>
                </value>
                <value>
                    <fullName>Notice of default, foreclosure or repossession</fullName>
                </value>
                <value>
                    <fullName>Not operating in requested state</fullName>
                </value>
                <value>
                    <fullName>Number of recent inquiries on credit bureau report</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Reported Credit (single score) below our minimum requirement</fullName>
                </value>
                <value>
                    <fullName>Reported credit below our minimum requirement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Select reason for the lead loss.</inlineHelpText>
        <label>Loss Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Loss_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Select Lead Loss Type (Decline, Invalid, or No Sale)</inlineHelpText>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/leadDeclineHelper_test.cls
/************************************************************************************
 Apex Class Name     : leadDeclineHelperTest
 Version             : 1.0
 Created Date        : 27th August 2019
 Function            : test Class to cover leadDeclineHelperClass
 Author              : Jason Sun
 
 Modification Log    :
* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Jason Sun           	08/27/2019                Original Version
*************************************************************************************
* changed by Caro Veliz.
* Implementing ticket : https://unison-technology.atlassian.net/browse/BUS-155110006
* 
*/
@isTest
public class leadDeclineHelper_test {

    public static testMethod void test_declineTestLead(){
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('Lead');
        Schema.DescribeSobjectResult objTypeDesc = objType.getDescribe();
        map<Id, Schema.RecordTypeInfo> recTypeMap = objTypeDesc.getRecordTypeInfosById();
        system.debug('**recTypeMap**'+recTypeMap);
        Map<string,Id> mapretypes = new Map<string,Id>();
        for(Schema.RecordTypeInfo s : recTypeMap.values()){
            mapretypes.put(s.getDeveloperName(),s.getrecordtypeId());
        }
        
        //setup firstName Case
		List<Lead> ldlist = new List<Lead>();
        Lead ld1 = new Lead();
        ld1.recordtypeid = mapretypes.get('HomeOwner');
        ld1.FirstName = 'jeiroTestERlif';
        ld1.LastName = 'Last';
        ld1.Company = 'Test Last Company'; 
        ld1.Autopilot_Sync__c = true;
        
        //setup LastName Case        
        Lead ld2 = new Lead();
        ld2.recordtypeid = mapretypes.get('HomeOwner');
        ld2.FirstName = 'First';
        ld2.LastName = 'asldkfjTest23049fdj';
        ld2.Company = 'John Company';
        ld2.Autopilot_Sync__c = true;
        
        //setup Negative Case           
        Lead ld3 = new Lead();
        ld3.recordtypeid = mapretypes.get('HomeOwner');
        ld3.FirstName = 'First';
        ld3.LastName = 'Last';
        ld3.Company = 'First Last Company'; 
        ld3.Autopilot_Sync__c = true;        
        
        ldlist.add(ld1);
        ldlist.add(ld2);
        ldlist.add(ld3);
		
        //invoke processing method
		leadDeclineHelper.autoDeclineLeads(ldlist);
		
        //asserts positive casees
        system.assertEquals(false,ld1.Autopilot_Sync__c);
        system.assertEquals(LABEL.Closed_Lost,ld1.Status);
        system.assertEquals(LABEL.Invalid,ld1.Loss_Type__c);       
        
        system.assertEquals(false,ld2.Autopilot_Sync__c);
        system.assertEquals(LABEL.Closed_Lost,ld2.Status);
        system.assertEquals(LABEL.Invalid,ld2.Loss_Type__c);
        system.assertEquals(LABEL.CustomerInformationFake,ld2.Loss_Reason_Type__c);
        
        system.assertNotEquals(false,ld3.Autopilot_Sync__c);
        system.assertNotEquals(LABEL.CustomerInformationFake,ld3.Loss_Reason__c);
        system.assertNotEquals(LABEL.Closed_Lost,ld3.Status);
        system.assertNotEquals(LABEL.Invalid,ld3.Loss_Type__c);        
    }
    
}