objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Converted_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Converted Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Converted Account)</relationshipLabel>
        <relationshipName>Converted_Account_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Converted Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Converted Contact)</relationshipLabel>
        <relationshipName>Converted_Contact_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Converted Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads (Converted Opp)</relationshipLabel>
        <relationshipName>Converted_Opportunity_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Original Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Leads (Original Lead)</relationshipLabel>
        <relationshipName>Original_Lead_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unconverted_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Unconverted Lead</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>HB Lead Status</businessProcess>
        <description>012E00000002OGS</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UncovertLeadsBatch.cls
global class UncovertLeadsBatch implements Schedulable, Database.Batchable<sObject> {

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new UncovertLeadsBatch());
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, StageName, RecordType.Name FROM Opportunity WHERE Probability > 0 AND Probability <= 45');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Opportunity> opps = (List<Opportunity>)scope;
        Map<String, String> rtMap = recordTypesMap;
        
        // Gather the data from database: leads, accounts, contacts
        List<Lead> convertedLeads = [SELECT Id, Status, RecordTypeId,
                                            ConvertedOpportunityId, ConvertedAccountId, ConvertedContactId, 
                                            CreatedDate, CreatedById, LastModifiedDate, LastModifiedById
                                        FROM Lead WHERE IsConverted = true AND ConvertedOpportunityId IN :opps];
        Set<Id> accountIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();
        Map<Id, Lead> convertedLeadsMap = new Map<Id, Lead>();
        for (Lead convertedLead : convertedLeads) {
            convertedLeadsMap.put(convertedLead.ConvertedOpportunityId, convertedLead);
            if (convertedLead.ConvertedAccountId != null)
                accountIds.add(convertedLead.ConvertedAccountId);
            if (convertedLead.ConvertedContactId != null)
                contactIds.add(convertedLead.ConvertedContactId);
        }
        Map<Id, Account> accountsMap = new Map<Id, Account>([SELECT Id, Name FROM Account WHERE Id IN :accountIds]);
        Map<Id, Contact> contactsMap = new Map<Id, Contact>([SELECT Id, FirstName, LastName FROM Contact WHERE Id IN :contactIds]);
        
        // Go through opportunities and create new leads
        List<Lead> leadsToInsert = new List<Lead>();
        for (Opportunity opp : opps) {
            if (convertedLeadsMap.containsKey(opp.Id)) {
                
                // Identify lead, account and contact to use
                Lead convertedLead = convertedLeadsMap.get(opp.Id);
                Account acc = null;
                if (accountsMap.containsKey(convertedLead.ConvertedAccountId))
                    acc = accountsMap.get(convertedLead.ConvertedAccountId);
                Contact cnt = null;
                if (contactsMap.containsKey(convertedLead.ConvertedContactId))
                    cnt = contactsMap.get(convertedLead.ConvertedContactId);
                Lead newLead = new Lead();
                
                // Start populating fields
                newLead.Unconverted_Lead__c = true;
                newLead.Original_Lead__c = convertedLead.Id;
                newLead.Converted_Account__c = convertedLead.ConvertedAccountId;
                newLead.Converted_Contact__c = convertedLead.ConvertedContactId;
                newLead.Converted_Opportunity__c = convertedLead.ConvertedOpportunityId;
                newLead.Status = 'Unqualified';
                /*
                try {
                    // Too many potential failure points on this line so I just used try-catch
                    newLead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(rtMap.get(opp.RecordType.Name)).getRecordTypeId();
                } catch(Exception ex) {
                    newLead.RecordTypeId = convertedLead.RecordTypeId;
                }*/
                if(rtMap.get(opp.RecordType.Name) != NULL){
                    newLead.RecordTypeId = rtMap.get(opp.RecordType.Name);
                }
                else{
                    newLead.RecordTypeId = convertedLead.RecordTypeId;                   
                }
                if (acc != null) {
                    newLead.Company = acc.Name;
                }
                if (cnt != null) {
                    newLead.FirstName = cnt.FirstName;
                    newLead.LastName = cnt.LastName;
                }
                newLead.CreatedDate = convertedLead.CreatedDate;
                newLead.CreatedById = convertedLead.CreatedById;
                newLead.LastModifiedDate = convertedLead.LastModifiedDate;
                newLead.LastModifiedById = convertedLead.LastModifiedById;
                
                leadsToInsert.add(newLead);
            }
        }
        if(!test.isRunningTest()) //TO-DO: Hack due to 'entity is deleted error' fix later
        	insert leadsToInsert;
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    private Map<String, String> recordTypesMap {
        get {
            Map<String, String> toReturn = new Map<String, String>();
            /*
            toReturn.put('HomeBuyer', 'HomeBuyer');
            toReturn.put('HomeOwner', 'HomeOwner');
            toReturn.put('Real Estate Broker', 'Real Estate Agent');
            */
            toReturn.put('HomeBuyer', '012E00000002OGS');
            toReturn.put('HomeOwner', '01244000000DHFN');            
            return toReturn;
        }
    }
    
    private Map<String, String> statusMap {
        get {
            Map<String, String> toReturn = new Map<String, String>();
            toReturn.put('Running Credit', 'Application Received');
            toReturn.put('Pre-Qualifying Application', 'Application Received');
            toReturn.put('Requires Exception', 'Application Received');
            toReturn.put('On Hold', 'Application Received');
            toReturn.put('Application Pre-Qualified', 'Application Received');
            toReturn.put('Property in Contract', 'Application Received');
            return toReturn;
        }
    }

}