objects/Lead.object
<CustomObject>
    <fields>
        <fullName>First_Lender_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lender of the first mortgage on the subject property. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <inlineHelpText>Look-up Mortgage or HELOC credit tradeline from Personal Credit
            Report</inlineHelpText>
        <label>First Lender Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>LASERCA__Trade_Accounts__c.LASERCA__Credit_Loan_Type__c</field>
                <operation>equals</operation>
                <value>Mortgage</value>
            </filterItems>
            <filterItems>
                <field>LASERCA__Trade_Accounts__c.LASERCA__Account_Balance__c</field>
                <operation>greaterThan</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Trade_Accounts__c</referenceTo>
        <relationshipLabel>Leads (First Lender)</relationshipLabel>
        <relationshipName>Leads_First_Lender_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Lender_Open_Date__c</fullName>
        <description>The date the first mortgage on the subject property was opened. As of Q4-2019,
            this field has been identified by Business Systems (and relevant stakeholders) as used
            or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>First Lender Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Lender_Original_Amount__c</fullName>
        <description>The original mortgage amount of the first mortgage on the subject property. As
            of Q4-2019, this field has been identified by Business Systems (and relevant
            stakeholders) as used or otherwise relevant to current business processes. To be
            reviewed next Q4 2021.</description>
        <label>First Lender Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Balance__c</fullName>
        <description>2019-10-28 - The balance of what is owned to the lender who is in first lien
            position. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Lien First Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_First_Lender_Name__c</fullName>
        <description>2019-10-28 - The name of the lender in first lien position. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Lien First Lender Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lien_Second_Lender_Balance__c</fullName>
        <description>2019-10-28 - The balance of what is owned to the lender who is in second lien
            position. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Lien Second Lender Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lien_Second_Lender_Name__c</fullName>
        <description>2019-10-28 - The name of the lender in second lien position. As of Q4-2019,
            this field has been identified by Business Systems (and relevant stakeholders) as used
            or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Lien Second Lender Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Credit_Score_PCR__c</fullName>
        <description>2019-10-28 - Need to find out how this is used. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Personal Credit Report Id with the highest credit score</inlineHelpText>
        <label>Max Credit Score PCR</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Monthly_First_Mortgage__c</fullName>
        <description>Monthly first mortgage payment As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Monthly Payment of First Mortgage (entered manually or populated from
            Personal Credit Report)</inlineHelpText>
        <label>Payment Monthly First Mortgage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Monthly_Second_Mortgage__c</fullName>
        <description>Monthly secondmortgage payment As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Monthly Payment of Second Mortgage (entered manually or populated from
            Personal Credit Report)</inlineHelpText>
        <label>Payment Monthly Second Mortgage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It's a link to the credit report of the lead contact As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Selected Personal Credit Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LASERCA__Personal_Credit_Report__c.LASERCA__Lead__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Lender_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to calculate DTI and LTV As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Look-up Mortgage or HELOC credit tradeline from Personal Credit Report</inlineHelpText>
        <label>Second Lender Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LASERCA__Trade_Accounts__c.LASERCA__Personal_Credit_Report__r.LASERCA__Lead__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>LASERCA__Trade_Accounts__c.LASERCA__Credit_Loan_Type__c</field>
                <operation>equals</operation>
                <value>Mortgage,HELOC</value>
            </filterItems>
            <filterItems>
                <field>LASERCA__Trade_Accounts__c.LASERCA__Account_Balance__c</field>
                <operation>greaterThan</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LASERCA__Trade_Accounts__c</referenceTo>
        <relationshipLabel>Leads (Second Lender Name)</relationshipLabel>
        <relationshipName>Leads_Second_Lender_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sum_of_Debt_Payments__c</fullName>
        <description>The sum of debt payments. Used in DTI and LTV calculation As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <inlineHelpText>Sum of Monthly Debt not being Paid Off (excluding monthly mortgage payments)</inlineHelpText>
        <label>Sum of Debt Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sum_of_Debt_to_be_Paid_Off__c</fullName>
        <description>The sum of all debts to be paid off in the course of doing business with
            Unison. Used in DTI and LTV calculation As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Total Trade Account balances marked to be paid off.</inlineHelpText>
        <label>Sum of Debt to be Paid Off</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Lead_Financial_Calc_EXT.cls
/**
 *  About
 *  -----
 *  Author: Cloud Mine Consulting
 *  Create date: 9/1/2017
 *
 *  Details
 *  -----
 *  Controller Extension for Lead Financial Calculator Controller
 *  Test Class: Lead_Financial_Calc_Test
 *
 *  Update History
 *  -----
 *
 *  Issues / TODOs
 *  -----
 *
**/
public class Lead_Financial_Calc_EXT {

    private final Id leadId;
    public Lead theLead {get; set;}
    public List<LASERCA__Trade_Accounts__c> tradeAccounts {get;set;}

    public Lead_Financial_Calc_EXT(ApexPages.StandardController sc){
        this.leadId = sc.getId();
        init();
    }

    private void init(){
        List<Schema.FieldSetMember> leadFields = SObjectType.Lead.FieldSets.Lead_Financial_Calc_Fields.getFields();

        String query = 'SELECT ';
        for(Schema.FieldSetMember f : leadFields) {
            query += f.getFieldPath() + ', ';
        }
        query += ' Id, Max_Credit_Score_PCR__c, Personal_Credit_Report__c FROM Lead WHERE Id=\'' + this.LeadId + '\'LIMIT 1';

        this.theLead = Database.query(query);
        tradeAccounts = new List<LASERCA__Trade_Accounts__c>();
        for(LASERCA__Trade_Accounts__c tradeAcct: [SELECT To_Be_Paid_Off__c, Name, LASERCA__Account_Balance__c, LASERCA__Credit_Loan_Type__c, LASERCA__Monthly_Payment__c,LASERCA__Account_Type__c,Unison_Calculated_Monthly_Payment__c, Exclude__c, Lien_Position__c, LASERCA__Personal_Credit_Report__r.Sum_of_Debt_Payments__c
                                                   FROM LASERCA__Trade_Accounts__c
                                                   WHERE LASERCA__Account_Status_Type__c = 'Open'
                                                   AND (LASERCA__Account_Balance__c > 0  OR LASERCA__Account_Balance__c = NULL)
                                                   //Filters originally defined by Paul Tucker
                                                   //removed on 4/2/2019 per Tutt, Director of Sales
                                                   //"Our needs are changing so it's important to get all trade lines"
                                                   /*AND (NOT (Remaining_Term__c <= 10
                                                             AND Remaining_Term__c > 0
                                                             AND Remaining_Term__c != NULL
                                                             AND LASERCA__Account_Type__c = 'Installment'
                                                             AND (NOT (LASERCA__Credit_Text__c LIKE '%lease%' AND LASERCA__Credit_Loan_Type__c = 'Automobile'))
                                                            )
                                                       )*/
                                                   AND LASERCA__Personal_Credit_Report__r.LASERCA__Lead__c =:this.leadId AND LASERCA__Personal_Credit_Report__c = :theLead.Personal_Credit_Report__c
                                                   ORDER BY LASERCA__Account_Balance__c DESC NULLS LAST]){
            tradeAccounts.add(tradeAcct);
        }
    }

    public void updateCalcs(){
        if(validateLienPositions()){
            system.savePoint sp = database.setSavepoint();
            update tradeAccounts;

            System.System.debug('*** in update CALC: ');
            theLead.First_Lender_Name__c = NULL;
            theLead.Second_Lender_Name__c = NULL;

            // Brad: Updated conditionals on "First"/"Second" to "1" and "2"
            // Uncommented assignment and NULL assigments below
            for(LASERCA__Trade_Accounts__c acct: this.tradeAccounts){
                if(acct.Lien_Position__c == '1'){
                  // system.System.debug('*** HERE FIRST: ');
                  theLead.First_Lender_Name__c = acct.Id;
                }
                if(acct.Lien_Position__c == '2'){
                  // System.System.debug('*** HERE IN 2: ');
                    theLead.Second_Lender_Name__c = acct.Id;
                }
            }

            //clear 1st & 2nd lender associated fields if they're still null by this point
            if(theLead.First_Lender_Name__c == NULL){
                theLead.Lien_First_Lender_Name__c = NULL;
                theLead.Lien_First_Lender_Balance__c = NULL;
                theLead.First_Lender_Open_Date__c = NULL;
                theLead.First_Lender_Original_Amount__c = NULL;
                theLead.Payment_Monthly_First_Mortgage__c = NULL;
            }
            if(theLead.Second_Lender_Name__c == NULL){
                theLead.Lien_Second_Lender_Name__c = NULL;
                theLead.Lien_Second_Lender_Balance__c = NULL;
                theLead.Payment_Monthly_Second_Mortgage__c = NULL;
            }

            List<LASERCA__Personal_Credit_Report__c> pcr = [SELECT Sum_of_Debt_Payments__c, Sum_of_Debt_to_be_Paid_Off__c FROM LASERCA__Personal_Credit_Report__c WHERE Id =: theLead.Personal_Credit_Report__c];
            if(pcr.size() > 0)
            {
                theLead.Sum_of_Debt_Payments__c = pcr[0].Sum_of_Debt_Payments__c;
                theLead.Sum_of_Debt_to_be_Paid_Off__c = pcr[0].Sum_of_Debt_to_be_Paid_Off__c;
            }
            try{
                update theLead;
            }
            catch(DmlException e){
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'An error occurred trying to save.  ' + e.getMessage()) );
                database.rollback(sp);
            }
        }
        else{
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'You cannot assign more than one lien position of each type') );
        }
        init();
    }

    private boolean validateLienPositions(){
        integer first_count = 0;
        integer second_count = 0;
        integer third_count = 0;
        for(LASERCA__Trade_Accounts__c acct: this.tradeAccounts){
            if(acct.Lien_Position__c == 'First'){
                first_count++;
            }
            if(acct.Lien_Position__c == 'Second'){
                second_count++;
            }
            if(acct.Lien_Position__c == 'Third'){
                third_count++;
            }

            if(first_count > 1 || second_count > 1 || third_count > 1){
                return false;
            }
        }
        return true;
    }

}