objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_Tracking_ID__c</fullName>
        <description>There is one application id per application. Unison generates this at lead
            creation. We pushed this data into encompass. As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <displayFormat>FRX-{000000}</displayFormat>
        <label>Application Tracking ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Median__c</fullName>
        <description>Forumula to get data from PCR object As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <formula>Personal_Credit_Report__r.LASERCA__Credit_Score_Median__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Score (Median)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Greenlight_Id__c</fullName>
        <description>The unique identifier for the Greenlight inquiry. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Greenlight Inquiry ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Value__c</fullName>
        <description>This is the estimated value of the home, according to AVMs provided by
            Greenlight. As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inquiry_Sequence_ID__c</fullName>
        <description>Unique identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made. As this field has direct effects on calls made to the Property Service, do not deprecate or otherwise alter without the express consent of the Engineering team.</description>
        <inlineHelpText>Unique Identifier linked to a Greenlight inquiry ID, used to identify the sequence in which the inquiry was made.</inlineHelpText>
        <label>Inquiry Sequence ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Construction_Dropdown__c</fullName>
        <description>Deprecate As of Q4-2019, this field has been identified by Business Systems
            (and relevant stakeholders) as used or otherwise relevant to current business processes.
            To be reviewed next Q4 2021.</description>
        <label>Property New Construction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupancy_Statement_Dropdown__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Occupancy Statement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal Residence</fullName>
                </value>
                <value>
                    <fullName>Second Vacation Home</fullName>
                </value>
                <value>
                    <fullName>Investment Property</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>City of prospective customer's property</inlineHelpText>
        <label>Property Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Pre_Qualification_Status__c</fullName>
        <description>status of the pre-qual As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Property Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Pre_Qualification_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>State of customer's property</inlineHelpText>
        <label>Property Address State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Property Street Number and Street Name</inlineHelpText>
        <label>Property Address Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single-family detached</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>2-4 Family</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <description>As of Q4-2019, this field has been identified by Business Systems (and
            relevant stakeholders) as used or otherwise relevant to current business processes. To
            be reviewed next Q4 2021.</description>
        <inlineHelpText>Zip Code of customer's property</inlineHelpText>
        <label>Property Address Zip/Postal Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>greenlight field As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as used or otherwise relevant to current business
            processes. To be reviewed next Q4 2021.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Pre_Qualification_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Not Enough Information</fullName>
    </customValue>
    <masterLabel>Property Pre-Qualification Status</masterLabel>
</GlobalValueSet>

classes/GreenLightInquiry.cls
public class GreenLightInquiry {
    
    public Id leadId { get; set; }
    public Lead theLead;
    public boolean submitted { get; set; }
    public string preQualResult {get; set; }
    
    public GreenLightInquiry(ApexPages.StandardController ctrl) {
        leadId = ctrl.getId();
        theLead = [SELECT Id, Name,Credit_Score_Median__c, Property_State__c, Property_Zip_Code__c, Property_Street_Number_and_Name__c, Application_Tracking_ID__c, Property_Type__c,
                  			Home_Value__c, Property_City__c, RecordType.Name, Owner.Name, Owner.Email, Qualifies_for_New_HomeOwner_Pricing__c,
                   			New_Construction_Dropdown__c, Occupancy_Statement_Dropdown__c, Greenlight_Id__c, Inquiry_Sequence_ID__c, Property_Pre_Qualification_Status__c
                 	FROM Lead WHERE Id = :leadId];
        submitted = false;
    }
    
    public void MakeCall() {
		//validate all required values are present
        List<ApexPages.Message> errorMessages = new List<ApexPages.Message>();
        if (theLead.Property_Street_Number_and_Name__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'Property Street Number and Name is required order to submit inquiry.'));            
        }
        if (theLead.Property_City__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'Property City is required order to submit inquiry.'));            
        }  
        if (theLead.Property_State__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'Property State is required order to submit inquiry.'));            
        } 
        if (theLead.Property_Zip_Code__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'Property Zip is required order to submit inquiry.'));            
        }   
        if (theLead.New_Construction_Dropdown__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'New Construction is required order to submit inquiry.'));            
        }
        if (theLead.Occupancy_Statement_Dropdown__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'Occupancy Statement is required order to submit inquiry.'));            
        }
        if (theLead.Property_Type__c == NULL) {
            errorMessages.add(new ApexPages.Message(ApexPages.Severity.ERROR, 'Property Type is required order to submit inquiry.'));            
        }
 
        if (!errorMessages.isEmpty()) {
            for (ApexPages.Message msg: errorMessages) {
            	ApexPages.addMessage(msg);   
            }	   
        } else {                    
            GreenLightHelper.InquiryResponse result = GreenLightHelper.SendInquiry(theLead);
            if (result.success) {

                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Inquiry submitted successfully'));
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Property Pre-Qual Result:' + theLead.Property_Pre_Qualification_Status__c));
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Inquiry Id:' + theLead.Greenlight_Id__c));
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Inquiry Sequence Id:' + theLead.Inquiry_Sequence_ID__c));

                try {
                    update theLead;
                } catch (Exception ex) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error updating lead:' + ex.getMessage()));
                }
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error from GreenLight Server: ' + result.error.message));
            }
        }
        submitted = true;        
    }

}