objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Agency_or_Non_Agency__c</fullName>
        <description>Homebuyer only. Whether the first mortgage will be agency or non-agency. As of
            Q4-2019, this field has been identified by Business Systems (and relevant stakeholders)
            as used or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Agency or Non-Agency?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bankrupcy_in_last_seven_years_co__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Bankrupcy in last seven years? (Co)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Address__c</fullName>
        <description>The address of the Co-Applicant As of Q4-2019, this field has been identified
            by Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Address Street Name and Number (Co)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_BirthDate__c</fullName>
        <description>2019-10-18 - Birthdate of the co-applicant. Used in many places. As of Q4-2019,
            this field has been identified by Business Systems (and relevant stakeholders) as used
            or otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Co-Applicant BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_City__c</fullName>
        <description>Current Address (city) of the co-applicant As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <label>Address City (Co)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <description>Co-applicant's email address As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Email (Co)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_First_Name__c</fullName>
        <description>Co-applicant's first name As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>First Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Last_Name__c</fullName>
        <description>Last name of the co-applicant. As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Last Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Postal_Code__c</fullName>
        <description>Co-applicant's current address (postal code) As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <label>Address Zip / Postal Code (Co)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_State__c</fullName>
        <description>The state of residence of the co-applicant. As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <label>Address State (Co)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Total_Monthly_Income_co__c</fullName>
        <defaultValue>0</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Income Monthly Est Total (Co)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Felonies_co__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Felonies? (Co)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Given_Deed_For_Foreclosure_In_7_Years_Co__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not found on application according to Confluence page As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Given Deed For Foreclosure In 7 Yrs (Co)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marital_Status_co__c</fullName>
        <description>2019-10-28 - The maritial status of the co-applicant. As of Q4-2019, this field
            has been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <label>Marital Status (Co)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Separated</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Widowed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Foreclosure_co__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Previous Foreclosure? (Co)</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>HB Lead Status</businessProcess>
        <description>012E00000002OGS</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SuccessFactorsHelperTest.cls
/************************************************************************************
 Apex Class Name     : SuccessFactorsHelperTest
 Version             : 1.0
 Created Date        : 19th September 2019
 Function            : APEX test class for SuccessFactorsHelper
 Author              : Jason Sun
 
 Modification Log    :
* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Jason Sun           	09/19/2019                Original Version
*************************************************************************************
*/
@isTest
public class SuccessFactorsHelperTest {

    public static testMethod void test_generateLeadSuccessFactors(){
		Lead ld1 = new Lead();
        ld1.recordtypeid = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        ld1.FirstName = 'First';
        ld1.LastName = 'Last';
        ld1.Company = 'First Last Household';
        ld1.OwnerId = UserInfo.getUserId();
        ld1.Status = 'New';
        ld1.Street = 'Test Street';
        ld1.City = 'Test City';
        ld1.State = 'Test State';
        ld1.Country = 'United States';
        ld1.PostalCode = 'TX1234';
        ld1.Co_Applicant_Address__c = 'Street';
        ld1.Co_Applicant_BirthDate__c = System.Today();
        ld1.Co_Applicant_City__c = 'City';
        ld1.Co_Applicant_Email__c  = 'coapplicant@test.com';
        ld1.Co_Applicant_First_Name__c  = 'CoApplicantFirst';
        ld1.Co_Applicant_Last_Name__c  = 'CoApplicantLast';
        ld1.Co_Applicant_Postal_Code__c = '12345';
        ld1.Co_Applicant_State__c = 'State';
        ld1.Bankrupcy_in_last_seven_years_co__c = true;
        ld1.Estimated_Total_Monthly_Income_co__c = 12345;
        ld1.Felonies_co__c = true;
        ld1.Given_deed_for_foreclosure_in_7_years_co__c = true;
        ld1.Marital_Status_co__c = 'Single';
        ld1.Previous_Foreclosure_co__c = true;
        ld1.Agency_or_Non_Agency__c = 'Agency';
        ld1.Street = 'Test Street';
        ld1.City = 'Test City';
        ld1.State = 'CA';
        ld1.PostalCode = 'TestCode';     
        insert ld1;
        
        //Process Builder that invokes SuccessFactorsHelper fires on Lead Create
        //confirm that successFactors were created        
        List<Success_Factor__c> sfList = [SELECT Id FROM Success_Factor__c WHERE Lead__c = :ld1.Id];
        system.assertNotEquals(0, sfList.size());
        
    }
    
    public static testMethod void test_CloseLostLead_SuccessFactors(){
		Lead ld1 = new Lead();
        ld1.recordtypeid = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeBuyer').getRecordTypeId();
        ld1.FirstName = 'First';
        ld1.LastName = 'Last';
        ld1.Company = 'First Last Household';
        ld1.OwnerId = UserInfo.getUserId();
        ld1.Status = 'Closed Lost';
        ld1.Street = 'Test Street';
        ld1.City = 'Test City';
        ld1.State = 'Test State';
        ld1.Country = 'United States';
        ld1.PostalCode = 'TX1234';
        ld1.Co_Applicant_Address__c = 'Street';
        ld1.Co_Applicant_BirthDate__c = System.Today();
        ld1.Co_Applicant_City__c = 'City';
        ld1.Co_Applicant_Email__c  = 'coapplicant@test.com';
        ld1.Co_Applicant_First_Name__c  = 'CoApplicantFirst';
        ld1.Co_Applicant_Last_Name__c  = 'CoApplicantLast';
        ld1.Co_Applicant_Postal_Code__c = '12345';
        ld1.Co_Applicant_State__c = 'State';
        ld1.Bankrupcy_in_last_seven_years_co__c = true;
        ld1.Estimated_Total_Monthly_Income_co__c = 12345;
        ld1.Felonies_co__c = true;
        ld1.Given_deed_for_foreclosure_in_7_years_co__c = true;
        ld1.Marital_Status_co__c = 'Single';
        ld1.Previous_Foreclosure_co__c = true;
        ld1.Agency_or_Non_Agency__c = 'Agency';
        ld1.Street = 'Test Street';
        ld1.City = 'Test City';
        ld1.State = 'CA';
        ld1.PostalCode = 'TestCode';     
        insert ld1;
        
        //delete all success Factors
        List<Success_Factor__c> sfList = [SELECT Id FROM Success_Factor__c WHERE Lead__c = :ld1.Id];
		delete sfList;
        
        //return lead from Closed Lost
        ld1.Status = 'Discovery';
        update ld1;             
        
        //confirm that successFactors were created        
        sfList = [SELECT Id FROM Success_Factor__c WHERE Lead__c = :ld1.Id];
        system.assertNotEquals(0, sfList.size());        
    }    
    
}