objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <description>Co-applicant's email address As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Email (Co)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_First_Name__c</fullName>
        <description>Co-applicant's first name As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>First Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Last_Name__c</fullName>
        <description>Last name of the co-applicant. As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Last Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Converted_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Converted Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads (Converted Opp)</relationshipLabel>
        <relationshipName>Converted_Opportunity_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating whether the applicatoin has a co-applicant. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <formula>Co_Applicant__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Co-Applicant Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Yodlee_Order_Request__c.object
<CustomObject>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Lead_Yodlee_EXT_TEST.cls
/**********************************************************
 * @className   : Lead_Yodlee_EXT_TEST.cls
 * @date        : May 7, 2018
 * @description : This class provide test methods for Lead_Yodlee_EXT.cls
 *
 *
 **********************************************************/ 

@isTest 
private class Lead_Yodlee_EXT_TEST {

	@isTest
	private static void testName() {


		Account acc = new Account(Name = 'New Account');
		insert acc; 

		Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
		                          AccountID = acc.Id);
		insert con;

		Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
		                          AccountID = acc.Id);
		insert con2;

		Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
									CloseDate = Date.today().addDays(20));
		insert oppty;

		Lead lead1 = new Lead(FirstName = 'FNAme', LastName = 'LName', Email = 'fName.LName.@test.com', Co_Applicant_Last_Name__c = 'CoLName',
								Co_Applicant_First_Name__c = 'CoName', Co_Applicant_Email__c = 'coLName.Co@test.com', Is_there_Co_App__c = true,
								Company = 'ABC', Converted_Opportunity__c = oppty.Id);
		insert lead1;
		
		System.Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(lead1);
			Lead_Yodlee_EXT ctrl = new Lead_Yodlee_EXT(sc);
			ctrl.BackToLead();
			ctrl.generateYodleeOrder();

		System.Test.stopTest();

		List<Yodlee_Order_Request__c> yodleeOrderRequests = [Select Id from Yodlee_Order_Request__c];

		System.assert(yodleeOrderRequests.size() > 0);
	}

	@isTest
	private static void testName2() {


		Account acc = new Account(Name = 'New Account');
		insert acc; 

		Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
		                          AccountID = acc.Id);
		insert con;

		Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
		                          AccountID = acc.Id);
		insert con2;

		Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
									CloseDate = Date.today().addDays(20));
		insert oppty;

		Lead lead1 = new Lead(FirstName = null, LastName = 'LName', Email = 'fName.LName.@test.com', Co_Applicant_Last_Name__c = 'CoLName',
								Co_Applicant_First_Name__c = 'CoName', Co_Applicant_Email__c = 'coLName.Co@test.com', Is_there_Co_App__c = false,
								Company = 'ABC', Converted_Opportunity__c = oppty.Id);
		insert lead1;
		
		System.Test.startTest();

			ApexPages.StandardController sc = new ApexPages.StandardController(lead1);
			Lead_Yodlee_EXT ctrl = new Lead_Yodlee_EXT(sc);
			ctrl.BackToLead();
			ctrl.generateYodleeOrder();

		System.Test.stopTest();

		List<Yodlee_Order_Request__c> yodleeOrderRequests = [Select Id from Yodlee_Order_Request__c];

		System.assert(yodleeOrderRequests.size() == 0);
	}
}