objects/Lead.object
<CustomObject>
    <fields>
        <fullName>SuccessFactor_Creation_TimeStamp__c</fullName>
        <description>When the process builder fires, this marks the time sucess factors get created
            As of Q4-2019, this field has been identified by Business Systems (and relevant
            stakeholders) as used or otherwise relevant to current business processes. To be
            reviewed next Q4 2021.</description>
        <label>SuccessFactor Creation TimeStamp</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Success_Factor__mdt.object
<CustomObject>
    <description>Metadata to store the initial set of success factors that should be created upon Lead creation</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <default>true</default>
                    <label>Cash to Consumer</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Success Factor</label>
    <pluralLabel>Lead Success Factors</pluralLabel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SuccessFactorsHelper.cls
public class SuccessFactorsHelper {

	@InvocableMethod(label='Generate Lead Success Factors' description='Generates Lead Success Factors from Custom Metadata settings and updates success factor generation timestamp')
	public static void generateLeadSuccessFactors(List<Id> leadIds) {
        List<Success_Factor__c> sfList = new List<Success_Factor__c>();
        List<Lead> leadsToUpdate = new List<Lead>();
        for(Lead l: [SELECT Id, (SELECT Id FROM Risk_Factors__r) FROM Lead WHERE Id IN: leadIds]){
            if(l.Risk_Factors__r.isEmpty()){
        		for(Lead_Success_Factor__mdt lsfMeta: [SELECT Status__c ,Success_Factor__c FROM Lead_Success_Factor__mdt ]){
            		sfList.add(new Success_Factor__c(Lead__c = l.Id, Status__c =lsfMeta.Status__c, Success_Factor__c=lsfMeta.Success_Factor__c) );                
        		}            
				leadsToUpdate.add(new Lead(Id=l.Id,SuccessFactor_Creation_TimeStamp__c =datetime.now() ));                             
            }
        }
        insert sfList;
        update leadsToUpdate;
    }      
    
}