objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Credit_Pre_Qualification_Status__c</fullName>
        <description>Status indicating whether the person is credit qualified. It is set
            automatically when Laser Credit pulls the credit. This is not the self-stated credit.
            No-match means that Laser credit wasn't able identify the person. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Credit Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Match</fullName>
                </value>
                <value>
                    <fullName>Approved (Single score)</fullName>
                </value>
                <value>
                    <fullName>Declined (Single score)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Pre_Qualification_Status__c</fullName>
        <description>status of the pre-qual As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Property Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Pre_Qualification_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tune_Offer_Id__c</fullName>
        <label>Tune Offer Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tune_Transaction_Id__c</fullName>
        <label>Tune Transaction Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>New HO Funnel</businessProcess>
        <description>01244000000DHFN</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Credit_Pre_Qualification_Status__c</fullName>
        <label>Credit Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Match</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Pre_Qualification_Status__c</fullName>
        <label>Property Pre-Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Property_Pre_Qualification_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tune_Offer_Id__c</fullName>
        <label>Tune Offer Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tune_Transaction_Id__c</fullName>
        <label>Tune Transaction Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tune_Integration_Log__c.object
<CustomObject>
    <label>Tune Integration Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Tune Integration Log No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tune Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Property_Pre_Qualification_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Not Enough Information</fullName>
    </customValue>
    <masterLabel>Property Pre-Qualification Status</masterLabel>
</GlobalValueSet>

classes/TuneIntegrationTest.cls
@isTest
public class TuneIntegrationTest {

    public class MockHttpResponse implements HttpCalloutMock {
    	public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('Success');
            res.setStatusCode(200);
            return res;
        }
    }

    public static testMethod void TestLeadInsert() {
        
        // Data setup
		Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        Lead l = new Lead();
        l.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        l.Tune_Transaction_Id__c = 'test283862';
        l.Tune_Offer_Id__c = '4';
        l.LastName = 'Tst918236';
        l.Company = 'Tst983273';
        l.Status = 'Pending Qualification';
        
		// Run the code
		Test.startTest();
		
		insert l;
        
		Test.stopTest();
		
		// Verify Results
		System.assertEquals(1, [SELECT COUNT() FROM Tune_Integration_Log__c]);
        
    }
    
    public static testMethod void TestLeadUpdate() {
        
        // Data setup
		Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        Lead l = new Lead();
        l.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        l.Tune_Transaction_Id__c = 'test283862';
        l.Tune_Offer_Id__c = '4';
        l.LastName = 'Test918236';
        l.Company = 'Test983273';
		insert l;
        
		// Run the code
		Test.startTest();
		
        LeadTriggerHandlerPC.tunedIds = new Set<Id>();
        l.Credit_Pre_Qualification_Status__c = 'Approved';
        l.Property_Pre_Qualification_Status__c = 'Approved';
        update l;
        
		Test.stopTest();
		
		// Verify Results
		System.assertEquals(2, [SELECT COUNT() FROM Tune_Integration_Log__c]);
        
    }
    
    public static testMethod void TestOpportunity() {
        
        // Data setup
		Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        Opportunity o = new Opportunity();
        o.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('HomeOwner').getRecordTypeId();
        o.Tune_Transaction_Id__c = 'test283862';
        o.Tune_Offer_Id__c = '4';
        o.Name = 'Test387263';
        o.StageName = 'Ready for Ops';
        o.CloseDate = Date.today();
		insert o;
        
		// Run the code
		Test.startTest();
        
        o.Wire_to_Agent_Date__c = Date.today();
        update o;
		
		Test.stopTest();
		
		// Verify Results
		System.assertEquals(1, [SELECT COUNT() FROM Tune_Integration_Log__c]);
        
    }
    
}