objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <description>Co-applicant's email address As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Email (Co)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_First_Name__c</fullName>
        <description>Co-applicant's first name As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>First Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Last_Name__c</fullName>
        <description>Last name of the co-applicant. As of Q4-2019, this field has been identified by
            Business Systems (and relevant stakeholders) as used or otherwise relevant to current
            business processes. To be reviewed next Q4 2021.</description>
        <label>Last Name (Co)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Converted_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Converted Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads (Converted Opp)</relationshipLabel>
        <relationshipName>Converted_Opportunity_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating whether the applicatoin has a co-applicant. As of Q4-2019, this
            field has been identified by Business Systems (and relevant stakeholders) as used or
            otherwise relevant to current business processes. To be reviewed next Q4
            2021.</description>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Lead_Yodlee_EXT.cls
/**********************************************************
 * @className   : Lead_Yodlee_EXT.cls
 * @testClass   : Lead_Yodlee_EXT_TEST.cls
 * @date        : May 2, 2018
 * @description : This class provides extension methods for Lead_Yodlee_VF.page
 *
 *
 **********************************************************/ 

public class Lead_Yodlee_EXT {

	private Lead leadRec;
	public Boolean displayError {get;set;}
    
    public Lead_Yodlee_EXT(ApexPages.StandardController sc){
        this.leadRec = (Lead)sc.getRecord();   
		this.displayError = false;
    }

	/*****
	*
	*
	*
	******/
	public PageReference BackToLead(){
		return new PageReference('/' + this.leadRec.Id);
	}

	/******
	*
	* This method generate and submit a yodlee order record
	*
	******/
    public PageReference generateYodleeOrder(){
		Lead leadRecInfo = [Select ID, FirstName, LastName, Email, Co_Applicant_First_Name__c, Converted_Opportunity__c,
							 Co_Applicant_Last_Name__c, Is_there_Co_App__c, Co_Applicant_Email__c from Lead Where Id =: leadRec.Id];

        Id yodleeOrderId = YodleeHelper.CreateOrder(leadRecInfo);
		if (yodleeOrderId != null){
			return new PageReference('/' + YodleeOrderId);
		}else{
			this.displayError = true;
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please make sure that all required fields(First Name (Co), Last Name (Co), Email (Co)) are NOT NULL Or Empty.');
			ApexPages.addMessage(msg);

			return null;
		}
    }
}