objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Income_Monthly_Base__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Income field used to determine DTI for the Lead. As of Q4-2019, this field has
            been identified by Business Systems (and relevant stakeholders) as used or otherwise
            relevant to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Income field used to determine DTI for the Lead: Base Income of the
            Applicant.</inlineHelpText>
        <label>Income Monthly Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Specialist_to_Call_Now__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Product Specialist to Call Now?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Investment_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Investment Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FindNullsTest.cls
@isTest
private class FindNullsTest {
    @isTest
    static void findNullsForLeads() {
        Lead newLead = new Lead();
        newLead.FirstName = 'John';
        newLead.LastName = 'Doe';
        newLead.Email = 'doe@example.com';
        newLead.Phone = '1234567890';
        newLead.Company = 'Test Inc';
        newLead.Product_Specialist_to_Call_Now__c = true;
        newLead.Status = 'New';
        newLead.Street = 'Test Street';
        newLead.City = 'Test City';
        newLead.State = 'Test State';
        newLead.PostalCode = 'Test ZipCode';
        newLead.Income_Monthly_Base__c = 100;

        Test.startTest();
        insert newLead;
        Test.stopTest();

    }
    
    @isTest
    static void findNullsForOpportunities() {
        Account newAcc = new Account (Name='Test Account');
        insert newAcc;

        Opportunity newOppty = new Opportunity();
        newOppty.Name = 'Test Opportunity';
        newOppty.AccountId = newAcc.Id;
        newOppty.StageName = 'Property in Contract';
        newOppty.CloseDate = System.today();
        newOppty.UnisonProcessor__c = UserInfo.getUserId();
        newOppty.Investment_Analyst2__c = UserInfo.getUserId();

        Test.startTest();
        insert newOppty;
        Test.stopTest();
    }

}