objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Minimum_Required_Documents__c</fullName>
        <description>TO BE DEPRECATED - As of Q4-2019, this field has been identified by Business
            Systems (and relevant stakeholders) as either redundant, obsolete, or otherwise unused,
            and thus marked for deprecation.</description>
        <label>Minimum Required Documents</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Reviewed</fullName>
                    <default>true</default>
                    <label>Not Reviewed</label>
                </value>
                <value>
                    <fullName>Documentation Incomplete</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Conditionally Passed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Minimum_Required_Documents__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant</fullName>
                    <default>true</default>
                    <label>Applicant</label>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Asset_Statement 
Business_Tax 
Personal_Tax 
Sale_Contract 
W2 
Hazard_Insurance 
Appraisal 
Lender_Pre 
Mortgage 
Paystub 
Award</description>
        <inlineHelpText>Asset_Statement 
Business_Tax 
Personal_Tax 
Sale_Contract 
W2 
Hazard_Insurance 
Appraisal 
Lender_Pre 
Mortgage 
Paystub 
Award
Sale Contract
W2
Hazard Insurance
Appraisal
Lender Pre
Mortgage
Paystub
Award</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>W2</fullName>
                </value>
                <value>
                    <fullName>Paystubs</fullName>
                </value>
                <value>
                    <fullName>Social Security Award Letter/Pension Income</fullName>
                </value>
                <value>
                    <fullName>Personal Tax Return</fullName>
                </value>
                <value>
                    <fullName>Business Tax Return</fullName>
                </value>
                <value>
                    <fullName>Asset Statement</fullName>
                </value>
                <value>
                    <fullName>Hazard Insurance Dec Page</fullName>
                </value>
                <value>
                    <fullName>Mortgage Statements</fullName>
                </value>
                <value>
                    <fullName>Lender Pre-Qualification/ Pre-Approval</fullName>
                </value>
                <value>
                    <fullName>Fully Executed Purchase and Sale Contract</fullName>
                </value>
                <value>
                    <fullName>Appraisal Report</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Trust Documents</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Minimum Required Documents</relationshipLabel>
        <relationshipName>Minimum_Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <label>Minimum Required Documents</label>
    <nameField>
        <displayFormat>MRD-{000000000}</displayFormat>
        <label>Minimum Required Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minimum Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MrdToAwsTriggerTest.cls
@isTest 
public class MrdToAwsTriggerTest {
    @isTest static void TestInsertUpdate() {
        Test.setMock(HttpCalloutMock.class, new UnisonAPIHttpCalloutMock()); 
        
		Lead lead = new Lead(LastName = 'Test', Email = 'test@unison.com', mobilephone = '+1234567890', Company = 'Test company');
        insert lead;
        
        // Try creating an MRD
        Minimum_Required_Documents__c mrd = new Minimum_Required_Documents__c(Lead__c=lead.id, Category__c='W2', Applicant_Type__c='Applicant');
        insert mrd;
        
        // Try updating an MRD
        mrd.Uploaded__c = true;
        update mrd;
        
        // Not sure how to apply asserts for this, but we have the coverage.
        // Probably need to mock the UnisonAPI class somehow to see if fSendMRDUpsert is being called with the mrd.id
    }
}