objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Source__c</fullName>
        <description>Owen check with Jessica to get context As of Q4-2019, this field has been
            identified by Business Systems (and relevant stakeholders) as used or otherwise relevant
            to current business processes. To be reviewed next Q4 2021.</description>
        <inlineHelpText>Campaign source (e.g. Bing, Google, Facebook)</inlineHelpText>
        <label>Campaign Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Net_Promoter_Measurement__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Net Promoter Measurement</label>
    <nameField>
        <displayFormat>NPM-{0000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Net Promoter Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelightedScheduledBatchTest.cls
@isTest
public class DelightedScheduledBatchTest {

    @isTest
	public static void TestLead() {
		
		// Data setup
		Lead l = new Lead();
        l.FirstName = 'RealFirstName';
        l.LastName = 'RealLastName923078';
        l.Email = 'AnEmail.email923078@example.com';
        l.Company = 'Company923078';
        l.Campaign_Source__c = 'web';
        insert l;
        
        Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
        npm.Status__c = 'Draft';
        npm.Lead__c = l.Id;
        insert npm;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
		
		// Run the code
		Test.startTest();
		(new DelightedScheduledBatch()).execute(null);
		Test.stopTest();
		
		// Verify Results
        System.assertEquals(1, [SELECT COUNT() FROM Net_Promoter_Measurement__c WHERE Status__c = 'Success']);
	}
    
    @isTest
	public static void TestOpp() {
		
		// Data setup
		Account a = new Account();
        a.Name = 'Totally a Real Account';
        insert a;
        
        Opportunity o = new Opportunity();
        o.Name = 'Opportunity923079';
        o.StageName = 'Introduction';
        o.CloseDate = Date.today();
        o.AccountId = a.Id;
        insert o;
        
        Net_Promoter_Measurement__c npm = new Net_Promoter_Measurement__c();
        npm.Status__c = 'Draft';
        npm.Opportunity__c = o.Id;
        insert npm;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
		
		// Run the code
		Test.startTest();
		(new DelightedScheduledBatch()).execute(null);
		Test.stopTest();
		
		// Verify Results
        System.assertEquals(1, [SELECT COUNT() FROM Net_Promoter_Measurement__c WHERE Status__c = 'Success']);
	}

}