objects/Net_Promoter_Measurement__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Net Promoter Measurements</relationshipLabel>
        <relationshipName>Net_Promoter_Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Net Promoter Measurement</label>
    <nameField>
        <displayFormat>NPM-{0000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Net Promoter Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelightedScheduledBatch.cls
global class DelightedScheduledBatch implements Schedulable, Database.Stateful, Database.AllowsCallouts, Database.Batchable<sObject> {

	global void execute(SchedulableContext SC) {
		Database.executeBatch(new DelightedScheduledBatch(), 1);
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator('SELECT Id, Lead__c, Opportunity__c FROM Net_Promoter_Measurement__c WHERE Status__c = \'Draft\'');
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope) {
        Net_Promoter_Measurement__c npm = (Net_Promoter_Measurement__c)scope[0];
        
        if (npm.Lead__c != null)
            DelightedHelper.SendSurveyLead(npm.Id, npm.Lead__c);
        
        if (npm.Opportunity__c != null)
            DelightedHelper.SendSurveyOpportunity(npm.Id, npm.Opportunity__c);
	}
	
	global void finish(Database.BatchableContext BC) {
	}
}