objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Yodlee_Order_Request__c.object
<CustomObject>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Opp_Yodlee_EXT_TEST.cls
/**********************************************************
 * @className   : Opp_Yodlee_EXT_TEST.cls
 * @date        : May 7, 2018
 * @description : This class provide test methods for Opp_Yodlee_EXT.cls
 *
 *
 **********************************************************/ 

@isTest 
private class Opp_Yodlee_EXT_TEST {

    @isTest
    private static void testName() {


        Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                                  AccountID = acc.Id);
        insert con2;

         /* 4/2/2019 Sundar Subramaniam - Is_there_Co_App__c removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20), Applicant__c = con.Id,
                                    Co_Applicant__c = con2.Id);
        insert oppty;
        
        System.Test.startTest();

            ApexPages.StandardController sc = new ApexPages.StandardController(oppty);
            Opp_Yodlee_EXT ctrl = new Opp_Yodlee_EXT(sc);
            ctrl.generateYodleeOrder();
            ctrl.BackToOppty();

        System.Test.stopTest();

        List<Yodlee_Order_Request__c> yodleeOrderRequests = [Select Id from Yodlee_Order_Request__c];

        System.assert(yodleeOrderRequests.size() > 0);
    }

    @isTest
    private static void testName2() {


        Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                                  AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                                  AccountID = acc.Id);
        insert con2;

        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting', 
                                    CloseDate = Date.today().addDays(20));
        insert oppty;
        
        System.Test.startTest();

            ApexPages.StandardController sc = new ApexPages.StandardController(oppty);
            Opp_Yodlee_EXT ctrl = new Opp_Yodlee_EXT(sc);
            ctrl.generateYodleeOrder();
            ctrl.BackToOppty();

        System.Test.stopTest();

        List<Yodlee_Order_Request__c> yodleeOrderRequests = [Select Id from Yodlee_Order_Request__c];

        System.assert(yodleeOrderRequests.size() == 0);
    }
}