objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application_DateTime__c</fullName>
        <inlineHelpText>Time stamp of when DocuSign application was completed</inlineHelpText>
        <label>Application Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Encompass_Loan_Number__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Deal ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Title_Held__c</fullName>
        <label>Final Title to be Held</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individually</fullName>
                </value>
                <value>
                    <fullName>Jointly</fullName>
                </value>
                <value>
                    <fullName>In Trust</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IM_Approved_Date__c</fullName>
        <label>IM Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MAD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Max LTV; ELSE 1) Post-Close LTV if HB, or 2) MAX(Post-Close LTV, 70%) with a cap at 75% if HO</description>
        <inlineHelpText>This value defaults to the value in Maximum Authorized LTV. If Maximum Authorized LTV does not exist, for HO it is the larger % between Post-Close LTV and 70% with a cap at 75%, and for HB, it is Post-Close LTV.</inlineHelpText>
        <label>MAD %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Post_Close_LTV2__c</fullName>
        <description>Hardcoded
This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <inlineHelpText>This is the total proposed mortgage debt on the property as a percentage of the Final OAV. It is expressed as the Post-Close Mortgage Debt divided by the Final OAV. Final OAV can change as more appraisals and other information is gathered.</inlineHelpText>
        <label>Post-Close LTV2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>State / Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Number_and_Name__c</fullName>
        <label>Property Street Number and Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_New_HomeOwner_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Qualifies for New HomeOwner Pricing?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NintexDocGenValidationTest.cls
@isTest
public class NintexDocGenValidationTest {
    
    @isTest
	public static void Test_Success() {
		
		// Data setup
		Account acc = new Account();
        acc.Name = 'Test123452';
        insert acc;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test435733';
        opp.AccountId = acc.Id;
        opp.StageName = 'Introduction';
        opp.CloseDate = System.today();
        opp.Property_Street_Number_and_Name__c = '10';
        opp.Application_DateTime__c = system.today();
        opp.Property_City__c = 'catest';
        opp.Post_Close_LTV2__c = 1;
        opp.Encompass_Loan_Number__c = '1';
        opp.Wire_to_Agent_Date__c = system.today();
        opp.Approval_Status__c = 'Pending';
        opp.IM_Approved_Date__c = system.today();
        opp.Qualifies_for_New_HomeOwner_Pricing__c = true;
        opp.Final_Title_Held__c = 'test';
        opp.Property_State__c = 'test';
        opp.Property_Zip_Code__c = '12345';
        opp.IA_OAV_Override__c = 10;
        opp.MAD__c = 10;
        opp.Final_OAV_Calculation__c = 10;
        insert opp;
		
		// Run the code
		Test.startTest();
        NintexDocGenValidation ctrl = new NintexDocGenValidation(new ApexPages.StandardController(opp));
        PageReference pr = ctrl.Validate();
		Test.stopTest();
		
		// Verify Results
		System.assertNotEquals(null, pr);
    }
    
    @isTest
	public static void Test_Fail() {
		
		// Data setup
		Account acc = new Account();
        acc.Name = 'Test123452';
        insert acc;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test435733';
        opp.AccountId = acc.Id;
        opp.StageName = 'Introduction';
        opp.CloseDate = System.today();
        opp.Property_Street_Number_and_Name__c = '10';
        opp.Application_DateTime__c = system.today();
        opp.Property_City__c = 'catest';
        opp.Post_Close_LTV2__c = 1;
        opp.Encompass_Loan_Number__c = '1';
        opp.Wire_to_Agent_Date__c = system.today();
        opp.Approval_Status__c = 'Pending';
        opp.IM_Approved_Date__c = system.today();
        opp.Qualifies_for_New_HomeOwner_Pricing__c = true;
        opp.Final_Title_Held__c = 'test';
        opp.Property_State__c = 'test';
        opp.Property_Zip_Code__c = '12345';
        insert opp;
		
		// Run the code
		Test.startTest();
        NintexDocGenValidation ctrl = new NintexDocGenValidation(new ApexPages.StandardController(opp));
        PageReference pr = ctrl.Validate();
		Test.stopTest();
		
		// Verify Results
		System.assertEquals(null, pr);
	}


}