objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finder</fullName>
                    <label>Finders Program</label>
                </value>
                <value>
                    <fullName>HomeBuyer</fullName>
                </value>
                <value>
                    <fullName>HomeOwner</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Conforming</fullName>
                </value>
                <value>
                    <fullName>HomeBuyer Non-Conforming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recorded_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recorded Information</label>
        <referenceTo>Recorded_Information__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recorded_Information__c.object
<CustomObject>
    <fields>
        <fullName>Fund_Number__c</fullName>
        <label>Fund Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Recorded Informations</relationshipLabel>
        <relationshipName>Recorded_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recorded Information</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Recorded Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recorded Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Success_Factor__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Risk_Factors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HB</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Requirement Blocked</fullName>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                    <isActive>false</isActive>
                    <label>Cleared</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Factor__c</fullName>
        <label>Success Factor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash to Consumer</fullName>
                    <label>Net Cash to Partner</label>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>DTI</fullName>
                </value>
                <value>
                    <fullName>LTV</fullName>
                </value>
                <value>
                    <fullName>OAV</fullName>
                </value>
                <value>
                    <fullName>Property Ownership</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Post-Closing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Success Factor</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>Success Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SuccessFactorsTriggerPCTest.cls
/**
 * Created by Mind on 5/23/2019.
 */

@isTest
public class SuccessFactorsTriggerPCTest {

    @isTest
    private static void SFTest1() {

        Account acc = new Account();
        acc.Name = 'test acc';
        insert acc;
        
        Recorded_Information__c rec = new Recorded_Information__c();
        rec.Fund_Number__c = 45;
        insert rec;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'test opp';
        opp.StageName = 'Investment Due Diligence';
        opp.CloseDate = System.today();
        opp.Estimated_Funding_Amount__c = 2;
        opp.Pricing_Ratio__c = 2;
        opp.Final_OAV_Calculation__c = 4;
        opp.IA_OAV_Override__c =2; 
        opp.Recorded_Information__c = rec.Id;
        insert opp;
        
            
        Success_Factor__c sf1 = new Success_Factor__c();
        sf1.Opportunity__c = opp.Id;
        sf1.Success_Factor__c = 'Cash to Consumer';
        sf1.Status__c = 'Completed';
        sf1.Program__c = 'HO';
        insert sf1;

        sf1.Success_Factor__c = 'Credit';
        sf1.Status__c = 'In Progress';
        update sf1;

        List<Success_Factor__c> sfList = new List<Success_Factor__c>();
        sfList.add(sf1);
        SuccessFactorsTriggerPC.handleAfterInsert(sfList);

    }
}