objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delighted_Post_Closing_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delighted Post Closing Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wire_to_Agent_Date__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Date wire to escrow agent was requested by Unison</inlineHelpText>
        <label>Wire to Agent Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelightedFundedOppBatchTest.cls
@isTest
public class DelightedFundedOppBatchTest {

    @isTest
	private static void testName() {
		
        // Data setup
        Account a = new Account();
        a.Name = 'Totally a Real Account';
        insert a;
        
        contact con = new Contact();
        con.FirstName = 'fname';
        con.LastName = 'lname';
        con.Email='lname@test.com';
        con.AccountId = a.Id;
		insert con;
        
        Opportunity o = new Opportunity();
        o.Name = 'Opportunity923079';
        o.Applicant__c = con.Id;
        o.StageName = 'Post-Closing';
        o.CloseDate = Date.today();
        o.AccountId = a.Id;
        o.Wire_to_Agent_Date__c = Date.today().addDays(-7);
        insert o;
        
        Test.setMock(HttpCalloutMock.class, new DelightedMock());
        
        // Run the code
        Test.startTest();
			(new DelightedFundedOppBatch()).execute(null);
        Test.stopTest(); 
        
        // Verify Results
		o = [Select Id, Delighted_Post_Closing_Sent__c from Opportunity Where Id = :o.Id];
        System.assertEquals(true, o.Delighted_Post_Closing_Sent__c);
	}
    
}