objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SFDC2_Opportunity_Id__c</fullName>
        <label>SFDC2 Opportunity Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wire_Reference_Number__c</fullName>
        <label>Wire Reference Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_to_SFDC_Log__c.object
<CustomObject>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SFDC to SFDC Log</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Log N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDC to SFDC Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunitySyncBatchTest.cls
@isTest
public class OpportunitySyncBatchTest {
    
    public static testMethod void Test_Success() {
        
        // Data setup
        Account ac1 = new Account();
        ac1.Name = 'Test498043';
        insert ac1;
        
        Opportunity op1 = new Opportunity();
        op1.AccountId = ac1.Id;
        op1.Name = 'Test681108';
        op1.StageName = 'Post-Closing';
        op1.Wire_Reference_Number__c = '1234';
        op1.CloseDate = Date.today();
        insert op1;

        Test.setMock(HttpCalloutMock.class, new AccountUtilityClassTest.MockClass(op1.Id));
        
        // Run the code
        Test.startTest();
        (new OpportunitySyncBatch()).execute(null);
        Test.stopTest();
        
        // Verify Results 
        op1 = [SELECT SFDC2_Opportunity_Id__c FROM Opportunity WHERE Id = :op1.Id];
        System.assertEquals('0061700000LSODhAAP', op1.SFDC2_Opportunity_Id__c);

        SFDC_to_SFDC_Log__c log = [SELECT Response_Code__c FROM SFDC_to_SFDC_Log__c LIMIT 1];
        System.assertEquals(200, log.Response_Code__c);
        
    }

    public static testMethod void Test_Error() {
        
        // Data setup
        Account ac1 = new Account();
        ac1.Name = 'Test498043';
        insert ac1;
        
        Opportunity op1 = new Opportunity();
        op1.AccountId = ac1.Id;
        op1.Name = 'Test681108';
        op1.StageName = 'Post-Closing';
        op1.Wire_Reference_Number__c = '1234';
        op1.CloseDate = Date.today();
        insert op1;

        Test.setMock(HttpCalloutMock.class, new AccountUtilityClassTest.MockClass(null));
        
        // Run the code
        Test.startTest();
        (new OpportunitySyncBatch()).execute(null);
        Test.stopTest();
        
        // Verify Results 
        SFDC_to_SFDC_Log__c log = [SELECT Response_Code__c FROM SFDC_to_SFDC_Log__c LIMIT 1];
        System.assertEquals(500, log.Response_Code__c);
        
    }
    
}