objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OIP_Numbers_to_Words__c</fullName>
        <label>OIP Numbers to Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConvertCurrencyToWordsTest.cls
/**
 * Created by Ivan Garcia on 7/22/2019.
 */

@IsTest
public with sharing class ConvertCurrencyToWordsTest {
    @testSetup static void setup(){
        Account tmpAcc = new Account(Name = 'TestAcc');
        insert tmpAcc;
    }

    @IsTest private static void mainTest(){
        Account tmpAcc = [SELECT id FROM Account LIMIT 1];
        Opportunity tmpOpp = new Opportunity(Name = 'TestOpp', Estimated_Funding_Amount__c = 500, AccountId = tmpAcc.id, StageName = 'Ready for Ops', CloseDate = System.today());
        insert tmpOpp;
        test.startTest();
        tmpOpp.Estimated_Funding_Amount__c = 20000;
        update tmpOpp;
        Opportunity loadOpp = [SELECT id,OIP_Numbers_to_Words__c FROM Opportunity WHERE Id = :tmpOpp.id LIMIT 1];
        System.assertEquals('Twenty Thousand Dollars',loadOpp.OIP_Numbers_to_Words__c);
        test.stopTest();
    }

    @IsTest private static void SpecificOneHundred(){
        Account tmpAcc = [SELECT id FROM Account LIMIT 1];
        Opportunity tmpOpp = new Opportunity(Name = 'TestOpp', Estimated_Funding_Amount__c = 500, AccountId = tmpAcc.id, StageName = 'Ready for Ops', CloseDate = System.today());
        insert tmpOpp;
        test.startTest();
        tmpOpp.Estimated_Funding_Amount__c = 100;
        update tmpOpp;
        Opportunity loadOpp = [SELECT id,OIP_Numbers_to_Words__c FROM Opportunity WHERE Id = :tmpOpp.id LIMIT 1];
        System.assertEquals('One Hundred  Dollars',loadOpp.OIP_Numbers_to_Words__c);
        test.stopTest();
    }

    @IsTest private static void DirectClass(){
        Test.startTest();
        string returnedValue = ConvertCurrencyToWords.convert_nn(100);
        System.assertEquals('One Hundred',returnedValue);
        Test.stopTest();
    }
}