objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>UnisonProcessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Transaction Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Properties Due Diligence Reports</relationshipLabel>
        <relationshipName>Properties_Due_Diligence_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spruce_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Spruce Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spruce_Title_Report_Downloaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spruce Title Report Downloaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>new</fullName>
                    <default>true</default>
                    <label>new</label>
                </value>
                <value>
                    <fullName>initial_docs_available</fullName>
                    <label>Initial Docs Available</label>
                </value>
                <value>
                    <fullName>title_report_available</fullName>
                    <label>Title Report Available</label>
                </value>
                <value>
                    <fullName>closing_scheduled</fullName>
                    <label>Closing Scheduled</label>
                </value>
                <value>
                    <fullName>closing_confirmed</fullName>
                    <label>Closing Confirmed</label>
                </value>
                <value>
                    <fullName>closing_docs_submitted</fullName>
                    <label>Closing Docs Submitted</label>
                </value>
                <value>
                    <fullName>closing_occurred</fullName>
                    <label>Closing Occurred</label>
                </value>
                <value>
                    <fullName>funded</fullName>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>recorded</fullName>
                    <label>Recorded</label>
                </value>
                <value>
                    <fullName>policy_issued</fullName>
                    <label>Policy Issued</label>
                </value>
                <value>
                    <fullName>Required</fullName>
                    <isActive>false</isActive>
                    <label>Required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpruceTitleReportBatch.cls
global class SpruceTitleReportBatch implements Database.Batchable<Property_Due_Diligence_Reports__c>, Database.AllowsCallouts
{	
	// Start Method
    global List<Property_Due_Diligence_Reports__c> start(Database.BatchableContext BC)
    {
    	system.debug('Start SpruceTitleReportBatch');

    	List<Property_Due_Diligence_Reports__c> propertyDueDiligenceReportList = 
    		[
    			SELECT Id, Opportunity__r.Name, Spruce_Title_Report_Downloaded__c, Opportunity__c, Status__c, Opportunity__r.Owner.Id, Opportunity__r.Owner.Email, Spruce_Order_Id__c, Opportunity__r.UnisonProcessor__r.Email, Opportunity__r.UnisonProcessor__c
    			FROM Property_Due_Diligence_Reports__c
    			WHERE Spruce_Title_Report_Downloaded__c = false
    			AND Status__c = 'title_report_available'
    			AND Opportunity__c != null
    			AND Opportunity__r.UnisonProcessor__c != null
    		];

    	return propertyDueDiligenceReportList;
	}

   	global void execute(Database.BatchableContext BC, List<Property_Due_Diligence_Reports__c> propertyDueDiligenceReportList) 
   	{
   		system.debug('Execute SpruceTitleReportBatch');

   		List<Attachment> attachmentList = new List<Attachment>();
   		List<FeedItem> feedItemList = new List<FeedItem>();
   		List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

		for(Property_Due_Diligence_Reports__c propertyDueDiligenceReport : propertyDueDiligenceReportList)
		{
			SpruceAPI.RetrieveAvailableDocumentOfGivenTypeResponse response = SpruceHelper.RetrieveAvailableDocumentOfGivenType(propertyDueDiligenceReport.Spruce_Order_Id__c, 'TitleSearchReport');
                
            Blob file = response.file;

            if(file != null)
            { 
                Attachment attachment = new Attachment();
                attachment.ParentId = propertyDueDiligenceReport.Opportunity__c;
                attachment.Name = 'TitleSearchReport.pdf';
                attachment.ContentType = 'application/pdf';
                attachment.Body = file;                
                attachmentList.add(attachment);

                propertyDueDiligenceReport.Spruce_Title_Report_Downloaded__c = true;

                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();	         
		        email.setToAddresses(new List<String>{propertyDueDiligenceReport.Opportunity__r.Owner.Email, propertyDueDiligenceReport.Opportunity__r.UnisonProcessor__r.Email});	         
		        email.setSubject('Title Search Report');	         
		        email.setHtmlBody('Your title order has been fulfilled for <a href="' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + propertyDueDiligenceReport.Opportunity__c + '">' + propertyDueDiligenceReport.Opportunity__r.Name + ' </a> and is ready to download.');
            	emailList.add(email);

            	// Chatter Post for Opportunity Owner
            	FeedItem post = new FeedItem();
				post.ParentId = propertyDueDiligenceReport.Opportunity__r.Owner.Id;
				post.Body = 'Your title order has been fulfilled for ' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + propertyDueDiligenceReport.Opportunity__c + ' and is ready to download.';
				feedItemList.add(post);

				// Chatter Post for Transaction Specialist
				FeedItem post2 = new FeedItem();
				post2.ParentId = propertyDueDiligenceReport.Opportunity__r.UnisonProcessor__c;
				post2.Body = 'Your title order has been fulfilled for ' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + propertyDueDiligenceReport.Opportunity__c + ' and is ready to download.';
				feedItemList.add(post2);
            }
		}

		if(attachmentList.size() > 0)
		{
			insert attachmentList;
			update propertyDueDiligenceReportList;				
			insert feedItemList;

			Messaging.sendEmail(emailList);
		}  
	}
	
	global void finish(Database.BatchableContext BC) 
	{
		system.debug('Finish SpruceTitleReportBatch');
        // Logic to be Executed at finish
	}
	
}