objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IA_OAV_Override__c</fullName>
        <inlineHelpText>Manually entered OAV by IA. Only available on "Lock Screen". Overrides the Final OAV implied by other data.</inlineHelpText>
        <label>IA OAV Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityTaskListTest.cls
/**
 * Created by Ivan Garcia on 5/22/2019.
 */

@IsTest public with sharing class OpportunityTaskListTest {
    @testSetup static void setup(){
        Account acc = new Account(Name = 'New Account');
        insert acc;

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com',
                AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com',
                AccountID = acc.Id);
        insert con2;

        /* 4/2/2019 Sundar Subramaniam - Is_there_Co_App__c removed from query for Data Model Cleanup */
        Opportunity oppty = new Opportunity(Name = 'New Oppty', AccountId = acc.Id, StageName = 'Submitted to Underwriting',
                CloseDate = Date.today().addDays(20), Applicant__c = con.Id, IA_OAV_Override__c = 2,
                Co_Applicant__c = con2.Id);
        insert oppty;
    }

    @isTest private static void test0(){
        Opportunity tmpOpp = [SELECT id FROM Opportunity LIMIT 1];
        OpportunityTaskList ctrl = new OpportunityTaskList(new ApexPages.StandardController(tmpOpp));
        ctrl.message = 'test';
        ctrl.save();
    }
}