objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant2)</relationshipLabel>
        <relationshipName>Opportunities_Applicant2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant3</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant3)</relationshipLabel>
        <relationshipName>Opportunities_Applicant3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (CoApplicant2)</relationshipLabel>
        <relationshipName>Opportunities_CoApplicant2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Applicant3</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (CoApplicant3)</relationshipLabel>
        <relationshipName>Opportunities_CoApplicant3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Co-Applicant for opportunity. Updated via Apex</description>
        <label>Co-Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicant Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_there_Co_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is there Co-App?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VantagePointHelperTest.cls
@isTest
private class VantagePointHelperTest 
{	
	@isTest static void test_method_one() 
    {
		// Data Setup
        Attachment newAttachment = new Attachment();
        newAttachment.Body = Blob.valueOf('test');

        Account acc = new Account(Name = 'New Account');
        insert acc; 

        Contact con = new Contact(FirstName = 'FirstName', LastName = 'LastName', Email = 'fisrtName.lastName@test.com', AccountID = acc.Id);
        insert con;

        Contact con2 = new Contact(FirstName = 'FirstNam2e', LastName = 'LastNa2me', Email = 'fisrtNa2me.lastName@test.com', AccountID = acc.Id);
        insert con2;

        Opportunity oppty = new Opportunity(
            Name = 'New Oppty', 
            AccountId = acc.Id, 
            StageName = 'Submitted to Underwriting', 
            CloseDate = Date.today().addDays(20), 
            Is_there_Co_App__c = true, 
            Applicant__c = con.Id,
            Applicant2__c = con.Id, 
            Applicant3__c = con.Id,
            Co_Applicant__c = con2.Id,
            Co_Applicant2__c = con2.Id,
            Co_Applicant3__c = con2.Id
        );

        insert oppty;

        // Test Code
        Test.setMock(HttpCalloutMock.class, new VantagePointCalloutMock());

        VantagePointHelper.PlaceOrder(oppty);
	}
}