objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Funding_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <inlineHelpText>Estimated Funding Amount</inlineHelpText>
        <label>OIP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_OAV_Calculation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>1. IA Override Value; else 2. Purchase Price / Summary_Appraised_Value (whichever is less) - OAV Discount Amount; else 3. Summary Appraised Value - OAV Discount Amount; else 4. Home Value

This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Final OAV</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Ratio__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used to determine whether investor guidelines are broken. Do not change this field without first consulting Brodie or Abinhay Korukonda.</description>
        <label>Pricing Ratio</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NewTradeAccountOppTest.cls
@isTest
public class NewTradeAccountOppTest {

    static testMethod void tradeTest(){
            Account acc = new Account();
            acc.Name = 'test acc';
            insert acc;

            Opportunity opp = new Opportunity();
            opp.AccountId = acc.Id;
            opp.Name = 'test opp';
            opp.StageName = 'Investment Due Diligence';
            opp.CloseDate = System.today();
            opp.Estimated_Funding_Amount__c = 2;
            opp.Pricing_Ratio__c = 2;
            opp.Final_OAV_Calculation__c = 4;
            insert opp;

            ApexPages.StandardController sc = new ApexPages.StandardController(opp);
            NewTradeAccountOpp_EXT newtradeExt = new NewTradeAccountOpp_EXT(sc);
            //PageReference pageRef = Page.NewTradeAccount_VF;
            //Test.setCurrentPage(pageRef);
            newtradeExt.saveTradeAccount();
            newtradeExt.cancel();
            System.assertNotEquals(null, opp.Id);
    }
}