objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>HomeBuyer</fullName>
        <active>true</active>
        <businessProcess>NewHomeBuyerFunnel</businessProcess>
        <description>012E00000002OH1</description>
        <label>HomeBuyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>HomeOwner</fullName>
        <active>true</active>
        <businessProcess>NewHomeOwnerFunnel</businessProcess>
        <description>012E00000002OHB</description>
        <label>HomeOwner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Passbook_Config__mdt.object
<CustomObject>
    <description>Integration configuration for Passbook integration</description>
    <fields>
        <fullName>URI__c</fullName>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X_API_Client__c</fullName>
        <label>X API Client</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X_API_Secret__c</fullName>
        <label>X API Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passbook Config</label>
    <pluralLabel>Passbook Configs</pluralLabel>
</CustomObject>

objects/Passbook_Logs__c.object
<CustomObject>
    <description>This object captures logs for passbook integration</description>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Passbook Logs</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Passbook Logs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passbook Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PassbookRestHelper.cls
/**
 *  About
 *  -----
 *  Author: Cloud Mine Consulting
 *  Create date: Sun Mar 25 2018
 *  
 *  Details
 *  -----
 *  Apex class to handle integration with Passbook
 *
 *  Update History
 *  -----
 * 
 *  Issues / TODOs
 *  -----
 *  
 **/
global class PassbookRestHelper {

    private static final Passbook_Config__mdt passbookConfig = [Select URI__c,X_API_Client__c,X_API_Secret__c  from Passbook_Config__mdt Limit 1];
    
	private static void initConfig(){        
        
	}    
    
    global PassbookRestHelper(){
        initConfig();
    }        
    
    global static string postToPassbook(passbookJSON passbookClass){
        
		//generate Passbook payload to submit
		string jsonToSend = json.serialize(passbookClass);
        system.debug('jsonToSend---' + jsonToSend);
		Http http = new Http();
		HttpRequest request = new HttpRequest();
		request.setEndpoint(passbookConfig.URI__c);
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json');
		//request.setHeader('passbook-key', passbookConfig.X_API_Client__c);
		request.setHeader('x-api-key', passbookConfig.X_API_Secret__c);        

		// Set the body as a JSON object
		request.setBody(jsonToSend);
        HttpResponse response;
        
        if (!System.Test.isRunningTest()){
            response = http.send(request);
        }else{
            response = PassbookRestMockImpl.respond(request);
        }
		  
        system.debug('request---' + request);
        system.debug('responsebody---' + response.getBody());
        
        CreateLogEntry(jsonToSend,response.getBody(),String.valueOf(response.getStatusCode()),response.getStatus());
        
        return response.getBody();
        
        
        
    }      
    
    global class passbookJSON{
        
        public integer Origination_Credit_Score {get;set;} // Median FICO score from Opportunity and related Personal Credit Report
        public integer num_borrowers {get;set;} // Is there a co-applicant?
        public decimal Income {get;set;}
        public decimal Origination_Front_End_DTI {get;set;}
        public decimal Original_Loan_Amount{get;set;}
        public string Property_State {get;set;}
        public string Occupancy_Status {get;set;}
        public string Product_Type {get;set;} //Homeowner -> HO, Homebuyer -> HB
        public decimal Origination_CLTV {get;set;} // LTV from Opportunity
        public Datetime Cut_Off_Date {get;set;}
        public decimal Total_Monthly_Debt_Payment {get;set;}
        
        //ld passbook values
        //public decimal dti {get;set;} // DTI from Opportunity
        //public string partner_id {get;set;} //the Contact Id       
        //public string mortgage_type {get;set;} // 
        //public Datetime Cut_Off_Date {get;set;}       
        //public string yodlee_report_id {get;set;} // The Yodlee report ID      
        
        
        
        public passbookJSON(){
            //hardcoded values for initial testing
            /*
            this.partner_id = '0064400000nfQQm';
            this.product_type = 'HO';
            this.mortgage_type = 'A';
            this.ltv = 67.21;
            this.fico = 712;
            this.dti = 43.12;
            this.has_co_app = false;
            this.yodlee_report_id = '4b0cb48e-f10a-46bd-4e2d-8f9cfed674b6';
			*/
        }                
    }
    
    global class passbookResponse{
        //{"id":"d1bf1580-344c-11e8-a212-f56282bb4517R","response":"Decline","yodlee_report":{"messages":["Resource not found"]},"comments":"None"
        public string id {get;set;}
        public string response {get;set;}
        public string comments {get;set;}   
        public string exception_reason {get;set;}
        public string loss_reason {get;set;}     
        public string grid_one_result {get;set;}     
        public string grid_two_result {get;set;}             
    }
    
    public static void CreateLogEntry(String request,String response,String statuscode,String status){
    	Passbook_Logs__c newLog = new Passbook_Logs__c();
        newLog.Request__c = request;
        newLog.Response__c= response;
        newLog.Status_Code__c=statuscode;
        newLog.Status__c= status;
        
        insert newLog;
    }
    
}