objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProjectTasksTriggerHandler.cls
/**
 * Created by Eliot Rojas on 5/1/2019.
 */

public with sharing class ProjectTasksTriggerHandler {

    public static void handleAfterInsert(List<Project_Task__c> newList) {
        //ProjectTasksDocumentNotification.notifyPS(newList);
    }
    
    public static void handleAfterUpdate(List<Project_Task__c> newList, Map<Id, Project_Task__c> oldMap) {
        //ProjectTasksDocumentNotification.notifyPS(newList, oldMap);
        List<Project_Task__c> projectTasksToProcess = new List<Project_Task__c>();
        for(Project_Task__c pTask : newList) {
    	    /*Caro Veliz: BUS-155110073*/
            //if(pTask.Completed__c != oldMap.get(pTask.Id).Completed__c && pTask.Completed__c) {
            if(pTask.Status__c != oldMap.get(pTask.Id).Status__c && pTask.Status__c == 'Completed') {
                projectTasksToProcess.add(pTask);
            }
        }
        UnisonMasterNotifications.ManageNotificationsForProjectTasks(projectTasksToProcess);
    }
}