objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To:</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to inform External Forecasting Reports. Do not change this field without first consulting Brodie Gay or Aditya Bhandari.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prevent_Rollback_from_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent if task is in status completed, not moved back to any other status</description>
        <label>Prevent Rollback from Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Current_Conditions__c</referenceTo>
        <relationshipLabel>Project_Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProjectTasksUtil.cls
/************************************************************************************
 Apex Class Name     : ProjectTasksUtil
 Version             : 1.0
 Created Date        : 13th MAY 2019
 Function            : 
 Author              : Neeraja Cherukuri
 
 Modification Log    :

* Developer                   Date                    Description
* ----------------------------------------------------------------------------------                 
* Neeraja Cherukuri            13/05/2019               Original Version
*************************************************************************************
*/
public class ProjectTasksUtil
{
	public static Project_Task__c createProjectTasks(String projectTaskName, String projectTaskCode, Id OptyId, Id reqId, Id assignedTo, Boolean preventRollbackFromComplete)
    {
    	Project_Task__c ptask = new Project_Task__c();  
        ptask.Name                = projectTaskName;
        ptask.Code__c             = projectTaskCode;
        ptask.Opportunity__c      = OptyId;
        ptask.Requirement__c      = reqId;
        ptask.Assigned_To__c      = assignedTo; 
        ptask.Prevent_Rollback_from_Complete__c = preventRollbackFromComplete; /*Caro Veliz: BUS-155110073*/

        return ptask;  
    }
}