objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property_Legal_Description__c</fullName>
        <label>Property Legal Description</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property_Parcel_Number__c</fullName>
        <label>Property Parcel Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spruce_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Spruce Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>new</fullName>
                    <default>true</default>
                    <label>new</label>
                </value>
                <value>
                    <fullName>initial_docs_available</fullName>
                    <label>Initial Docs Available</label>
                </value>
                <value>
                    <fullName>title_report_available</fullName>
                    <label>Title Report Available</label>
                </value>
                <value>
                    <fullName>closing_scheduled</fullName>
                    <label>Closing Scheduled</label>
                </value>
                <value>
                    <fullName>closing_confirmed</fullName>
                    <label>Closing Confirmed</label>
                </value>
                <value>
                    <fullName>closing_docs_submitted</fullName>
                    <label>Closing Docs Submitted</label>
                </value>
                <value>
                    <fullName>closing_occurred</fullName>
                    <label>Closing Occurred</label>
                </value>
                <value>
                    <fullName>funded</fullName>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>recorded</fullName>
                    <label>Recorded</label>
                </value>
                <value>
                    <fullName>policy_issued</fullName>
                    <label>Policy Issued</label>
                </value>
                <value>
                    <fullName>Required</fullName>
                    <isActive>false</isActive>
                    <label>Required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetTitleInfoController.cls
public with sharing class GetTitleInfoController 
{
    public Id propertyDueDiligenceId {get; set;}

	public GetTitleInfoController(ApexPages.StandardController stdController) 
    {
        propertyDueDiligenceId = ((Property_Due_Diligence_Reports__c)stdController.getRecord()).Id;
	}

    public PageReference UpdateRecordInfo()
    {   
        List<Property_Due_Diligence_Reports__c> pddrList =
            [
                SELECT Id, Status__c, Spruce_Order_Id__c
                FROM Property_Due_Diligence_Reports__c
                WHERE Id = :propertyDueDiligenceId
            ];

        if(pddrList.size() > 0)
        {
            if(pddrList[0].Status__c != 'new' && pddrList[0].Status__c != 'initial_docs_available')
            {
                if(String.isEmpty(pddrList[0].Spruce_Order_Id__c))
                { 
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'This record has no Order Id.'));
                }
                else
                {                    
                    SpruceAPI.GetTitleReportDataResponse serverResponse = SpruceHelper.GetTitleReportData(pddrList[0].Spruce_Order_Id__c);

                    // if no error was encounter
                    if(String.isEmpty(serverResponse.errorMessage))
                    {       
                        if(!String.isEmpty(serverResponse.effective_date))
                        {
                            pddrList[0].Effective_Date__c = Date.valueOf(serverResponse.effective_date);                       
                        }
                        
                        pddrList[0].Property_Legal_Description__c = serverResponse.legal_description;
                        pddrList[0].Property_Parcel_Number__c = serverResponse.apn;

                        update pddrList[0];

                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'The record info were updated successfully.'));
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'An error occurred: ' + serverResponse.errorMessage));
                    }
                }
            }
            else
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'The status for this record must be \'Title Report Available\' or higher.'));
            }
        }

        return null;
    }

    public PageReference goBack()
    {
        PageReference url = new PageReference('/'+ propertyDueDiligenceId);
        url.setRedirect(true);
        return url;
    }
}