objects/Property_Due_Diligence_Reports__c.object
<CustomObject>
    <fields>
        <fullName>Spruce_Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Spruce Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>new</fullName>
                    <default>true</default>
                    <label>new</label>
                </value>
                <value>
                    <fullName>initial_docs_available</fullName>
                    <label>Initial Docs Available</label>
                </value>
                <value>
                    <fullName>title_report_available</fullName>
                    <label>Title Report Available</label>
                </value>
                <value>
                    <fullName>closing_scheduled</fullName>
                    <label>Closing Scheduled</label>
                </value>
                <value>
                    <fullName>closing_confirmed</fullName>
                    <label>Closing Confirmed</label>
                </value>
                <value>
                    <fullName>closing_docs_submitted</fullName>
                    <label>Closing Docs Submitted</label>
                </value>
                <value>
                    <fullName>closing_occurred</fullName>
                    <label>Closing Occurred</label>
                </value>
                <value>
                    <fullName>funded</fullName>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>recorded</fullName>
                    <label>Recorded</label>
                </value>
                <value>
                    <fullName>policy_issued</fullName>
                    <label>Policy Issued</label>
                </value>
                <value>
                    <fullName>Required</fullName>
                    <isActive>false</isActive>
                    <label>Required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Due Diligence Reports</label>
    <nameField>
        <label>Property Due Diligence Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Due Diligence Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpruceRestService.cls
@RestResource(urlMapping='/SpruceRS/*')
global class SpruceRestService {
	
    @HttpPost
    global static String doPost() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            boolean validrequest = false;
            
            for(string key : req.headers.keySet()){
                if(key.equalsIgnoreCase('apikey') && req.headers.get(key) ==  System.Label.Spruce_Header){
                    validrequest = true;
                }
            }
            
            if(validrequest){
                System.debug('request body'+req.requestBody.toString());
                RequestWrapper rw = (RequestWrapper)JSON.deserialize(req.requestBody.toString(), RequestWrapper.class);
                
                List<Property_Due_Diligence_Reports__c> pddrs = [SELECT Id FROM Property_Due_Diligence_Reports__c WHERE Spruce_Order_Id__c = :rw.payload.file_number];
                
                for (Property_Due_Diligence_Reports__c pddr : pddrs) {
                    pddr.Status__c = rw.payload.status;
                }
                if(!pddrs.isempty()){
                    update pddrs;
                }
            }else{
                return 'apikey Incorrect';    
            }
            return 'OK';
        } catch (Exception ex) {
            res.statusCode = 500;
            return ex.getMessage();
        }
    }
    public class RequestWrapper {
        //public EventWrapper event { get; set; }
        public string event_id { get; set; }
        public string event { get; set; }
        public string timestamp {get; set; }
        public payloadWrapper payload {get; set; }
    }
    public class payloadWrapper {
        public string file_number { get; set; }
        public string order_id { get; set; }
        public string status { get; set; }
    }
    /*
    public class EventWrapper {
        public string event_status { get; set; }
        public string event_time { get; set; }
    }*/
    /*public class OrderWrapper {
        public string id { get; set; }
        public string order_status { get; set; }
    }*/
    
}