objects/RequirementToAWSEndpoint__mdt.object
<CustomObject>
    <fields>
        <fullName>AWSEndpoint__c</fullName>
        <label>AWSEndpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>X_API_Key__c</fullName>
        <label>X-API-Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RequirementToAWSEndpoint</label>
    <pluralLabel>RequirementToAWSEndpoints</pluralLabel>
</CustomObject>

classes/UnisonRequirementUpsertHttpCalloutMock.cls
@isTest
global class UnisonRequirementUpsertHttpCalloutMock implements HttpCalloutMock {
    global static HTTPResponse respond(HTTPRequest request) {
		RequirementToAWSEndpoint__mdt AwsEndpointSetting = [SELECT X_API_Key__c, AWSEndpoint__c FROM RequirementToAWSEndpoint__mdt LIMIT 1];

        System.assertEquals(AwsEndpointSetting.AWSEndpoint__c, request.getEndpoint());
        System.assertEquals(AwsEndpointSetting.X_API_Key__c, request.getHeader('x-api-key'));
        //System.assertEquals('application/json', request.getHeader('Content-Type'));
        System.assertEquals('POST', request.getMethod());

        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody(request.getBody());
        response.setStatusCode(200);
        return response;
    }
}