objects/Yodlee_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status Code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yodlee_Public_Id__c</fullName>
        <label>Yodlee Public Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Yodlee Order Request</label>
    <nameField>
        <label>Yodlee Order Request  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Yodlee_YOR_Report_Ext.cls
/**********************************************************
 * @className   : Yodlee_YOR_Report_Ext.cls
 * @testClass   : Yodlee_YOR_Report_Ext_TEST.cls
 * @date        : May 11, 2018
 * @description : This is used to display a pdf in a Yodlee_YOR_Report.page received from a rest call
 *
 *
 **********************************************************/

public class Yodlee_YOR_Report_Ext  {

	private Yodlee_Order_Request__c yor;
	public Boolean displayError {get;set;}
	public Attachment attach {get;set;}

	public Yodlee_YOR_Report_Ext(ApexPages.StandardController sc){
		this.yor = (Yodlee_Order_Request__c)sc.getRecord();
		this.displayError = false;
		attach = new Attachment();
	}

	public PageReference init(){
		String errorMessage = '';
		Yodlee_Order_Request__c currentYor = [Select Id, Yodlee_Public_Id__c, Status__c from Yodlee_Order_Request__c Where Id =: this.yor.Id];

		if (currentYor != null && String.isNotBlank(currentYor.Yodlee_Public_Id__c)){
			Blob pdfFile = YodleeHelper.RetriveReportOrder(currentYor.Yodlee_Public_Id__c);

			if (pdfFile != null){
				Long lNow = Datetime.now().getTime();

				attach = new Attachment();
				attach.Body = pdfFile;
				attach.Name = 'YodleeOrderReport-' + lNow + '.pdf';
				attach.ParentId = currentYor.Id;
				attach.IsPrivate = false;
				attach.ContentType = 'application/pdf';

				insert attach;

				return new PageReference('/servlet/servlet.FileDownload?file=' + attach.Id);
			}else{
				errorMessage = 'The response received is not valid. No PDF File was generated.';
			}
		}else{
			errorMessage = 'The "Yodlee Public Id" field is empty.';
		}

		if (String.isNotBlank(errorMessage)){
			this.displayError = true;
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage);
			ApexPages.addMessage(msg);
		}	
		return null;
	}
}